USE [DIVA_SEV_WARRANTY_JULY_21_JUNE_23]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--DYNAMIC_SCRIPT_START

CREATE   FUNCTION [dbo].[REMOVE_LEADING_ZEROES](@Temp VarChar(1000))
Returns VarChar(1000)
AS
Begin
	Return SUBSTRING(@Temp, PATINDEX('%[^0]%', @Temp+'.'), LEN(@Temp))
End

GO
