USE [DIVA_GB00_FY23_24]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[SP_TEST_DUPS_FOR_EACH_TABLE]
AS

/* Initialize parameters from globals table */

     DECLARE 	 
			 @currency nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'currency')
			,@date1 nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'date1')
			,@date2 nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'date2')
			,@downloaddate nvarchar(max)		= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'downloaddate')
			,@exchangeratetype nvarchar(max)	= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'exchangeratetype')
			,@language1 nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'language1')
			,@language2 nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'language2')
			,@year nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'year')
			,@id nvarchar(max)					= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'id')
			,@ZV_LIMIT nvarchar(max)		    = (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'ZV_LIMIT')


/* Drop table if it already exists*/

EXEC sp_droptable 'LOG_DUP_IN_PROC'
	CREATE TABLE [DBO].[LOG_DUP_IN_PROC] ([SP_NAME] NVARCHAR(MAX) NULL, [SP_TABLE] NVARCHAR(MAX) NULL, 
	[NUM_RECORDS] INT NULL, KEY_FIELD NVARCHAR(MAX), QUERY_TIME DATETIME, ID INT IDENTITY(1, 1)) 
--Step 1: Check duplication for SAP table (A_)
DECLARE @ZV_CMD varchar(4000)
DECLARE CMD_CURSOR CURSOR FOR
SELECT 'EXEC SP_TEST_DUP_KEY_FIELDS ''SP_TEST_DUPS_FOR_EACH_TABLE'', ''' + TABLE_NAME + ''', ''' +
	STUFF((
		SELECT ', ' + SUBSTRING(TABLE_NAME, 3, LEN(TABLE_NAME)) + '_' + FIELDNAME FROM zzSAP_DDIC..TURKEY_DD03L
			WHERE 'A_' + TABNAME COLLATE Latin1_General_CI_AS = TABLE_NAME COLLATE Latin1_General_CI_AS AND NOT ISNULL(KEYFLAG, '') IN ('', 'NULL') AND CHARINDEX(FIELDNAME, 'MANDT') = 0
			FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)'),1,1,'') + ''''
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE 'A[_]%'
	AND NOT EXISTS(SELECT FIELDNAME FROM zzSAP_DDIC..RUSSIA_DD03L WHERE TABNAME COLLATE Latin1_General_CI_AS = TABLE_NAME COLLATE Latin1_General_CI_AS)

OPEN CMD_CURSOR
WHILE 1 = 1
BEGIN
    FETCH CMD_CURSOR INTO @ZV_CMD
    IF @@fetch_status != 0 BREAK
	IF @ZV_CMD IS NOT NULL
	BEGIN
		EXEC(@ZV_CMD)
	END
END
CLOSE CMD_CURSOR;
DEALLOCATE CMD_CURSOR


--Step 2: Check duplication for SAP table _IT_ table
EXEC SP_TEST_DUP_KEY_FIELDS 'B01_USERS', 'B01_01_IT_USERS', 'B01_USR02_BNAME'
EXEC SP_TEST_DUP_KEY_FIELDS 'B02_FIN_COA', 'B02_04_IT_FIN_COA', 'B02_SKB1_SAKNR, B02_T001_BUKRS'
-- B03 TRIAL BALANCE DOES NOT HAVE IT OWN UNIQUE KEY
EXEC SP_TEST_DUP_KEY_FIELDS 'B04_FIN_GENERAL_LEDGER', 'B04_11_IT_FIN_GL', 'B04_BSEG_BUKRS, B04_BSEG_GJAHR, B04_BSEG_BELNR, B04_BSEG_BUZEI'
EXEC SP_TEST_DUP_KEY_FIELDS 'B08_PTP_SMD', 'B08_06_IT_PTP_SMD', 'B08_LFB1_BUKRS, B08_LFB1_LIFNR'
EXEC SP_TEST_DUP_KEY_FIELDS 'B09_PTP_POS', 'B09_13_IT_PTP_POS', 'B09_EKKO_EBELN, B09_EKPO_EBELP'
EXEC SP_TEST_DUP_KEY_FIELDS 'B10_PTP_PO_HISTORY', 'B10_02_IT_PTP_PO_HISTORY', 'B10_EKPO_BUKRS, B10_EKBE_GJAHR, B10_EKBE_BELNR, B10_EKBE_BUZEI, B10_EKKO_EBELN, B10_EKPO_EBELP, B10_EKBE_VGABE, B10_EKBE_ZEKKN'

EXEC SP_TEST_DUP_KEY_FIELDS 'B11_PTP_APA', 'B11_04_IT_PTP_APA', 'B11B_BSAIK_BUKRS, B11B_BSAIK_GJAHR, B11B_BSAIK_BELNR, B11B_BSAIK_BUZEI'
EXEC SP_TEST_DUP_KEY_FIELDS 'B11_PTP_APA', 'B11_05_IT_PTP_INVS_AND_CANCS', 'B11_BSAIK_BUKRS, B11_BSAIK_GJAHR, B11_BSAIK_BELNR, B11_BSAIK_BUZEI'

EXEC SP_TEST_DUP_KEY_FIELDS 'B11_PTP_APA', 'B11_06_IT_PTP_INV', 'B11C_BSAIK_BUKRS, B11C_BSAIK_GJAHR, B11C_BSAIK_BELNR, B11C_BSAIK_BUZEI'
EXEC SP_TEST_DUP_KEY_FIELDS 'B11_PTP_APA', 'B11_07_IT_PTP_INV_CANC', 'B11D_BSAIK_BUKRS, B11D_BSAIK_GJAHR, B11D_BSAIK_BELNR, B11D_BSAIK_BUZEI'
EXEC SP_TEST_DUP_KEY_FIELDS 'B11_PTP_APA', 'B11_08_IT_PTP_PAY', 'B11E_BSAIK_BUKRS, B11E_BSAIK_GJAHR, B11E_BSAIK_BELNR, B11E_BSAIK_BUZEI'
EXEC SP_TEST_DUP_KEY_FIELDS 'B11_PTP_APA', 'B11_09_IT_PTP_PAY_CANC', 'B11F_BSAIK_BUKRS, B11F_BSAIK_GJAHR, B11F_BSAIK_BELNR, B11F_BSAIK_BUZEI'
EXEC SP_TEST_DUP_KEY_FIELDS 'B11_PTP_APA', 'B11_14_IT_AP_AGEING', 'B11G_BSAIK_BUKRS, B11G_BSAIK_GJAHR, B11G_BSAIK_BELNR, B11G_BSAIK_BUZEI, B11G_ZF_MNTH_END'

EXEC SP_TEST_DUP_KEY_FIELDS 'B12_PTP_PO_APA_MAPPING', 'B12B_01_IT_PTP_GL', 'B12_GL_BSEG_BUKRS, B12_GL_BSEG_GJAHR, B12_GL_BSEG_BELNR, B12_GL_BSEG_BUZEI'
EXEC SP_TEST_DUP_KEY_FIELDS 'B12_PTP_PO_APA_MAPPING', 'B12B_02_IT_PTP_AP', 'B11_BSAIK_BUKRS, B11_BSAIK_GJAHR, B11_BSAIK_BELNR, B11_BSAIK_BUZEI'
EXEC SP_TEST_DUP_KEY_FIELDS 'B12_PTP_PO_APA_MAPPING', 'B12B_03_IT_PTP_PO', 'B09_EKKO_EBELN, B09_EKPO_EBELP'



EXEC SP_TEST_DUP_KEY_FIELDS 'B13_OTC_CMD', 'B13_05_IT_CMD', 'B13_KNB1_BUKRS, B13_KNB1_KUNNR'
EXEC SP_TEST_DUP_KEY_FIELDS 'B14_OTC_ARE', 'B14_06_IT_ARE', 'B14_BSAID_BUKRS, B14_BSAID_GJAHR, B14_BSAID_BELNR, B14_BSAID_BUZEI'
EXEC SP_TEST_DUP_KEY_FIELDS 'B14_OTC_ARE', 'B14_19_IT_T4_OUTPUT', 'B14B_BSAID_BUKRS, B14B_BSAID_BELNR, B14B_BSAID_AUGBL, B14B_BSAID_AUGDT, 
						B14B_BSAID_BUZEI, B14B_BSAID_WAERS, B14B_ZF_SNAPSHOT_DATE, B14B_ZF_SNAPSHOT_DATE_AGEING, B14B_ZF_DOCUMENT_TYPE'

EXEC SP_TEST_DUP_KEY_FIELDS 'B15_OTC_ARE_changes', 'B15_05_IT_ARE_CHANGES', 'B15_CDPOS_CHANGENR, B15_CDHDR_OBJECTID, 
								B15_CDPOS_CHNGIND,B15_CDPOS_TABNAME, B15_CDPOS_TABKEY, B15_CDPOS_FNAME'
-- ADDED B15_CDPOS_TABKEY TO FINAL CUBE FOR DUPLICATION CHECK
EXEC SP_TEST_DUP_KEY_FIELDS 'B15_OTC_ARE_changes', 'B15_05_IT_ARE_CHANGES', 
								'B15_CDPOS_CHANGENR, B15_CDHDR_OBJECTID, B15_CDPOS_TABKEY, B15_CDPOS_TABNAME, B15_CDPOS_FNAME'
EXEC SP_TEST_DUP_KEY_FIELDS 'B16_OTC_AR_ageing', 'B16_04_IT_OTC_AR_AGEING', 
								'B16_BSAID_BUKRS, B16_BSAID_GJAHR, B16_BSAID_BELNR, B16_BSAID_BUZEI, B16_ZF_MNTH_END'
EXEC SP_TEST_DUP_KEY_FIELDS 'B17_OTC_INV_MMD', 'B17_03_IT_INV_MMD', 
								'B17_MARA_MATNR, B17_MARC_WERKS'
EXEC SP_TEST_DUP_KEY_FIELDS 'B18_OTC_COPA', 'B18B_08_IT_COPA_HIERARCHY_VALUE', 
								'B18B_COPA_BUKRS, B18B_COPA_GJAHR, B18B_COPA_BELNR, B18B_COPA_POSNR, B18B_COMA_M_COPA_field_label,
								B18B_ZF_FIELD_NAME_TECH, B18B_COMA_M_Hierarchy_L1, B18B_COMA_M_Hierarchy_L2, B18B_COMA_M_Hierarchy_L3'
EXEC SP_TEST_DUP_KEY_FIELDS 'B18_OTC_COPA', 'B18_09_IT_COPA_TRANSACTION', 
								'B18_COPA_BUKRS, B18_COPA_GJAHR, B18_COPA_BELNR, B18_COPA_POSNR, B18_COPA_PALEDGER'

-- Step 3: print out duplication log to user
SELECT * FROM [LOG_DUP_IN_PROC]






GO
