USE [DIVA_GB00_FY23_24]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--ALTER PROCEDURE [dbo].[A_005D_CREATE_PROCUREMENT_CATEGORY_STRUCTURE] 
CREATE   PROCEDURE [dbo].[A_005D_CREATE_PROCUREMENT_CATEGORY_STRUCTURE_EXE] 

WITH EXEC AS CALLER

AS

BEGIN

/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END

--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL

/* Initialize parameters from globals table */

     DECLARE 	 
			 @CURRENCY NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
			,@DATE1 NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
			,@DATE2 NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
			,@DOWNLOADDATE NVARCHAR(MAX)		= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
			,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
			,@EXCHANGERATETYPE NVARCHAR(MAX)	= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
			,@LANGUAGE1 NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
			,@LANGUAGE2 NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
			,@YEAR NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
			,@ID NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
			,@LIMIT_RECORDS INT		            = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)


/*Test mode*/

SET ROWCOUNT @LIMIT_RECORDS

/*
  Title		    :	ALTER PROCurement category structure
  Description	:  

  --------------------------------------------------------------
  Update history
  --------------------------------------------------------------
  Date		    | Who |	Description
  11/09/2017	 CW	   Creation  
*/

-- The procurement category structure table is used in cube B09 (create list of purchase orders)
-- However, this table has been replaced in the spend category drill-down on spend overview dashboard
-- by the spend category table that is rather based on the account definition.
-- We leave the procurement category definition here for reference, as it may be used at the PO level in the future
-- for POs that are not yet linked to invoices and so that do not yet impact the spend overview dashboard

-- Step 1/ Create a unique list of material numbers and their material group codes

EXEC SP_DROPTABLE 'A005D_01_TT_EKPO_MATNR_MATKL'


SELECT 
   EKPO_MANDT, EKPO_MATNR, EKPO_MATKL
   INTO A005D_01_TT_EKPO_MATNR_MATKL
   FROM A_EKPO
   GROUP BY EKPO_MANDT, EKPO_MATNR, EKPO_MATKL


EXEC SP_DROPTABLE 'A005D_02_TT_MARA_GROUPBY'


-- Step 2/ Create a unique list of material numbers and material type codes

SELECT
	MARA_MANDT,	MARA_MATNR,	MARA_MTART
	INTO A005D_02_TT_MARA_GROUPBY
	FROM A_MARA
	GROUP BY MARA_MANDT, MARA_MATNR, MARA_MTART

-- Step 3/ Create the procurement category table


EXEC SP_DROPTABLE 'AM_PROC_CAT'

SELECT 
		COALESCE(A005D_01_TT_EKPO_MATNR_MATKL.EKPO_MATNR,'')	AS [PROC_CAT_ID],
		COALESCE(A_T134T.T134T_MTBEZ,'')				AS [PROC_CAT_L1],    
		COALESCE(A005D_01_TT_EKPO_MATNR_MATKL.EKPO_MATKL, '')	AS [PROC_CAT_MTRL_GRP_CODE],
		COALESCE(A_T023T.T023T_WGBEZ, '')				AS [PROC_CAT_L2],
		COALESCE (A_MAKT.MAKT_MAKTX,'')				AS [PROC_CAT_L3]

INTO AM_PROC_CAT
FROM 		A005D_01_TT_EKPO_MATNR_MATKL
			-- Material master data
	LEFT JOIN A005D_02_TT_MARA_GROUPBY
		ON A005D_01_TT_EKPO_MATNR_MATKL.EKPO_MATNR = A005D_02_TT_MARA_GROUPBY.MARA_MATNR 
	
	-- Material type descriptions
	LEFT JOIN A_T134T
		ON  A005D_02_TT_MARA_GROUPBY.MARA_MTART = A_T134T.T134T_MTART
		
	-- Material descriptions
	LEFT JOIN A_MAKT
		ON  A005D_01_TT_EKPO_MATNR_MATKL.EKPO_MATNR = A_MAKT.MAKT_MATNR
	
	-- Material group descriptions	
	LEFT JOIN A_T023T
		ON  A005D_01_TT_EKPO_MATNR_MATKL.EKPO_MATKL = A_T023T.T023T_MATKL
	WHERE COALESCE(A005D_01_TT_EKPO_MATNR_MATKL.EKPO_MATNR,'') <> ''	
	GROUP BY A005D_01_TT_EKPO_MATNR_MATKL.EKPO_MATNR, A_T134T.T134T_MTBEZ, A005D_01_TT_EKPO_MATNR_MATKL.EKPO_MATKL, A_T023T.T023T_WGBEZ, 
	A_MAKT.MAKT_MAKTX


/* log cube creation*/

INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','AM_PROC_CAT',(SELECT COUNT(*) FROM AM_PROC_CAT) 


/* log end of procedure*/


INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(date,GETDATE()),CONVERT(time,GETDATE()),'Procedure finished',NULL,NULL


END   















GO
