USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[SP_SET_GLOBAL_LIMIT](@INPUT AS INTEGER)
AS
UPDATE AM_GLOBALS
SET GLOBALS_VALUE = CAST(@INPUT AS NVARCHAR(10))
WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS'

SELECT * FROM AM_GLOBALS

GO
