USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION [dbo].[COMPARE_NUMBER_ONLY](@INPUT VARCHAR(MAX), @INPUT2 VARCHAR(MAX))
RETURNS VARCHAR(MAX)
BEGIN
   DECLARE @RESULT NVARCHAR(MAX)

   IF (CAST(dbo.[RemoveNonNumericCharacters](@INPUT) AS float) = CAST(dbo.[RemoveNonNumericCharacters](@INPUT2) AS float) + 1)
	SET @RESULT = 'SEQUENCE'
	ELSE
	SET @RESULT = 'N'

	RETURN @RESULT
END

GO
