USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE   PROCEDURE [dbo].[A_009_CREATE/UPDATE_AM_COPA_MAPPING]
AS
BEGIN
	/*
		Step 1: Create AM_COPA_MAPPING if it do not exists
	*/
	PRINT 'Creating AM_COPA_MAPPING table.'
	IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'AM_COPA_MAPPING')
		BEGIN
			CREATE TABLE [dbo].[AM_COPA_MAPPING](
				[COPA_MANDT] [nvarchar](100) NULL,
				[COPA_BUKRS] [nvarchar](100) NULL,
				[COPA_KOKRS] [nvarchar](100) NULL,
				[COPA_RACCT] [nvarchar](100) NULL,
				[COPA_RACCT_TXT50] [nvarchar](100) NULL,
				[COPA_RACCT_Hierarchy_L1] [nvarchar](100) NULL,
				[COPA_RACCT_Hierarchy_L2] [nvarchar](100) NULL,
				[COPA_RACCT_Hierarchy_L3] [nvarchar](100) NULL,
				[COPA_Contractual_Condition] [nvarchar](100) NULL,
				[COPA_Settlement_method] [nvarchar](100) NULL,
				[COPA_Rebate_basis] [nvarchar](100) NULL,
				[COPA_CI_or_non_CI] [nvarchar](100) NULL,
				[COPA_Value] [nvarchar](100) NULL
			)
		END

	/*
		Step 2: Collect all active g/l from ACDOCA table
	*/
	EXEC SP_REMOVE_TABLES 'A09_01_TT_ACTIV_ACCTS'
	SELECT DISTINCT ACDOCA_RCLNT, ACDOCA_RLDNR, ACDOCA_RBUKRS, ACDOCA_KTOPL, ACDOCA_KOKRS, ACDOCA_RACCT, YEAR(ACDOCA_BUDAT) ACDOCA_BUDAT_YEAR
	INTO A09_01_TT_ACTIV_ACCTS
	FROM A_ACDOCA
	WHERE ACDOCA_XPAOBJNR_CO_REL = 'X' AND ACDOCA_CO_BELNR <> ''

	/*
		Step 3: Only keep ledger accounts relate to COPA CSKB_KATYP = 1, 11, 12.
	*/
	EXEC SP_REMOVE_TABLES 'A09_02_TT_COPA_ACCTS'
	SELECT DISTINCT ACDOCA_RCLNT, ACDOCA_RBUKRS, ACDOCA_KOKRS, ACDOCA_RACCT, SKAT_TXT50,
	CASE 
		WHEN CSKB_KATYP = 1 THEN 'COGS'
		WHEN CSKB_KATYP = 11 THEN 'Gross Sales' 
		ELSE 'Sales Reductions'
	END AS COPA_LEVEL_1
	INTO A09_02_TT_COPA_ACCTS
	FROM A09_01_TT_ACTIV_ACCTS
	LEFT JOIN A_CSKB
	ON	ACDOCA_RCLNT = A_CSKB.CSKB_MANDT AND
		ACDOCA_KOKRS = A_CSKB.CSKB_KOKRS AND
		ACDOCA_RACCT = A_CSKB.CSKB_KSTAR AND
		(YEAR(A_CSKB.CSKB_DATBI) = N'9999' OR YEAR(A_CSKB.CSKB_DATBI) >= ACDOCA_BUDAT_YEAR)
	
	LEFT JOIN A_SKAT
	ON ACDOCA_RCLNT = A_SKAT.SKAT_MANDT AND
	   ACDOCA_KTOPL = A_SKAT.SKAT_KTOPL AND
	   ACDOCA_RACCT = A_SKAT.SKAT_SAKNR
	WHERE CAST(A_CSKB.CSKB_KATYP AS INT) IN (11, 12) OR
		  (CAST(A_CSKB.CSKB_KATYP AS INT) = 1 AND ( ACDOCA_RACCT LIKE '[A-Z]5%' OR SKAT_TXT50 LIKE '%COGS%'))

	/*
		Step 4: Insert new COPA ledger accounts to AM_COPA_MAPPING
	*/
	INSERT INTO [dbo].[AM_COPA_MAPPING] ([COPA_MANDT], [COPA_BUKRS] ,[COPA_KOKRS] ,[COPA_RACCT] ,[COPA_RACCT_TXT50] ,[COPA_RACCT_Hierarchy_L1])
	SELECT DISTINCT ACDOCA_RCLNT, ACDOCA_RBUKRS, ACDOCA_KOKRS, ACDOCA_RACCT, SKAT_TXT50, COPA_LEVEL_1
	FROM A09_02_TT_COPA_ACCTS
	WHERE NOT EXISTS (
		SELECT TOP 1 1 
		FROM AM_COPA_MAPPING
		WHERE AM_COPA_MAPPING.COPA_MANDT = ACDOCA_RCLNT AND
			AM_COPA_MAPPING.COPA_BUKRS = ACDOCA_RBUKRS AND
			AM_COPA_MAPPING.COPA_KOKRS = ACDOCA_KOKRS AND
			AM_COPA_MAPPING.COPA_RACCT = ACDOCA_RACCT
	)
	
	EXEC SP_REMOVE_TABLES 'A09_%'
END
GO
