USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[ReadTextfiles]
	@path [nvarchar](max)
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [CLRReadLines].[ReadWriteFileTips].[ReadTextFile]
GO
