USE [DIVA_SOLA_FY20Q4_INCREMENTAL]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROC [dbo].[SP_CREATE_INDEX](@field NVARCHAR(1000), @table NVARCHAR(1000))

AS

   IF NOT EXISTS(SELECT * 
    FROM sys.indexes 
    WHERE name='IDX' AND object_id = OBJECT_ID(@table))
    BEGIN
        DECLARE @SQLCMD NVARCHAR(1000) = 'CREATE NONCLUSTERED INDEX IDX ON ' + @table + '(' + @field + ')'
        PRINT @SQLCMD
        EXEC SP_EXECUTESQL @SQLCMD
    END
    ELSE PRINT 'INDEX IS ALREADY IN TABLE'
GO
