USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC [dbo].[B00_REPLACE_VIEW_BY_TABLE](@DBNAME as NVARCHAR(MAX))
AS
EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B00%'
--EXEC SP_EXEC_DYNAMIC @DBNAME, 'SP_AM_TABLES_VALIDATION'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B00_REPLACE_VIEW_BY_TABLE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B00_SS01_VENDOR_CUSTOMER_BALANCE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_BOO_CREATE_INDEX_TABLE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B00_TCURR_TCURF'

GO
