USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_B11_SS02_ADD_USER_INV_PAY]
AS
-- =============================================
-- Author:		Khoi
-- Create date: <Create Date,,>
-- Description:	Create a sub script to add neccesary field for cube B11_04_IT_PTP_APA
-- 22-03-2022	   Thuan	Remove MANDT field in join
-- =============================================

--AS
--DYNAMIC_SCRIPT_START
/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('_DatabaseLogTable', 'U') IS NULL BEGIN CREATE TABLE [dbo].[_DatabaseLogTable] ([Database] nvarchar(max) NULL,[Object] nvarchar(max) NULL,[Object Type] nvarchar(max) NULL,[User] nvarchar(max) NULL,[Date] date NULL,[Time] time NULL,[Description] nvarchar(max) NULL,[Table] nvarchar(max),[Rows] int) END

--Log start of procedure
INSERT INTO [dbo].[_DatabaseLogTable] ([Database],[Object],[Object Type],[User],[Date],[Time],[Description],[Table],[Rows])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(date,GETDATE()),CONVERT(time,GETDATE()),'Procedure started',NULL,NULL

/* Initialize parameters from globals table */
 
     DECLARE 	 
			 @currency nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'currency')
			,@date1 nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'date1')
			,@date2 nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'date2')
			,@downloaddate nvarchar(max)		= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'downloaddate')
			,@exchangeratetype nvarchar(max)	= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'exchangeratetype')
			,@language1 nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'language1')
			,@language2 nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'language2')
			,@year nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'year')
			,@id nvarchar(max)					= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'id')
			--,@ZV_LIMIT nvarchar(max)		    = (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'LIMIT_RECORDS')
			,@errormsg NVARCHAR(MAX)
			
DECLARE @dateformat varchar(3)
SET @dateformat   = (SELECT dbo.get_param('dateformat'))
SET DATEFORMAT @dateformat;


--Step1 Add username,name of the user who create the supplier 
--Add supplier create date,
EXEC SP_REMOVE_TABLES 'B11_SS02_%'
EXEC SP_REMOVE_TABLES'XTEMP'

SELECT 
		B11B_BSAIK_MANDT AS BSAIK_MANDT,
		B11B_BSAIK_BUKRS AS BSAIK_BUKRS,
		B11B_BSAIK_GJAHR AS BSAIK_GJAHR,
		B11B_BSAIK_BELNR AS BSAIK_BELNR,
		B11B_BSAIK_BUZEI AS BSAIK_BUZEI,
		B11B_BSAIK_BSCHL AS BSAIK_BSCHL,
		B11B_BSAIK_SHKZG AS BSAIK_SHKZG,
		B11B_BSAIK_BLART AS BSAIK_BLART,
		B11B_BSAIK_LIFNR AS BSAIK_LIFNR,
		B11B_BSAIK_WAERS AS BSAIK_WAERS,
		B11B_BSAIK_DMBTR AS BSAIK_DMBTR,
		B11B_BSAIK_DMBE2 AS BSAIK_DMBE2,
		B11B_BSAIK_DMBE3 AS BSAIK_DMBE3,
		B11B_BSAIK_UMSKS AS BSAIK_UMSKS,
		B11B_BSAIK_UMSKZ AS BSAIK_UMSKZ,
		B11B_BSAIK_AUGDT AS BSAIK_AUGDT,
		B11B_BSAIK_AUGBL AS BSAIK_AUGBL,
		B11B_BSAIK_ZUONR AS BSAIK_ZUONR,
		B11B_BSAIK_BUDAT AS BSAIK_BUDAT,
		B04_BKPF_CPUTM AS BSAIK_CPUTM,
		B11B_BSAIK_BLDAT AS BSAIK_BLDAT,
		B11B_BSAIK_CPUDT AS BSAIK_CPUDT,
		B11B_BSAIK_XBLNR AS BSAIK_XBLNR,
		B11B_BSAIK_MONAT AS BSAIK_MONAT,
		B11B_BSAIK_ZUMSK AS BSAIK_ZUMSK,
		B11B_BSAIK_GSBER AS BSAIK_GSBER,
		B11B_BSAIK_WRBTR AS BSAIK_WRBTR,
		B11B_BSAIK_MWSKZ AS BSAIK_MWSKZ,
		B11B_BSAIK_MWSTS AS BSAIK_MWSTS,
		B11B_BSAIK_WMWST AS BSAIK_WMWST,
		B11B_BSAIK_SGTXT AS BSAIK_SGTXT,
		B11B_BSAIK_AUFNR AS BSAIK_AUFNR,
		B11B_BSAIK_EBELN AS BSAIK_EBELN,
		B11B_BSAIK_EBELP AS BSAIK_EBELP,
		B11B_BSAIK_HKONT AS BSAIK_HKONT,
		B11B_BSAIK_ZFBDT AS BSAIK_ZFBDT,
		B11B_BSAIK_ZTERM AS BSAIK_ZTERM,
		B11B_BSAIK_ZBD1T AS BSAIK_ZBD1T,
		B11B_BSAIK_ZBD2T AS BSAIK_ZBD2T,
		B11B_BSAIK_ZBD3T AS BSAIK_ZBD3T,
		B11B_BSAIK_ZBD1P AS BSAIK_ZBD1P,
		B11B_BSAIK_ZBD2P AS BSAIK_ZBD2P,
		B11B_BSAIK_SKFBT AS BSAIK_SKFBT,
		B11B_BSAIK_SKNTO AS BSAIK_SKNTO,
		B11B_BSAIK_WSKTO AS BSAIK_WSKTO,
		B11B_BSAIK_ZLSCH AS BSAIK_ZLSCH,
		B11B_BSAIK_ZLSPR AS BSAIK_ZLSPR,
		B11B_BSAIK_BSTAT AS BSAIK_BSTAT,
		B11B_BSAIK_PROJK AS BSAIK_PROJK,
		B11B_BSAIK_XRAGL AS BSAIK_XRAGL,
		B11B_BSAIK_KOSTL AS BSAIK_KOSTL,
		B11B_BSAIK_XNEGP AS BSAIK_XNEGP,
		B11B_BSAIK_PRCTR AS BSAIK_PRCTR,
		B11B_BSAIK_AUGGJ AS BSAIK_AUGGJ,
		B11B_ZF_BSAIK_CPUDT_AGE_DAYS AS ZF_BSAIK_CPUDT_AGE_DAYS,
		B11B_ZF_BSAIK_OPEN_CLOSED AS ZF_BSAIK_OPEN_CLOSED,
		B11B_ZF_BSAIK_SHKZG_DESC AS ZF_BSAIK_SHKZG_DESC,
		B11B_ZF_BSAIK_SHKZG_INTEGER AS ZF_BSAIK_SHKZG_INTEGER,
		B11B_ZF_BSAK_AUGDT_YEAR_MNTH AS ZF_BSAK_AUGDT_YEAR_MNTH,
		B11B_ZF_BSAIK_WSKTO_SKBFT AS ZF_BSAIK_WSKTO_SKBFT,
		B11B_T001_WAERS AS T001_WAERS,
		B11B_ZF_BSAIK_DMBTR_S AS ZF_BSAIK_DMBTR_S,
		B11B_ZF_BSAIK_DMBE2_S AS ZF_BSAIK_DMBE2_S,
		B11B_ZF_BSAIK_DMBE3_S AS ZF_BSAIK_DMBE3_S,
		B11B_GLOBALS_CURRENCY AS GLOBALS_CURRENCY,
		B11B_ZF_BSAIK_DMBTR_S_CUC AS ZF_BSAIK_DMBTR_S_CUC,
		B11B_LFA1_KTOKK AS LFA1_KTOKK,
		B11B_T077Y_TXT30 AS T077Y_TXT30,
		B11B_T003T_LTEXT AS T003T_LTEXT,
		B11B_BKPF_TCODE AS BKPF_TCODE,
		B11B_ZF_SUPP_INV AS ZF_SUPP_INV,
		B11B_ZF_SUPP_INV_CANC AS ZF_SUPP_INV_CANC,
		B11B_ZF_SUPP_PAY AS ZF_SUPP_PAY,
		B11B_ZF_SUPP_PAY_CANC AS ZF_SUPP_PAY_CANC,
		B11B_ZF_OTHERS AS ZF_OTHERS,
		B11B_ZF_FLAG_SUMMARY AS ZF_FLAG_SUMMARY,
		B11B_TGSBT_GTEXT AS TGSBT_GTEXT,
		B11B_SCOPE_BUSINESS_DMN_L1 AS SCOPE_BUSINESS_DMN_L1,
		B11B_SCOPE_BUSINESS_DMN_L2 AS SCOPE_BUSINESS_DMN_L2,
		B11B_T001_BUTXT AS T001_BUTXT,
		B11B_T001_LAND1 AS T001_LAND1,
		B11B_LFA1_NAME1 AS LFA1_NAME1,
		B11B_LFA1_LAND1 AS LFA1_LAND1,
		B11B_LFA1_VBUND AS LFA1_VBUND,
		B11B_INTERCO_TXT AS INTERCO_TXT,
		B11B_DD07T_DDTEXT AS DD07T_DDTEXT,
		B11B_COUNTRY_MAPPING_DESC AS COUNTRY_MAPPING_DESC,
		B11B_T001_COUNTRY_MAPPING_DESC AS T001_COUNTRY_MAPPING_DESC,
		B11B_TBSLT_LTEXT AS TBSLT_LTEXT,
		B11B_ZF_BSAIK_WRBTR_S AS ZF_BSAIK_WRBTR_S,
		B11B_ZF_BSAIK_WRBTR_S_CUC AS ZF_BSAIK_WRBTR_S_CUC,
		B11B_ZF_BSAIK_DMBTR_CUC AS ZF_BSAIK_DMBTR_CUC,
		B11B_BKPF_USNAM AS BKPF_USNAM,
		B11B_V_USERNAME_NAME_TEXT AS V_USERNAME_NAME_TEXT,
		B11B_USR02_USTYP AS USR02_USTYP,
		B11B_ZF_USR02_USTYP_DESC AS ZF_USR02_USTYP_DESC,
		B11B_SKAT_TXT50 AS SKAT_TXT50,
		B11B_ZF_BSAIK_PRCTR AS ZF_BSAIK_PRCTR,
		B11B_ZF_CEPCT_LTEXT AS ZF_CEPCT_LTEXT,
		B11B_ZF_BKPF_AWTYP_MM_INV AS ZF_BKPF_AWTYP_MM_INV,
		B11B_ZF_BKPF_AWTYP_MM_INV_NUM AS ZF_BKPF_AWTYP_MM_INV_NUM,
		B11B_ZF_BKPF_AWTYP_MM_INV_YEAR AS ZF_BKPF_AWTYP_MM_INV_YEAR,
		B11B_BKPF_AWKEY AS BKPF_AWKEY,
		B11B_ZF_BSAIK_BUDAT_CY AS ZF_BSAIK_BUDAT_CY,
		B11B_ZF_BSAIK_BUDAT_CY_MNTH AS ZF_BSAIK_BUDAT_CY_MNTH,
		B11B_ZF_BSAIK_BUDAT_CY_CQ AS ZF_BSAIK_BUDAT_CY_CQ,
		B11B_ZF_BSAIK_MONAT_FQ AS ZF_BSAIK_MONAT_FQ,
		B11B_ZF_BSAIK_GJAHR_MONAT AS ZF_BSAIK_GJAHR_MONAT,
		B11B_ZF_BSAIK_BUDAT_MNTH AS ZF_BSAIK_BUDAT_MNTH,
		CONCAT( DBO.TRIM(B11B_BSAIK_BUKRS),'-',
		DBO.TRIM(B11B_BSAIK_GJAHR),'-',
		DBO.TRIM(B11B_BSAIK_BELNR))  AS ZF_DOCUMENT_NUMBER,
		ZF_CREDIT_HKONT_TXT20_LIST AS ZF_CREDIT_HKONT_TXT20_LIST,
		ZF_DEBIT_HKONT_TXT20_LIST AS ZF_DEBIT_HKONT_TXT20_LIST,
		ZF_DEBIT_BSEG_KOSTL_AND_DESC AS ZF_DEBIT_BSEG_KOSTL_AND_DESC,
		ZF_CREDIT_BSEG_KOSTL_AND_DESC AS ZF_CREDIT_BSEG_KOSTL_AND_DESC,
		ZF_DEBIT_BSEG_PRCTR_AND_DESC AS ZF_DEBIT_BSEG_PRCTR_AND_DESC,
		ZF_CREDIT_BSEG_PRCTR_AND_DESC AS ZF_CREDIT_BSEG_PRCTR_AND_DESC,
		B04_BSEG_MATNR AS BSEG_MATNR,
		T134T_MTBEZ,
		MARA_MTART,
		MAKT_MAKTX
INTO XTEMP
FROM B11_04_IT_PTP_APA
LEFT JOIN B04_07_IT_BSEG_BKPF_ACC_SCH
	ON BSEG_BUKRS=B11B_BSAIK_BUKRS AND
       BSEG_GJAHR=B11B_BSAIK_GJAHR AND
       BSEG_BELNR=B11B_BSAIK_BELNR
LEFT JOIN B04_11_IT_FIN_GL
	ON B11B_BSAIK_BELNR=B04_BSEG_BELNR
	AND B11B_BSAIK_GJAHR=B04_BSEG_GJAHR
	AND B11B_BSAIK_BUKRS=B04_BSEG_BUKRS
	AND B11B_BSAIK_BUZEI=B04_BSEG_BUZEI
LEFT JOIN B00_MAKT
	ON MAKT_MATNR=B04_BSEG_MATNR
LEFT JOIN A_MARA
	ON MARA_MATNR=B04_BSEG_MATNR
LEFT JOIN B00_T134T
	ON MARA_MTART=T134T_MTART

WHERE B11_04_IT_PTP_APA.B11B_BSAIK_BUKRS IN
(
	SELECT DISTINCT COMPANY_CODE FROM AM_COMPANY_CODE
) AND (B11B_ZF_SUPP_INV='X' OR B11B_ZF_SUPP_PAY='X')
           
		   
EXEC SP_DROPTABLE 'B11_SS02_01_IT_PTP_APA'
SELECT 
		XTEMP.*,
		B08_LFA1_ERNAM AS LFA1_ERNAM,--User who create the supplier
		B08_LFA1_ERDAT AS LFA1_ERDAT,--Supplier create date
		A_V_USERNAME.V_USERNAME_NAME_TEXT AS V_USERNAME_NAME_TEXT_LFA1,--Name of the supplier,
				TSTCT_TTEXT AS TSTCT_TTEXT
INTO B11_SS02_01_IT_PTP_APA
FROM XTEMP
LEFT JOIN B08_06_IT_PTP_SMD
	ON XTEMP.BSAIK_BUKRS = B08_06_IT_PTP_SMD.B08_LFB1_BUKRS 
	AND XTEMP.BSAIK_LIFNR = B08_06_IT_PTP_SMD.B08_LFB1_LIFNR
LEFT JOIN A_V_USERNAME
    ON B08_LFA1_ERNAM=V_USERNAME_BNAME
LEFT JOIN B00_TSTCT
	ON TSTCT_TCODE=BKPF_TCODE
-- STep 2 Separete invoice and payment table
--EXEC SP_DROPTABLE 'B11_SS02_01_IT_PTP_APA_INV'
EXEC SP_DROPTABLE 'B11_SS02_02_IT_PTP_APA_PAY'

/*SELECT *
INTO B11_SS02_01_IT_PTP_APA_INV
FROM B11_SS02_01_IT_PTP_APA WHERE ZF_SUPP_INV='X'*/

SELECT * 
INTO B11_SS02_02_IT_PTP_APA_PAY
FROM B11_SS02_01_IT_PTP_APA WHERE ZF_SUPP_PAY='X'

--Step 3 For Process ming ,Add BVTYP to the payment cube
EXEC SP_DROPTABLE B11_SS02_03_TT_PTP_APA_PAY_ADD_FIELD
SELECT DISTINCT 
B11_SS02_02_IT_PTP_APA_PAY.*,
BSAK_BVTYP AS BSAIK_BVTYP
INTO B11_SS02_03_TT_PTP_APA_PAY_ADD_FIELD
FROM B11_SS02_02_IT_PTP_APA_PAY
LEFT JOIN
(
	SELECT  BSAK_BUKRS,BSAK_LIFNR,BSAK_UMSKS,
					BSAK_UMSKZ,BSAK_AUGDT,BSAK_AUGBL,
					BSAK_ZUONR,BSAK_GJAHR,BSAK_BELNR,
					BSAK_BUZEI,BSAK_BVTYP FROM A_BSAK
	UNION
	SELECT  BSIK_BUKRS,BSIK_LIFNR,BSIK_UMSKS,
					BSIK_UMSKZ,BSIK_AUGDT,BSIK_AUGBL,
					BSIK_ZUONR,BSIK_GJAHR,BSIK_BELNR,
					BSIK_BUZEI,BSIK_BVTYP FROM A_BSIK
) AS A ON 
BSAK_BUKRS=BSAIK_BUKRS AND 
BSAK_LIFNR=BSAIK_LIFNR AND
BSAK_UMSKS=BSAIK_UMSKS AND
BSAK_UMSKZ=BSAIK_UMSKZ AND
BSAK_AUGDT=BSAIK_AUGDT AND
BSAK_AUGBL=BSAIK_AUGBL AND
BSAK_ZUONR=BSAIK_ZUONR AND
BSAK_GJAHR=BSAIK_GJAHR AND
BSAK_BELNR=BSAIK_BELNR AND
BSAK_BUZEI=BSAIK_BUZEI

--Step 4 Join to LFBK to get Bank account number
-- and join to REGUH to gert REGUH_ZBNKN
EXEC SP_DROPTABLE B11_SS02_04_TT_PTP_APA_PAY_ADD_LFBK

SELECT DISTINCT
B11_SS02_03_TT_PTP_APA_PAY_ADD_FIELD.*,
ZF_LFBK_BANKN_LIST AS LFBK_BANKN,
ZF_REGUH_ZBNKN_LIST AS REGUH_ZBNKN
INTO B11_SS02_04_TT_PTP_APA_PAY_ADD_LFBK
FROM B11_SS02_03_TT_PTP_APA_PAY_ADD_FIELD
LEFT JOIN 
(
	SELECT 
	    A.LFBK_LIFNR,
		A.LFBK_BVTYP,
		STUFF((SELECT DISTINCT '_' + B.LFBK_BANKN
							 FROM A_LFBK B
							 WHERE (B.LFBK_LIFNR = A.LFBK_LIFNR  
								   AND B.LFBK_BVTYP = A.LFBK_BVTYP)
							 GROUP BY LFBK_BANKN
							 FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
							 ,1,1,'') AS ZF_LFBK_BANKN_LIST
		FROM A_LFBK AS A
		GROUP BY LFBK_LIFNR,LFBK_BVTYP
) AS D
ON BSAIK_LIFNR=D.LFBK_LIFNR AND BSAIK_BVTYP=D.LFBK_BVTYP
LEFT JOIN 
(
		SELECT A.REGUH_ZBUKR,
		YEAR(A.REGUH_LAUFD) AS ZF_REGUH_LAUFD_YEAR,
		A.REGUH_VBLNR,
		STUFF((SELECT DISTINCT '_' + B.REGUH_ZBNKN
							 FROM A_REGUH B
							 WHERE (B.REGUH_ZBUKR = A.REGUH_ZBUKR  
								   AND YEAR(B.REGUH_LAUFD) = YEAR(A.REGUH_LAUFD)
								   AND B.REGUH_VBLNR = A.REGUH_VBLNR)
							 GROUP BY REGUH_ZBNKN
							 FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
							 ,1,1,'') AS ZF_REGUH_ZBNKN_LIST
		FROM A_REGUH AS A
		WHERE A.REGUH_ZBUKR IN
		( SELECT DISTINCT COMPANY_CODE FROM AM_COMPANY_CODE )
		GROUP BY A.REGUH_ZBUKR,
		YEAR(A.REGUH_LAUFD),
		A.REGUH_VBLNR
) AS C
ON BSAIK_BUKRS=C.REGUH_ZBUKR AND 
BSAIK_GJAHR=ZF_REGUH_LAUFD_YEAR AND
BSAIK_BELNR=C.REGUH_VBLNR

----Step 5 Group by the payment , to caculate the total line item value
EXEC SP_DROPTABLE B11_SS02_05_IT_PTP_APA_PAY_GROUP
SELECT DISTINCT BSAIK_BUKRS,
				BSAIK_GJAHR,
				BSAIK_BELNR,T001_WAERS,
				BKPF_USNAM,
				V_USERNAME_NAME_TEXT,
				BSAIK_BLDAT,
		BSAIK_CPUDT,BSAIK_CPUTM,
				BSAIK_LIFNR,
				LFA1_ERNAM,
				SUM(ZF_BSAIK_DMBTR_S) AS ZF_BSAIK_DMBTR_S,
				SUM(ZF_BSAIK_DMBTR_S_CUC) AS ZF_BSAIK_DMBTR_S_CUC,
				SUM(ZF_BSAIK_DMBE2_S) AS ZF_BSAIK_DMBE2_S,
				SUM(ZF_BSAIK_DMBE3_S) AS ZF_BSAIK_DMBE3_S,
				T003T_LTEXT,
				BSAIK_AUGDT,
				BSAIK_AUGBL,
				LFBK_BANKN,REGUH_ZBNKN
INTO B11_SS02_05_IT_PTP_APA_PAY_GROUP
FROM B11_SS02_04_TT_PTP_APA_PAY_ADD_LFBK
GROUP BY
		BSAIK_BUKRS,
		BSAIK_GJAHR,
		BSAIK_BELNR,
		BSAIK_CPUDT,BSAIK_CPUTM,
		BKPF_USNAM,
		V_USERNAME_NAME_TEXT,
		BSAIK_BLDAT,
		BSAIK_LIFNR,
		LFA1_ERNAM,
		T003T_LTEXT,
		BSAIK_AUGDT,
		BSAIK_AUGBL,
		LFBK_BANKN,REGUH_ZBNKN,T001_WAERS


--Step 6 Get the list of banks per JE number
-- Create this cube to check in the PTP process mining flow if it has change to bank or not

EXEC SP_DROPTABLE 'B11_SS02_06_IT_PTP_APA_PAY_ACCOUNT_LINE'

SELECT DISTINCT
		BSAIK_BUKRS,
		BSAIK_GJAHR,
		BSAIK_BELNR,
 LFBK_BANKN,
 REGUH_ZBNKN
INTO B11_SS02_06_IT_PTP_APA_PAY_ACCOUNT_LINE
FROM B11_SS02_03_TT_PTP_APA_PAY_ADD_FIELD
LEFT JOIN 
 A_LFBK AS  D
ON BSAIK_LIFNR=D.LFBK_LIFNR AND BSAIK_BVTYP=D.LFBK_BVTYP
LEFT JOIN  A_REGUH AS  C
ON 
	BSAIK_BUKRS=C.REGUH_ZBUKR AND 
	BSAIK_GJAHR=YEAR(REGUH_LAUFD) AND
	BSAIK_BELNR=C.REGUH_VBLNR


--Step 7 Rename the field
EXEC SP_RENAME_FIELD 'B11B_SS02_' ,B11_SS02_01_IT_PTP_APA
--EXEC SP_RENAME_FIELD 'B11B_SS02_01_' ,B11_SS02_01_IT_PTP_APA_INV
EXEC SP_RENAME_FIELD 'B11B_SS02_02_' ,B11_SS02_02_IT_PTP_APA_PAY
EXEC SP_RENAME_FIELD 'B11B_SS02_05_' ,B11_SS02_05_IT_PTP_APA_PAY_GROUP
EXEC SP_DROPTABLE XTEMP

 

GO
