USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC [dbo].[B18_OTC_COPA](@DBNAME as NVARCHAR(MAX))
AS


EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B18%'

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B18_OTC_COPA'


--IF @DBNAME LIKE '%RUSSIA%' EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B18_SS01_CUS_GRP_DESC_RUSSIA'
GO
