USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC[dbo].[P08_T04_DUPLICATE_INVOICES_OPTIMIZED] (@DB_NAME NVARCHAR(100))

AS 

EXEC SP_EXEC_DYNAMIC @DB_NAME, 'script_P08_T04_DUPLICATE_INVOICES_OPTIMIZED'

GO
