USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE   PROC [dbo].[script_B22_SOD_MATRIX_PREPARATION]
AS
--DYNAMIC_SCRIPT_START

	IF EXISTS(SELECT * FROM SYS.all_columns
	WHERE name = 'USOBT_C_NAME')
	BEGIN
		EXEC SP_UNNAME_FIELD 'USOBT_C_', 'A_USOBT_C'
		EXEC SP_RENAME_FIELD'USOBT_', 'A_USOBT_C'

		EXEC SP_UNNAME_FIELD 'USOBX_C_', 'A_USOBX_C'
		EXEC SP_RENAME_FIELD 'USOBX_', 'A_USOBX_C'
		
	END
GO
