USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE     PROC [dbo].[script_BOO_CREATE_INDEX_TABLE]
AS

--DYNAMIC_SCRIPT_START

EXEC SP_REMOVE_TABLES 'B00%[_]INDEX'
SELECT ZF_BUKRS, ZF_GJAHR, ZF_BELNR, ZF_BUZEI, 
ROW_NUMBER() OVER (ORDER BY ZF_BUKRS, ZF_GJAHR, ZF_BELNR, ZF_BUZEI) ZF_GL_LINE_INDEX
INTO B00_LINE_INDEX
FROM 
    (SELECT BSEG_BUKRS ZF_BUKRS, BSEG_GJAHR ZF_GJAHR, BSEG_BELNR ZF_BELNR, BSEG_BUZEI ZF_BUZEI FROM A_BSEG
    UNION
    SELECT BSAD_BUKRS, BSAD_GJAHR, BSAD_BELNR, BSAD_BUZEI
    FROM A_BSAD
    UNION
    SELECT BSID_BUKRS, BSID_GJAHR, BSID_BELNR, BSID_BUZEI
    FROM A_BSID
    UNION
    SELECT BSAK_BUKRS, BSAK_GJAHR, BSAK_BELNR, BSAK_BUZEI
    FROM A_BSAK
    UNION
    SELECT BSIK_BUKRS, BSIK_GJAHR, BSIK_BELNR, BSIK_BUZEI
    FROM A_BSIK) A
CREATE CLUSTERED INDEX IDX ON B00_LINE_INDEX(ZF_BUKRS, ZF_GJAHR, ZF_BELNR, ZF_BUZEI) 


SELECT ZF_BUKRS, ZF_GJAHR, ZF_BELNR,
ROW_NUMBER() OVER (ORDER BY ZF_BUKRS, ZF_GJAHR, ZF_BELNR) ZF_HEADER_INDEX
INTO B00_HEADER_INDEX
FROM 
    (SELECT DISTINCT BKPF_BUKRS ZF_BUKRS, BKPF_GJAHR ZF_GJAHR, BKPF_BELNR ZF_BELNR FROM A_BKPF
    UNION
    SELECT DISTINCT BSAD_BUKRS, BSAD_GJAHR, BSAD_BELNR
    FROM A_BSAD
    UNION
    SELECT DISTINCT BSID_BUKRS, BSID_GJAHR, BSID_BELNR
    FROM A_BSID
    UNION
    SELECT DISTINCT BSAK_BUKRS, BSAK_GJAHR, BSAK_BELNR
    FROM A_BSAK
    UNION
    SELECT DISTINCT BSIK_BUKRS, BSIK_GJAHR, BSIK_BELNR
    FROM A_BSIK) A
CREATE CLUSTERED INDEX IDX ON B00_HEADER_INDEX(ZF_BUKRS, ZF_GJAHR, ZF_BELNR)

GO
