USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
	CREATE   PROCEDURE [dbo].[script_B12B_SALE_REDUCTION_AGING]
	AS
	--DYNAMIC_SCRIPT_START
/* Initialize parameters from globals table */


/*Change history comments*/


  /*
/* 
	Title        :  B12B_SALE_REDUCTION_AGING 
    Description  :  Sale reduction aging
	22-03-2022	   Thuan	Remove MANDT field in join
       
*/ 

  */

/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END

--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL
	/*Step 0: prepare GL GRIR account table */
	/* Initialize parameters from globals table */

     DECLARE 	 
			 @CURRENCY NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'currency')
			,@DATE1 NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'date1')
			,@DATE2 NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'date2')
			,@DOWNLOADDATE NVARCHAR(MAX)		= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'downloaddate')
			,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'dateformat')
			,@EXCHANGERATETYPE NVARCHAR(MAX)	= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'exchangeratetype')
			,@LANGUAGE1 NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'language1')
			,@LANGUAGE2 NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'language2')
			,@YEAR NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'year')
			,@ID NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'id')
			,@LIMIT_RECORDS INT		            = CAST((SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)

	SET ROWCOUNT @LIMIT_RECORDS;
	
	/*
		Step 1: Loop every snapshot date begin date1 to date2 and select and insert the documents that still open in this snapshot
	*/
	EXEC SP_REMOVE_TABLES 'B12_07_IT_SR_SNAPSHOT'
	SELECT TOP 0 BSEG_MANDT, BSEG_BUKRS, BSEG_GJAHR, BSEG_BELNR, BSEG_BUZEI, BSEG_AUGDT AS BKPF_BUDAT, BSEG_AUGDT AS BKPF_BLDAT, BSEG_AUGDT, BSEG_AUGDT AS BKPF_CPUDT
	INTO B12_07_IT_SR_SNAPSHOT
	FROM A_BSEG;

	ALTER TABLE B12_07_IT_SR_SNAPSHOT ADD SR_FLAG NVARCHAR(30);
	ALTER TABLE B12_07_IT_SR_SNAPSHOT ADD SNAPSHOT_DATE DATE;
	ALTER TABLE B12_07_IT_SR_SNAPSHOT ADD ZF_BUDAT_MINUS_SNAPSHOT_DATE BIGINT;
	ALTER TABLE B12_07_IT_SR_SNAPSHOT ADD ZF_BUDAT_MINUS_SNAPSHOT_DATE_BUCKET NVARCHAR(50);
	ALTER TABLE B12_07_IT_SR_SNAPSHOT ADD ZF_BLDAT_MINUS_SNAPSHOT_DATE BIGINT;
	ALTER TABLE B12_07_IT_SR_SNAPSHOT ADD ZF_BLDAT_MINUS_SNAPSHOT_DATE_BUCKET NVARCHAR(50);
	ALTER TABLE B12_07_IT_SR_SNAPSHOT ADD ZF_AUGDT_MINUS_SNAPSHOT_DATE BIGINT;
	ALTER TABLE B12_07_IT_SR_SNAPSHOT ADD ZF_AUGDT_MINUS_SNAPSHOT_DATE_BUCKET NVARCHAR(50);
	ALTER TABLE B12_07_IT_SR_SNAPSHOT ADD ZF_CPUDT_MINUS_SNAPSHOT_DATE BIGINT;
	ALTER TABLE B12_07_IT_SR_SNAPSHOT ADD ZF_CPUDT_MINUS_SNAPSHOT_DATE_BUCKET NVARCHAR(50);
	WHILE EOMONTH(@DATE1) <= EOMONTH(@DATE2)
	BEGIN
		PRINT CONCAT('Process for snapshot date: ',@DATE1);
		INSERT INTO B12_07_IT_SR_SNAPSHOT
		SELECT 
				B04_BKPF_MANDT,
				B04_BSEG_BUKRS,
				B04_BSEG_GJAHR,
				B04_BSEG_BELNR,
				B04_BSEG_BUZEI,
				B04_BKPF_BUDAT,
				B04_BKPF_BLDAT,
				B04_BSEG_AUGDT,
				B04_BKPF_CPUDT,
				SR_FLAG,
				@DATE1,
				DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1),
				CASE
					WHEN DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) >=0 AND DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) <= 10 THEN '0-10 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) >= 11 AND DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) <= 20 THEN '11-20 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) >= 21 AND DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) <= 30 THEN '21-30 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) >= 31 AND DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) <= 60 THEN '31-60 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) >= 61 AND DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) <= 180 THEN '61-180 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) >= 181 AND DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) <= 360 THEN '181-360 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BUDAT, @DATE1) > 360 THEN '360+ days'
					ELSE '<0 days'
				END,
				DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1),
				CASE
					WHEN DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) >=0 AND DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) <= 10 THEN '0-10 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) >= 11 AND DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) <= 20 THEN '11-20 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) >= 21 AND DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) <= 30 THEN '21-30 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) >= 31 AND DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) <= 60 THEN '31-60 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) >= 61 AND DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) <= 180 THEN '61-180 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) >= 181 AND DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) <= 360 THEN '181-360 days'
					WHEN DATEDIFF(DAY, B04_BKPF_BLDAT, @DATE1) > 360 THEN '360+ days'
					ELSE '<0 days'
				END,
				DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1),
				CASE
					WHEN DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) >=0 AND DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) <= 10 THEN '0-10 days'
					WHEN DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) >= 11 AND DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) <= 20 THEN '11-20 days'
					WHEN DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) >= 21 AND DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) <= 30 THEN '21-30 days'
					WHEN DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) >= 31 AND DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) <= 60 THEN '31-60 days'
					WHEN DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) >= 61 AND DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) <= 180 THEN '61-180 days'
					WHEN DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) >= 181 AND DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) <= 360 THEN '181-360 days'
					WHEN DATEDIFF(DAY, B04_BSEG_AUGDT, @DATE1) > 360 THEN '360+ days'
					ELSE '<0 days'
				END,
				DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1),
				CASE
					WHEN DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) >=0 AND DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) <= 10 THEN '0-10 days'
					WHEN DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) >= 11 AND DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) <= 20 THEN '11-20 days'
					WHEN DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) >= 21 AND DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) <= 30 THEN '21-30 days'
					WHEN DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) >= 31 AND DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) <= 60 THEN '31-60 days'
					WHEN DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) >= 61 AND DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) <= 180 THEN '61-180 days'
					WHEN DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) >= 181 AND DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) <= 360 THEN '181-360 days'
					WHEN DATEDIFF(DAY, B04_BKPF_CPUDT, @DATE1) > 360 THEN '360+ days'
					ELSE '<0 days'
				END
		FROM B04_11_IT_FIN_GL
		INNER JOIN AM_SALE_REDUCTION_AGING
		ON B04_BSEG_HKONT = SR_GL_ACCT AND SR_FLAG<>''
		WHERE B04_BKPF_BUDAT <= @DATE1 AND (B04_BSEG_AUGDT IS NULL OR ISNULL(B04_BSEG_AUGBL, '') = '' OR B04_BSEG_AUGDT > @DATE1)
		SET @DATE1 = EOMONTH(DATEADD(MM,1,@DATE1))
	END

	/*
		Step 2: Create a cube from full GL cube only include the documents have been in the IR/GR account
	*/
	EXEC SP_REMOVE_TABLES 'B12_08_IT_SR_DOCUMENTS'
	SELECT B04_11_IT_FIN_GL.*,
		CASE	
			WHEN CAST(B04_BKPF_MONAT AS INT) = 0 THEN 'Open'
			WHEN CAST(B04_BKPF_MONAT AS INT) IN (1, 2, 3) THEN 'Q1'
			WHEN CAST(B04_BKPF_MONAT AS INT) IN (4, 5, 6) THEN 'Q2'
			WHEN CAST(B04_BKPF_MONAT AS INT) IN (7, 8, 9) THEN 'Q3'
			WHEN CAST(B04_BKPF_MONAT AS INT) IN (10, 11, 12) THEN 'Q4'
			ELSE 'Special Quater' 
		END AS ZF_BKPF_MONAT_FQ,
		A_T001.T001_BUTXT,
		A_SKAT.SKAT_TXT50,
		A_T003T.T003T_LTEXT,
		A_TBSLT.TBSLT_LTEXT,
		A_LFA1.LFA1_NAME1,
		A_LFA1.LFA1_KTOKK,
		A_KNA1.KNA1_NAME1,
		A_KNA1.KNA1_KTOKD,
		A_V_USERNAME.*,
		AM_SCOPE.SCOPE_BUSINESS_DMN_L1,
		AM_SCOPE.SCOPE_BUSINESS_DMN_L2,
		AM_T077Y.INTERCO_TXT AS T077Y_INTERCO_TXT,
		AM_T077Y.T077Y_TXT30,
		AM_T077X.INTERCO_TXT AS T077X_INTERCO_TXT,
		AM_T077X.T077X_TXT30,
		A_TSTCT.TSTCT_TTEXT,
		A_T074T.T074T_LTEXT,
		AM_SALE_REDUCTION_AGING.*

	INTO B12_08_IT_SR_DOCUMENTS
	FROM B04_11_IT_FIN_GL
	INNER JOIN AM_SALE_REDUCTION_AGING
	ON B04_BSEG_HKONT = SR_GL_ACCT

	--Get company information from T001 tables
	LEFT JOIN A_T001
	ON A_T001.T001_BUKRS = B04_11_IT_FIN_GL.B04_BSEG_BUKRS

	--Get g/l account information from SKAT
	LEFT JOIN A_SKAT
	ON A_SKAT.SKAT_KTOPL = A_T001.T001_KTOPL AND
	   A_SKAT.SKAT_SAKNR = B04_11_IT_FIN_GL.B04_BSEG_HKONT AND
	   A_SKAT.SKAT_SPRAS IN ('E', 'EN')

	--Get document type text description
	LEFT JOIN A_T003T
	ON A_T003T.T003T_SPRAS IN ('E', 'EN') AND
	   A_T003T.T003T_BLART = B04_11_IT_FIN_GL.B04_BKPF_BLART

	--Get posting key desctiption from TBSLT
	LEFT JOIN A_TBSLT
	ON A_TBSLT.TBSLT_SPRAS IN ('E', 'EN') AND
	   A_TBSLT.TBSLT_BSCHL = B04_11_IT_FIN_GL.B04_BSEG_BSCHL AND
	   A_TBSLT.TBSLT_UMSKZ = B04_11_IT_FIN_GL.B04_BSEG_UMSKZ

	--Get vendor name from LFA1
	LEFT JOIN A_LFA1
	ON A_LFA1.LFA1_LIFNR = B04_11_IT_FIN_GL.B04_BSEG_LIFNR

	-- Get customer from KNA1
	LEFT JOIN A_KNA1
	ON A_KNA1.KNA1_KUNNR = B04_11_IT_FIN_GL.B04_BSEG_KUNNR

	--Get user name for V_USNAM
	LEFT JOIN A_V_USERNAME
	ON A_V_USERNAME.V_USERNAME_BNAME = B04_11_IT_FIN_GL.B04_BKPF_USNAM

	--Get information from AM_SCOPE
	LEFT JOIN AM_SCOPE
	ON AM_SCOPE.SCOPE_CMPNY_CODE = B04_11_IT_FIN_GL.B04_BSEG_BUKRS

	--Get vendor group description
	LEFT JOIN AM_T077Y
	ON AM_T077Y.T077Y_KTOKK = A_LFA1.LFA1_KTOKK AND
	   AM_T077Y.T077Y_SPRAS IN ('E', 'EN')

	--Get customer group description
	LEFT JOIN AM_T077X
	ON AM_T077X.T077X_KTOKD = A_KNA1.KNA1_KTOKD AND
	   AM_T077X.T077X_SPRAS IN ('E', 'EN')
	
	--Get transaction code desction
	LEFT JOIN A_TSTCT
	ON A_TSTCT.TSTCT_SPRSL IN ('E', 'EN') AND
	   A_TSTCT.TSTCT_TCODE = B04_11_IT_FIN_GL.B04_BKPF_TCODE

	--Get special g/l indicator description
	LEFT JOIN A_T074T
	ON A_T074T.T074T_SPRAS IN ('E', 'EN') AND
	   A_T074T.T074T_KOART = B04_11_IT_FIN_GL.B04_BSEG_KOART AND
	   A_T074T.T074T_SHBKZ = B04_11_IT_FIN_GL.B04_BSEG_UMSKZ

/*Step 6: Create PO blanket table.*/
	EXEC SP_REMOVE_TABLES 'B12_06_IT_PTP_PO_BLANKET'
	SELECT B09_13_IT_PTP_POS.*,
		   A_LFA1.LFA1_NAME1 AS B09_ZF_LFA1_NAME1
	INTO B12_06_IT_PTP_PO_BLANKET
	FROM B09_13_IT_PTP_POS
		LEFT JOIN A_LFA1
		ON B09_13_IT_PTP_POS.B09_EKKO_LIFNR = A_LFA1.LFA1_LIFNR
	WHERE B09_ZF_BLANKET_PO = 'Yes'

	EXEC SP_RENAME_FIELD 'B12_07_', 'B12_07_IT_SR_SNAPSHOT'
	EXEC SP_UNNAME_FIELD 'B04_', 'B12_08_IT_SR_DOCUMENTS'
	EXEC SP_RENAME_FIELD 'B12_08_', 'B12_08_IT_SR_DOCUMENTS'	   
GO
