USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE   PROC [dbo].[script_B00_REPLACE_VIEW_BY_TABLE]

AS

/*  Change history comments
	Update history 
	-------------------------------------------------------
	Date            | Who   |  Description 
	--  23-03-2022	| Thuan	| Remove MANDT field in join
*/

--DYNAMIC_SCRIPT_START

			--Declare parameters here
			DECLARE
			@currency nvarchar(max)			= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'currency')
			,@date1 nvarchar(max)				= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'date1')
			,@date2 nvarchar(max)				= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'date2')
			,@downloaddate nvarchar(max)		= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'downloaddate')
			,@exchangeratetype nvarchar(max)	= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'exchangeratetype')
			,@language1 nvarchar(max)			= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'language1')
			,@language2 nvarchar(max)			= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'language2')
			,@year nvarchar(max)				= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'year')
			,@id nvarchar(max)					= (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'id')
			,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
			,@ZV_DATE nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'ZV_DATE')

/*Test mode*/

SET ROWCOUNT @LIMIT_RECORDS

DECLARE @NEWGL NVARCHAR(10) = (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'New_GL')

EXEC SP_DROPTABLE 'B00_CEPCT'

SELECT 
	DISTINCT A.*
INTO B00_CEPCT
FROM A_CEPCT A
INNER JOIN 
	(
		SELECT CEPCT_MANDT, CEPCT_KOKRS, CEPCT_PRCTR, MAX(CEPCT_DATBI) AS ZF_CEPCT_DATBI_MAX
		FROM A_CEPCT
		WHERE CEPCT_SPRAS IN 
			(
				SELECT dbo.GET_PARAM('language1')
				UNION 
				SELECT dbo.GET_PARAM('language2')
			)
		GROUP BY CEPCT_MANDT, CEPCT_KOKRS, CEPCT_PRCTR
	) B
ON  A.CEPCT_KOKRS = B.CEPCT_KOKRS
AND A.CEPCT_PRCTR = B.CEPCT_PRCTR
AND A.CEPCT_DATBI = B.ZF_CEPCT_DATBI_MAX
WHERE A.CEPCT_SPRAS IN 
			(
				SELECT dbo.GET_PARAM('language1')
				UNION 
				SELECT dbo.GET_PARAM('language2')
			)

EXEC SP_CREATE_INDEX  'CEPCT_KOKRS, CEPCT_PRCTR', 'B00_CEPCT'

EXEC SP_DROPTABLE 'B00_CSKT'

SELECT 
	DISTINCT A.*
INTO B00_CSKT
FROM A_CSKT A
INNER JOIN 
	(
		SELECT CSKT_MANDT, CSKT_KOKRS, CSKT_KOSTL, MAX(CSKT_DATBI) AS ZF_CSKT_DATBI_MAX
		FROM A_CSKT
		WHERE CSKT_SPRAS IN 
			(
				SELECT dbo.GET_PARAM('language1')
				UNION 
				SELECT dbo.GET_PARAM('language2')
			)
		GROUP BY CSKT_MANDT, CSKT_KOKRS, CSKT_KOSTL
	) B
ON  A.CSKT_KOKRS = B.CSKT_KOKRS
AND A.CSKT_KOSTL = B.CSKT_KOSTL
AND A.CSKT_DATBI = B.ZF_CSKT_DATBI_MAX
WHERE A.CSKT_SPRAS IN 
			(
				SELECT dbo.GET_PARAM('language1')
				UNION 
				SELECT dbo.GET_PARAM('language2')
			)

EXEC SP_CREATE_INDEX 'CSKT_MANDT, CSKT_KOSTL', 'B00_CSKT'

EXEC SP_DROPTABLE 'B00_DD07T'

SELECT 
		A_DD07T.DD07T_DOMNAME,
		A_DD07T.DD07T_VALPOS,
		DD07T_language1.DD07T_DDLANGUAGE,
		DD07T_language1.DD07T_DDTEXT,
		A_DD07T.DD07T_DOMVALUE_L,
		LEFT(A_DD07T.DD07T_DOMVALUE_L,1) DD07T_DOMVALUE_L_LEFT_1
INTO B00_DD07T
FROM     (SELECT DISTINCT  DD07T_DOMNAME, DD07T_VALPOS, DD07T_DOMVALUE_L
                  FROM      dbo.A_DD07T) AS A_DD07T LEFT OUTER JOIN
                      (SELECT  DD07T_DOMNAME, DD07T_VALPOS, DD07T_DDLANGUAGE, MAX(DD07T_DDTEXT) AS DD07T_DDTEXT
                       FROM      dbo.A_DD07T
                       WHERE   (DD07T_DDLANGUAGE = dbo.GET_PARAM('language1'))
                       GROUP BY DD07T_DOMNAME, DD07T_VALPOS, DD07T_DDLANGUAGE) AS DD07T_language1 ON A_DD07T.DD07T_VALPOS = DD07T_language1.DD07T_VALPOS AND 
                  A_DD07T.DD07T_DOMNAME = DD07T_language1.DD07T_DOMNAME

EXEC SP_CREATE_INDEX 'DD07T_DOMVALUE_L_LEFT_1', 'B00_DD07T'

EXEC SP_DROPTABLE 'B00_TB'
IF @NEWGL = 'N'
BEGIN
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '00' AS GLT0_MONAT, Sum(GLT0_HSLVT) AS [HSLV1_16], Sum(GLT0_KSLVT) AS [KSLV1_16]
	INTO B00_TB
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '01' AS GLT0_MONAT, Sum(GLT0_HSL01) AS [HSLV1_16], Sum(GLT0_KSL01) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '02' AS GLT0_MONAT, Sum(GLT0_HSL02) AS [HSLV1_16], Sum(GLT0_KSL02) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '03' AS GLT0_MONAT, Sum(GLT0_HSL03) AS [HSLV1_16], Sum(GLT0_KSL03) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '04' AS GLT0_MONAT, Sum(GLT0_HSL04) AS [HSLV1_16], Sum(GLT0_KSL04) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '05' AS GLT0_MONAT, Sum(GLT0_HSL05) AS [HSLV1_16], Sum(GLT0_KSL05) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '06' AS GLT0_MONAT, Sum(GLT0_HSL06) AS [HSLV1_16], Sum(GLT0_KSL06) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '07' AS GLT0_MONAT, Sum(GLT0_HSL07) AS [HSLV1_16], Sum(GLT0_KSL07) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					 GLT0_RTCUR, '08' AS GLT0_MONAT, Sum(GLT0_HSL08) AS [HSLV1_16], Sum(GLT0_KSL08) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '09' AS GLT0_MONAT, Sum(GLT0_HSL09) AS [HSLV1_16], Sum(GLT0_KSL09) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '10' AS GLT0_MONAT, Sum(GLT0_HSL10) AS [HSLV1_16], Sum(GLT0_KSL10) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					 GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '11' AS GLT0_MONAT, Sum(GLT0_HSL11) AS [HSLV1_16], Sum(GLT0_KSL11) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '12' AS GLT0_MONAT, Sum(GLT0_HSL12) AS [HSLV1_16], Sum(GLT0_KSL12) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '13' AS GLT0_MONAT, Sum(GLT0_HSL13) AS [HSLV1_16], Sum(GLT0_KSL13) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '14' AS GLT0_MONAT, Sum(GLT0_HSL14) AS [HSLV1_16], Sum(GLT0_KSL14) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '15' AS GLT0_MONAT, Sum(GLT0_HSL15) AS [HSLV1_16], Sum(GLT0_KSL15) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR
	UNION ALL
	SELECT GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR, '16' AS GLT0_MONAT, Sum(GLT0_HSL16) AS [HSLV1_16], Sum(GLT0_KSL16) AS [KSLV1_16]
	FROM     A_GLT0
	GROUP BY GLT0_RCLNT, GLT0_BUKRS, GLT0_RACCT,   GLT0_RYEAR, GLT0_RLDNR, GLT0_RRCTY, GLT0_DRCRK, GLT0_RBUSA, 
					  GLT0_RTCUR

	EXEC SP_UNNAME_FIELD 'GLT0_','B00_TB'
	EXEC SP_RENAME_FIELD 'TB_', 'B00_TB'
END
ELSE
BEGIN
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
                  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '00' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSLVT) AS [HSLV1_16], Sum(FAGLFLEXT_KSLVT) AS [KSLV1_16]
	INTO B00_TB
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '01' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL01) AS [HSLV1_16], Sum(FAGLFLEXT_KSL01) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '02' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL02) AS [HSLV1_16], Sum(FAGLFLEXT_KSL02) AS [HSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '03' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL03) AS [HSLV1_16], Sum(FAGLFLEXT_KSL03) AS [HSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '04' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL04) AS [HSLV1_16], Sum(FAGLFLEXT_KSL04) AS [HSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '05' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL05) AS [HSLV1_16], Sum(FAGLFLEXT_KSL05) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '06' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL06) AS [HSLV1_16], Sum(FAGLFLEXT_KSL06) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '07' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL07) AS [HSLV1_16], Sum(FAGLFLEXT_KSL07) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '08' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL08) AS [HSLV1_16], Sum(FAGLFLEXT_KSL08) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '09' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL09) AS [HSLV1_16], Sum(FAGLFLEXT_KSL09) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '10' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL10) AS [HSLV1_16], Sum(FAGLFLEXT_KSL10) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '11' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL11) AS [HSLV1_16], Sum(FAGLFLEXT_KSL11) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '12' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL12) AS [HSLV1_16], Sum(FAGLFLEXT_KSL12) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '13' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL13) AS [HSLV1_16], Sum(FAGLFLEXT_KSL13) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '14' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL14) AS [HSLV1_16], Sum(FAGLFLEXT_KSL14) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '15' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL15) AS [HSLV1_16], Sum(FAGLFLEXT_KSL15) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	UNION ALL
	SELECT FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS FAGLFLEXT_BUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR, '16' AS FAGLFLEXT_MONAT, Sum(FAGLFLEXT_HSL16) AS [HSLV1_16], Sum(FAGLFLEXT_KSL16) AS [KSLV1_16]
	FROM     A_FAGLFLEXT
	GROUP BY FAGLFLEXT_RCLNT, FAGLFLEXT_RBUKRS, FAGLFLEXT_RACCT, FAGLFLEXT_KOKRS, FAGLFLEXT_PRCTR, FAGLFLEXT_RYEAR, FAGLFLEXT_RLDNR, FAGLFLEXT_RRCTY, FAGLFLEXT_DRCRK, FAGLFLEXT_RBUSA, 
					  FAGLFLEXT_SEGMENT, FAGLFLEXT_RTCUR
	EXEC SP_UNNAME_FIELD 'FAGLFLEXT_','B00_TB'
	EXEC SP_RENAME_FIELD 'TB_', 'B00_TB'
END

	
	ALTER TABLE B00_TB ADD ZF_DATE DATE
	IF CHARINDEX('RUSSIA', DB_NAME() ) <> 0
	BEGIN

		UPDATE B00_TB
		SET ZF_DATE = 
				CASE
					WHEN CAST(TB_MONAT AS INT) = 0 THEN CAST(CAST(TB_RYEAR-1 AS NVARCHAR)+'-'+@ZV_DATE AS DATE)
					WHEN CAST(TB_MONAT AS INT) BETWEEN 1 AND 11  THEN DATEADD(MONTH, CAST(TB_MONAT AS INT), CAST(CAST(TB_RYEAR-1 AS NVARCHAR)+'-'+@ZV_DATE AS DATE))
					ELSE CAST(CAST(TB_RYEAR AS NVARCHAR)+'-'+@ZV_DATE AS DATE)
				END 
	END
	ELSE
		BEGIN
			
		UPDATE B00_TB
		SET ZF_DATE = 
				CASE
					WHEN CAST(TB_MONAT AS INT) = 0 THEN CAST(CAST(TB_RYEAR AS NVARCHAR)+'-'+@ZV_DATE AS DATE)
					WHEN CAST(TB_MONAT AS INT) BETWEEN 1 AND 11  THEN DATEADD(MONTH, CAST(TB_MONAT AS INT), CAST(CAST(TB_RYEAR AS NVARCHAR)+'-'+@ZV_DATE AS DATE))
					ELSE CAST(CAST(TB_RYEAR + 1 AS NVARCHAR)+'-'+@ZV_DATE AS DATE)
				END 
		END


EXEC SP_CREATE_INDEX 'TB_RCLNT, TB_RACCT, TB_BUKRS', 'B00_TB'

EXEC SP_DROPTABLE 'B00_MAKT'

SELECT 
	A_MAKT.MAKT_MANDT,
	A_MAKT.MAKT_MATNR,
	ISNULL(MAKT_1.MAKT_SPRAS, MAKT_2.MAKT_SPRAS) AS MAKT_SPRAS,
	ISNULL(MAKT_1.MAKT_MAKTX, MAKT_2.MAKT_MAKTX) AS MAKT_MAKTX
INTO B00_MAKT
FROM     (SELECT MAKT_MANDT, MAKT_MATNR
                  FROM      dbo.A_MAKT AS MAKT_5
                  GROUP BY MAKT_MANDT, MAKT_MATNR) AS A_MAKT LEFT OUTER JOIN
                      (SELECT MAKT_MANDT, MAKT_MATNR, MAKT_SPRAS, MAX(MAKT_MAKTX) AS MAKT_MAKTX
                       FROM      dbo.A_MAKT AS MAKT_4
                       WHERE   (MAKT_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY MAKT_MANDT, MAKT_MATNR, MAKT_SPRAS) AS MAKT_1 ON A_MAKT.MAKT_MATNR = MAKT_1.MAKT_MATNR  LEFT OUTER JOIN
                      (SELECT MAKT_MANDT, MAKT_MATNR, MAKT_SPRAS, MAX(MAKT_MAKTX) AS MAKT_MAKTX
                       FROM      dbo.A_MAKT AS MAKT_3
                       WHERE   (MAKT_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY MAKT_MANDT, MAKT_MATNR, MAKT_SPRAS) AS MAKT_2 ON A_MAKT.MAKT_MATNR = MAKT_2.MAKT_MATNR

EXEC SP_CREATE_INDEX 'MAKT_MANDT, MAKT_MATNR', 'B00_MAKT'

EXEC SP_DROPTABLE 'B00_SKAT'
SELECT A_SKAT.SKAT_MANDT, A_SKAT.SKAT_KTOPL, A_SKAT.SKAT_SAKNR, ISNULL(SKAT_1.SKAT_TXT20, SKAT_2.SKAT_TXT20) AS SKAT_TXT20, ISNULL(SKAT_1.SKAT_TXT50, SKAT_2.SKAT_TXT50) AS SKAT_TXT50, 
                  ISNULL(SKAT_1.SKAT_MCOD1, SKAT_2.SKAT_MCOD1) AS SKAT_MCOD1, ISNULL(SKAT_1.SKAT_SPRAS, SKAT_2.SKAT_SPRAS) AS SKAT_SPRAS
INTO B00_SKAT
FROM     (SELECT DISTINCT SKAT_MANDT, SKAT_KTOPL, SKAT_SAKNR
                  FROM      dbo.A_SKAT) AS A_SKAT LEFT OUTER JOIN
                      (SELECT SKAT_MANDT, SKAT_KTOPL, SKAT_SAKNR, SKAT_SPRAS, MAX(SKAT_TXT20) AS SKAT_TXT20, MAX(SKAT_TXT50) AS SKAT_TXT50, MAX(SKAT_MCOD1) AS SKAT_MCOD1
                       FROM      dbo.A_SKAT
                       WHERE   (SKAT_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY SKAT_MANDT, SKAT_KTOPL, SKAT_SAKNR, SKAT_SPRAS) AS SKAT_1 ON  A_SKAT.SKAT_KTOPL = SKAT_1.SKAT_KTOPL AND 
                  A_SKAT.SKAT_SAKNR = SKAT_1.SKAT_SAKNR LEFT OUTER JOIN
                      (SELECT SKAT_MANDT, SKAT_KTOPL, SKAT_SAKNR, SKAT_SPRAS, MAX(SKAT_TXT20) AS SKAT_TXT20, MAX(SKAT_TXT50) AS SKAT_TXT50, MAX(SKAT_MCOD1) AS SKAT_MCOD1
                       FROM      dbo.A_SKAT
                       WHERE   (SKAT_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY SKAT_MANDT, SKAT_KTOPL, SKAT_SAKNR, SKAT_SPRAS) AS SKAT_2 ON  A_SKAT.SKAT_KTOPL = SKAT_2.SKAT_KTOPL AND 
                  A_SKAT.SKAT_SAKNR = SKAT_2.SKAT_SAKNR

EXEC SP_CREATE_INDEX 'SKAT_MANDT, SKAT_SAKNR, SKAT_KTOPL', 'B00_SKAT'

EXEC SP_DROPTABLE 'B00_T003T'
SELECT A_T003T.T003T_MANDT, A_T003T.T003T_BLART, ISNULL(T003T_language1.T003T_SPRAS, T003T_language2.T003T_SPRAS) AS T003T_SPRAS, ISNULL(T003T_language1.T003T_LTEXT, T003T_language2.T003T_LTEXT) 
                  AS T003T_LTEXT
INTO B00_T003T
FROM     (SELECT DISTINCT T003T_MANDT, T003T_BLART
                  FROM      dbo.A_T003T) AS A_T003T LEFT OUTER JOIN
                      (SELECT T003T_MANDT, T003T_BLART, T003T_SPRAS, MAX(T003T_LTEXT) AS T003T_LTEXT
                       FROM      dbo.A_T003T
                       WHERE   (T003T_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T003T_MANDT, T003T_BLART, T003T_SPRAS) AS T003T_language1 ON A_T003T.T003T_BLART = T003T_language1.T003T_BLART LEFT OUTER JOIN
                      (SELECT T003T_MANDT, T003T_BLART, T003T_SPRAS, MAX(T003T_LTEXT) AS T003T_LTEXT
                       FROM      dbo.A_T003T
                       WHERE   (T003T_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T003T_MANDT, T003T_BLART, T003T_SPRAS) AS T003T_language2 ON  A_T003T.T003T_BLART = T003T_language2.T003T_BLART

EXEC SP_CREATE_INDEX 'T003T_MANDT, T003T_BLART', 'B00_T003T'

EXEC SP_REMOVE_TABLES 'B00_T009B'
SELECT DISTINCT 
	T009B_PERIV,
	T009B_BDATJ,
	CAST(T009B_BUMON AS INT) T009B_BUMON,
	CAST(T009B_BUTAG AS INT) T009B_BUTAG,
	CAST(T009B_POPER AS INT) T009B_POPER,
	CAST(T009B_RELJR AS INT) T009B_RELJR
INTO B00_T009B
FROM A_T009B

EXEC SP_DROPTABLE 'B00_T014T'
SELECT A_T014T.T014T_MANDT, A_T014T.T014T_KKBER, ISNULL(T014T_language1.T014T_SPRAS, T014T_language2.T014T_SPRAS) AS T014T_SPRAS, ISNULL(T014T_language1.T014T_KKBTX, T014T_language2.T014T_KKBTX) 
                  AS T014T_KKBTX
INTO B00_T014T
FROM     (SELECT DISTINCT T014T_MANDT, T014T_KKBER, T014T_KKBTX
                  FROM      dbo.A_T014T) AS A_T014T LEFT OUTER JOIN
                      (SELECT T014T_MANDT, T014T_KKBER, T014T_SPRAS, MAX(T014T_KKBTX) AS T014T_KKBTX
                       FROM      dbo.A_T014T
                       WHERE   (T014T_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T014T_MANDT, T014T_KKBER, T014T_SPRAS) AS T014T_language1 ON A_T014T.T014T_KKBER = T014T_language1.T014T_KKBER  LEFT OUTER JOIN
                      (SELECT T014T_MANDT, T014T_KKBER, T014T_SPRAS, MAX(T014T_KKBTX) AS T014T_KKBTX
                       FROM      dbo.A_T014T
                       WHERE   (T014T_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T014T_MANDT, T014T_KKBER, T014T_SPRAS) AS T014T_language2 ON A_T014T.T014T_KKBER = T014T_language2.T014T_KKBER 

EXEC SP_CREATE_INDEX 'T014T_MANDT, T014T_KKBER', 'B00_T014T'

EXEC SP_DROPTABLE 'B00_T023T'

SELECT A_T023T.T023T_MANDT, A_T023T.T023T_MATKL, ISNULL(T023T_language1.T023T_SPRAS, T023T_language2.T023T_SPRAS) AS T023T_SPRAS, ISNULL(T023T_language1.T023T_WGBEZ, T023T_language2.T023T_WGBEZ) 
                  AS T023T_WGBEZ
INTO B00_T023T
FROM     (SELECT DISTINCT T023T_MANDT, T023T_MATKL
                  FROM      dbo.A_T023T AS T023T_3) AS A_T023T LEFT OUTER JOIN
                      (SELECT T023T_MANDT, T023T_MATKL, T023T_SPRAS, MAX(T023T_WGBEZ) AS T023T_WGBEZ
                       FROM      dbo.A_T023T AS T023T_2
                       WHERE   (T023T_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T023T_MANDT, T023T_MATKL, T023T_SPRAS) AS T023T_language1 ON A_T023T.T023T_MATKL = T023T_language1.T023T_MATKL LEFT OUTER JOIN
                      (SELECT T023T_MANDT, T023T_MATKL, T023T_SPRAS, MAX(T023T_WGBEZ) AS T023T_WGBEZ
                       FROM      dbo.A_T023T AS T023T_1
                       WHERE   (T023T_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T023T_MANDT, T023T_MATKL, T023T_SPRAS) AS T023T_language2 ON  A_T023T.T023T_MATKL = T023T_language2.T023T_MATKL

EXEC SP_CREATE_INDEX 'T023T_MANDT, T023T_MATKL', 'B00_T023T'



EXEC SP_DROPTABLE 'B00_T052U'

SELECT A_T052U.T052U_MANDT, A_T052U.T052U_ZTERM, ISNULL(T052U_lang1.T052U_TEXT1, T052U_lang2.T052U_TEXT1) AS T052U_TEXT1
INTO B00_T052U
FROM     (SELECT DISTINCT T052U_MANDT, T052U_ZTERM
                  FROM      dbo.A_T052U AS T052U_3) AS A_T052U LEFT OUTER JOIN
                      (SELECT T052U_MANDT, T052U_ZTERM, MAX(T052U_TEXT1) AS T052U_TEXT1
                       FROM      dbo.A_T052U AS T052U_2
                       WHERE   (T052U_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T052U_MANDT, T052U_ZTERM) AS T052U_lang1 ON A_T052U.T052U_ZTERM = T052U_lang1.T052U_ZTERM  LEFT OUTER JOIN
                      (SELECT T052U_MANDT, T052U_ZTERM, MAX(T052U_TEXT1) AS T052U_TEXT1
                       FROM      dbo.A_T052U AS T052U_1
                       WHERE   (T052U_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T052U_MANDT, T052U_ZTERM) AS T052U_lang2 ON A_T052U.T052U_ZTERM = T052U_lang2.T052U_ZTERM 

EXEC SP_CREATE_INDEX 'T052U_MANDT, T052U_ZTERM', 'B00_T052U'


EXEC SP_DROPTABLE 'B00_T077X'

SELECT A_T077X.T077X_MANDT, A_T077X.T077X_KTOKD, ISNULL(T077X_language1.T077X_SPRAS, T077X_language2.T077X_SPRAS) AS T077X_SPRAS, ISNULL(T077X_language1.T077X_TXT30, T077X_language2.T077X_TXT30) 
                  AS T077X_TXT30
INTO B00_T077X
FROM     (SELECT DISTINCT T077X_MANDT, T077X_KTOKD, T077X_TXT30
                  FROM      dbo.A_T077X) AS A_T077X LEFT OUTER JOIN
                      (SELECT T077X_MANDT, T077X_KTOKD, T077X_SPRAS, MAX(T077X_TXT30) AS T077X_TXT30
                       FROM      dbo.A_T077X
                       WHERE   (T077X_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T077X_MANDT, T077X_KTOKD, T077X_SPRAS) AS T077X_language1 ON A_T077X.T077X_KTOKD = T077X_language1.T077X_KTOKD  LEFT OUTER JOIN
                      (SELECT T077X_MANDT, T077X_KTOKD, T077X_SPRAS, MAX(T077X_TXT30) AS T077X_TXT30
                       FROM      dbo.A_T077X
                       WHERE   (T077X_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T077X_MANDT, T077X_KTOKD, T077X_SPRAS) AS T077X_language2 ON A_T077X.T077X_KTOKD = T077X_language2.T077X_KTOKD 

EXEC SP_CREATE_INDEX 'T077X_MANDT, T077X_KTOKD', 'B00_T077X'


EXEC SP_DROPTABLE 'B00_T077Y'

SELECT A_T077Y.T077Y_MANDT, A_T077Y.T077Y_KTOKK, ISNULL(T077Y_language1.T077Y_SPRAS, T077Y_language2.T077Y_SPRAS) AS T077Y_SPRAS, ISNULL(T077Y_language1.T077Y_TXT30, T077Y_language2.T077Y_TXT30) 
                  AS T077Y_TXT30
INTO B00_T077Y
FROM     (SELECT DISTINCT T077Y_MANDT, T077Y_KTOKK
                  FROM      dbo.A_T077Y) AS A_T077Y LEFT OUTER JOIN
                      (SELECT T077Y_MANDT, T077Y_KTOKK, T077Y_SPRAS, MAX(T077Y_TXT30) AS T077Y_TXT30
                       FROM      dbo.A_T077Y
                       WHERE   (T077Y_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T077Y_MANDT, T077Y_KTOKK, T077Y_SPRAS) AS T077Y_language1 ON A_T077Y.T077Y_KTOKK = T077Y_language1.T077Y_KTOKK  LEFT OUTER JOIN
                      (SELECT T077Y_MANDT, T077Y_KTOKK, T077Y_SPRAS, MAX(T077Y_TXT30) AS T077Y_TXT30
                       FROM      dbo.A_T077Y
                       WHERE   (T077Y_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T077Y_MANDT, T077Y_KTOKK, T077Y_SPRAS) AS T077Y_language2 ON  A_T077Y.T077Y_KTOKK = T077Y_language2.T077Y_KTOKK

EXEC SP_CREATE_INDEX 'T077Y_MANDT, T077Y_KTOKK', 'B00_T077Y'



EXEC SP_DROPTABLE 'B00_T134T'

SELECT A_T134T.T134T_MANDT, A_T134T.T134T_MTART, ISNULL(T134T_language1.T134T_SPRAS, T134T_language2.T134T_SPRAS) AS T134T_SPRAS, ISNULL(T134T_language1.T134T_MTBEZ, T134T_language2.T134T_MTBEZ) 
                  AS T134T_MTBEZ
INTO B00_T134T
FROM     (SELECT DISTINCT T134T_MANDT, T134T_MTART
                  FROM      dbo.A_T134T) AS A_T134T LEFT OUTER JOIN
                      (SELECT T134T_MANDT, T134T_MTART, T134T_SPRAS, MAX(T134T_MTBEZ) AS T134T_MTBEZ
                       FROM      dbo.A_T134T
                       WHERE   (T134T_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T134T_MANDT, T134T_MTART, T134T_SPRAS) AS T134T_language1 ON A_T134T.T134T_MTART = T134T_language1.T134T_MTART  LEFT OUTER JOIN
                      (SELECT T134T_MANDT, T134T_MTART, T134T_SPRAS, MAX(T134T_MTBEZ) AS T134T_MTBEZ
                       FROM      dbo.A_T134T
                       WHERE   (T134T_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T134T_MANDT, T134T_MTART, T134T_SPRAS) AS T134T_language2 ON A_T134T.T134T_MTART = T134T_language2.T134T_MTART

EXEC SP_CREATE_INDEX 'T134T_MANDT, T134T_MTART', 'B00_T134T'

EXEC SP_DROPTABLE 'B00_T163Y'

SELECT A_T163Y.T163Y_MANDT, A_T163Y.T163Y_PSTYP, ISNULL(T163Y_language1.T163Y_SPRAS, T163Y_language2.T163Y_SPRAS) AS T163Y_SPRAS, ISNULL(T163Y_language1.T163Y_PTEXT, T163Y_language2.T163Y_PTEXT) 
                  AS T163Y_PTEXT
INTO B00_T163Y
FROM     (SELECT DISTINCT T163Y_MANDT, T163Y_PSTYP
                  FROM      dbo.A_T163Y) AS A_T163Y LEFT OUTER JOIN
                      (SELECT T163Y_MANDT, T163Y_PSTYP, T163Y_SPRAS, MAX(T163Y_PTEXT) AS T163Y_PTEXT
                       FROM      dbo.A_T163Y
                       WHERE   (T163Y_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T163Y_MANDT, T163Y_PSTYP, T163Y_SPRAS) AS T163Y_language1 ON A_T163Y.T163Y_PSTYP = T163Y_language1.T163Y_PSTYP  LEFT OUTER JOIN
                      (SELECT T163Y_MANDT, T163Y_PSTYP, T163Y_SPRAS, MAX(T163Y_PTEXT) AS T163Y_PTEXT
                       FROM      dbo.A_T163Y
                       WHERE   (T163Y_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T163Y_MANDT, T163Y_PSTYP, T163Y_SPRAS) AS T163Y_language2 ON  A_T163Y.T163Y_PSTYP = T163Y_language2.T163Y_PSTYP

EXEC SP_CREATE_INDEX 'T163Y_MANDT, T163Y_PSTYP', 'B00_T163Y'


EXEC SP_DROPTABLE 'B00_TBSLT'

SELECT A_TBSLT.TBSLT_MANDT, A_TBSLT.TBSLT_BSCHL, A_TBSLT.TBSLT_UMSKZ, ISNULL(TBSLT_1.TBSLT_SPRAS, TBSLT_2.TBSLT_SPRAS) AS TBSLT_SPRAS, ISNULL(TBSLT_1.TBSLT_LTEXT, TBSLT_2.TBSLT_LTEXT) 
                  AS TBSLT_LTEXT
INTO B00_TBSLT
FROM     (SELECT TBSLT_MANDT, TBSLT_BSCHL, ISNULL(TBSLT_UMSKZ, '') AS TBSLT_UMSKZ
                  FROM      dbo.A_TBSLT
                  GROUP BY TBSLT_MANDT, TBSLT_BSCHL, TBSLT_UMSKZ) AS A_TBSLT LEFT OUTER JOIN
                      (SELECT TBSLT_MANDT, TBSLT_BSCHL, ISNULL(TBSLT_UMSKZ, '') AS TBSLT_UMSKZ, TBSLT_SPRAS, MAX(TBSLT_LTEXT) AS TBSLT_LTEXT
                       FROM      dbo.A_TBSLT
                       WHERE   (TBSLT_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY TBSLT_MANDT, TBSLT_BSCHL, TBSLT_UMSKZ, TBSLT_SPRAS) AS TBSLT_1 ON A_TBSLT.TBSLT_UMSKZ = TBSLT_1.TBSLT_UMSKZ AND A_TBSLT.TBSLT_BSCHL = TBSLT_1.TBSLT_BSCHL  LEFT OUTER JOIN
                      (SELECT TBSLT_MANDT, TBSLT_BSCHL, ISNULL(TBSLT_UMSKZ, '') AS TBSLT_UMSKZ, TBSLT_SPRAS, MAX(TBSLT_LTEXT) AS TBSLT_LTEXT
                       FROM      dbo.A_TBSLT
                       WHERE   (TBSLT_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY TBSLT_MANDT, TBSLT_BSCHL, TBSLT_UMSKZ, TBSLT_SPRAS) AS TBSLT_2 ON A_TBSLT.TBSLT_UMSKZ = TBSLT_2.TBSLT_UMSKZ AND A_TBSLT.TBSLT_BSCHL = TBSLT_2.TBSLT_BSCHL 

EXEC SP_CREATE_INDEX 'TBSLT_MANDT, TBSLT_UMSKZ, TBSLT_BSCHL', 'B00_TBSLT'

EXEC SP_DROPTABLE 'B00_TCURX'

SELECT TCURX_CURRKEY, POWER(CAST(10 AS real), 2 - TCURX_CURRDEC) AS TCURX_FACTOR
INTO B00_TCURX
FROM     dbo.A_TCURX

EXEC SP_CREATE_INDEX 'TCURX_CURRKEY', 'B00_TCURX'

EXEC SP_DROPTABLE 'B00_TKUKT'

SELECT A_TKUKT.TKUKT_MANDT, A_TKUKT.TKUKT_KUKLA, ISNULL(TKUKT_language1.TKUKT_SPRAS, TKUKT_language2.TKUKT_SPRAS) AS TKUKT_SPRAS, ISNULL(TKUKT_language1.TKUKT_VTEXT, TKUKT_language2.TKUKT_VTEXT) 
                  AS TKUKT_VTEXT
INTO B00_TKUKT
FROM     (SELECT DISTINCT TKUKT_MANDT, TKUKT_KUKLA, TKUKT_VTEXT
                  FROM      dbo.A_TKUKT) AS A_TKUKT LEFT OUTER JOIN
                      (SELECT TKUKT_MANDT, TKUKT_KUKLA, TKUKT_SPRAS, MAX(TKUKT_VTEXT) AS TKUKT_VTEXT
                       FROM      dbo.A_TKUKT
                       WHERE   (TKUKT_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY TKUKT_MANDT, TKUKT_KUKLA, TKUKT_SPRAS) AS TKUKT_language1 ON A_TKUKT.TKUKT_KUKLA = TKUKT_language1.TKUKT_KUKLA  LEFT OUTER JOIN
                      (SELECT TKUKT_MANDT, TKUKT_KUKLA, TKUKT_SPRAS, MAX(TKUKT_VTEXT) AS TKUKT_VTEXT
                       FROM      dbo.A_TKUKT
                       WHERE   (TKUKT_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY TKUKT_MANDT, TKUKT_KUKLA, TKUKT_SPRAS) AS TKUKT_language2 ON A_TKUKT.TKUKT_KUKLA = TKUKT_language2.TKUKT_KUKLA 

EXEC SP_CREATE_INDEX 'TKUKT_MANDT, TKUKT_KUKLA', 'B00_TKUKT'


EXEC SP_DROPTABLE 'B00_TSTCT'

SELECT A_TSTCT.TSTCT_TCODE, ISNULL(TSTCT_language1.TSTCT_SPRSL, TSTCT_language2.TSTCT_SPRSL) AS TSTCT_SPRSL, ISNULL(TSTCT_language1.TSTCT_TTEXT, TSTCT_language2.TSTCT_TTEXT) 
                  AS TSTCT_TTEXT
INTO B00_TSTCT
FROM     (SELECT DISTINCT TSTCT_TCODE
                  FROM      dbo.A_TSTCT AS TSTCT_3) AS A_TSTCT LEFT OUTER JOIN
                      (SELECT TSTCT_TCODE, TSTCT_SPRSL, MAX(TSTCT_TTEXT) AS TSTCT_TTEXT
                       FROM      dbo.A_TSTCT AS TSTCT_2
                       WHERE   (TSTCT_SPRSL = dbo.GET_PARAM('language1'))
                       GROUP BY TSTCT_TCODE, TSTCT_SPRSL) AS TSTCT_language1 ON A_TSTCT.TSTCT_TCODE = TSTCT_language1.TSTCT_TCODE LEFT OUTER JOIN
                      (SELECT TSTCT_TCODE, TSTCT_SPRSL, MAX(TSTCT_TTEXT) AS TSTCT_TTEXT
                       FROM      dbo.A_TSTCT AS TSTCT_1
                       WHERE   (TSTCT_SPRSL = dbo.GET_PARAM('language2'))
                       GROUP BY TSTCT_TCODE, TSTCT_SPRSL) AS TSTCT_language2 ON A_TSTCT.TSTCT_TCODE = TSTCT_language2.TSTCT_TCODE

EXEC SP_CREATE_INDEX 'TSTCT_TCODE', 'B00_TSTCT'


EXEC SP_DROPTABLE 'B00_TUTYP'

SELECT A_TUTYP.TUTYP_USERTYP, ISNULL(TUTYP_language1.TUTYP_LANGU, TUTYP_language2.TUTYP_LANGU) AS TUTYP_LANGU, ISNULL(TUTYP_language1.TUTYP_UTYPTEXT, 
                  TUTYP_language2.TUTYP_UTYPTEXT) AS TUTYP_UTYPTEXT
INTO B00_TUTYP
FROM     (SELECT DISTINCT TUTYP_USERTYP
                  FROM      dbo.A_TUTYP AS TUTYP_3) AS A_TUTYP LEFT OUTER JOIN
                      (SELECT TUTYP_USERTYP, TUTYP_LANGU, MAX(TUTYP_UTYPTEXT) AS TUTYP_UTYPTEXT
                       FROM      dbo.A_TUTYP AS TUTYP_2
                       WHERE   (TUTYP_LANGU = dbo.GET_PARAM('language1'))
                       GROUP BY TUTYP_USERTYP, TUTYP_LANGU) AS TUTYP_language1 ON A_TUTYP.TUTYP_USERTYP = TUTYP_language1.TUTYP_USERTYP LEFT OUTER JOIN
                      (SELECT TUTYP_USERTYP, TUTYP_LANGU, MAX(TUTYP_UTYPTEXT) AS TUTYP_UTYPTEXT
                       FROM      dbo.A_TUTYP AS TUTYP_1
                       WHERE   (TUTYP_LANGU = dbo.GET_PARAM('language2'))
                       GROUP BY TUTYP_USERTYP, TUTYP_LANGU) AS TUTYP_language2 ON A_TUTYP.TUTYP_USERTYP = TUTYP_language2.TUTYP_USERTYP

EXEC SP_CREATE_INDEX 'TUTYP_USERTYP', 'B00_TUTYP'


EXEC SP_DROPTABLE 'B00_TVKOT'

SELECT A_TVKOT.TVKOT_MANDT, A_TVKOT.TVKOT_VKORG, ISNULL(TVKOT_language1.TVKOT_SPRAS, TVKOT_language2.TVKOT_SPRAS) AS TVKOT_SPRAS, ISNULL(TVKOT_language1.TVKOT_VTEXT, TVKOT_language2.TVKOT_VTEXT) 
                  AS TVKOT_VTEXT
INTO B00_TVKOT
FROM     (SELECT DISTINCT TVKOT_MANDT, TVKOT_VKORG
                  FROM      dbo.A_TVKOT) AS A_TVKOT LEFT OUTER JOIN
                      (SELECT TVKOT_MANDT, TVKOT_VKORG, TVKOT_SPRAS, MAX(TVKOT_VTEXT) AS TVKOT_VTEXT
                       FROM      dbo.A_TVKOT
                       WHERE   (TVKOT_SPRAS =
                                             (SELECT GLOBALS_VALUE
                                              FROM      dbo.AM_GLOBALS
                                              WHERE   (GLOBALS_PARAMETER = 'language1')))
                       GROUP BY TVKOT_MANDT, TVKOT_VKORG, TVKOT_SPRAS) AS TVKOT_language1 ON A_TVKOT.TVKOT_VKORG = TVKOT_language1.TVKOT_VKORG LEFT OUTER JOIN
                      (SELECT TVKOT_MANDT, TVKOT_VKORG, TVKOT_SPRAS, MAX(TVKOT_VTEXT) AS TVKOT_VTEXT
                       FROM      dbo.A_TVKOT
                       WHERE   (TVKOT_SPRAS =
                                             (SELECT GLOBALS_VALUE
                                              FROM      dbo.AM_GLOBALS
                                              WHERE   (GLOBALS_PARAMETER = 'language2')))
                       GROUP BY TVKOT_MANDT, TVKOT_VKORG, TVKOT_SPRAS) AS TVKOT_language2 ON  A_TVKOT.TVKOT_VKORG = TVKOT_language2.TVKOT_VKORG

EXEC SP_CREATE_INDEX 'TVKOT_MANDT, TVKOT_VKORG', 'B00_TVKOT'


EXEC SP_DROPTABLE 'B00_USR02'

SELECT USR02_MANDT, USR02_BNAME, USR02_BCODE, USR02_GLTGV, USR02_GLTGB, USR02_USTYP, USR02_CLASS, USR02_LOCNT, USR02_UFLAG, USR02_ACCNT, USR02_ANAME, USR02_ERDAT, USR02_TRDAT, USR02_LTIME, 
                  USR02_CODVN, USR02_TZONE, USR02_PASSCODE, USR02_PWDCHGDATE
INTO B00_USR02
FROM     dbo.A_USR02

EXEC SP_CREATE_INDEX  'USR02_BNAME', 'B00_USR02'


EXEC SP_DROPTABLE 'B00_T161T'


SELECT A_T161T.T161T_MANDT, A_T161T.T161T_BSART, A_T161T.T161T_BSTYP, 
  ISNULL([T161T_language1].[T161T_SPRAS],[T161T_language2].[T161T_SPRAS]) AS T161T_SPRAS,
  ISNULL([T161T_language1].[T161T_BATXT],[T161T_language2].[T161T_BATXT]) AS T161T_BATXT
INTO B00_T161T
  FROM ((SELECT DISTINCT T161T_MANDT, T161T_BSART, T161T_BSTYP FROM A_T161T)  AS A_T161T 

  LEFT JOIN (SELECT T161T_MANDT, T161T_BSART, T161T_BSTYP,T161T_SPRAS,MAX(T161T_BATXT) as T161T_BATXT FROM A_T161T WHERE T161T_SPRAS=dbo.get_param('language1') GROUP BY T161T_MANDT, T161T_BSART, T161T_BSTYP,T161T_SPRAS)  AS T161T_language1 ON (A_T161T.T161T_BSART = T161T_language1.T161T_BSART) AND (A_T161T.T161T_BSTYP = T161T_language1.T161T_BSTYP)) 

  LEFT JOIN (SELECT T161T_MANDT, T161T_BSART, T161T_BSTYP,T161T_SPRAS,MAX(T161T_BATXT) as T161T_BATXT FROM A_T161T WHERE T161T_SPRAS=dbo.get_param('language2') GROUP BY T161T_MANDT, T161T_BSART, T161T_BSTYP,T161T_SPRAS)  AS T161T_language2 ON (A_T161T.T161T_BSART = T161T_language2.T161T_BSART) AND (A_T161T.T161T_BSTYP = T161T_language2.T161T_BSTYP)

EXEC SP_CREATE_INDEX 'T161T_BSTYP,T161T_SPRAS,T161T_BATXT', 'B00_T161T'


--DECLARE @COPA_TABLE_NAME NVARCHAR(50) = (SELECT GLOBALS_VALUE FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'COPA_TABLE_NAME'),
--		@SQLCMD NVARCHAR(MAX) = ''
--EXEC SP_DROPTABLE 'B00_COPA'
--SET @SQLCMD = 'SELECT * INTO B00_COPA FROM ' + @COPA_TABLE_NAME
--EXEC SP_EXECUTESQL @SQLCMD
--DECLARE @UNNAMED_FIELD_VALUE NVARCHAR(50) = REPLACE(@COPA_TABLE_NAME, 'A_', '') + '_'
--EXEC SP_UNNAME_FIELD @UNNAMED_FIELD_VALUE, 'B00_COPA'
--EXEC SP_RENAME_FIELD 'COPA_', 'B00_COPA'


--Step XX: Table text descrption

	EXEC SP_DROPTABLE 'B00_DD02T_ENGLISH'
	SELECT DD02T_TABNAME, MAX(DD02T_DDTEXT) AS DD02T_DDTEXT
	INTO B00_DD02T_ENGLISH
	FROM A_DD02T
	WHERE (DD02T_DDLANGUAGE = @LANGUAGE1 OR DD02T_DDLANGUAGE = @LANGUAGE2) AND DD02T_AS4LOCAL = 'A'
	GROUP BY DD02T_TABNAME

--Step XX: Field text descrption


	EXEC SP_DROPTABLE 'B00_DDFTX_ENGLISH'
	SELECT DDFTX_TABNAME, DDFTX_FIELDNAME, DDFTX_DDLANGUAGE, MAX(DDFTX_SCRTEXT_L) DDFTX_SCRTEXT_L
	INTO B00_DDFTX_ENGLISH
	FROM A_DDFTX
	WHERE (DDFTX_DDLANGUAGE = @LANGUAGE1 OR DDFTX_DDLANGUAGE = @LANGUAGE2) 
	GROUP BY DDFTX_TABNAME, DDFTX_FIELDNAME, DDFTX_DDLANGUAGE

--Step XX: User type description

	EXEC SP_DROPTABLE 'B00_DD07T_XUUSTYP_ENGLISH'
	SELECT DD07T_DOMNAME, DD07T_DOMVALUE_L, MAX(DD07T_DDTEXT) AS DD07T_DDTEXT
	INTO B00_DD07T_XUUSTYP_ENGLISH
	FROM A_DD07T
	WHERE DD07T_DOMNAME = 'XUUSTYP' AND (DD07T_DDLANGUAGE = @LANGUAGE1 OR DD07T_DDLANGUAGE = @LANGUAGE2) AND DD07T_AS4LOCAL = 'A'
	GROUP BY DD07T_DOMNAME, DD07T_DOMVALUE_L


EXEC SP_CREATE_INDEX 'BSEG_BUKRS, BSEG_GJAHR, BSEG_BELNR', 'A_BSEG'
EXEC SP_CREATE_INDEX 'BKPF_BUKRS, BKPF_GJAHR, BKPF_BELNR', 'A_BKPF'

GO
