USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC [dbo].[B07D_FIN_AR_DOC_TYPES_FILL_BUCKET](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B07_FIN_AR_AUTO_MAPPING'

GO
