USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Khoio
-- Create date: <Create Date,,>
-- Description:	Create a fact table cube for SOD PTP test
-- =============================================
CREATE     PROCEDURE [dbo].[script_SOD05_P2P_FACT_TABLE]

AS
BEGIN


--Step 1 Create fact table for SOD test
--Add the list of user who approve the PO and INV
--Add a list of key for each test, which will be update later

EXEC SP_DROPTABLE SOD05_01_IT_SOD_FACT_TABLE
SELECT A.*,
	B21_20_ZF_CDPOS_CDHDR_USERNAME1 AS ZF_CDPOS_CDHDR_USERNAME1_EKKO,
	B21_20_ZF_CDPOS_CDHDR_USERNAME2 AS ZF_CDPOS_CDHDR_USERNAME2_EKKO,
	B21_20_ZF_CDPOS_CDHDR_USERNAME3 AS ZF_CDPOS_CDHDR_USERNAME3_EKKO,
	B21_20_ZF_CDPOS_CDHDR_USERNAME4 AS ZF_CDPOS_CDHDR_USERNAME4_EKKO,
	B21_20_ZF_CDPOS_CDHDR_USERNAME5 AS ZF_CDPOS_CDHDR_USERNAME5_EKKO,
	B21_20_ZF_CDPOS_CDHDR_USERNAME6 AS ZF_CDPOS_CDHDR_USERNAME6_EKKO,
	B21_19_ZF_CDPOS_CDHDR_USERNAME1 AS ZF_CDPOS_CDHDR_USERNAME1_RSEG,
	B21_19_ZF_CDPOS_CDHDR_USERNAME2 AS ZF_CDPOS_CDHDR_USERNAME2_RSEG,
	B21_19_ZF_CDPOS_CDHDR_USERNAME3 AS ZF_CDPOS_CDHDR_USERNAME3_RSEG,
	B21_19_ZF_CDPOS_CDHDR_USERNAME4 AS ZF_CDPOS_CDHDR_USERNAME4_RSEG,
	B21_19_ZF_CDPOS_CDHDR_USERNAME5 AS ZF_CDPOS_CDHDR_USERNAME5_RSEG,
	B21_19_ZF_CDPOS_CDHDR_USERNAME6 AS ZF_CDPOS_CDHDR_USERNAME6_RSEG,
	'' AS ZF_SOD_SU_PO,-- Same creator of Supplier,PO
	'' AS ZF_SOD_SU_PO_GR,-- Same creator of Supplier,PO,GR
	'' AS ZF_SOD_SU_PO_IN,-- Same creator of Supplier,PO,INV
	'' AS ZF_SOD_SU_PO_GR_IN,-- Same creator of Supplier,PO,GR,INV
	'' AS ZF_SOD_SU_PO_GR_IN_PAY,-- Same creator of Supplier,PO,INV,PAY
	'' AS ZF_SOD_SU_PO_IN_PAY,-- Same creator of Supplier,PO,INV,PAY
	'' AS ZF_SOD_SU_PAY,-- Same creator of Supplier,Pay
	'' AS ZF_SOD_PO_APPR,-- Same creator of PO, PO approval
	'' AS ZF_SOD_INV_APPR,-- Same creator of INV, INV approval
	'' AS ZF_SOD_INV_PAY,-- Same creator of INV,PAY
	'' AS ZF_SOD_SAME_USER_SUPPLIER,-- User who create their own transaction
	'' AS ZF_SOD_SAME_USER_PRICE_CHANGE,-- Same creator of PO and do the price change
	'' AS ZF_DOC_ACCESS_CONFLICT--Flow which has conflicts
INTO SOD05_01_IT_SOD_FACT_TABLE
FROM B24_01_IT_PTP_GLOBAL_TABLE AS A
--Add the PO approval user list
LEFT JOIN B21_20_IT_PO_APPROVAL_USER
ON ZF_EKPO_EBELN_EBELP LIKE CONCAT('%',B21_20_CDHDR_OBJECTID,'%') 
--Add the Invoice approval user list
LEFT JOIN B21_19_IT_INV_APPROVAL_USER
ON ZF_RSEG_BELNR_GJAHR_BUZEI LIKE CONCAT('%',B21_19_CDHDR_OBJECTID,'%') 

--Rename fields of table
EXEC SP_RENAME_FIELD 'SOD05_01_',SOD05_01_IT_SOD_FACT_TABLE

END
GO
