USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[SP_TEST_DUP_KEY_FIELDS](@ZV_SP_NAME VARCHAR(MAX), @ZV_TEST_TABLE NVARCHAR(MAX),@ZV_TEST_FIELDS NVARCHAR(MAX))
AS



IF OBJECT_ID('LOG_DUP_IN_PROC', 'U') IS NULL 
BEGIN 
	CREATE TABLE [DBO].[LOG_DUP_IN_PROC] ([SP_NAME] NVARCHAR(MAX) NULL, [SP_TABLE] NVARCHAR(MAX) NULL, 
	[NUM_RECORDS] INT NULL, KEY_FIELD NVARCHAR(MAX), QUERY_TIME DATETIME, ID INT IDENTITY(1, 1)) 
END
DECLARE @ZV_REC_COUNT INT = (SELECT TOP 1 ID FROM LOG_DUP_IN_PROC ORDER BY ID DESC)

DECLARE @CURRENT DATETIME = GETDATE()

--Insert duplication results and related details to LOG_DUP_IN_PROC table
DECLARE @ZV_STR_SQL NVARCHAR(MAX) =  
'INSERT INTO LOG_DUP_IN_PROC
SELECT ''' + @ZV_SP_NAME + ''',''' + @ZV_TEST_TABLE + ''', 
(SELECT ISNULL(SUM(DUP), 0) FROM 
(SELECT COUNT(*) DUP
FROM '+ @ZV_TEST_TABLE+'
GROUP BY '+ @ZV_TEST_FIELDS+' 
HAVING COUNT(*) > 1) A), ''' + @ZV_TEST_FIELDS + ''', ''' + CAST(@CURRENT AS NVARCHAR(MAX)) + ''''

EXEC SP_EXECUTESQL @ZV_STR_SQL

IF @ZV_REC_COUNT < (SELECT TOP 1 ID FROM LOG_DUP_IN_PROC ORDER BY ID DESC)
	SET @ZV_STR_SQL = 'FOUND ' +  (SELECT TOP 1 CAST(ISNULL([NUM_RECORDS], '0') AS NVARCHAR(MAX)) 
	+ ' duplicate(s) from table ' +  [SP_TABLE] + ' with key ' +  KEY_FIELD FROM LOG_DUP_IN_PROC ORDER BY ID DESC)
ELSE SET @ZV_STR_SQL = 'ERROR FOUND IN STORED PROCEDURE'

RAISERROR (@ZV_STR_SQL, 0, 1) WITH NOWAIT


IF @ZV_REC_COUNT < (SELECT TOP 1 ID FROM LOG_DUP_IN_PROC ORDER BY ID DESC)
	AND (SELECT TOP 1 ISNULL([NUM_RECORDS], 0) FROM LOG_DUP_IN_PROC ORDER BY ID DESC) > 0
	BEGIN
		SET @ZV_STR_SQL = 'USE THIS STORED PROCEDURE TO CHECK: 
			SELECT ' + @ZV_TEST_FIELDS + ' FROM '+ @ZV_TEST_TABLE+'
		GROUP BY '+ @ZV_TEST_FIELDS+ ' HAVING COUNT(*) > 1'
		RAISERROR (@ZV_STR_SQL, 0, 1) WITH NOWAIT
	END

GO
