USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE     PROC[dbo].[script_B11_SPNI_INVOICE_PATTERN]

AS
--DYNAMIC_SCRIPT_START

IF ISNULL((SELECT TOP 1 COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'B11_05_IT_PTP_INVS_AND_CANCS' 
	AND COLUMN_NAME = 'B11_ZF_XBLNR_PATTERN'), '') = ''
BEGIN 
	DECLARE @SQLCMD NVARCHAR(MAX) ='
									ALTER TABLE B11_05_IT_PTP_INVS_AND_CANCS
									ADD B11_ZF_XBLNR_PATTERN NVARCHAR(100)'
	EXEC SP_EXECUTESQL @SQLCMD
END
SET @SQLCMD = '
				UPDATE B11_05_IT_PTP_INVS_AND_CANCS
				SET B11_ZF_XBLNR_PATTERN = DBO.getStringPattern(B11_BSAIK_XBLNR)'
EXEC SP_EXECUTESQL @SQLCMD

GO
