USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE      PROC [dbo].[B33_DUPLICATE_INVOICES](@DBNAME as NVARCHAR(MAX))
AS
EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B33_%'

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B33_DUPLICATE_INVOICES'
GO
