USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE       PROCEDURE [dbo].[script_B31_BSAIK_ECC_SPEND_CAT_LEVEL3]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START

-- Step 1 : Insert value to AP table.

INSERT INTO DIVA_MASTER_SCRIPT..B31_01_IT_AP_SPEND_LEVEL3
SELECT  
		A.B11_BSAIK_BELNR+A.B11_BSAIK_BUKRS+A.B11_BSAIK_GJAHR+A.B11_BSAIK_BUZEI as ZF_REMOVE_DUP_AP_SIDE,
		A.B11_T001_BUTXT,
		A.B11_BSAIK_MANDT,
		A.B11_BSAIK_BUKRS,
		A.B11_BSAIK_GJAHR,
		A.B11_BSAIK_BELNR,
		A.B11_BSAIK_BUZEI,
		A.B11_BSAIK_BSCHL,
		A.B11_BSAIK_SHKZG,
		A.B11_BSAIK_BLART,
		A.B11_BSAIK_LIFNR,
		A.B11_BSAIK_WAERS,
		A.B11_BSAIK_DMBTR,
		A.B11_BSAIK_UMSKS,
		A.B11_BSAIK_UMSKZ,
		A.B11_BSAIK_AUGDT,
		A.B11_BSAIK_AUGBL,
		A.B11_BSAIK_ZUONR,
		A.B11_BSAIK_BUDAT,
		A.B11_BSAIK_BLDAT,
		A.B11_BSAIK_CPUDT,
		A.B11_BSAIK_XBLNR,
		A.B11_BSAIK_MONAT,
		A.B11_BSAIK_GSBER,
		A.B11_BSAIK_WRBTR,
		A.B11_BSAIK_MWSKZ,
		A.B11_BSAIK_MWSTS,
		A.B11_BSAIK_WMWST,
		A.B11_BSAIK_SGTXT,
		A.B11_BSAIK_AUFNR,
		A.B11_BSAIK_EBELN,
		A.B11_BSAIK_EBELP,
		A.B11_BSAIK_HKONT,
		A.B11_BSAIK_ZFBDT,
		A.B11_BSAIK_ZTERM,
		A.B11_BSAIK_ZBD1T,
		A.B11_BSAIK_ZBD2T,
		A.B11_BSAIK_ZBD3T,
		A.B11_BSAIK_ZBD1P,
		A.B11_BSAIK_ZBD2P,
		A.B11_BSAIK_SKFBT,
		A.B11_BSAIK_WSKTO,
		A.B11_BSAIK_ZLSCH,
		A.B11_BSAIK_ZLSPR,
		A.B11_BSAIK_BSTAT,
		A.B11_BSAIK_KOSTL,
		A.B11_BSAIK_AUGGJ,
		A.B11_T003T_LTEXT,
		A.B11_TBSLT_LTEXT,
		A.B11_GLOBALS_CURRENCY,
		A.B11_ZF_BSAIK_CPUDT_AGE_DAYS,
		A.B11_ZF_BSAIK_OPEN_CLOSED ,
		A.B11_ZF_BSAIK_SHKZG_DESC ,
		A.B11_ZF_BSAIK_SHKZG_INTEGER,
		A.B11_ZF_BSAK_AUGDT_YEAR_MNTH,
		A.B11_ZF_BSAIK_WSKTO_SKBFT,
		A.B11_ZF_BSAIK_DMBTR_S,
		A.B11_ZF_BSAIK_DMBTR_S_CUC,
		A.B11_ZF_FLAG_SUMMARY,
		-- Header information
		A_BKPF.BKPF_AWTYP
		-- Local currency code
		,A_T001.T001_WAERS
        ,A_T001.T001_KTOPL
		--Supplier account group
		,A_LFA1.LFA1_KTOKK
		,A_LFA1.LFA1_NAME1
		,A_LFA1.LFA1_LAND1
		,A_LFA1.LFA1_KUNNR
		--Supplier account group description
		,B00_T077Y.T077Y_TXT30
		-- Add G/L Account Text
		,B00_SKAT.SKAT_TXT20
		,B00_SKAT.SKAT_TXT50
		,DB_NAME()
		,''
		,B11_ZF_BSAIK_DMBE2_S
		,BKPF_HWAE2
FROM B12_02_IT_PTP_AP A
-- Filter BELNR in AP side base on
-- BELNR in GL table have SPEND LEVEL 3 found in AM_SPEND_LEVEL3_SUPPLIER
INNER JOIN 
(
-- List of BELNR from GL table have SPEND LEVEL 3 found in AM_SPEND_LEVEL3_SUPPLIER
	SELECT 
		DISTINCT B12_GL_BSEG_BELNR, B12_GL_BSEG_GJAHR, B12_GL_BSEG_BUKRS
	FROM B12_01_IT_PTP_GL 
	INNER JOIN AM_SPEND_CATEGORY AS B ON dbo.REMOVE_LEADING_ZEROES(B12_GL_BSEG_HKONT) = dbo.REMOVE_LEADING_ZEROES(B.SPCAT_GL_ACCNT)
	WHERE  EXISTS   
	(
		(
			SELECT TOP 1 1
			FROM DIVA_MASTER_SCRIPT..AM_SPEND_LEVEL3_SUPPLIER
			WHERE 
			dbo.REMOVE_LEADING_ZEROES(B.SPCAT_SPEND_CAT_LEVEL_3)  =  AM_SPEND_LEVEL3_SUPPLIER.SPCAT_SPEND_CAT_LEVEL_3 
			AND DB_NAME() LIKE '%' + AM_SPEND_LEVEL3_SUPPLIER.ZF_DATABASE_NAME + '%'
								
		)     
	)
) AS B
	ON A.B11_BSAIK_BUKRS = B.B12_GL_BSEG_BUKRS
	AND A.B11_BSAIK_GJAHR = B.B12_GL_BSEG_GJAHR
	AND A.B11_BSAIK_BELNR = B.B12_GL_BSEG_BELNR
-- Add some header information from BKPF tables
LEFT JOIN A_BKPF
	ON A.B11_BSAIK_BUKRS = A_BKPF.BKPF_BUKRS AND
		A.B11_BSAIK_GJAHR = A_BKPF.BKPF_GJAHR AND
		A.B11_BSAIK_BELNR = A_BKPF.BKPF_BELNR 

-- Add supplier information
LEFT JOIN A_LFA1
		ON A.B11_BSAIK_LIFNR = A_LFA1.LFA1_LIFNR
-- Add supplier account group text
LEFT JOIN B00_T077Y
		ON A_LFA1.LFA1_KTOKK = B00_T077Y.T077Y_KTOKK
-- Obtain company description and house currency
LEFT JOIN A_T001
		ON  A.B11_BSAIK_BUKRS = A_T001.T001_BUKRS
    
-- Add G/L Account Text
LEFT JOIN B00_SKAT                                             
			ON  B00_SKAT.SKAT_KTOPL = A_T001.T001_KTOPL AND               
		B00_SKAT.SKAT_SAKNR = A.B11_BSAIK_HKONT
-- Remove duplication same region. 
WHERE A.B11_BSAIK_BELNR+A.B11_BSAIK_BUKRS+A.B11_BSAIK_GJAHR+A.B11_BSAIK_BUZEI NOT IN 
( 
	SELECT DISTINCT ZF_REMOVE_DUP_AP_SIDE
	FROM DIVA_MASTER_SCRIPT..B31_01_IT_AP_SPEND_LEVEL3
	-- Region inserted (same region).
	INNER JOIN DIVA_MASTER_SCRIPT..AM_SPEND_LEVEL3_SUPPLIER
	ON B31_01_IT_AP_SPEND_LEVEL3.ZF_DATABASE_FLAG = AM_SPEND_LEVEL3_SUPPLIER.ZF_DATABASE_NAME	
)


-- Step 2 :  Insert value to GL  table.

INSERT INTO DIVA_MASTER_SCRIPT..B31_02_IT_GL_SPEND_LEVEL3

SELECT 
	A.B12_GL_BSEG_BELNR+A.B12_GL_BSEG_BUKRS+A.B12_GL_BSEG_GJAHR+A.B12_GL_BSEG_BUZEI as ZF_REMOVE_DUP_GL_SIDE,
	A.B12_GL_BSEG_BUKRS ,
	A.B12_GL_BSEG_GJAHR ,
	A.B12_GL_BSEG_BELNR ,
	A.B12_GL_BSEG_BUZEI,
	A.B12_GL_BSEG_KOART ,
	A.B12_GL_ZF_BSEG_DMBTR_S  ,
	A.B12_GL_ZF_BSEG_DMBE2_S  ,
	A.B12_GL_ZF_BSEG_DMBE3_S  ,
	A.B12_GL_ZF_BSEG_DMBTR_S_CUC ,
	C.SPCAT_SPEND_CAT_LEVEL_1 ,
	C.SPCAT_SPEND_CAT_LEVEL_2 ,
	C.SPCAT_SPEND_CAT_LEVEL_3 ,
	C.SPCAT_SPEND_CAT_LEVEL_4 ,
	A.B12_GL_BSEG_SHKZG,
	A.B12_GL_BSEG_HKONT  ,
	A.B12_GL_SKAT_TXT50 ,
	A.B12_GL_AM_GLOBALS_CURRENCY,
	DB_NAME()
FROM B12_01_IT_PTP_GL A
INNER JOIN AM_SPEND_CATEGORY AS C ON dbo.REMOVE_LEADING_ZEROES(B12_GL_BSEG_HKONT) = dbo.REMOVE_LEADING_ZEROES(C.SPCAT_GL_ACCNT)
--INNER JOIN DIVA_MASTER_SCRIPT..AM_SPEND_LEVEL3_SUPPLIER AS C
--	ON dbo.REMOVE_LEADING_ZEROES(A.B12_GL_BSEG_HKONT) = dbo.REMOVE_LEADING_ZEROES(C.SPCAT_GL_ACCNT) AND
--	 DB_NAME() LIKE '%' + C.ZF_DATABASE_NAME + '%'
INNER JOIN 
(
-- List of BELNR from GL table have SPEND LEVEL 3 found in AM_SPEND_LEVEL3_SUPPLIER
	SELECT 
		DISTINCT B12_GL_BSEG_BELNR, B12_GL_BSEG_GJAHR, B12_GL_BSEG_BUKRS, B12_GL_BSEG_BUZEI
	FROM B12_01_IT_PTP_GL  -- GL cube join with AM_SPEND_CATE to get SPEND level 3 . then link with AM table
	INNER JOIN AM_SPEND_CATEGORY AS B ON dbo.REMOVE_LEADING_ZEROES(B12_GL_BSEG_HKONT) = dbo.REMOVE_LEADING_ZEROES(B.SPCAT_GL_ACCNT)
	WHERE  EXISTS   
	(
		( 
			SELECT TOP 1 1
			FROM DIVA_MASTER_SCRIPT..AM_SPEND_LEVEL3_SUPPLIER
			WHERE 
			dbo.REMOVE_LEADING_ZEROES(B.SPCAT_SPEND_CAT_LEVEL_3)  =  AM_SPEND_LEVEL3_SUPPLIER.SPCAT_SPEND_CAT_LEVEL_3 
			AND DB_NAME() LIKE '%' + AM_SPEND_LEVEL3_SUPPLIER.ZF_DATABASE_NAME + '%'
								
		)     
	)
) AS B ON A.B12_GL_BSEG_BUKRS = B.B12_GL_BSEG_BUKRS 
		 AND A.B12_GL_BSEG_GJAHR = B.B12_GL_BSEG_GJAHR 
		 AND A.B12_GL_BSEG_BELNR = B.B12_GL_BSEG_BELNR
		 AND A.B12_GL_BSEG_BUZEI = B.B12_GL_BSEG_BUZEI
-- Remove duplication same region.
WHERE A.B12_GL_BSEG_BELNR+A.B12_GL_BSEG_BUKRS+A.B12_GL_BSEG_GJAHR+A.B12_GL_BSEG_BUZEI NOT IN 
( 
	SELECT DISTINCT ZF_REMOVE_DUP_GL_SIDE
	FROM DIVA_MASTER_SCRIPT..B31_02_IT_GL_SPEND_LEVEL3
		-- Region inserted (same region).
	INNER JOIN DIVA_MASTER_SCRIPT..AM_SPEND_LEVEL3_SUPPLIER
	ON B31_02_IT_GL_SPEND_LEVEL3.GL_ZF_DATABASE_FLAG = AM_SPEND_LEVEL3_SUPPLIER.ZF_DATABASE_NAME	
)
GO
