USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

 

CREATE    PROCEDURE [dbo].[script_DV13_QLIK_AR_OVERVIEW_VS_SAP_FBL5N]
--CREATE OR ALTER PROCEDURE [dbo].[DV13_QLIK_AR_OVERVIEW_VS_SAP_FBL5N]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START
BEGIN



/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END

--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL

/* Initialize parameters from globals table */

     DECLARE 	 
			 @CURRENCY NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
			,@DATE1 NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
			,@DATE2 NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
			,@DOWNLOADDATE NVARCHAR(MAX)		= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
			,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
			,@EXCHANGERATETYPE NVARCHAR(MAX)	= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
			,@LANGUAGE1 NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
			,@LANGUAGE2 NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
			,@YEAR NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
			,@ID NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
			,@LIMIT_RECORDS INT		            = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
			

/*Test mode*/

SET ROWCOUNT @LIMIT_RECORDS

/*
    Title            : DV13: Compare DIVA AR Overview of Customer to 
	                   to SAP FBL5N
    --------------------------------------------------------------
    Update history
    --------------------------------------------------------------
    Date             |      Who |  Description
    08-22-2017             Nhat        Creation
	
*/


--Step 1/
-- Create table for send message back to DIVA_BULK_IMPORT.jar

	EXEC SP_DROPTABLE 'DV00_RT_USER_FEEDBACK_MESSAGE'

	CREATE TABLE DV00_RT_USER_FEEDBACK_MESSAGE          
     (OLD_NAME NVARCHAR(MAX), NEW_NAME NVARCHAR(MAX), _LOG NVARCHAR(MAX))

-- Step 2/
-- Adding the row number to help identify records 
-- which have the same Company Code, Customer Number,Document Number, Document Type and Posting Date
-- Add QLIK_ prefix to field names
-- Totals from DIVA data 

	DECLARE @SAP_SNAPSHOT_DATE DATE = dbo.trim((SELECT TOP 1 CONVERT(DATE,snapshot_date,120) FROM ASAP_FBL5N))
	DECLARE @DIVAQL_SNAPSHOT_DATE DATE = dbo.trim((SELECT TOP 1 CONVERT(DATE,[Snapshot date],120) FROM AQLIK_AR_DETAILS))
	
	DECLARE @SAP_BUKRS NVARCHAR(10) = dbo.trim((SELECT TOP 1 BUKRS_FROM_FILE_NAME FROM ASAP_FBL5N))
	DECLARE @DIVAQL_BUKRS NVARCHAR(10) = dbo.trim((SELECT TOP 1 [Company code] FROM AQLIK_AR_DETAILS))
	SELECT * FROM AQLIK_AR_DETAILS
	EXECUTE SP_DROPTABLE 'DV13_01_TT_DIVAQL_AR_REPORT'
	SELECT 
		DBO.TRIM([Company code]) DIVAQL_BUKRS		
		,DBO.REMOVE_LEADING_ZEROES([Document nr]) DIVAQL_BELNR
		,DBO.REMOVE_LEADING_ZEROES([Customer nr]) DIVAQL_KUNNR
		,DBO.REMOVE_LEADING_ZEROES([Document type]) DIVAQL_BLART
		-- =============================================
		-- Author:		<VinhLe>
		-- Create date: <29/12/2018>
		-- Description:	Add CONVERT(DATETIME,[Document date],104) DIVAQL_BLDAT statement
		-- =============================================
		,CONVERT(DATETIME,[Document date],102) DIVAQL_BLDAT
		,[Fiscal year] DIVAQL_GJAHR
		,SUM(DBO.STRING_TO_NUMBER([Value Company])) DIVAQL_DMBTR
		,IIF(DBO.STRING_TO_NUMBER([Value Company]) > 0, 'DEBIT', 'CREDIT') ZF_DIVAQL_SHKZG
		,[Snapshot date] DIVAQL_SNAPSHOT_DATE
	INTO DV13_01_TT_DIVAQL_AR_REPORT
	FROM AQLIK_AR_DETAILS
	GROUP BY
		[Company code]
		,[Document nr]
		,[Customer nr]
		,[Document type]
		,CONVERT(DATETIME,[Document date],102)
		,[Fiscal year]
		,[Snapshot date]
		,IIF(DBO.STRING_TO_NUMBER([Value Company]) > 0, 'DEBIT', 'CREDIT')
		
--Step 3A: adding the row number to help identify records 
--which have the same Company Code, Customer Number,Document Number, Document Type and Posting Date
EXEC SP_SAP_REPORT_FIELD_TO_STANDARD 'ASAP_FBL5N' 
EXEC SP_DROPTABLE 'DV13_02_TT_SAP_AR_REPORT_A'

SELECT 
		 DBO.TRIM(BUKRS_FROM_FILE_NAME) SAP_BUKRS
		,DBO.REMOVE_LEADING_ZEROES(BELNR) SAP_BELNR
		,DBO.TRIM(Typ) SAP_BLART
		,DBO.REMOVE_LEADING_ZEROES(KUNNR) SAP_KUNNR
		,BLDAT_CONVERTED SAP_BLDAT
		,DMBTR_CONVERTED SAP_DMBTR
		,DBO.TRIM(CONVERT(DATE,snapshot_date,104)) SAP_SNAPSHOT_DATE
		,IIF(DMBTR_CONVERTED > 0, 'DEBIT', 'CREDIT') ZF_SAP_SHKZG
	INTO DV13_02_TT_SAP_AR_REPORT_A
	FROM ASAP_FBL5N

	
---step 3B: 
-- Totals from SAP report
-- Add SAP_ prefix to field names

	EXECUTE SP_DROPTABLE 'DV13_02_TT_SAP_AR_REPORT_B'	
	SELECT 
		 SAP_BUKRS
		,SAP_BELNR
		,SAP_BLART
		,SAP_KUNNR
		,SAP_BLDAT
		,SAP_SNAPSHOT_DATE
		,ZF_SAP_SHKZG
		,SUM(SAP_DMBTR) AS SAP_DMBTR

	INTO DV13_02_TT_SAP_AR_REPORT_B

	FROM DV13_02_TT_SAP_AR_REPORT_A

	GROUP BY
		 SAP_BUKRS
		,SAP_BELNR
		,SAP_BLART
		,SAP_KUNNR
		,SAP_BLDAT
		,SAP_SNAPSHOT_DATE
		,ZF_SAP_SHKZG
	

--Step 4/
--Compare totals from Qlik to totals from SAP


	EXECUTE SP_DROPTABLE 'DV13_03_TT_COMP_DIVAQL_AR_SAP'

	SELECT	
		   [DIVAQL_BUKRS]
		  ,[SAP_BUKRS]	  
		  ,[DIVAQL_BELNR]
		  ,[SAP_BELNR]
		  ,[DIVAQL_KUNNR]
		  ,[SAP_KUNNR]
		  ,[DIVAQL_BLART]
		  ,[SAP_BLART]
		  ,[DIVAQL_GJAHR]
		  ,[SAP_BLDAT]
		  ,[DIVAQL_SNAPSHOT_DATE]
		  ,[SAP_SNAPSHOT_DATE]
		  ,ZF_DIVAQL_SHKZG
		  ,ZF_SAP_SHKZG
		  ,ISNULL(DIVAQL_DMBTR, 0) AS  DIVAQL_DMBTR
		  ,ISNULL([SAP_DMBTR], 0)	AS SAP_DMBTR
		  ,ISNULL(DIVAQL_DMBTR, 0) - ISNULL (SAP_DMBTR, 0) AS ZF_DIVAQL_MINUS_SAP_AMOUNT,
			CASE WHEN	ISNULL(DIVAQL_KUNNR ,'') <> '' AND
						ISNULL(SAP_KUNNR ,'') = '' 
						THEN 'Invoice in DIVA not SAP'
				 WHEN	ISNULL(DIVAQL_KUNNR ,'') = '' AND
						ISNULL(SAP_KUNNR ,'') <> '' 
						THEN 'Invoice in SAP not DIVA'
				WHEN	ISNULL(DIVAQL_KUNNR ,'') <> '' AND
						ISNULL(SAP_KUNNR ,'') <> '' 
						THEN 'Invoice in SAP and DIVA'
				ELSE	'Case not identified'
			END 									AS ZF_CUSTM_MATCH_CATEGORY
	INTO	DV13_03_TT_COMP_DIVAQL_AR_SAP
	FROM	DV13_01_TT_DIVAQL_AR_REPORT
		FULL OUTER JOIN DV13_02_TT_SAP_AR_REPORT_B
			ON	DV13_01_TT_DIVAQL_AR_REPORT.DIVAQL_BUKRS		= DV13_02_TT_SAP_AR_REPORT_B.SAP_BUKRS
			AND	DV13_01_TT_DIVAQL_AR_REPORT.DIVAQL_KUNNR	= DV13_02_TT_SAP_AR_REPORT_B.SAP_KUNNR
			AND	DV13_01_TT_DIVAQL_AR_REPORT.DIVAQL_BELNR		= DV13_02_TT_SAP_AR_REPORT_B.SAP_BELNR
			AND DV13_01_TT_DIVAQL_AR_REPORT.DIVAQL_BLART		= DV13_02_TT_SAP_AR_REPORT_B.SAP_BLART
			-- =============================================
			-- Author:		<VinhLe>
			-- Create date: <29/12/2018>
			-- Description:	Change DIVAQL_GJAHR to DIVAQL_BLDAT
			-- =============================================
			AND DV13_01_TT_DIVAQL_AR_REPORT.DIVAQL_BLDAT = DV13_02_TT_SAP_AR_REPORT_B.SAP_BLDAT
			AND DV13_01_TT_DIVAQL_AR_REPORT.DIVAQL_SNAPSHOT_DATE		= DV13_02_TT_SAP_AR_REPORT_B.SAP_SNAPSHOT_DATE
			AND DV13_01_TT_DIVAQL_AR_REPORT.ZF_DIVAQL_SHKZG = DV13_02_TT_SAP_AR_REPORT_B.ZF_SAP_SHKZG

--Step 5/
--Split the compariARn into two tables: Enable independent filtering in QLIK

	EXEC SP_DROPTABLE 'DV13_04_RT_FULL_DIVAQL_AR'

	SELECT	DIVAQL_BUKRS
		  ,DIVAQL_BELNR
		  ,DIVAQL_KUNNR
		  ,DIVAQL_BLART
		  ,DIVAQL_GJAHR
		  ,DIVAQL_SNAPSHOT_DATE
		  
		  ,DIVAQL_DMBTR
			,DIVAQL_BUKRS + '|' +  DIVAQL_KUNNR + '|' + DIVAQL_BELNR AS ZF_KEY_JOIN_DIVAQL
	INTO	DV13_04_RT_FULL_DIVAQL_AR
	FROM	DV13_03_TT_COMP_DIVAQL_AR_SAP
	WHERE	DIVAQL_KUNNR IS NOT NULL

	EXEC sp_droptable 'DV13_05_RT_FULL_SAP_AR'

	SELECT	SAP_BUKRS
		  ,SAP_BELNR
		  ,SAP_BLART
		  ,SAP_KUNNR
		  ,SAP_BLDAT
		  ,SAP_SNAPSHOT_DATE
		  ,SAP_DMBTR
		  ,SAP_BUKRS + '|' +  SAP_KUNNR + '|' + SAP_BELNR AS ZF_KEY_JOIN_SAP
	INTO	DV13_05_RT_FULL_SAP_AR
	FROM	DV13_03_TT_COMP_DIVAQL_AR_SAP
	WHERE	SAP_KUNNR IS NOT NULL

--Step 6/
--Split the compariARn into two discrepancy tables: Enable independent filtering in QLIK

	EXEC SP_DROPTABLE 'DV13_06_RT_DISC_DIVAQL_AR_SAP'
		
	SELECT  DIVAQL_BUKRS		  
		  ,DIVAQL_BELNR
		  ,DIVAQL_KUNNR
		  ,DIVAQL_BLART
		  ,DIVAQL_GJAHR
		  ,DIVAQL_SNAPSHOT_DATE
		  ,DIVAQL_DMBTR
		  ,ZF_DIVAQL_MINUS_SAP_AMOUNT
		  ,ZF_CUSTM_MATCH_CATEGORY
		  ,DIVAQL_BUKRS + '|' +  DIVAQL_KUNNR + '|' + DIVAQL_BELNR AS ZF_KEY_JOIN_DIVAQL
	INTO	DV13_06_RT_DISC_DIVAQL_AR_SAP
	FROM	DV13_03_TT_COMP_DIVAQL_AR_SAP
	WHERE	(ABS(ZF_DIVAQL_MINUS_SAP_AMOUNT) > 10 OR 
		ZF_CUSTM_MATCH_CATEGORY = 'Invoice in DIVA not SAP' OR ZF_CUSTM_MATCH_CATEGORY = 'Case not identified')
		AND NOT(
		ABS(ZF_DIVAQL_MINUS_SAP_AMOUNT) > 10 AND 
		ZF_CUSTM_MATCH_CATEGORY = 'Invoice in SAP not DIVA')
-- Discrepancy table for spend overview for SAP

	EXEC SP_DROPTABLE 'DV13_07_RT_DISC_SAP_AR_DIVAQL'

	SELECT	SAP_BUKRS
		  ,SAP_BELNR
		  ,SAP_BLART
		  ,SAP_KUNNR
		  ,SAP_BLDAT
		  ,SAP_SNAPSHOT_DATE
		  ,SAP_DMBTR
		  ,ZF_DIVAQL_MINUS_SAP_AMOUNT
		  ,ZF_CUSTM_MATCH_CATEGORY
		  ,SAP_BUKRS + '|' +  SAP_KUNNR + '|' + SAP_BELNR AS ZF_KEY_JOIN_SAP
	INTO	DV13_07_RT_DISC_SAP_AR_DIVAQL
	FROM	DV13_03_TT_COMP_DIVAQL_AR_SAP
	WHERE	(ABS(ZF_DIVAQL_MINUS_SAP_AMOUNT) > 10 OR 
		ZF_CUSTM_MATCH_CATEGORY = 'Invoice in SAP not DIVA' OR ZF_CUSTM_MATCH_CATEGORY = 'Case not identified')
		AND NOT(
		ABS(ZF_DIVAQL_MINUS_SAP_AMOUNT) > 10 AND 
		ZF_CUSTM_MATCH_CATEGORY = 'Invoice in DIVA not SAP')
--Step 7/
--Rename field
EXEC SP_RENAME_FIELD 'DV13A_', 'DV13_04_RT_FULL_DIVAQL_AR'
EXEC SP_RENAME_FIELD 'DV13B_', 'DV13_05_RT_FULL_SAP_AR'
EXEC SP_RENAME_FIELD 'DV13C_', 'DV13_06_RT_DISC_DIVAQL_AR_SAP'
EXEC SP_RENAME_FIELD 'DV13D_', 'DV13_07_RT_DISC_SAP_AR_DIVAQL'

--Delete temporary tables
	EXECUTE SP_DROPTABLE 'DV13_01_TT_DIVAQL_AR_REPORT'
	EXECUTE SP_DROPTABLE 'DV13_02_TT_SAP_AR_REPORT'
  	--EXECUTE SP_DROPTABLE 'DV13_03_TT_COMP_DIVAQL_AR_SAP'


-- Step 8/
--Send Finish Message for DIVA_BULK_IMPORT.jar: 

	INSERT INTO DV00_RT_USER_FEEDBACK_MESSAGE VALUES('', '', 'DV13 stored procedure has finished.')

/* log cube creation*/

INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV13_04_RT_FULL_DIVAQL_AR',(SELECT COUNT(*) FROM DV13_04_RT_FULL_DIVAQL_AR) 
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV13_05_RT_FULL_SAP_AR',(SELECT COUNT(*) FROM DV13_05_RT_FULL_SAP_AR) 
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV13_06_RT_DISC_DIVAQL_AR_SAP',(SELECT COUNT(*) FROM DV13_06_RT_DISC_DIVAQL_AR_SAP) 
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV13_07_RT_DISC_SAP_AR_DIVAQL',(SELECT COUNT(*) FROM DV13_07_RT_DISC_SAP_AR_DIVAQL) 

/* log end of procedure*/


INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(date,GETDATE()),CONVERT(time,GETDATE()),'Procedure finished',NULL,NULL


END 
GO
