USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[PM_PROCESS_MINING]  @DBNAME NVARCHAR(MAX)
AS
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B21_02_IT_CDHDR_CDPOS_EINKBELEG'
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B21_04_IT_CDHDR_CDPOS_INCOMINGINVOICE'
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B21_06_IT_CDHDR_CDPOS_IBAN'
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B21_08_IT_CDHDR_CDPOS_KRED'
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B21_10_IT_CDHDR_CDPOS_BELEG'
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B21_12_IT_REGUH_BANK'
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B21_17_IT_CHANGE_LFBK_INSERT_DEL'

	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B24_%'
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME,  'B11_SS02_%'

	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B00_SS01_OTC_INFO_TABLE'
----Material movement cube(Good receipt and Good issue)
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B24_MATERIAL_MOVEMENT_CUBE' 
--Script for PTP
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B21_CHANGE_DOCUMENT_CUBE_V2' --Change cubes
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B23_PTP_PURCHASE_REQUEST' --PR cube
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B09_SS02_ADD_USER_PO' --PO cube
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B11_SS02_ADD_USER_INV_PAY' --Invoice/Payemnt cube (BSAK-BSIK)
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B25A_BSEG_BKPF_INVOICES' -- Invoice cube(BSEG-BKPF)
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B25_PTP_GLOBAL_CUBES' --GLobal cube
	EXEC SP_EXEC_DYNAMIC @DBNAME,'script_PM01_PROCESS_MINING_NEW'

--	--Script for OTC
    EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B00_SS01_OTC_INFO_TABLE' -- Text cube need for OTC
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B21_SS01_OTC_PROCESS_MINING_CHANGE' --Change cube
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B33_SALE_ORDER_CUBE' --Sale order cube
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B34_DELIVERY_CUBE' --Delivery cube
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B36_INVOICE_DOCS' --Billing invoice cube
	EXEC SP_EXEC_DYNAMIC @DBNAME,'script_B14_SS01_INVOICE_PAYMENT_CUBE' -- Invoice,payment cube
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B37_OTC_GLOBAL_TABLE' -- Global cube
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_PM02_OTC_PROCESS_MINING'
--SOD user flag script (Flag the user who did SOD in both PTP and OTC)
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_PM03_FLAG_USER_PTP_OTC'
GO
