USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC [dbo].[B09_PTP_POS](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B09%'

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B09_PTP_POS'

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B09B_PTP_DUPLICATE_PO_PREPARE'

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B09C_PTP_DUPLICATE_PO'


GO
