USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE     PROCEDURE [dbo].[script_DV03_DIVASQLGL_VERSUS_DIVASQLAP]

WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START
BEGIN
 
 /*
    Title            :  DV03: Data Validation dashboard 
    Description      :  Compares the GL cube to the AP cube
       --------------------------------------------------------------
    Update history
    --------------------------------------------------------------
    Date             |      Who |  Description
	15-06-2018          HuyTran        Creation
	23-03-2022			Thuan		   Remove MANDT field in join
	                                  
*/
--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END

--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL

--Step 1/
-- Create table for send message back to TRIAL_BAL Tool
	EXEC sp_droptable 'DV00_RT_USER_FEEDBACK_MESSAGE'
	CREATE TABLE DV00_RT_USER_FEEDBACK_MESSAGE          
     (old_name NVARCHAR(MAX), new_name NVARCHAR(MAX), _log NVARCHAR(MAX))

-- The following code can be put wherever we want and whenever we want to send a message back to the user
-- that has pressed Java Upload app button for running this script.

--SET @msg = '<Feedback message for user>' --print back status for users
--INSERT INTO DV00_RT_USER_FEEDBACK_MESSAGE VALUES('', '', @msg)

-- Step 2/ Get amount per month on GL table per GL account which contain only Vendor
EXEC SP_DROPTABLE 'DV03_01_DIVASQLGL_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR'
	SELECT
		B04_BKPF_MANDT AS B04_BKPF_MANDT,
		B04_BSEG_BUKRS AS B04_BSEG_BUKRS,
		B04_BSEG_GJAHR AS B04_BSEG_GJAHR,
		RIGHT(B04_ZF_BKPF_GJAHR_MONAT,2) AS B04_ZF_BKPF_GJAHR_MONAT,
		B04_BSEG_HKONT AS B04_BSEG_HKONT,
		B04_BSEG_BELNR AS B04_BSEG_BELNR,
		B04_BSEG_BUZEI AS B04_BSEG_BUZEI,
		SUM(IIF(B04_BSEG_SHKZG = 'S', B04_ZF_BSEG_DMBTR_S, 0)) AS B04_ZF_BSEG_DMBTR_DB,
		SUM(IIF(B04_BSEG_SHKZG = 'H', B04_ZF_BSEG_DMBTR_S, 0)) AS B04_ZF_BSEG_DMBTR_CR,
		SUM(B04_ZF_BSEG_DMBTR_S) AS B04_ZF_BSEG_DMBTR_S
	INTO DV03_01_DIVASQLGL_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR
    FROM B04_11_IT_FIN_GL
    WHERE B04_BSEG_KOART = 'K'
    GROUP BY
            B04_BKPF_MANDT,
            B04_BSEG_BUKRS,
			B04_BSEG_GJAHR,
            B04_ZF_BKPF_GJAHR_MONAT,
            B04_BSEG_HKONT,
            B04_BSEG_BELNR,
            B04_BSEG_BUZEI             
 
--Step 3/ Get amount per month on PTP table per GL account
-- Update 28/05/2019 by thuan  SUM(IIF(B11B_BSAIK_SHKZG = 'S', B11B_ZF_BSAIK_DMBTR_S, 0)) AS B11B_ZF_BSAIK_DMBTR_DEBIT, -> 
EXEC SP_DROPTABLE 'DV03_02_DIVASQLAP_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR'
	SELECT
            B11B_BSAIK_MANDT AS B11B_BSAIK_MANDT,
			B11B_BSAIK_BUKRS AS B11B_BSAIK_BUKRS,
            B11B_BSAIK_GJAHR AS B11B_BSAIK_GJAHR,
            B11B_BSAIK_MONAT AS B11B_BSAIK_MONAT,
            B11B_BSAIK_HKONT AS B11B_BSAIK_HKONT,
            B11B_BSAIK_BELNR AS B11B_BSAIK_BELNR,
            B11B_BSAIK_BUZEI AS B11B_BSAIK_BUZEI,
            SUM(IIF(B11B_BSAIK_SHKZG = 'S', B11B_ZF_BSAIK_DMBTR_S, 0)) AS B11B_ZF_BSAIK_DMBTR_DEBIT,
            SUM(IIF(B11B_BSAIK_SHKZG = 'H', B11B_ZF_BSAIK_DMBTR_S, 0)) AS B11B_ZF_BSAIK_DMBTR_CREDIT
    INTO DV03_02_DIVASQLAP_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR
    FROM B11_04_IT_PTP_APA
    GROUP BY
			B11B_BSAIK_MANDT,
			B11B_BSAIK_BUKRS,
			B11B_BSAIK_GJAHR,
			B11B_BSAIK_MONAT,
			B11B_BSAIK_HKONT,
			B11B_BSAIK_BELNR,
			B11B_BSAIK_BUZEI

--Step 4/ Comparing GL and AP so that we have all data which stored in GL or AP or in both
	EXECUTE SP_DROPTABLE 'DV03_03_RT_COMP_DIVASQLGL_DIVASQLAP'
    SELECT
			 B04_BKPF_MANDT
			,B11B_BSAIK_MANDT
			,B04_BSEG_BUKRS
			,B11B_BSAIK_BUKRS
			,B04_BSEG_GJAHR
			,B11B_BSAIK_GJAHR
			,B04_ZF_BKPF_GJAHR_MONAT
			,B11B_BSAIK_MONAT
			,B04_BSEG_HKONT
			,B11B_BSAIK_HKONT
			,B04_BSEG_BELNR
			,B11B_BSAIK_BELNR
			,B04_BSEG_BUZEI
			,B11B_BSAIK_BUZEI
			-- check field			
			,CASE 
				WHEN ISNULL(B04_BSEG_BELNR,'') <> '' AND 
					ISNULL(B11B_BSAIK_BELNR,'') = '' 
				THEN 'DOC IN GL NOT IN AP'
				WHEN ISNULL(B04_BSEG_BELNR,'') = '' AND 
					ISNULL(B11B_BSAIK_BELNR,'') <> '' 
				THEN 'DOC IN AP NOT IN GL'
				WHEN ISNULL(B04_BSEG_BELNR,'') <> '' AND 
				ISNULL(B11B_BSAIK_BELNR,'') <> ''
				THEN 'DOC IN GL AND AP'
				ELSE 'CASE NOT IDENTIFIED'
			END AS   ZF_CHECK_BELNR_IN_DIVASQLGL_AND_DIVASQLAP       --ZF_CHECK_BELNR_IN_DIVASQLGL_AND_DIVASQLAP
			--numeric check
			,B04_ZF_BSEG_DMBTR_DB
			,B11B_ZF_BSAIK_DMBTR_DEBIT
			,ISNULL(B04_ZF_BSEG_DMBTR_DB, 0) - ISNULL(B11B_ZF_BSAIK_DMBTR_DEBIT, 0) AS ZF_DIVASQLGL_DB_MINUS_DIVASQLAP_DB
			,B04_ZF_BSEG_DMBTR_CR
			,B11B_ZF_BSAIK_DMBTR_CREDIT
			,ISNULL(B04_ZF_BSEG_DMBTR_CR, 0) - ISNULL(B11B_ZF_BSAIK_DMBTR_CREDIT, 0) AS ZF_DIVASQLGL_CR_MINUS_DIVASQLAP_CR
    INTO   DV03_03_RT_COMP_DIVASQLGL_DIVASQLAP--DV03_03_RT_COMP_DIVASQLGL_DIVASQLAP
    FROM DV03_01_DIVASQLGL_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR
    FULL OUTER JOIN DV03_02_DIVASQLAP_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR ON
		DV03_01_DIVASQLGL_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B04_BSEG_BUKRS			= DV03_02_DIVASQLAP_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B11B_BSAIK_BUKRS AND
		DV03_01_DIVASQLGL_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B04_BSEG_GJAHR			= DV03_02_DIVASQLAP_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B11B_BSAIK_GJAHR AND
		DV03_01_DIVASQLGL_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B04_ZF_BKPF_GJAHR_MONAT	= DV03_02_DIVASQLAP_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B11B_BSAIK_MONAT AND
		DV03_01_DIVASQLGL_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B04_BSEG_HKONT			= DV03_02_DIVASQLAP_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B11B_BSAIK_HKONT AND
		DV03_01_DIVASQLGL_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B04_BSEG_BELNR			= DV03_02_DIVASQLAP_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B11B_BSAIK_BELNR AND
		DV03_01_DIVASQLGL_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B04_BSEG_BUZEI			= DV03_02_DIVASQLAP_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR.B11B_BSAIK_BUZEI
 
  
--Step 5/ Split the comparison into two tables so that we can be able to filter them separately
	--5.1 DIVA SQL GL full table
	EXEC SP_DROPTABLE 'DV03_04_RT_FULL_DIVASQLGL'
	SELECT
		*
		,B04_BSEG_BUKRS + '|' + B04_BSEG_GJAHR +  '|' +  B04_BSEG_BELNR  + '|' + B04_BSEG_BUZEI  AS ZF_KEY_JOIN_GL
	INTO DV03_04_RT_FULL_DIVASQLGL
	FROM DV03_03_RT_COMP_DIVASQLGL_DIVASQLAP
	WHERE B04_BSEG_HKONT IS NOT NULL
	
	---- 
	EXEC SP_DROPTABLE 'DV03_05_RT_FULL_DIVASQLAP'
	--5.2  DIVA SQL AP full tablle
	SELECT 
		*                 
		,B11B_BSAIK_BUKRS + '|' + B11B_BSAIK_GJAHR +  '|' +  B11B_BSAIK_BELNR  + '|' + B11B_BSAIK_BUZEI  AS ZF_KEY_JOIN_APA
	INTO DV03_05_RT_FULL_DIVASQLAP
	FROM DV03_03_RT_COMP_DIVASQLGL_DIVASQLAP
	WHERE B11B_BSAIK_HKONT IS NOT NULL
 
-- Step 6/ Split the comparison into two discrepancy tables so that we can be able to filter them separately
 	
	--Step 6.1  DIVASQLGL discrepancy table
	EXEC SP_DROPTABLE 'DV03_06_RT_DISC_DIVASQLGL'
	SELECT
		*
		,B04_BSEG_BUKRS + '|' + B04_BSEG_GJAHR +  '|' +  B04_BSEG_BELNR  + '|' + B04_BSEG_BUZEI  AS ZF_KEY_JOIN_GL
	INTO DV03_06_RT_DISC_DIVASQLGL
	FROM DV03_03_RT_COMP_DIVASQLGL_DIVASQLAP
	WHERE 
		(ABS(ZF_DIVASQLGL_DB_MINUS_DIVASQLAP_DB)>10 OR
		ZF_CHECK_BELNR_IN_DIVASQLGL_AND_DIVASQLAP = 'DOC IN GL NOT IN AP' 
		OR ZF_CHECK_BELNR_IN_DIVASQLGL_AND_DIVASQLAP = 'Case not identified')
		AND NOT
		(ABS(ZF_DIVASQLGL_DB_MINUS_DIVASQLAP_DB)>10 AND
		ZF_CHECK_BELNR_IN_DIVASQLGL_AND_DIVASQLAP = 'DOC IN AP NOT IN GL' )

	----Step 6.2  DIVASQLAP discrepancy table
	EXEC SP_DROPTABLE 'DV03_07_RT_DISC_DIVASQLAP'
	SELECT
		*
		,B11B_BSAIK_BUKRS + '|' + B11B_BSAIK_GJAHR +  '|' +  B11B_BSAIK_BELNR  + '|' + B11B_BSAIK_BUZEI  AS ZF_KEY_JOIN_APA
	INTO DV03_07_RT_DISC_DIVASQLAP
	FROM DV03_03_RT_COMP_DIVASQLGL_DIVASQLAP
	WHERE
		(ABS(ZF_DIVASQLGL_DB_MINUS_DIVASQLAP_DB)>10 OR
		ZF_CHECK_BELNR_IN_DIVASQLGL_AND_DIVASQLAP = 'DOC IN AP NOT IN GL' 
		OR ZF_CHECK_BELNR_IN_DIVASQLGL_AND_DIVASQLAP = 'Case not identified')
		AND NOT
		(ABS(ZF_DIVASQLGL_DB_MINUS_DIVASQLAP_DB)>10 AND
		ZF_CHECK_BELNR_IN_DIVASQLGL_AND_DIVASQLAP = 'DOC IN GL NOT IN AP')

--step 7 Send Finish Message for the tool
	INSERT INTO DV00_RT_USER_FEEDBACK_MESSAGE VALUES('', '', 'DV03_DIVASQLGL_VERSUS_DIVASQLAP')

--Step 8/
--Delete temporary tables
	
	EXEC SP_DROPTABLE 'DV03_01_DIVASQLGL_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR'
	EXEC SP_DROPTABLE 'DV03_02_DIVASQLAP_TOT_BUKRS_GJAHR_HKONT_BELNR_BUZEI_DMBTR'

-- Step 9/
-- Rename fields 
EXEC SP_RENAME_FIELD 'DV03A_', 'DV03_03_RT_COMP_DIVASQLGL_DIVASQLAP'
EXEC SP_RENAME_FIELD 'DV03B_', 'DV03_04_RT_FULL_DIVASQLGL'
EXEC SP_RENAME_FIELD 'DV03C_', 'DV03_05_RT_FULL_DIVASQLAP'
EXEC SP_RENAME_FIELD 'DV03D_', 'DV03_06_RT_DISC_DIVASQLGL'
EXEC SP_RENAME_FIELD 'DV03E_', 'DV03_07_RT_DISC_DIVASQLAP'

INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV03_04_RT_FULL_DIVASQLGL',(SELECT COUNT(*) FROM DV03_04_RT_FULL_DIVASQLGL) 
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV03_05_RT_FULL_DIVASQLAP',(SELECT COUNT(*) FROM DV03_05_RT_FULL_DIVASQLAP)      
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV03_06_RT_DISC_DIVASQLGL',(SELECT COUNT(*) FROM DV03_06_RT_DISC_DIVASQLGL)  
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV03_07_RT_DISC_DIVASQLAP',(SELECT COUNT(*) FROM DV03_07_RT_DISC_DIVASQLAP)  

/* log end of procedure*/
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure finished',NULL,NULL

END
GO
