USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC[dbo].[script_B09B_PTP_DUPLICATE_PO_PREPARE]
AS
--DYNAMIC_SCRIPT_START
IF COL_LENGTH('dbo.B09_13_IT_PTP_POS', 'B09_ZF_DUPLICATE_PO_FLAG') IS NULL
BEGIN
	ALTER TABLE B09_13_IT_PTP_POS ADD B09_ZF_DUPLICATE_PO_FLAG NVARCHAR(100)
	ALTER TABLE B09_13_IT_PTP_POS ADD B09_ZF_DUPLICATE_PO_SAME_MENGE_FLAG NVARCHAR(100)
	ALTER TABLE B09_13_IT_PTP_POS ADD B09_ZF_DUPLICATE_PO_KEY NVARCHAR(100)
END


GO
