USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE       PROC [dbo].[B00_CREATE_STANDARD_CUBES_FOR_SU_REPORTS] (@DBNAME NVARCHAR(MAX))
AS



-- Step 1: Create transactions infor cubes
EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B00%'

EXEC SP_EXEC_DYNAMIC @DBNAME,'B00_CREATE_AM_T077X_T077Y' 
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B00_REPLACE_VIEW_BY_TABLE'
EXEC SP_EXEC_DYNAMIC  @DBNAME, 'script_B00_SS01_OTC_INFO_TABLE' 
EXEC SP_EXEC_DYNAMIC @DBNAME,'script_B00_TCURR_TCURF'


-- Step 2: Create JE infor cube
EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B04%'

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B04_FIN_GENERAL_LEDGER'

-- Step 3: Create PTP cubes
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B07_FIN_AP_AUTOMAPPING' 

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B08_PTP_SMD'

EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B09%'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B09_PTP_POS'

EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B11_%'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B11_PTP_APA' 

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B24_MATERIAL_MOVEMENT_CUBE'

EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B33_%'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B33_DUPLICATE_INVOICES'


-- Step 4: Create OTC cubes
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B33_SALE_ORDER_CUBE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B34_DELIVERY_CUBE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B36_INVOICE_DOCS'


GO
