USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_PM03_FLAG_USER_PTP_OTC]
AS
--THis is is used for updating the User SOD flag,
--Flag the user who did SOD in Both OTC and PTP
--DYNAMIC_SCRIPT_START
--Update the flag for PTP

--DYNAMIC_SCRIPT_START

UPDATE PM_OTC_20_RT_USER_SOD_ACTIVITY
SET ZF_PTP_FLAG='X'
WHERE ZF_INTEGER_FOR_USER IN
(
	SELECT DISTINCT ZF_INTEGER_FOR_USER FROM 
	PM_20_RT_USER_SOD_ACTIVITY
)
--Update the flag for OTC
UPDATE PM_20_RT_USER_SOD_ACTIVITY
SET ZF_OTC_FLAG='X'
WHERE ZF_INTEGER_FOR_USER IN
(
	SELECT DISTINCT ZF_INTEGER_FOR_USER FROM 
	PM_OTC_20_RT_USER_SOD_ACTIVITY
)
GO
