USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE     PROC [dbo].[script_B09C_PTP_DUPLICATE_PO]
AS
--DYNAMIC_SCRIPT_START

UPDATE B09_13_IT_PTP_POS
SET B09_ZF_DUPLICATE_PO_KEY = B09_EKKO_LIFNR + B09_EKPO_MATNR + CAST(B09_EKPO_MENGE AS NVARCHAR(MAX))
CREATE INDEX B09_ZF_DUPLICATE_PO_KEY_IDX ON B09_13_IT_PTP_POS(B09_ZF_DUPLICATE_PO_KEY)

-- 29-03-2023 : Removed filter B09_ZF_EKKO_BEDAT_DOC_DATE_IN_PER in our cube. Need to load full PO in PTP dashboard.
DELETE B09_13_IT_PTP_POS
WHERE NOT (
		--B09_ZF_EKKO_BEDAT_DOC_DATE_IN_PER = 'X' AND 
        B09_ZF_EKPO_LOEKZ_DEL=''
		AND	B09_EKKO_BSTYP	= 'F' 
		AND	B09_EKPO_RETPO <> 'X'
		AND	B09_EKPO_PSTYP <> '7')


UPDATE B09_13_IT_PTP_POS SET B09_ZF_DUPLICATE_PO_FLAG = NULL, B09_ZF_DUPLICATE_PO_SAME_MENGE_FLAG = NULL


UPDATE B09_13_IT_PTP_POS
SET B09_ZF_DUPLICATE_PO_SAME_MENGE_FLAG = B09_ZF_DUPLICATE_PO_KEY
FROM B09_13_IT_PTP_POS
WHERE B09_ZF_DUPLICATE_PO_KEY IN
		(SELECT DISTINCT B09_ZF_DUPLICATE_PO_KEY
			FROM B09_13_IT_PTP_POS A
			WHERE EXISTS(SELECT * FROM B09_13_IT_PTP_POS B WHERE
				A.B09_EKKO_EBELN <> B.B09_EKKO_EBELN
				AND A.B09_EKPO_NETWR <> 0
				AND A.B09_EKPO_MATNR <> '' --https://answers.sap.com/questions/208602/how-bseg-matnr-fills-from-sales--distribution-flow.html
				AND ABS(DATEDIFF(DAY, A.B09_EKKO_AEDAT, B.B09_EKKO_AEDAT)) <= 30
				AND A.B09_EKKO_LIFNR  = B.B09_EKKO_LIFNR
				AND A.B09_EKPO_MATNR = B.B09_EKPO_MATNR
				AND A.B09_EKPO_MENGE = B.B09_EKPO_MENGE))

UPDATE B09_13_IT_PTP_POS
SET B09_ZF_DUPLICATE_PO_FLAG = B09_EKKO_LIFNR + B09_EKPO_MATNR
FROM B09_13_IT_PTP_POS
WHERE B09_ZF_DUPLICATE_PO_KEY IN
		(SELECT DISTINCT B09_ZF_DUPLICATE_PO_KEY
			FROM B09_13_IT_PTP_POS A
			WHERE EXISTS(SELECT * FROM B09_13_IT_PTP_POS B WHERE
				A.B09_EKKO_EBELN <> B.B09_EKKO_EBELN
				AND A.B09_EKPO_NETWR <> 0
				AND A.B09_EKPO_MATNR <> '' --https://answers.sap.com/questions/208602/how-bseg-matnr-fills-from-sales--distribution-flow.html
				AND ABS(DATEDIFF(DAY, A.B09_EKKO_AEDAT, B.B09_EKKO_AEDAT)) <= 30
				AND A.B09_EKKO_LIFNR  = B.B09_EKKO_LIFNR
				AND A.B09_EKPO_MATNR = B.B09_EKPO_MATNR))


GO
