USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC [dbo].[FR06_CHANGE_CLEARING_DATE](@DBNAME as NVARCHAR(MAX))
AS
--DYNAMIC_SCRIPT_START
EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'FR06%'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_FR06_CHANGE_CLEARING_DATE'

GO
