USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[script_DC02_FIN_GENERAL_LEDGER]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START
/* Initiate the log */ 
----Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END
 
--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL
 
/* Initialize parameters from globals table */
 
     DECLARE  
                      @CURRENCY NVARCHAR(MAX)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
                     ,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
                     ,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
                     ,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
                     ,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
                     ,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
                     ,@LANGUAGE1 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
                     ,@LANGUAGE2 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
                     ,@YEAR NVARCHAR(MAX)                     = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
                     ,@ID NVARCHAR(MAX)                       = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
                     ,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
					 ,@ZV_SAME_QUARTER_BY_BLDAT NVARCHAR(MAX) = ISNULL((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'ZV_SAME_QUARTER_BY_BLDAT'), '')



--Step 1/ Compare values (USD) between table B04_11_IT_FIN_GL_NEW (use TCURR and TCURF) and table B04_11_IT_FIN_GL (use AM_EXCHNG)
EXEC SP_DROPTABLE 	'DC02_01_IT_FIN_GL' 

SELECT 
	A.B04_BSEG_BUKRS,
	A.B04_BSEG_GJAHR, 
	A.B04_BSEG_BELNR, 
	A_T001.T001_WAERS,
	MAX(A.B04_BKPF_BUDAT) AS B04_BKPF_BUDAT,
	SUM(B.B04_ZF_BSEG_DMBTR_S) AS B04_ZF_BSEG_DMBTR_S,
	SUM(B.B04_ZF_BSEG_DMBTR_S_CUC) AS B04_ZF_BSEG_DMBTR_S_CUC_OLD,
	SUM(A.B04_ZF_BSEG_DMBTR_S_CUC) AS B04_ZF_BSEG_DMBTR_S_CUC_NEW,
	MAX(EXCHNG_RATIO) AS EXCH_RATE_OLD,
	MAX(COALESCE(CAST(B00_IT_TCURR.TCURR_UKURS AS FLOAT),1) * COALESCE(B00_IT_TCURF.TCURF_TFACT,1) / COALESCE(B00_IT_TCURF.TCURF_FFACT,1)) AS EXCH_RATE_NEW
INTO DC02_01_IT_FIN_GL
FROM 
	(
		SELECT DISTINCT 
			B04_BSEG_BUKRS,
			B04_BSEG_GJAHR,
			B04_BSEG_BELNR,
			SUM(B04_ZF_BSEG_DMBTR_S_CUC) AS B04_ZF_BSEG_DMBTR_S_CUC,
			MAX(B04_BKPF_BUDAT) AS B04_BKPF_BUDAT
		FROM B04_11_IT_FIN_GL_NEW
		WHERE B04_BSEG_SHKZG = 'S'
		GROUP BY
			B04_BSEG_BUKRS,
			B04_BSEG_GJAHR,
			B04_BSEG_BELNR
	) A

INNER JOIN 
	(
		SELECT DISTINCT 
			B04_BSEG_BUKRS,
			B04_BSEG_GJAHR,
			B04_BSEG_BELNR,
			SUM(B04_ZF_BSEG_DMBTR_S) AS B04_ZF_BSEG_DMBTR_S,
			SUM(B04_ZF_BSEG_DMBTR_S_CUC) AS  B04_ZF_BSEG_DMBTR_S_CUC
		FROM B04_11_IT_FIN_GL
		WHERE B04_BSEG_SHKZG = 'S'
		GROUP BY
			B04_BSEG_BUKRS,
			B04_BSEG_GJAHR,
			B04_BSEG_BELNR
	)B
ON A.B04_BSEG_BUKRS = B.B04_BSEG_BUKRS
AND A.B04_BSEG_GJAHR = B.B04_BSEG_GJAHR
AND A.B04_BSEG_BELNR = B.B04_BSEG_BELNR

LEFT JOIN A_T001
	ON  A.B04_BSEG_BUKRS = A_T001.T001_BUKRS
	
LEFT JOIN AM_EXCHNG
	ON  AM_EXCHNG.EXCHNG_FROM = A_T001.T001_WAERS
	AND AM_EXCHNG.EXCHNG_TO   =  @currency

LEFT JOIN B00_IT_TCURF
	ON A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR
	AND B00_IT_TCURF.TCURF_TCURR  = @currency  
	AND B00_IT_TCURF.TCURF_GDATU = (
		SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
		FROM B00_IT_TCURF
		WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
				B00_IT_TCURF.TCURF_TCURR  = @currency  AND
				B00_IT_TCURF.TCURF_GDATU <= A.B04_BKPF_BUDAT
		ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
		)

LEFT JOIN B00_IT_TCURR
	ON A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR
	AND B00_IT_TCURR.TCURR_TCURR  = @currency  
	AND B00_IT_TCURR.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.B04_BKPF_BUDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 
GROUP BY A.B04_BSEG_BUKRS,
		 A.B04_BSEG_GJAHR, 
		 A.B04_BSEG_BELNR,
		 A_T001.T001_WAERS



--Step 2/ Compare values (USD) between table B04_10_IT_BSAK_BSIK_AP_ACC_SCH_NEW (use TCURR and TCURF) and table B04_10_IT_BSAK_BSIK_AP_ACC_SCH (use AM_EXCHNG)

EXEC SP_DROPTABLE 	'DC02_02_IT_BSAK_BSIK_AP_ACC_SCH' 

SELECT 
	A.BSAIK_BUKRS,
	A.BSAIK_GJAHR, 
	A.BSAIK_BELNR, 
	A_T001.T001_WAERS,
	A.BSAIK_BUDAT AS BSAIK_BUDAT,
	B.ZF_BSAIK_DMBTR_S AS ZF_BSAIK_DMBTR_S,
	B.ZF_BSAIK_DMBTR_S_CUC AS ZF_BSAIK_DMBTR_S_CUC_OLD,
	A.ZF_BSAIK_DMBTR_S_CUC AS ZF_BSAIK_DMBTR_S_CUC_NEW,
	EXCHNG_RATIO AS EXCH_RATE_OLD,
	COALESCE(CAST(B00_IT_TCURR.TCURR_UKURS AS FLOAT),1) * COALESCE(B00_IT_TCURF.TCURF_TFACT,1) / COALESCE(B00_IT_TCURF.TCURF_FFACT,1) AS EXCH_RATE_NEW
INTO DC02_02_IT_BSAK_BSIK_AP_ACC_SCH
FROM 
    (SELECT BSAIK_BUKRS,
	        BSAIK_GJAHR, 
	        BSAIK_BELNR,
			MAX(BSAIK_BUDAT) AS BSAIK_BUDAT,
			SUM(ZF_BSAIK_DMBTR_S_CUC) AS ZF_BSAIK_DMBTR_S_CUC
     FROM B04_10_IT_BSAK_BSIK_AP_ACC_SCH_NEW
	 WHERE BSAIK_SHKZG ='S'
	 GROUP BY BSAIK_BUKRS,
	          BSAIK_GJAHR, 
	          BSAIK_BELNR ) A
INNER JOIN 
    (SELECT BSAIK_BUKRS,
	        BSAIK_GJAHR, 
	        BSAIK_BELNR,
			SUM(ZF_BSAIK_DMBTR_S) AS ZF_BSAIK_DMBTR_S,
			SUM(ZF_BSAIK_DMBTR_S_CUC) AS ZF_BSAIK_DMBTR_S_CUC
	FROM B04_10_IT_BSAK_BSIK_AP_ACC_SCH
	WHERE BSAIK_SHKZG ='S'
	GROUP BY BSAIK_BUKRS,
	          BSAIK_GJAHR, 
	          BSAIK_BELNR ) B

	ON A.BSAIK_BUKRS = B.BSAIK_BUKRS
	AND A.BSAIK_GJAHR = B.BSAIK_GJAHR
	AND A.BSAIK_BELNR = B.BSAIK_BELNR

LEFT JOIN A_T001
	ON  A.BSAIK_BUKRS = A_T001.T001_BUKRS
	
LEFT JOIN AM_EXCHNG
	ON  AM_EXCHNG.EXCHNG_FROM = A_T001.T001_WAERS
	AND AM_EXCHNG.EXCHNG_TO   =  @currency

LEFT JOIN B00_IT_TCURF
	ON A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR
	AND B00_IT_TCURF.TCURF_TCURR  = @currency  
	AND B00_IT_TCURF.TCURF_GDATU = (
		SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
		FROM B00_IT_TCURF
		WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
				B00_IT_TCURF.TCURF_TCURR  = @currency  AND
				B00_IT_TCURF.TCURF_GDATU <= A.BSAIK_BUDAT
		ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
		)

LEFT JOIN B00_IT_TCURR
	ON A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR
	AND B00_IT_TCURR.TCURR_TCURR  = @currency  
	AND B00_IT_TCURR.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.BSAIK_BUDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 



--Step 3/ Compare values (USD) between table B04_12_IT_BSAD_BSID_AR_ACC_SCH_NEW (use TCURR and TCURF) and table B04_12_IT_BSAD_BSID_AR_ACC_SCH (use AM_EXCHNG)


EXEC SP_DROPTABLE 	'DC02_03_IT_BSAD_BSID_AR_ACC_SCH' 

SELECT 
	A.B04B_BSAID_BUKRS,
	A.B04B_BSAID_GJAHR, 
	A.B04B_BSAID_BELNR, 
	A_T001.T001_WAERS,
	MAX(A.B04B_BSAID_BUDAT) AS B04B_BSAID_BUDAT,
	SUM(B.B04B_ZF_BSAID_DMBTR_S) AS B04B_ZF_BSAID_DMBTR_S,
	SUM(B.B04B_ZF_BSAID_DMBTR_S_CUC) AS B04B_ZF_BSAID_DMBTR_S_CUC_OLD,
	SUM(A.B04B_ZF_BSAID_DMBTR_S_CUC) AS B04B_ZF_BSAID_DMBTR_S_CUC_NEW,
	MAX(AM_EXCHNG.EXCHNG_RATIO) AS EXCH_RATE_OLD,
	MAX(COALESCE(CAST(B00_IT_TCURR.TCURR_UKURS AS FLOAT),1) * COALESCE(B00_IT_TCURF.TCURF_TFACT,1) / COALESCE(B00_IT_TCURF.TCURF_FFACT,1)) AS EXCH_RATE_NEW
INTO DC02_03_IT_BSAD_BSID_AR_ACC_SCH
	FROM (SELECT B04B_BSAID_BUKRS,
				 B04B_BSAID_GJAHR, 
				 B04B_BSAID_BELNR, 
				 MAX(B04B_BSAID_BUDAT) AS B04B_BSAID_BUDAT,
				 SUM(B04B_ZF_BSAID_DMBTR_S) AS B04B_ZF_BSAID_DMBTR_S,
				 SUM(B04B_ZF_BSAID_DMBTR_S_CUC) AS B04B_ZF_BSAID_DMBTR_S_CUC
          FROM B04_12_IT_BSAD_BSID_AR_ACC_SCH_NEW
	      WHERE B04B_BSAID_SHKZG = 'S'
		  GROUP BY B04B_BSAID_BUKRS,
				 B04B_BSAID_GJAHR, 
				 B04B_BSAID_BELNR) A

INNER JOIN (SELECT B04B_BSAID_BUKRS,
				   B04B_BSAID_GJAHR, 
				   B04B_BSAID_BELNR, 
				   SUM(B04B_ZF_BSAID_DMBTR_S) AS B04B_ZF_BSAID_DMBTR_S,
				   SUM(B04B_ZF_BSAID_DMBTR_S_CUC) AS B04B_ZF_BSAID_DMBTR_S_CUC
          FROM B04_12_IT_BSAD_BSID_AR_ACC_SCH
	      WHERE B04B_BSAID_SHKZG = 'S'
		  GROUP BY B04B_BSAID_BUKRS,
				 B04B_BSAID_GJAHR, 
				 B04B_BSAID_BELNR) B
	ON A.B04B_BSAID_BUKRS = B.B04B_BSAID_BUKRS
	AND A.B04B_BSAID_GJAHR = B.B04B_BSAID_GJAHR
	AND A.B04B_BSAID_BELNR = B.B04B_BSAID_BELNR

LEFT JOIN A_T001
	ON  A.B04B_BSAID_BUKRS = A_T001.T001_BUKRS
	
LEFT JOIN AM_EXCHNG
	ON  AM_EXCHNG.EXCHNG_FROM = A_T001.T001_WAERS
	AND AM_EXCHNG.EXCHNG_TO   =  @currency

LEFT JOIN B00_IT_TCURF
	ON A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR
	AND B00_IT_TCURF.TCURF_TCURR  = @currency  
	AND B00_IT_TCURF.TCURF_GDATU = (
		SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
		FROM B00_IT_TCURF
		WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
				B00_IT_TCURF.TCURF_TCURR  = @currency  AND
				B00_IT_TCURF.TCURF_GDATU <= A.B04B_BSAID_BUDAT
		ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
		)

LEFT JOIN B00_IT_TCURR
	ON A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR
	AND B00_IT_TCURR.TCURR_TCURR  = @currency  
	AND B00_IT_TCURR.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.B04B_BSAID_BUDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 
GROUP BY A.B04B_BSAID_BUKRS,
	A.B04B_BSAID_GJAHR, 
	A.B04B_BSAID_BELNR,
	A_T001.T001_WAERS

EXEC SP_UNNAME_FIELD 'B04_',DC02_01_IT_FIN_GL
EXEC SP_RENAME_FIELD 'DC02_01_',DC02_01_IT_FIN_GL
EXEC SP_RENAME_FIELD 'DC02_02_',DC02_02_IT_BSAK_BSIK_AP_ACC_SCH
EXEC SP_UNNAME_FIELD 'B04B_',DC02_03_IT_BSAD_BSID_AR_ACC_SCH
EXEC SP_RENAME_FIELD 'DC02_03_',DC02_03_IT_BSAD_BSID_AR_ACC_SCH
GO
