USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Khoi
-- Create date: <Create Date,,>
-- Description:	Create the change document cubes
--Each Objectclas might have many change document cube
--List of cubes:
--		Objectclas is EINKBELEG:
--				PO approval
--				PO price change
--				PO creation date change
--				PO amount change
--				Release strategy Change
--		Objectclas is INCOMINGINVOICE:
--				Invoice approval
--				Release invoice required
--				Invoice quantity changes
--		Objectclas is IBAN:
--				IBAN change
--		Objectclas is KRED(changes To suppliers):
--				Change to release group
--				Supplier is blocked
--				Supplier payment terms
--		Objectclas is BELEG:
--				Change to payment method
--				Change to payment block
--		Objectclas is SACH (changes to Chart Of Accounts)
--		Objectclas is DEBI (Change to customer)
-- =============================================
CREATE   PROCEDURE [dbo].[script_B21_CHANGE_DOCUMENT_CUBE]
as

--DYNAMIC_SCRIPT_START
/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('_DatabaseLogTable', 'U') IS NULL BEGIN CREATE TABLE [dbo].[_DatabaseLogTable] ([Database] nvarchar(max) NULL,[Object] nvarchar(max) NULL,[Object Type] nvarchar(max) NULL,[User] nvarchar(max) NULL,[Date] date NULL,[Time] time NULL,[Description] nvarchar(max) NULL,[Table] nvarchar(max),[Rows] int) END

--Log start of procedure
INSERT INTO [dbo].[_DatabaseLogTable] ([Database],[Object],[Object Type],[User],[Date],[Time],[Description],[Table],[Rows])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(date,GETDATE()),CONVERT(time,GETDATE()),'Procedure started',NULL,NULL

/* Initialize parameters from globals table */

     DECLARE 	 
			 @currency nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'currency')
			,@date1 nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'date1')
			,@date2 nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'date2')
			,@downloaddate nvarchar(max)		= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'downloaddate')
			,@exchangeratetype nvarchar(max)	= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'exchangeratetype')
			,@language1 nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'language1')
			,@language2 nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'language2')
			,@year nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'year')
			,@id nvarchar(max)					= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'id')
			,@ZV_LIMIT nvarchar(max)		    = (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'ZV_LIMIT')
			,@errormsg NVARCHAR(MAX)
			
DECLARE @dateformat varchar(3)
SET @dateformat   = (SELECT dbo.get_param('dateformat'))
SET DATEFORMAT @dateformat;

--Step 1 Join CDHDR and CDPOS to create the cube
--Add name of the user who create the cube
--Filter on Objectclass and other condition base on each cube
	EXEC SP_REMOVE_TABLES 'B21_%'

--STep 1.1 CDHDR_OBJECTCLAS='EINKBELEG'
	EXEC SP_DROPTABLE 'B21_01_TT_CDHDR_CDPOS_EINKBELEG'
	SELECT DISTINCT A_CDHDR.*,A_CDPOS.*
	INTO B21_01_TT_CDHDR_CDPOS_EINKBELEG
	FROM A_CDHDR 
	INNER JOIN A_CDPOS
	ON	CDHDR_MANDANT=CDPOS_MANDANT AND
		CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS AND
		CDHDR_OBJECTID=CDPOS_OBJECTID AND
		CDHDR_CHANGENR=CDPOS_CHANGENR
	WHERE CDHDR_OBJECTCLAS='EINKBELEG'

--Step 1.1.1 Get the list of PO approval
	EXEC SP_DROPTABLE B21_02_TT_PO_APPROVAL
	SELECT * 
	INTO B21_02_TT_PO_APPROVAL
	FROM B21_01_TT_CDHDR_CDPOS_EINKBELEG
	WHERE 
		CDPOS_TABNAME='EKKO' AND 
		CDPOS_FNAME='FRGZU' AND 
		CDHDR_CHANGE_IND='U'

--Step 1.1.2 Add other information
	EXEC SP_DROPTABLE B21_03_IT_PO_APPROVAL
	SELECT B21_02_TT_PO_APPROVAL.*,
	V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_03_IT_PO_APPROVAL
	FROM B21_02_TT_PO_APPROVAL
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME


-- STep 1.1.3 Get the list of PO price change

	EXEC SP_DROPTABLE B21_04_TT_PO_PRICE_CHANGE
	SELECT * 
	INTO B21_04_TT_PO_PRICE_CHANGE
	FROM B21_01_TT_CDHDR_CDPOS_EINKBELEG
	WHERE 
		CDPOS_TABNAME='EKPO' AND 
		CDPOS_FNAME='NETPR' AND 
		CDHDR_CHANGE_IND='U'
--Step 1.1.4 Add other information
	EXEC SP_DROPTABLE B21_05_IT_PO_PRICE_CHANGE
	SELECT B21_04_TT_PO_PRICE_CHANGE.*,
		V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_05_IT_PO_PRICE_CHANGE
	FROM B21_04_TT_PO_PRICE_CHANGE
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME
	

--STep 1.1.5 Get the list PO creation date change
	EXEC SP_DROPTABLE B21_06_TT_PO_DATE_CHANGE
	SELECT * 
	INTO B21_06_TT_PO_DATE_CHANGE
	FROM B21_01_TT_CDHDR_CDPOS_EINKBELEG
	WHERE 
		CDPOS_TABNAME='EKKO' AND 
		CDPOS_FNAME='AEDAT' AND 
		CDHDR_CHANGE_IND='U'

--Step 1.1.6 Add other information
	EXEC SP_DROPTABLE B21_07_IT_PO_DATE_CHANGE

	SELECT B21_06_TT_PO_DATE_CHANGE.*,
		V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_07_IT_PO_DATE_CHANGE
	FROM B21_06_TT_PO_DATE_CHANGE
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME

-- Step 1.1.7 Get the list PO amount change

	EXEC SP_DROPTABLE B21_08_TT_PO_AMOUNT_CHANGE
	SELECT * 
	INTO B21_08_TT_PO_AMOUNT_CHANGE
	FROM B21_01_TT_CDHDR_CDPOS_EINKBELEG
	WHERE 
		CDPOS_TABNAME='EKPO' AND 
		CDPOS_FNAME='NETWR' AND 
		CDHDR_CHANGE_IND='U'
--Step 1.1.8 Add other information
	EXEC SP_DROPTABLE B21_09_IT_PO_AMOUNT_CHANGE
		SELECT B21_08_TT_PO_AMOUNT_CHANGE.*,
		V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_09_IT_PO_AMOUNT_CHANGE
	FROM B21_08_TT_PO_AMOUNT_CHANGE
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME

--Step 1.1.9 Get the list of  release strategy Change

	EXEC SP_DROPTABLE B21_10_TT_RELEASE_STRATEGY

	SELECT * 
	INTO B21_10_TT_RELEASE_STRATEGY
	FROM B21_01_TT_CDHDR_CDPOS_EINKBELEG
	WHERE 
		CDPOS_FNAME='FRGSX' or  CDPOS_FNAME='FRGGR' AND
		CDHDR_CHANGE_IND='U'
--Step 1.1.10 Add other information
EXEC SP_DROPTABLE B21_11_IT_RELEASE_STRATEGY

		SELECT B21_10_TT_RELEASE_STRATEGY.*,
		V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_11_IT_RELEASE_STRATEGY
	FROM B21_10_TT_RELEASE_STRATEGY
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME



-- Step 1.2 CDHDR_OBJECTCLAS='INCOMINGINVOICE'

	EXEC SP_DROPTABLE B21_12_TT_CDHDR_CDPOS_INCO

	SELECT DISTINCT A_CDHDR.*,A_CDPOS.*	
	INTO B21_12_TT_CDHDR_CDPOS_INCO
	FROM A_CDHDR 
	INNER JOIN A_CDPOS
	ON 
		CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS
		AND CDHDR_OBJECTID=CDPOS_OBJECTID
		AND CDHDR_CHANGENR=CDPOS_CHANGENR
	WHERE CDHDR_OBJECTCLAS='INCOMINGINVOICE'

--Step 1.2.1 Get the list of release invoice required

	EXEC SP_DROPTABLE B21_13_TT_RELEASE_INVOICE

	SELECT * INTO B21_13_TT_RELEASE_INVOICE
	FROM B21_12_TT_CDHDR_CDPOS_INCO
	WHERE
	 CDPOS_FNAME='FRGKZ' AND CDHDR_CHANGE_IND='U'

--Step 1.2.2 Add other information
	 EXEC SP_DROPTABLE B21_14_IT_RELEASE_INVOICE

	 SELECT B21_13_TT_RELEASE_INVOICE.*,
	V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_14_IT_RELEASE_INVOICE
	FROM B21_13_TT_RELEASE_INVOICE
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME


--Step 1.2.3 Get the list of invoice value changes

	EXEC SP_DROPTABLE B21_15_TT_INV_VALUE
	SELECT * INTO B21_15_TT_INV_VALUE
	FROM B21_12_TT_CDHDR_CDPOS_INCO
	WHERE 
	 CDPOS_FNAME='WRBTR' AND CDHDR_CHANGE_IND='U'

-- Step 1.2.4 Add other information
	 EXEC SP_DROPTABLE B21_16_IT_INV_VALUE

	 SELECT B21_15_TT_INV_VALUE.*,
	V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_16_IT_INV_VALUE
	FROM B21_15_TT_INV_VALUE
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME

--Step 1.2.5 Get the list of Invoice approval
	
	EXEC SP_DROPTABLE B21_17_TT_INV_APPROVAL
	SELECT * INTO B21_17_TT_INV_APPROVAL
	FROM B21_12_TT_CDHDR_CDPOS_INCO
	WHERE
		CDPOS_FNAME='ZLSPR' OR 
		CDPOS_FNAME='RBSTAT' AND 
		CDHDR_CHANGE_IND='U'
		AND CDPOS_VALUE_OLD <> '' AND CDPOS_VALUE_NEW = ''
--Step 1.2.6 Add other information
EXEC SP_DROPTABLE B21_18_IT_INV_APPROVAL

	 SELECT B21_17_TT_INV_APPROVAL.*,
	V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_18_IT_INV_APPROVAL
	FROM B21_17_TT_INV_APPROVAL
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME


--Step 1.3 CDHDR_OBJECTCLAS='IBAN'

	EXEC SP_DROPTABLE B21_19_TT_CHANGE_IBAN

	SELECT DISTINCT A_CDHDR.*,A_CDPOS.*
	INTO B21_19_TT_CHANGE_IBAN
	FROM A_CDHDR 
	INNER JOIN A_CDPOS
	ON 
		CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS AND
		CDHDR_OBJECTID=CDPOS_OBJECTID AND
		CDHDR_CHANGENR=CDPOS_CHANGENR
	WHERE CDHDR_OBJECTCLAS='IBAN'
--Step 1.3.1 Add other information
	EXEC SP_DROPTABLE B21_20_IT_CHANGE_IBAN

		 SELECT B21_19_TT_CHANGE_IBAN.*,LFBK_LIFNR,
	V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_20_IT_CHANGE_IBAN
	FROM B21_19_TT_CHANGE_IBAN
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME
	LEFT JOIN A_LFBK  
		ON  REPLACE(CDHDR_OBJECTID,' ','') LIKE '%'+CONCAT(LFBK_BANKS,LFBK_BANKL,LFBK_BANKN,LFBK_BKONT)+'%'

		

--Step 1.4 CDHDR_OBJECTCLAS='Kred'
--Step 1.4.1 Filter the Objectclas is KRED
	
	EXEC SP_DROPTABLE B21_21_TT_CHANGE_KRED

	SELECT DISTINCT A_CDHDR.*,A_CDPOS.*
	INTO B21_21_TT_CHANGE_KRED
	FROM A_CDHDR 
	INNER JOIN A_CDPOS
	ON 
		 CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS AND
		 CDHDR_OBJECTID=CDPOS_OBJECTID AND
		 CDHDR_CHANGENR=CDPOS_CHANGENR
	WHERE CDHDR_OBJECTCLAS='KRED'
--STep 1.4.2 Add orther information
	EXEC SP_DROPTABLE B21_22_TT_CHANGE_KRED_ADD_INFO

 SELECT B21_21_TT_CHANGE_KRED.*,
	V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_22_TT_CHANGE_KRED_ADD_INFO
	FROM B21_21_TT_CHANGE_KRED
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME

--Step 1.4.3 Remove all the LFB1 not exists in the company code list
EXEC SP_DROPTABLE B21_23_IT_CHANGE_KRED

SELECT * 
INTO B21_23_IT_CHANGE_KRED
FROM B21_22_TT_CHANGE_KRED_ADD_INFO
WHERE CDPOS_TABKEY NOT IN 
(
	SELECT CDPOS_TABKEY FROM
	B21_22_TT_CHANGE_KRED_ADD_INFO
	WHERE CDPOS_TABNAME='LFB1' AND RIGHT(CDPOS_TABKEY,4) NOT IN 
	(
		SELECT * FROM AM_COMPANY_CODE
	)
)


-- STep 1.4.4 Get Change to release group 

	EXEC SP_DROPTABLE B21_24_IT_RELEASE_GROUP
	SELECT * INTO B21_24_IT_RELEASE_GROUP
	FROM B21_23_IT_CHANGE_KRED
	WHERE 
	  CDPOS_FNAME='FRGRP'

--Step 1.4.5 Get Supplier is blocked

	EXEC SP_DROPTABLE B21_25_IT_SUPP_BLOCK
	SELECT * INTO B21_25_IT_SUPP_BLOCK
	FROM B21_23_IT_CHANGE_KRED
	WHERE 
	  CDPOS_FNAME = 'LOEKZ' OR 
	  CDPOS_FNAME ='LOEVM' OR 
	  CDPOS_FNAME ='SPERR' OR
	  CDPOS_FNAME ='SPERM' OR 
	  CDPOS_FNAME ='SPERZ' OR 
	  CDPOS_FNAME ='NODEL'

--Step 1.4.6 Supplier payment terms

EXEC SP_DROPTABLE B21_26_IT_SUPP_PAYMENT_TERMS
SELECT * INTO B21_26_IT_SUPP_PAYMENT_TERMS
FROM B21_23_IT_CHANGE_KRED
WHERE 
	CDPOS_FNAME='ZTERM'

--Step 1.5 Objectclas='BELEG'
	EXEC SP_DROPTABLE B21_27_TT_CHANGE_BELEG

	SELECT DISTINCT A_CDHDR.*,A_CDPOS.*
	INTO B21_27_TT_CHANGE_BELEG
	FROM A_CDHDR 
	INNER JOIN A_CDPOS
	ON 
		 CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS AND
		 CDHDR_OBJECTID=CDPOS_OBJECTID AND
		 CDHDR_CHANGENR=CDPOS_CHANGENR
	WHERE CDHDR_OBJECTCLAS='BELEG'

--Step 1.5.1 Change to payment method

	EXEC SP_DROPTABLE B21_28_TT_PAYMENT_METHOD

	SELECT * 
	INTO B21_28_TT_PAYMENT_METHOD
	FROM B21_27_TT_CHANGE_BELEG
	WHERE 
		 CDPOS_FNAME = 'ZLSCH'
--Step 1.5.2 Add other infomation
	EXEC SP_DROPTABLE B21_29_IT_PAYMENT_METHOD

	 SELECT B21_28_TT_PAYMENT_METHOD.*,
	V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_29_IT_PAYMENT_METHOD
	FROM B21_28_TT_PAYMENT_METHOD
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME

--Step 1.5.3 Change to payment block

	EXEC SP_DROPTABLE B21_30_TT_PAYMENT_BLOCK

	SELECT * 
	INTO B21_30_TT_PAYMENT_BLOCK
	FROM B21_27_TT_CHANGE_BELEG
	WHERE 
		 CDPOS_FNAME = 'ZLSPR'
--Step 1.5.4 Add other infomation
EXEC SP_DROPTABLE B21_31_IT_PAYMENT_BLOCK

	 SELECT B21_30_TT_PAYMENT_BLOCK.*,
	V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_31_IT_PAYMENT_BLOCK
	FROM B21_30_TT_PAYMENT_BLOCK
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME


-- Step 1.6.1 Create list of Invoice approval username for each OBJECTCLASS

	EXEC SP_DROPTABLE 'TEMP1'
	SELECT
	DISTINCT CDHDR_OBJECTID,CDHDR_USERNAME,
	ROW_NUMBER() OVER (PARTITION BY CDHDR_OBJECTID ORDER BY  
	CDHDR_OBJECTID,CDHDR_USERNAME DESC ) AS ROWINDEX
	INTO TEMP1
	FROM B21_18_IT_INV_APPROVAL

--Step 1.6.2 Add other infomation

	EXEC SP_DROPTABLE 'B21_32_IT_INV_APPROVAL_USER'

	SELECT DISTINCT 
		A.CDHDR_OBJECTID,
		B.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME1,
		C.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME2,
		D.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME3,
		E.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME4,
		F.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME5,
		G.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME6,
		CONCAT('_',B.CDHDR_USERNAME,'_',C.CDHDR_USERNAME,'_',D.CDHDR_USERNAME,'_',E.CDHDR_USERNAME,'_',F.CDHDR_USERNAME,'_',G.CDHDR_USERNAME) AS ZF_LIST_CDHDR_USERNAME,
		A.CDHDR_OBJECTID AS ZF_KEY_JOIN_CDHDR_RSEG
	INTO B21_32_IT_INV_APPROVAL_USER
	FROM TEMP1 AS A
	LEFT JOIN TEMP1 AS B ON A.CDHDR_OBJECTID=B.CDHDR_OBJECTID AND B.ROWINDEX=1
	LEFT JOIN TEMP1 AS C ON A.CDHDR_OBJECTID=C.CDHDR_OBJECTID AND C.ROWINDEX=2 
	LEFT JOIN TEMP1 AS D ON A.CDHDR_OBJECTID=D.CDHDR_OBJECTID AND D.ROWINDEX=3 
	LEFT JOIN TEMP1 AS E ON A.CDHDR_OBJECTID=E.CDHDR_OBJECTID AND E.ROWINDEX=4
	LEFT JOIN TEMP1 AS F ON A.CDHDR_OBJECTID=F.CDHDR_OBJECTID AND F.ROWINDEX=5
	LEFT JOIN TEMP1 AS G ON A.CDHDR_OBJECTID=G.CDHDR_OBJECTID AND G.ROWINDEX=6

	EXEC SP_DROPTABLE TEMP1


-- Step 1.7.1Create the list of the list of PO approval user

	EXEC SP_DROPTABLE 'TEMP1'
	SELECT
	DISTINCT CDHDR_OBJECTID,CDHDR_USERNAME,
	ROW_NUMBER() OVER (PARTITION BY CDHDR_OBJECTID ORDER BY  
	CDHDR_OBJECTID,CDHDR_USERNAME DESC ) AS ROWINDEX
	INTO TEMP1
	FROM B21_03_IT_PO_APPROVAL
--Step 1.7.2  Add other infomation
	EXEC SP_DROPTABLE B21_33_IT_PO_APPROVAL_USER
	SELECT DISTINCT 
		A.CDHDR_OBJECTID,
		B.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME1,
		C.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME2,
		D.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME3,
		E.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME4,
		F.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME5,
		G.CDHDR_USERNAME AS ZF_CDPOS_CDHDR_USERNAME6,
		CONCAT('_',B.CDHDR_USERNAME,'_',C.CDHDR_USERNAME,'_',D.CDHDR_USERNAME,'_',E.CDHDR_USERNAME,'_',F.CDHDR_USERNAME,'_',G.CDHDR_USERNAME) AS ZF_LIST_CDHDR_USERNAME,
		A.CDHDR_OBJECTID AS ZF_KEY_JOIN_CDHDR_RSEG
	INTO B21_33_IT_PO_APPROVAL_USER
	FROM TEMP1 AS A
	LEFT JOIN TEMP1 AS B ON A.CDHDR_OBJECTID=B.CDHDR_OBJECTID AND B.ROWINDEX=1
	LEFT JOIN TEMP1 AS C ON A.CDHDR_OBJECTID=C.CDHDR_OBJECTID AND C.ROWINDEX=2 
	LEFT JOIN TEMP1 AS D ON A.CDHDR_OBJECTID=D.CDHDR_OBJECTID AND D.ROWINDEX=3 
	LEFT JOIN TEMP1 AS E ON A.CDHDR_OBJECTID=E.CDHDR_OBJECTID AND E.ROWINDEX=4
	LEFT JOIN TEMP1 AS F ON A.CDHDR_OBJECTID=F.CDHDR_OBJECTID AND F.ROWINDEX=5
	LEFT JOIN TEMP1 AS G ON A.CDHDR_OBJECTID=G.CDHDR_OBJECTID AND G.ROWINDEX=6

	EXEC SP_DROPTABLE TEMP1

--sTEP 1.8.1 Objectclas is SACH
EXEC SP_DROPTABLE B21_34_TT_CHANGE_SACH

	SELECT DISTINCT A_CDHDR.*,A_CDPOS.*
	INTO B21_34_TT_CHANGE_SACH
	FROM A_CDHDR 
	INNER JOIN A_CDPOS
	ON 
		 CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS AND
		 CDHDR_OBJECTID=CDPOS_OBJECTID AND
		 CDHDR_CHANGENR=CDPOS_CHANGENR
	WHERE CDHDR_OBJECTCLAS='SACH'
--Step 1.8.2 Add other information
EXEC SP_DROPTABLE B21_35_IT_CHANGE_SACH
	SELECT DISTINCT B21_34_TT_CHANGE_SACH.*,
	V_USERNAME_NAME_TEXT,
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name	
	INTO B21_35_IT_CHANGE_SACH
	FROM B21_34_TT_CHANGE_SACH 
	LEFT JOIN A_V_USERNAME
		ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME



--Step 1.9.1 Objectclas is DEBI

EXEC SP_DROPTABLE B21_36_TT_CHANGE_DEBI

	SELECT DISTINCT A_CDHDR.*,A_CDPOS.*
	INTO B21_36_TT_CHANGE_DEBI
	FROM A_CDHDR 
	INNER JOIN A_CDPOS
	ON 
		 CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS AND
		 CDHDR_OBJECTID=CDPOS_OBJECTID AND
		 CDHDR_CHANGENR=CDPOS_CHANGENR
	WHERE CDHDR_OBJECTCLAS='DEBI'

-- Step 1.9.2 Add other information
EXEC SP_DROPTABLE B21_37_IT_CHANGE_DEBI

	SELECT DISTINCT B21_36_TT_CHANGE_DEBI.*,
	V_USERNAME_NAME_TEXT,
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name	
	INTO B21_37_IT_CHANGE_DEBI
	FROM B21_36_TT_CHANGE_DEBI 
	LEFT JOIN A_V_USERNAME
		ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME
	WHERE CDHDR_OBJECTCLAS='DEBI'




	-- Step 1.10.1 New update for FI invoice value change

--FI Invoice value change
EXEC SP_DROPTABLE B21_38_TT_FI_INVOICE_VALUE


	SELECT * 
	INTO B21_38_TT_FI_INVOICE_VALUE
	FROM B21_27_TT_CHANGE_BELEG
	WHERE 
		 CDPOS_FNAME = 'WRBTR' AND CDPOS_TABNAME IN ('BSAK','BSIK')
--Step 1.10.2 Add other information
EXEC SP_DROPTABLE B21_39_IT_FI_INVOICE_VALUE

	 SELECT B21_38_TT_FI_INVOICE_VALUE.*,
	V_USERNAME_NAME_TEXT,	
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name
	INTO B21_39_IT_FI_INVOICE_VALUE
	FROM B21_38_TT_FI_INVOICE_VALUE
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME

--Step 2 Rename the fields of the tables


	EXEC SP_RENAME_FIELD 'B21_03_','B21_03_IT_PO_APPROVAL'
	EXEC SP_RENAME_FIELD 'B21_05_','B21_05_IT_PO_PRICE_CHANGE'
	EXEC SP_RENAME_FIELD 'B21_07_','B21_07_IT_PO_DATE_CHANGE'
	EXEC SP_RENAME_FIELD 'B21_09_','B21_09_IT_PO_AMOUNT_CHANGE'
	EXEC SP_RENAME_FIELD 'B21_11_','B21_11_IT_RELEASE_STRATEGY'
	EXEC SP_RENAME_FIELD 'B21_14_','B21_14_IT_RELEASE_INVOICE'
	EXEC SP_RENAME_FIELD 'B21_16_','B21_16_IT_INV_VALUE'
	EXEC SP_RENAME_FIELD 'B21_18_','B21_18_IT_INV_APPROVAL'
	EXEC SP_RENAME_FIELD 'B21_20_','B21_20_IT_CHANGE_IBAN'
	EXEC SP_RENAME_FIELD 'B21_23_','B21_23_IT_CHANGE_KRED'
	EXEC SP_RENAME_FIELD 'B21_24_','B21_24_IT_RELEASE_GROUP'
	EXEC SP_RENAME_FIELD 'B21_25_','B21_25_IT_SUPP_BLOCK'
	EXEC SP_RENAME_FIELD 'B21_26_','B21_26_IT_SUPP_PAYMENT_TERMS'
	EXEC SP_RENAME_FIELD 'B21_29_','B21_29_IT_PAYMENT_METHOD'
	EXEC SP_RENAME_FIELD 'B21_31_','B21_31_IT_PAYMENT_BLOCK'
	EXEC SP_RENAME_FIELD 'B21_32_','B21_32_IT_INV_APPROVAL_USER'
	EXEC SP_RENAME_FIELD 'B21_33_','B21_33_IT_PO_APPROVAL_USER'
	EXEC SP_RENAME_FIELD 'B21_35_','B21_35_IT_CHANGE_SACH'
	EXEC SP_RENAME_FIELD 'B21_37_','B21_37_IT_CHANGE_DEBI'
	EXEC SP_RENAME_FIELD 'B21_39_','B21_39_IT_FI_INVOICE_VALUE'
-- Step 3 Delete all temporary table

EXEC SP_REMOVE_TABLES '%_TT_%'
GO
