USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC [dbo].[P08_T24_BANK_OUT](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_P08_T24_BANK_OUT'

GO
