USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROCEDURE [dbo].[O08_T18_SALES_RED_PER_CUSTOMER_SOLA](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_O08_T18_SALES_RED_PER_CUSTOMER_SOLA'

GO
