USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE     PROCEDURE [dbo].[script_O08_T18_SALES_RED_PER_CUSTOMER_SOLA]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START

BEGIN
/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END

--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL


/* Initialize parameters from globals table */

     DECLARE 	 
			 @CURRENCY NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
			,@DATE1 NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
			,@DATE2 NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
			,@DOWNLOADDATE NVARCHAR(MAX)		= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
			,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
			,@EXCHANGERATETYPE NVARCHAR(MAX)	= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
			,@LANGUAGE1 NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
			,@LANGUAGE2 NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
			,@YEAR NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
			,@ID NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
			,@LIMIT_RECORDS INT		            = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)


/*Test mode*/

SET ROWCOUNT @LIMIT_RECORDS

/*Change history comments*/


  /*
  Title:	[O08_T18_SALES_RED_PER_CUSTOMER]
  Description: Create a table that will enable to show total sales reductions per customer

    --------------------------------------------------------------
    Update history
    --------------------------------------------------------------
    Date		    | Who |	Description
	07-09-2018	     CJW   Created
	12-06-2018	     Hung  Reworked

  */

/*--Step 0
	Update scope table with GL acount in range 5517000000 - 5517000299
*/
	INSERT INTO AM_SALES_RED_ACCOUNTS
	SELECT DISTINCT BSEG_HKONT FROM 
		(SELECT DISTINCT BSEG_HKONT FROM A_BSEG WHERE ISNUMERIC(BSEG_HKONT) = 1) A_BSEG
	WHERE CAST(BSEG_HKONT AS FLOAT) >= 5517000000 AND CAST(BSEG_HKONT AS FLOAT) <= 5517000299
	AND NOT EXISTS(SELECT * FROM AM_SALES_RED_ACCOUNTS WHERE AMSR_GL_ACCOUNT = BSEG_HKONT)

	INSERT INTO AM_CUST_RED_HIERARCHY
	SELECT DISTINCT 'Cost of sales', BSEG_HKONT FROM 
		(SELECT DISTINCT BSEG_HKONT FROM A_BSEG WHERE ISNUMERIC(BSEG_HKONT) = 1) A_BSEG
	WHERE CAST(BSEG_HKONT AS FLOAT) >= 5517000000 AND CAST(BSEG_HKONT AS FLOAT) <= 5517000299
	AND NOT EXISTS(SELECT * FROM AM_CUST_RED_HIERARCHY WHERE AM_GL_ACCOUNT = BSEG_HKONT)
/*--Step 1
--Create a list of journal entry numbers and customer numbers
  */
	EXEC SP_DROPTABLE 'O18_01_TT_JOURNAL_WITH_MORE_THAN_ONE_CUSTOMER'
	SELECT B04_BSEG_BUKRS, B04_BSEG_GJAHR, B04_BSEG_BELNR, COUNT(*) AS NR_CUSTOMER
	INTO O18_01_TT_JOURNAL_WITH_MORE_THAN_ONE_CUSTOMER
	FROM (SELECT DISTINCT B04_BSEG_BUKRS, B04_BSEG_GJAHR, B04_BSEG_BELNR, B04_BSEG_KUNNR 
			FROM B04_11_IT_FIN_GL
			WHERE ISNULL(B04_BSEG_KUNNR, '') <> '') B04_11_IT_FIN_GL
	GROUP BY B04_BSEG_BUKRS, B04_BSEG_GJAHR, B04_BSEG_BELNR
	HAVING COUNT(*) > 1

/*--Step 2
-- Get essential field for Sale reduction header table
-- Fill customer number for journal entry line item without customer name
-- Update Journal entry with multiple entry line item field
*/

	EXEC SP_DROPTABLE 'O18_02_TT_JES_HEADER'

	SELECT B04_11_IT_FIN_GL.B04_BSEG_BUKRS AS BSEG_BUKRS,
		   B04_11_IT_FIN_GL.B04_BSEG_GJAHR AS BSEG_GJAHR,
		   B04_11_IT_FIN_GL.B04_BSEG_BELNR AS BSEG_BELNR,
		   B04_BSEG_KOART AS BSEG_KOART,
		   B04_BSEG_BUZEI AS BSEG_BUZEI,
		   B04_BSEG_SHKZG AS BSEG_SHKZG,
		   B04_BSEG_HKONT AS BSEG_HKONT,
		   IIF(ISNULL(B04_11_IT_FIN_GL.B04_BSEG_KUNNR, '') <> '', B04_11_IT_FIN_GL.B04_BSEG_KUNNR,
				(SELECT TOP 1 B.B04_BSEG_KUNNR FROM B04_11_IT_FIN_GL B
											WHERE B.B04_BSEG_BUKRS = B04_11_IT_FIN_GL.B04_BSEG_BUKRS
												AND B.B04_BSEG_GJAHR = B04_11_IT_FIN_GL.B04_BSEG_GJAHR
												AND B.B04_BSEG_BELNR = B04_11_IT_FIN_GL.B04_BSEG_BELNR
												AND ISNULL(B.B04_BSEG_KUNNR, '') <> ''))
		   AS BSEG_KUNNR,
		   B04_BKPF_HWAER AS BKPF_HWAER,
		   B04_AM_GLOBALS_CURRENCY AS AM_GLOBALS_CURRENCY,
		   B04_BSEG_PRCTR as BSEG_PRCTR,
		   AM_ACCOUNT_BUCKET,
		   B04_ZF_BSEG_DMBTR_S AS ZF_BSEG_DMBTR_S,
		   B04_ZF_BSEG_DMBTR_S_CUC AS ZF_BSEG_DMBTR_S_CUC,
           B04_ZF_BSEG_DMBE2_S AS ZF_BSEG_DMBE2_S,
           B04_ZF_BSEG_DMBE3_S AS ZF_BSEG_DMBE3_S,		   
		   B04_ZF_BKPF_BUDAT_YEAR_MNTH AS ZF_BKPF_BUDAT_YEAR_MNTH,
		   ISNULL(NR_CUSTOMER, 0) AS CUSTOMER_IN_ONE_JOURNAL_ENTRY
		INTO O18_02_TT_JES_HEADER
		FROM B04_11_IT_FIN_GL

		INNER JOIN AM_SALES_RED_ACCOUNTS
			ON AM_SALES_RED_ACCOUNTS.AMSR_GL_ACCOUNT = B04_11_IT_FIN_GL.B04_BSEG_HKONT

		LEFT JOIN AM_CUST_RED_HIERARCHY
			ON  AM_SALES_RED_ACCOUNTS.AMSR_GL_ACCOUNT = AM_CUST_RED_HIERARCHY.AM_GL_ACCOUNT
		LEFT JOIN O18_01_TT_JOURNAL_WITH_MORE_THAN_ONE_CUSTOMER
			ON B04_11_IT_FIN_GL.B04_BSEG_BUKRS = O18_01_TT_JOURNAL_WITH_MORE_THAN_ONE_CUSTOMER.B04_BSEG_BUKRS
		   AND B04_11_IT_FIN_GL.B04_BSEG_GJAHR = O18_01_TT_JOURNAL_WITH_MORE_THAN_ONE_CUSTOMER.B04_BSEG_GJAHR
		   AND B04_11_IT_FIN_GL.B04_BSEG_BELNR = O18_01_TT_JOURNAL_WITH_MORE_THAN_ONE_CUSTOMER.B04_BSEG_BELNR

/*--Step 3
--Create table to calculate the sale reduction, gross sales, net sales
*/
	EXEC SP_DROPTABLE 'O18_03_IT_JES_LINES_CUST_RED'
	SELECT 	
		BSEG_BUKRS,
		BSEG_GJAHR,
		BSEG_BELNR,
		BSEG_BUZEI,
		'Non relevant for Sale reduction analysis' AM_ACCOUNT_BUCKET
	INTO  O18_03_IT_JES_LINES_CUST_RED
	FROM O18_02_TT_JES_HEADER
	WHERE AM_ACCOUNT_BUCKET IS NULL

	--Sale reduction calculation
	INSERT INTO O18_03_IT_JES_LINES_CUST_RED
	SELECT 
		BSEG_BUKRS,
		BSEG_GJAHR,
		BSEG_BELNR,
		BSEG_BUZEI,
		'Sale reduction' AM_ACCOUNT_BUCKET
	FROM O18_02_TT_JES_HEADER	 
	WHERE AM_ACCOUNT_BUCKET = 'SALES_REDUCTION'

	--Gross sales
	INSERT INTO O18_03_IT_JES_LINES_CUST_RED
	SELECT 	
		BSEG_BUKRS,
		BSEG_GJAHR,
		BSEG_BELNR,
		BSEG_BUZEI,
		'Gross sales' AM_ACCOUNT_BUCKET
	FROM O18_02_TT_JES_HEADER
	WHERE AM_ACCOUNT_BUCKET = 'TOTAL GROSS SALES'

	--Net sales
	INSERT INTO O18_03_IT_JES_LINES_CUST_RED
	SELECT 	
		BSEG_BUKRS,
		BSEG_GJAHR,
		BSEG_BELNR,
		BSEG_BUZEI,
		'Net sales' AM_ACCOUNT_BUCKET
	FROM O18_02_TT_JES_HEADER
	WHERE AM_ACCOUNT_BUCKET IN ( 'SALES_REDUCTION', 'TOTAL GROSS SALES') 

	--Cost of sales
	INSERT INTO O18_03_IT_JES_LINES_CUST_RED
	SELECT 	
		BSEG_BUKRS,
		BSEG_GJAHR,
		BSEG_BELNR,
		BSEG_BUZEI,
		'Cost of sales' AM_ACCOUNT_BUCKET
	FROM O18_02_TT_JES_HEADER
	WHERE AM_ACCOUNT_BUCKET IN ('Cost of sales') 

	--Gross profit
	INSERT INTO O18_03_IT_JES_LINES_CUST_RED
	SELECT 	
		BSEG_BUKRS,
		BSEG_GJAHR,
		BSEG_BELNR,
		BSEG_BUZEI,
		'Gross profit' AM_ACCOUNT_BUCKET
	FROM O18_02_TT_JES_HEADER
	WHERE AM_ACCOUNT_BUCKET IN ( 'SALES_REDUCTION', 'TOTAL GROSS SALES', 'Cost of sales') 
/*Rename fields for Qlik*/
EXEC SP_RENAME_FIELD 'O08_T18_', 'O18_02_TT_JES_HEADER'
EXEC SP_RENAME_FIELD 'O08_T18B_', 'O18_03_IT_JES_LINES_CUST_RED'
EXEC SP_DROPTABLE 'O18_04_RT_JES_HEADER'
EXEC sp_rename 'O18_02_TT_JES_HEADER', 'O18_04_RT_JES_HEADER'
/* log cube creation*/
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','O18_04_RT_JES_HEADER',(SELECT COUNT(*) FROM O18_04_RT_JES_HEADER) 

/* log end of procedure*/
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(date,GETDATE()),CONVERT(time,GETDATE()),'Procedure finished',NULL,NULL

END

GO
