USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_B14_SS01_INVOICE_PAYMENT_CUBE]

AS

--DYNAMIC_SCRIPT_START
--Create 3 tables which contains information of customer invoice,invoice cancelation and payment
--Extract data from B14_06_IT_ARE 

--Add sale organization
--Limit down the number of company code
EXEC SP_REMOVE_TABLES 'B14_SS01_%'


EXEC SP_DROPTABLE B14_SS01_01A_TT_ADD_SALE_ORG

SELECT DISTINCT 
B14_BSAID_MANDT AS 'BSAID_MANDT',
B14_SCOPE_BUSINESS_DMN_L1 AS 'SCOPE_BUSINESS_DMN_L1',
B14_SCOPE_BUSINESS_DMN_L2 AS 'SCOPE_BUSINESS_DMN_L2',
B14_BSAID_GSBER AS 'BSAID_GSBER',
B14_TGSBT_GTEXT AS 'TGSBT_GTEXT',
B14_BSAID_BUKRS AS 'BSAID_BUKRS',
B14_T001_BUTXT AS 'T001_BUTXT',
B14_BSAID_GJAHR AS 'BSAID_GJAHR',
B14_BSAID_BUDAT AS 'BSAID_BUDAT',
B14_BSAID_MONAT AS 'BSAID_MONAT',
B14_ZF_GJAHR_BUDAT_FQ AS 'ZF_GJAHR_BUDAT_FQ',
B14_ZF_BSAID_MONAT_FQ AS 'ZF_BSAID_MONAT_FQ',
B14_ZF_GJAHR_MONAT AS 'ZF_GJAHR_MONAT',
B14_ZF_BSAID_BUDAT_CYM AS 'ZF_BSAID_BUDAT_CYM',
B14_ZF_BSAID_BUDAT_1ST_DAY_MNTH AS 'ZF_BSAID_BUDAT_1ST_DAY_MNTH',
B14_ZF_BSAID_BUDAT_POSTED_IN_PERIOD AS 'ZF_BSAID_BUDAT_POSTED_IN_PERIOD',
B14_BSAID_BLDAT AS 'BSAID_BLDAT',
B14_BSAID_BELNR AS 'BSAID_BELNR',
B14_BSAID_BUZEI AS 'BSAID_BUZEI',
B14_BSAID_KUNNR AS 'BSAID_KUNNR',
B14_KNA1_NAME1 AS 'KNA1_NAME1',
B14_KNA1_LAND1 AS 'KNA1_LAND1',
B14_KNA1_KTOKD AS 'KNA1_KTOKD',
B14_T077X_TXT30 AS 'T077X_TXT30',
B14_KNA1_VBUND AS 'KNA1_VBUND',
B14_T880_NAME1 AS 'T880_NAME1',
B14_INTERCO_TXT AS 'INTERCO_TXT',
B14_KNA1_KONZS AS 'KNA1_KONZS',
B14_ZF_KNKK_CTLPC_RISK_CAT AS 'ZF_KNKK_CTLPC_RISK_CAT',
B14_ZF_KNKK_CTLPC_RISK_CAT_TXT AS 'ZF_KNKK_CTLPC_RISK_CAT_TXT',
B14_KNA1_BRAN1 AS 'KNA1_BRAN1',
B14_KNA1_BRAN2 AS 'KNA1_BRAN2',
B14_KNA1_BRAN3 AS 'KNA1_BRAN3',
B14_KNA1_BRAN4 AS 'KNA1_BRAN4',
B14_KNA1_BRAN5 AS 'KNA1_BRAN5',
B14_ZF_STRATEGIC_ACC AS 'ZF_STRATEGIC_ACC',
B14_ZF_STRATEGIC_ACC_TEXT AS 'ZF_STRATEGIC_ACC_TEXT',
B14_BSAID_BLART AS 'BSAID_BLART',
B14_T003T_LTEXT AS 'T003T_LTEXT',
B14_BSAID_BSCHL AS 'BSAID_BSCHL',
B14_TBSLT_LTEXT AS 'TBSLT_LTEXT',
B14_ZF_BSAID_SHKZG_DESC AS 'ZF_BSAID_SHKZG_DESC',
B14_BSAID_XNEGP AS 'BSAID_XNEGP',
B14_BSAID_WAERS AS 'BSAID_WAERS',
B14_ZF_BSAID_WRBTR_DOC AS 'ZF_BSAID_WRBTR_DOC',
B14_T001_WAERS AS 'T001_WAERS',
B14_ZF_BSAID_DMBTR_COC AS 'ZF_BSAID_DMBTR_COC',
B14_GLOBALS_CURRENCY AS 'GLOBALS_CURRENCY',
B14_ZF_BSAID_DMBTR_CUC AS 'ZF_BSAID_DMBTR_CUC',
B14_BSAID_ZUONR AS 'BSAID_ZUONR',
B14_BSAID_SGTXT AS 'BSAID_SGTXT',
B14_BSAID_HKONT AS 'BSAID_HKONT',
B14_SKAT_TXT50 AS 'SKAT_TXT50',
B14_BSAID_ZTERM AS 'BSAID_ZTERM',
B14_T052U_TEXT1 AS 'T052U_TEXT1',
B14_BSAID_ZLSCH AS 'BSAID_ZLSCH',
B14_T042Z_TEXT1 AS 'T042Z_TEXT1',
B14_VBRK_ZTERM AS 'VBRK_ZTERM',
B14_T052U_SD_T052U_TEXT1 AS 'T052U_SD_T052U_TEXT1',
B14_KNB1_ZTERM AS 'KNB1_ZTERM',
B14_T052U_CU_T052U_TEXT1 AS 'T052U_CU_T052U_TEXT1',
B14_ZF_BSAID_VBRK_USED_PMNT_TERM AS 'ZF_BSAID_VBRK_USED_PMNT_TERM',
B14_BSAID_ZFBDT AS 'BSAID_ZFBDT',
B14_BSAID_ZBD1T AS 'BSAID_ZBD1T',
B14_BSAID_ZBD2T AS 'BSAID_ZBD2T',
B14_BSAID_ZBD3T AS 'BSAID_ZBD3T',
B14_ZF_BLDAT_ZFBDT_DUE_DATE AS 'ZF_BLDAT_ZFBDT_DUE_DATE',
B14_ZF_BSAID_CPUDT_MINUS_BLDAT AS 'ZF_BSAID_CPUDT_MINUS_BLDAT',
B14_ZF_BSAID_CPUDT_MINUS_BUDAT AS 'ZF_BSAID_CPUDT_MINUS_BUDAT',
B14_ZF_BSAID_CPUDT_MINUS_ZFBDT AS 'ZF_BSAID_CPUDT_MINUS_ZFBDT',
B14_ZF_BSAID_BLDAT_MINUS_BUDAT AS 'ZF_BSAID_BLDAT_MINUS_BUDAT',
B14_ZF_BSAID_BLDAT_MINUS_ZFBDT AS 'ZF_BSAID_BLDAT_MINUS_ZFBDT',
B14_ZF_BLDAT_ZFBDT_DOC_DATE_TO_CAL_DATE AS 'ZF_BLDAT_ZFBDT_DOC_DATE_TO_CAL_DATE',
B14_ZF_AUGBL_AUGDT_DOC_DATE_TO_CLEARING_DATE AS 'ZF_AUGBL_AUGDT_DOC_DATE_TO_CLEARING_DATE',
B14_ZF_BUDAT_ZFBDT_POST_DATE_TO_BASELINE_DATE AS 'ZF_BUDAT_ZFBDT_POST_DATE_TO_BASELINE_DATE',
B14_ZF_BLDAT_ZFBDT_POST_DATE_TO_CAL_DATE AS 'ZF_BLDAT_ZFBDT_POST_DATE_TO_CAL_DATE',
B14_ZF_AUGBL_AUGDT_POST_DATE_TO_CLEAR_DATE AS 'ZF_AUGBL_AUGDT_POST_DATE_TO_CLEAR_DATE',
B14_ZF_BLDAT_ZFBDT_BASELINE_DATE_TO_CAL_DATE AS 'ZF_BLDAT_ZFBDT_BASELINE_DATE_TO_CAL_DATE',
B14_ZF_AUGBL_AUGDT_CAL_DATE_TO_CLEAR_DATE AS 'ZF_AUGBL_AUGDT_CAL_DATE_TO_CLEAR_DATE',
B14_BSAID_ZBD1P AS 'BSAID_ZBD1P',
B14_BSAID_ZBD2P AS 'BSAID_ZBD2P',
B14_ZF_BSAID_WSKTO_ACTUAL_DISCOUNT AS 'ZF_BSAID_WSKTO_ACTUAL_DISCOUNT',
B14_BSAID_AUGBL AS 'BSAID_AUGBL',
B14_ZF_BSAID_BLART_CLEARING_DOC_TYPE AS 'ZF_BSAID_BLART_CLEARING_DOC_TYPE',
B14_CLR_T003T_LTEXT AS 'CLR_T003T_LTEXT',
B14_BSAID_AUGGJ AS 'BSAID_AUGGJ',
B14_BSAID_AUGDT AS 'BSAID_AUGDT',
B14_BSAID_PRCTR AS 'BSAID_PRCTR',
B14_BSAID_KOSTL AS 'BSAID_KOSTL',
B14_BSAID_AUGDT_CLR_CALENDAR_YM AS 'BSAID_AUGDT_CLR_CALENDAR_YM',
B14_ZF_BSAID_AUGDT_CY_1ST_OF_MNTH AS 'ZF_BSAID_AUGDT_CY_1ST_OF_MNTH',
B14_ZF_BSAID_AUGDT_CLR_IN_PER AS 'ZF_BSAID_AUGDT_CLR_IN_PER',
B14_BKPF_STBLG AS 'BKPF_STBLG',
B14_BKPF_BKTXT AS 'BKPF_BKTXT',
B14_BKPF_STJAH AS 'BKPF_STJAH',
B14_ZF_BKPF_STBLG_REVERSED AS 'ZF_BKPF_STBLG_REVERSED',
B14_BSAID_VBELN AS 'BSAID_VBELN',
B14_BSAID_XBLNR AS 'BSAID_XBLNR',
B14_BKPF_GLVOR AS 'BKPF_GLVOR',
B14_T022T_TXT AS 'T022T_TXT',
B14_BKPF_TCODE AS 'BKPF_TCODE',
B14_TSTCT_TTEXT AS 'TSTCT_TTEXT',
B14_BSAID_BSTAT AS 'BSAID_BSTAT',
B14_DD07T_DDTEXT AS 'DD07T_DDTEXT',
B14_ZF_ENTRY_TYPE AS 'ZF_ENTRY_TYPE',
B14_ZF_CLEARNING_ENTRY_TYPE AS 'ZF_CLEARNING_ENTRY_TYPE',
B14_BSAID_CPUDT AS 'BSAID_CPUDT',
B14_BKPF_CPUTM AS 'BKPF_CPUTM',
B14_BKPF_USNAM AS 'BKPF_USNAM',
B14_V_USERNAME_NAME_TEXT AS 'V_USERNAME_NAME_TEXT',
B14_USR02_USTYP AS 'USR02_USTYP',
B14_BKPF_HWAER AS 'BKPF_HWAER',
B14_BKPF_AWTYP AS 'BKPF_AWTYP',
B14_BKPF_AWKEY AS 'BKPF_AWKEY',
B14_BKPF_HWAE2 AS 'BKPF_HWAE2',
B14_BKPF_HWAE3 AS 'BKPF_HWAE3',
B14_T074T_LTEXT AS 'T074T_LTEXT',
B14_BSAID_DMBTR AS 'BSAID_DMBTR',
B14_BSAID_DMBE2 AS 'BSAID_DMBE2',
B14_BSAID_DMBE3 AS 'BSAID_DMBE3',
B14_BSAID_UMSKZ AS 'BSAID_UMSKZ',
B14_ZF_CUC AS 'ZF_CUC',
B14_ZF_AR_DOC_TYPE_BUCKET AS 'ZF_AR_DOC_TYPE_BUCKET',
		ZF_CREDIT_HKONT_TXT20_LIST AS ZF_CREDIT_HKONT_TXT20_LIST,
		ZF_DEBIT_HKONT_TXT20_LIST AS ZF_DEBIT_HKONT_TXT20_LIST,
		ZF_DEBIT_BSEG_KOSTL_AND_DESC AS ZF_DEBIT_BSEG_KOSTL_AND_DESC,
		ZF_CREDIT_BSEG_KOSTL_AND_DESC AS ZF_CREDIT_BSEG_KOSTL_AND_DESC,
		ZF_DEBIT_BSEG_PRCTR_AND_DESC AS ZF_DEBIT_BSEG_PRCTR_AND_DESC,
		ZF_CREDIT_BSEG_PRCTR_AND_DESC AS ZF_CREDIT_BSEG_PRCTR_AND_DESC,
		B04_BSEG_MATNR AS BSEG_MATNR,
		T134T_MTBEZ,
		MARA_MTART,
		MAKT_MAKTX
INTO B14_SS01_01A_TT_ADD_SALE_ORG
FROM B14_06_IT_ARE
JOIN B00_TVKO
ON TVKO_BUKRS=B14_BSAID_BUKRS
LEFT JOIN B04_07_IT_BSEG_BKPF_ACC_SCH
	ON BSEG_BUKRS=B14_BSAID_BUKRS AND
       BSEG_GJAHR=B14_BSAID_GJAHR AND
       BSEG_BELNR=B14_BSAID_BELNR
LEFT JOIN B04_11_IT_FIN_GL
	ON B14_BSAID_BELNR=B04_BSEG_BELNR
	AND B14_BSAID_GJAHR=B04_BSEG_GJAHR
	AND B14_BSAID_BUKRS=B04_BSEG_BUKRS
	AND B14_BSAID_BUZEI=B04_BSEG_BUZEI
LEFT JOIN B00_MAKT
	ON MAKT_MATNR=B04_BSEG_MATNR
LEFT JOIN A_MARA
	ON MARA_MATNR=B04_BSEG_MATNR
LEFT JOIN B00_T134T
	ON MARA_MTART=T134T_MTART


--Customer invoice
EXEC SP_DROPTABLE 'B14_SS01_01_IT_CUSTOMER_INVOICE'
SELECT *,
CONCAT(
			BSAID_BUKRS,'|',
			BSAID_GJAHR,'|',
			BSAID_BELNR,'|',
			BSAID_BUZEI) AS ZF_CUSTOMER_INVOICE_KEY
			INTO B14_SS01_01_IT_CUSTOMER_INVOICE
FROM B14_SS01_01A_TT_ADD_SALE_ORG
WHERE ZF_AR_DOC_TYPE_BUCKET='Customer invoice'

--Customer canceltion (credit note)
EXEC SP_DROPTABLE 'B14_SS01_02_IT_CREDIT_NOTE'
SELECT *,
CONCAT(
			BSAID_BUKRS,'|',
			BSAID_GJAHR,'|',
			BSAID_BELNR,'|',
			BSAID_BUZEI) AS ZF_CUSTOMER_INVOICE_CANCELLATION_KEY,
CONCAT(
			BSAID_BUKRS,'|',
			BSAID_AUGBL,'|',
			BSAID_AUGDT
		)		ZF_CLEARING_KEY,
			'' AS ZF_CREDIT_IN_INV
			INTO B14_SS01_02_IT_CREDIT_NOTE
FROM B14_SS01_01A_TT_ADD_SALE_ORG
WHERE ZF_AR_DOC_TYPE_BUCKET='Credit note'

--Customer payment
EXEC SP_DROPTABLE 'B14_SS01_03_IT_CUSTOMER_PAYMENT'
SELECT *,
CONCAT(
			BSAID_BUKRS,'|',
			BSAID_GJAHR,'|',
			BSAID_BELNR,'|',
			BSAID_BUZEI) AS  ZF_CUSTOMER_PAYMENT_KEY,
CONCAT(
			BSAID_BUKRS,'|',
			BSAID_AUGBL,'|',
			BSAID_AUGDT
		)		ZF_CLEARING_KEY,
'' AS ZF_PAY_IN_INV
			INTO B14_SS01_03_IT_CUSTOMER_PAYMENT
FROM B14_SS01_01A_TT_ADD_SALE_ORG
WHERE ZF_AR_DOC_TYPE_BUCKET='Customer payment'

--Payment cancelation Customer payment cancellation
EXEC SP_DROPTABLE 'B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL'
SELECT *,
CONCAT(
			BSAID_BUKRS,'|',
			BSAID_GJAHR,'|',
			BSAID_BELNR,'|',
			BSAID_BUZEI) AS ZF_CUSTOMER_PAYMENT_CANCELLATION,
CONCAT(
			BSAID_BUKRS,'|',
			BSAID_AUGBL,'|',
			BSAID_AUGDT
		)		ZF_CLEARING_KEY,
			'' AS ZF_CANCLE_PAYMENT_HAS_INV,
			'' AS ZF_CANCLE_PAYMENT_NO_INV,
			'' AS ZF_CANCLE_NO_PAY
INTO B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL
FROM B14_SS01_01A_TT_ADD_SALE_ORG
WHERE ZF_AR_DOC_TYPE_BUCKET='Customer payment cancellation'

--Khoi Update get the Others
EXEC SP_DROPTABLE 'B14_SS01_05_IT_OTHERS'
SELECT *,
CONCAT(
			BSAID_BUKRS,'|',
			BSAID_GJAHR,'|',
			BSAID_BELNR,'|',
			BSAID_BUZEI) AS ZF_OTHERS,
CONCAT(
			BSAID_BUKRS,'|',
			BSAID_AUGBL,'|',
			BSAID_AUGDT
		)		ZF_CLEARING_KEY,
'' AS ZF_OTHER_IN_INV
INTO B14_SS01_05_IT_OTHERS
FROM B14_SS01_01A_TT_ADD_SALE_ORG
WHERE ZF_AR_DOC_TYPE_BUCKET='Others'


--Update the flag
UPDATE B14_SS01_02_IT_CREDIT_NOTE
SET ZF_CREDIT_IN_INV='X' WHERE EXISTS
(
	SELECT TOP 1 1 
	FROM B14_SS01_01_IT_CUSTOMER_INVOICE AS A
	WHERE B14_SS01_02_IT_CREDIT_NOTE.BSAID_AUGBL=A.BSAID_AUGBL AND
			B14_SS01_02_IT_CREDIT_NOTE.BSAID_AUGDT=A.BSAID_AUGDT AND
			B14_SS01_02_IT_CREDIT_NOTE.BSAID_BUKRS=A.BSAID_BUKRS AND
			LEN(B14_SS01_02_IT_CREDIT_NOTE.BSAID_AUGBL)>0 AND LEN(A.BSAID_AUGBL)>0
)
	
UPDATE B14_SS01_03_IT_CUSTOMER_PAYMENT
SET ZF_PAY_IN_INV='X' WHERE EXISTS
(
	SELECT TOP 1 1 
	FROM B14_SS01_01_IT_CUSTOMER_INVOICE AS A
	WHERE B14_SS01_03_IT_CUSTOMER_PAYMENT.BSAID_AUGBL=A.BSAID_AUGBL AND
			B14_SS01_03_IT_CUSTOMER_PAYMENT.BSAID_AUGDT=A.BSAID_AUGDT AND
			B14_SS01_03_IT_CUSTOMER_PAYMENT.BSAID_BUKRS=A.BSAID_BUKRS AND
			LEN(B14_SS01_03_IT_CUSTOMER_PAYMENT.BSAID_AUGBL)>0 AND LEN(A.BSAID_AUGBL)>0
)

UPDATE B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL
SET ZF_CANCLE_PAYMENT_HAS_INV='X' WHERE EXISTS
(
	SELECT TOP 1 1 
	FROM B14_SS01_01_IT_CUSTOMER_INVOICE AS A
	WHERE B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL.BSAID_AUGBL=A.BSAID_AUGBL AND
			B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL.BSAID_AUGDT=A.BSAID_AUGDT AND
			B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL.BSAID_BUKRS=A.BSAID_BUKRS AND
			LEN(B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL.BSAID_AUGBL)>0 AND LEN(A.BSAID_AUGBL)>0
)

UPDATE B14_SS01_05_IT_OTHERS
SET ZF_OTHER_IN_INV='X' WHERE EXISTS
(
	SELECT TOP 1 1 
	FROM B14_SS01_01_IT_CUSTOMER_INVOICE AS A
	WHERE B14_SS01_05_IT_OTHERS.BSAID_AUGBL=A.BSAID_AUGBL AND
			B14_SS01_05_IT_OTHERS.BSAID_AUGDT=A.BSAID_AUGDT AND
			B14_SS01_05_IT_OTHERS.BSAID_BUKRS=A.BSAID_BUKRS AND
			LEN(B14_SS01_05_IT_OTHERS.BSAID_AUGBL)>0 AND LEN(A.BSAID_AUGBL)>0
)


EXEC SP_RENAME_FIELD 'B14_01_',B14_SS01_01_IT_CUSTOMER_INVOICE
EXEC SP_RENAME_FIELD 'B14_02_',B14_SS01_02_IT_CREDIT_NOTE
EXEC SP_RENAME_FIELD 'B14_03_',B14_SS01_03_IT_CUSTOMER_PAYMENT
EXEC SP_RENAME_FIELD 'B14_04_',B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL
EXEC SP_RENAME_FIELD 'B14_05_',B14_SS01_05_IT_OTHERS

--EXEC SP_REMOVE_TABLES '%_TT_%'

-- Step 2 Do summary on the cube, to prevent duplications

EXEC SP_DROPTABLE B14_SS01_06_IT_CUSTOMER_INVOICE_SUMMARY

	SELECT
	B14_01_ZF_CUSTOMER_INVOICE_KEY,
	B14_01_BKPF_CPUTM,
	B14_01_BSAID_CPUDT,
	B14_01_BKPF_USNAM,
	B14_01_V_USERNAME_NAME_TEXT,
	 B14_01_BSAID_KUNNR,
	B14_01_BSAID_BUKRS,
	B14_01_BSAID_BLART,
	B14_01_T003T_LTEXT,
	 B14_01_T001_WAERS,
	 B14_01_BKPF_AWKEY,
	 B14_01_BSAID_AUGBL,
	 B14_01_BSAID_AUGDT,
	 SUM(B14_01_ZF_BSAID_DMBTR_COC) AS B14_01_ZF_BSAID_DMBTR_COC,
	 SUM(B14_01_ZF_BSAID_DMBTR_CUC)AS B14_01_ZF_BSAID_DMBTR_CUC
	 INTO B14_SS01_06_IT_CUSTOMER_INVOICE_SUMMARY
	 FROM B14_SS01_01_IT_CUSTOMER_INVOICE
	 GROUP BY 
     B14_01_ZF_CUSTOMER_INVOICE_KEY,
	 B14_01_BSAID_BLDAT,
	 B14_01_BKPF_USNAM,
	 B14_01_V_USERNAME_NAME_TEXT,
	 B14_01_BSAID_KUNNR,
	 B14_01_BSAID_BUKRS,
	 B14_01_BSAID_BLART,
 	 B14_01_T003T_LTEXT,
	 B14_01_T001_WAERS,
	 B14_01_BKPF_AWKEY,
	 B14_01_BSAID_AUGBL,
	 B14_01_BSAID_AUGDT,
	 B14_01_BKPF_CPUTM,
	 B14_01_BSAID_CPUDT



--Step 7 Summary on credit note,only get the one that are not link to  invoice

EXEC SP_DROPTABLE B14_SS01_07_IT_CUSTOMER_CREDIT_NOTE

	SELECT 
	 B14_02_BKPF_USNAM,
	 B14_02_V_USERNAME_NAME_TEXT,
	 B14_02_BSAID_BUKRS,
	 B14_02_BSAID_BLART,
	 B14_02_T003T_LTEXT,
	 B14_02_T001_WAERS,
	 B14_02_BSAID_AUGBL,
	 B14_02_BSAID_AUGDT,
	 SUM(B14_02_ZF_BSAID_DMBTR_COC) AS B14_02_ZF_BSAID_DMBTR_COC,
	 SUM(B14_02_ZF_BSAID_DMBTR_CUC)AS B14_02_ZF_BSAID_DMBTR_CUC
	 INTO B14_SS01_07_IT_CUSTOMER_CREDIT_NOTE
	 FROM B14_SS01_02_IT_CREDIT_NOTE
	 GROUP BY 
	B14_02_BKPF_USNAM,
	B14_02_V_USERNAME_NAME_TEXT,
	B14_02_BSAID_BUKRS,
	B14_02_BSAID_BLART,
	B14_02_T003T_LTEXT,
	 B14_02_T001_WAERS,
	 B14_02_BSAID_AUGBL,
	 B14_02_BSAID_AUGDT

--Step 5 Summary the payment cube, to prevent duplication, only get the one that are not link to  invoice
EXEC SP_DROPTABLE B14_SS01_08_IT_CUSTOMER_PAYMENT_SUMMARY

	SELECT 	
		B14_03_BKPF_USNAM,
		B14_03_V_USERNAME_NAME_TEXT,
		B14_03_BSAID_BUKRS,
		B14_03_BSAID_BLART,
		B14_03_T003T_LTEXT,
		B14_03_T001_WAERS,
		B14_03_BSAID_AUGBL,
		B14_03_BSAID_AUGDT,	 
		SUM(B14_03_ZF_BSAID_DMBTR_COC) AS B14_03_ZF_BSAID_DMBTR_COC,
	    SUM(B14_03_ZF_BSAID_DMBTR_CUC)AS B14_03_ZF_BSAID_DMBTR_CUC
	INTO B14_SS01_08_IT_CUSTOMER_PAYMENT_SUMMARY
	FROM B14_SS01_03_IT_CUSTOMER_PAYMENT
	GROUP BY 
		B14_03_BKPF_USNAM,
		B14_03_V_USERNAME_NAME_TEXT,
		B14_03_BSAID_BUKRS,
		B14_03_BSAID_BLART,
		B14_03_T003T_LTEXT,
		B14_03_T001_WAERS,
		B14_03_BSAID_AUGBL,
		B14_03_BSAID_AUGDT

--Step 6 Summary the payment cancelation cube, to prevent duplication,only get the one that are not link to  invoice

EXEC SP_DROPTABLE B14_SS01_09_IT_CUSTOMER_PAYMENT_CANCEL_SUMMARY

	SELECT 	
		B14_04_BKPF_USNAM,
		B14_04_V_USERNAME_NAME_TEXT,
		B14_04_BSAID_BUKRS,
		B14_04_BSAID_BLART,
		B14_04_T003T_LTEXT,
		 B14_04_T001_WAERS,
		 B14_04_BSAID_AUGBL,
		 B14_04_BSAID_AUGDT,	 
		 SUM(B14_04_ZF_BSAID_DMBTR_COC) AS B14_04_ZF_BSAID_DMBTR_COC,
	     SUM(B14_04_ZF_BSAID_DMBTR_CUC)AS B14_04_ZF_BSAID_DMBTR_CUC
	 INTO B14_SS01_09_IT_CUSTOMER_PAYMENT_CANCEL_SUMMARY
	 FROM B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL
	 GROUP BY 
		B14_04_BKPF_USNAM,
		B14_04_V_USERNAME_NAME_TEXT,
		B14_04_BSAID_BUKRS,
		B14_04_BSAID_BLART,
		B14_04_T003T_LTEXT,
		B14_04_T001_WAERS,
		B14_04_BSAID_AUGBL,
		B14_04_BSAID_AUGDT
	 
--Step 6 Summary the OTHER  cube, to prevent duplication,only get the one that are not link to  invoice

	EXEC SP_DROPTABLE B14_SS01_10_IT_CUSTOMER_OTHERS_SUMMARY
	SELECT  
		B14_05_BKPF_USNAM,
		B14_05_V_USERNAME_NAME_TEXT,
		B14_05_BSAID_BUKRS,
		B14_05_BSAID_BLART,
		B14_05_T003T_LTEXT,
		 B14_05_T001_WAERS,
		 B14_05_BSAID_AUGBL,
		 B14_05_BSAID_AUGDT, 
		 SUM(B14_05_ZF_BSAID_DMBTR_COC) AS B14_05_ZF_BSAID_DMBTR_COC,
	     SUM(B14_05_ZF_BSAID_DMBTR_CUC)AS B14_05_ZF_BSAID_DMBTR_CUC
		 INTO B14_SS01_10_IT_CUSTOMER_OTHERS_SUMMARY
		 FROM B14_SS01_05_IT_OTHERS AS A
		 GROUP BY 
		B14_05_BKPF_USNAM,
		B14_05_V_USERNAME_NAME_TEXT,
		B14_05_BSAID_BUKRS,
		B14_05_BSAID_BLART,
		B14_05_T003T_LTEXT,
		B14_05_T001_WAERS,
		B14_05_BSAID_AUGBL,
		B14_05_BSAID_AUGDT


GO
