USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC [dbo].[O08_T18_SALES_RED_PER_CUSTOMER_CHINA](@DBNAME NVARCHAR(MAX))
AS

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_O08_T18_SALES_RED_PER_CUSTOMER_CHINA'


/* Running Subscript specifically for each ENTITY*/



GO
