USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROC [dbo].[DSP_DATA_PROCESSING]
AS 
BEGIN
	
	DECLARE @TABNAME NVARCHAR(MAX) = ''
	DECLARE TABLE_CUR CURSOR LOCAL FOR 
			SELECT DISTINCT A.TABLE_NAME
			FROM INFORMATION_SCHEMA.TABLES AS A
			WHERE A.TABLE_NAME LIKE 'PJR5%'

	OPEN TABLE_CUR
	FETCH NEXT FROM TABLE_CUR INTO @TABNAME

	WHILE @@FETCH_STATUS = 0
	BEGIN
		RAISERROR(@TABNAME, 0, 1) WITH NOWAIT;
		FETCH NEXT FROM TABLE_CUR INTO @TABNAME
	END
	CLOSE TABLE_CUR
	DEALLOCATE TABLE_CUR

END
GO
