USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[script_DC17_DELIVERY_CUBE]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START
/* Initiate the log */ 
----Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END
 
--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL
 
/* Initialize parameters from globals table */
 
     DECLARE  
                      @CURRENCY NVARCHAR(MAX)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
                     ,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
                     ,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
                     ,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
                     ,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
                     ,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
                     ,@LANGUAGE1 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
                     ,@LANGUAGE2 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
                     ,@YEAR NVARCHAR(MAX)                     = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
                     ,@ID NVARCHAR(MAX)                       = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
                     ,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
					 ,@ZV_SAME_QUARTER_BY_BLDAT NVARCHAR(MAX) = ISNULL((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'ZV_SAME_QUARTER_BY_BLDAT'), '')

--Step 1/ Compare values (USD) between table B34_01_IT_DELIVERY_DOCS_NEW (use TCURR and TCURF) and table B34_01_IT_DELIVERY_DOCS_ (use AM_EXCHNG)
EXEC SP_DROPTABLE 	'DC17_01_IT_DELIVERY_DOCS' 
SELECT 
	A.B34_LIKP_VBELN,
	A.B34_LIPS_POSNR,
	A.B34_LIKP_WAERK,
	MAX(A.B34_LIKP_ERDAT) AS B34_LIKP_ERDAT,
	SUM(B.B34_ZF_LIPS_NETWR) AS B34_ZF_LIPS_NETWR,
	SUM(B.B34_ZF_LIPS_NETWR_CUC) AS B34_ZF_LIPS_NETWR_CUC_OLD,
	SUM(A.B34_ZF_LIPS_NETWR_CUC) AS B34_ZF_LIPS_NETWR_CUC_NEW,
	MAX(ISNULL(EXCHNG_RATIO,1)) AS EXCH_RATE_CUC_OLD,
	MAX(COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1)) AS EXCH_RATE_CUC_NEW
INTO DC17_01_IT_DELIVERY_DOCS
FROM B34_01_IT_DELIVERY_DOCS_NEW A

INNER JOIN B34_01_IT_DELIVERY_DOCS B
	ON A.B34_LIKP_VBELN = B.B34_LIKP_VBELN
	AND A.B34_LIPS_POSNR = B.B34_LIPS_POSNR

--Get currency
	LEFT JOIN B00_TCURX B00_TCURX_DOC
	ON B00_TCURX_DOC.TCURX_CURRKEY = A.B34_LIKP_WAERK COLLATE SQL_Latin1_General_CP1_CS_AS
	LEFT JOIN B00_IT_TCURF TCURF_CUC
	ON A.B34_LIKP_WAERK = TCURF_CUC.TCURF_FCURR
	AND TCURF_CUC.TCURF_TCURR  = 'USD'  
	AND TCURF_CUC.TCURF_GDATU = (
		SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
		FROM B00_IT_TCURF
		WHERE A.B34_LIKP_WAERK = B00_IT_TCURF.TCURF_FCURR AND 
				B00_IT_TCURF.TCURF_TCURR  = 'USD'  AND
				B00_IT_TCURF.TCURF_GDATU <= A.B34_LIKP_ERDAT
		ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
		)
	-- Add exchange rate from company currency to USD
	LEFT JOIN B00_IT_TCURR TCURR_CUC
		ON A.B34_LIKP_WAERK = TCURR_CUC.TCURR_FCURR
		AND TCURR_CUC.TCURR_TCURR  = 'USD'
		AND TCURR_CUC.TCURR_GDATU = (
			SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
			FROM B00_IT_TCURR
			WHERE A.B34_LIKP_WAERK = B00_IT_TCURR.TCURR_FCURR AND 
					B00_IT_TCURR.TCURR_TCURR  = 'USD'  AND
					B00_IT_TCURR.TCURR_GDATU <= A.B34_LIKP_ERDAT
			ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
			) 
LEFT JOIN AM_EXCHNG
ON A.B34_LIKP_WAERK = EXCHNG_FROM AND EXCHNG_TO = 'USD'
GROUP BY 
	A.B34_LIKP_VBELN,
	A.B34_LIPS_POSNR,
	A.B34_LIKP_WAERK



EXEC SP_UNNAME_FIELD 'B34_',DC17_01_IT_DELIVERY_DOCS
EXEC SP_RENAME_FIELD 'DC17_01_',DC17_01_IT_DELIVERY_DOCS
GO
