USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC [dbo].[B03_FIN_TRIAL_BALANCE](@DBNAME NVARCHAR(MAX))
AS

EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B03%'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B03_FIN_TRIAL_BALANCE'
EXEC SP_EXEC_DYNAMIC @DBNAME,'script_B03_S001_FIN_TRIAL_BALANCE_SUMMARY'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B03_SS01_TRIAL_BALANCE_RATIO'

/* Running Subscript specifically for each ENTITY*/

IF @DBNAME LIKE '%TURKEY%' EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B03_SS04_TURKEY'

--IF @DBNAME LIKE '%SCIS%' EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B03_FIN_TRIAL_BALANCE_RUSSIA'

GO
