USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE       PROCEDURE [dbo].[A_005A_CREATE_AM_SCOPE]
AS
BEGIN

		/*
			Step 1: Collect all active company code from BKPF and EKKO tables
		*/
		EXEC SP_REMOVE_TABLES 'A05_01_TT_ACTV_COMPANY'
		SELECT DISTINCT BKPF_MANDT, BKPF_BUKRS, T001_BUTXT
		INTO A05_01_TT_ACTV_COMPANY
	    FROM
		(
			SELECT DISTINCT BKPF_MANDT, BKPF_BUKRS FROM A_BKPF
			UNION 
			SELECT DISTINCT EKKO_MANDT, EKKO_BUKRS FROM A_EKKO
		)  A
		LEFT JOIN A_T001 AS B
		ON B.T001_MANDT = A.BKPF_MANDT AND
			B.T001_BUKRS = A.BKPF_BUKRS


		/*
			Step 2: Create AM_SCOPE tables.
		*/
		IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'AM_SCOPE')
		BEGIN
			PRINT 'Creating AM_SCOPE table.'
			CREATE TABLE [dbo].[AM_SCOPE](
				[SCOPE_MANDANT] [varchar](3) NOT NULL,
				[SCOPE_CMPNY_CODE] [varchar](20) NOT NULL,
				[SCOPE_BUSINESS_DMN_L1] [varchar](100)  NULL,
				[SCOPE_BUSINESS_DMN_L2] [nvarchar](100) NULL,
				[SCOPE_SYSTEM] [varchar](20) NULL
			)
		END

		/*
			Step 3: Insert active company code to AM_SCOPE table.
		*/

		INSERT INTO [dbo].[AM_SCOPE] ([SCOPE_MANDANT],[SCOPE_CMPNY_CODE],[SCOPE_BUSINESS_DMN_L1],[SCOPE_BUSINESS_DMN_L2],[SCOPE_SYSTEM])
		SELECT BKPF_MANDT, BKPF_BUKRS, 'replace',T001_BUTXT, 'replace'
		FROM A05_01_TT_ACTV_COMPANY
		WHERE NOT EXISTS (SELECT TOP 1 1 FROM AM_SCOPE WHERE AM_SCOPE.SCOPE_MANDANT = A05_01_TT_ACTV_COMPANY.BKPF_MANDT AND AM_SCOPE.SCOPE_CMPNY_CODE = A05_01_TT_ACTV_COMPANY.BKPF_BUKRS)
				  
		EXEC SP_REMOVE_TABLES 'A05_01_TT_ACTV_COMPANY'
	
	
END
GO
