USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC [dbo].[DV14_DIVAQLCOPA_VERSUS_SAPSE16N](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_DV14_SS01_DIVAQLCOPA_VERSUS_SAPSE16N'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_DV14_DIVAQLCOPA_VERSUS_SAPSE16N'
GO
