USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PM_OTC_PROCESS_MINING] 
 @DBNAME as NVARCHAR(MAX)
AS
--Need to run PTP first,then run OTC
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B00_SS01_OTC_INFO_TABLE'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B21_SS01_OTC_PROCESS_MINING_CHANGE'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B33_SALE_ORDER_CUBE'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B34_DELIVERY_CUBE'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B36_INVOICE_DOCS'
	EXEC SP_EXEC_DYNAMIC @DBNAME,'script_B14_SS01_INVOICE_PAYMENT_CUBE'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B37_OTC_GLOBAL_TABLE'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_PM02_OTC_PROCESS_MINING'


GO
