USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Khoi
-- Create date: <Create Date,,>
-- Description: Create Invoice cube base on BSEG-BKPF, instead of using BSAK-BSIK
-- Get the invoice details from  BSEG base AP mapping file
-- 23-03-2022	 Thuan	 Remove MANDT field in join
-- =============================================
CREATE     PROCEDURE [dbo].[script_B25A_BSEG_BKPF_INVOICES]
	-- Add the parameters for the stored procedure here
AS
--DYNAMIC_SCRIPT_START
BEGIN

--Step 1. Get the invoice values from BSEG, by joining back to AP mapping
--Join base on main keys
EXEC  SP_DROPTABLE B25A_01_TT_GET_BSEG_INV

SELECT DISTINCT
B04_11_IT_FIN_GL.*
INTO B25A_01_TT_GET_BSEG_INV
FROM B04_11_IT_FIN_GL
JOIN B07_03_IT_FIN_AP_INV_PAY_FLAGS
ON B07B_BSAIK_BELNR=B04_BSEG_BELNR
AND B07B_BSAIK_BUKRS=B04_BSEG_BUKRS
AND B07B_BSAIK_GJAHR=B04_BSEG_GJAHR
WHERE B07B_ZF_SUPP_INV='X'

--Step 1.1. Adding information for the cube
EXEC SP_DROPTABLE B25A_02_IT_GET_BSEG_INV
SELECT B25A_01_TT_GET_BSEG_INV.*,
A_V_USERNAME.V_USERNAME_NAME_TEXT AS BSEG_V_USERNAME_NAME_TEXT,LFA1_ERNAM AS BSEG_LFA1_ERNAM,
B00_T003T.T003T_LTEXT AS BSEG_T003T_LTEXT,
LFA1_NAME1 AS BSEG_LFA1_NAME1,
A_T001.T001_BUTXT AS BSEG_T001_BUTXT,A_T001.T001_WAERS,
SKAT_TXT20 AS BSEG_SKAT_TXT20,
TBSLT_LTEXT AS BSEG_TBSTL_LTEXT,
MARA_MTART AS BSEG_MARA_MTART,
T134T_MTBEZ AS BSEG_T134T_MTBEZ,
MAKT_MAKTX AS BSEG_MAKT_MAKTX,
ZF_DEBIT_BSEG_KOSTL_AND_DESC AS BSEG_ZF_DEBIT_BSEG_KOSTL_AND_DESC,
ZF_CREDIT_BSEG_KOSTL_AND_DESC AS BSEG_ZF_CREDIT_BSEG_KOSTL_AND_DESC,
ZF_DEBIT_BSEG_PRCTR_AND_DESC AS BSEG_ZF_DEBIT_BSEG_PRCTR_AND_DESC,
ZF_CREDIT_BSEG_PRCTR_AND_DESC AS BSEG_ZF_CREDIT_BSEG_PRCTR_AND_DESC,
ZF_DEBIT_HKONT_TXT20_LIST AS BSEG_ZF_DEBIT_HKONT_TXT20_LIST,
ZF_CREDIT_HKONT_TXT20_LIST AS BSEG_ZF_CREDIT_HKONT_TXT20_LIST, 
                    CASE
                        WHEN B04_BSEG_KOART = 'A' THEN 'Assets'
                        WHEN B04_BSEG_KOART = 'D' THEN 'Customers'
                        WHEN B04_BSEG_KOART = 'K' THEN 'Vendors'
                        WHEN B04_BSEG_KOART = 'M' THEN 'Material'
                        WHEN B04_BSEG_KOART = 'S' THEN 'G/L accounts'
                        ELSE ''
                    END                                                                  AS ZF_BSEG_KOART_DESC,
--TSTCT_TTEXT AS BSEG_TSTCT_TTEXT,
CONCAT( DBO.TRIM(B04_BSEG_BUKRS),'-',
		DBO.TRIM(B04_BSEG_BELNR),'-',
		DBO.TRIM(B04_BSEG_GJAHR))  AS ZF_BSEG_DOCUMENT_KEY
INTO B25A_02_IT_GET_BSEG_INV
FROM B25A_01_TT_GET_BSEG_INV
LEFT JOIN A_T001
	ON T001_BUKRS=B04_BSEG_BUKRS
LEFT JOIN A_V_USERNAME
		ON B04_BKPF_USNAM=V_USERNAME_BNAME 
LEFT JOIN A_LFA1
		ON LFA1_LIFNR=B04_BSEG_LIFNR
LEFT JOIN B00_T003T
		ON T003T_BLART=B04_BKPF_BLART
LEFT JOIN B00_SKAT                                             
       ON     B00_SKAT.SKAT_KTOPL = A_T001.T001_KTOPL AND               
              B00_SKAT.SKAT_SAKNR = B04_BSEG_HKONT
-- Get posting key description
		LEFT JOIN B00_TBSLT
		ON B00_TBSLT.TBSLT_BSCHL = B04_BSEG_BSCHL AND
		   B00_TBSLT.TBSLT_UMSKZ = B04_BSEG_UMSKZ
LEFT JOIN B00_MAKT
		ON B04_BSEG_MATNR=MAKT_MATNR
LEFT JOIN A_MARA
	ON MARA_MATNR=B04_BSEG_MATNR
LEFT JOIN B00_T134T
	ON MARA_MTART=T134T_MTART
LEFT JOIN B04_07_IT_BSEG_BKPF_ACC_SCH
	ON B04_BSEG_BUKRS=BSEG_BUKRS
	AND B04_BSEG_GJAHR=BSEG_GJAHR
	AND B04_BSEG_BELNR=BSEG_BELNR
WHERE B04_BSEG_KOART='K' OR B04_BSEG_KOART='S'

--Step 2 The line with K (Which will be in BSAK-BSIK )will don't have EBELN,EBELP,
--The line with S has,
--Come bine line K to one line get the EBELN and EBELP
EXEC SP_DROPTABLE B25A_03_TT_BKPF_BSEG_INVOICE_ADD_PO_NUM
SELECT DISTINCT 
A.B04_BSEG_BUKRS,
A.B04_BSEG_GJAHR,
A.B04_BSEG_BELNR ,
A.B04_BSEG_BUZEI,
A.B04_BKPF_USNAM ,A.T001_WAERS,
A.BSEG_V_USERNAME_NAME_TEXT,
A.B04_BKPF_CPUDT ,
A.B04_BKPF_CPUTM ,
A.B04_BSEG_LIFNR ,
A.BSEG_LFA1_ERNAM ,
A.BSEG_T003T_LTEXT ,
A.B04_ZF_BSEG_DMBTR_S,
A.B04_ZF_BSEG_DMBTR_S_CUC,
A.B04_ZF_BSEG_DMBE2_S,
A.B04_ZF_BSEG_DMBE3_S,
B04_ZF_BKPF_AWKEY_DOC_NUM,
B04_ZF_BKPF_AWKEY_YEAR,
B.B04_BSEG_EBELN,
B.B04_BSEG_EBELP ,
B04_BSEG_AUGBL,
B04_BSEG_AUGDT
INTO B25A_03_TT_BKPF_BSEG_INVOICE_ADD_PO_NUM
FROM
(SELECT DISTINCT
	B04_BSEG_BUKRS,
	B04_BSEG_GJAHR,
	B04_BSEG_BELNR ,
	B04_BSEG_BUZEI,
	B04_BKPF_USNAM ,
	B04_ZF_BKPF_AWKEY_DOC_NUM,
	B04_ZF_BKPF_AWKEY_YEAR,
	BSEG_V_USERNAME_NAME_TEXT,
	B04_BKPF_CPUDT ,
	B04_BKPF_CPUTM ,
	B04_BSEG_LIFNR ,
	BSEG_LFA1_ERNAM ,
	BSEG_T003T_LTEXT ,T001_WAERS,
	SUM(B04_ZF_BSEG_DMBTR_S) AS B04_ZF_BSEG_DMBTR_S,
	SUM(B04_ZF_BSEG_DMBTR_S_CUC) AS B04_ZF_BSEG_DMBTR_S_CUC,
	SUM(B04_ZF_BSEG_DMBE2_S) AS B04_ZF_BSEG_DMBE2_S,
	SUM(B04_ZF_BSEG_DMBE3_S) AS B04_ZF_BSEG_DMBE3_S,
	B04_BSEG_AUGBL,
	B04_BSEG_AUGDT
FROM B25A_02_IT_GET_BSEG_INV WHERE B04_BSEG_KOART='K'
GROUP BY
	B04_BSEG_BUKRS,
	B04_BSEG_GJAHR,
	B04_BSEG_BELNR ,
	B04_BSEG_BUZEI,
	B04_BKPF_USNAM ,
	B04_ZF_BKPF_AWKEY_DOC_NUM,
	B04_ZF_BKPF_AWKEY_YEAR,
	BSEG_V_USERNAME_NAME_TEXT,
	B04_BKPF_CPUDT ,
	B04_BKPF_CPUTM ,
	B04_BSEG_LIFNR ,
	BSEG_LFA1_ERNAM ,
	BSEG_T003T_LTEXT ,
	B04_BSEG_AUGBL,
	B04_BSEG_AUGDT,T001_WAERS
) AS A
LEFT JOIN
(SELECT DISTINCT B04_BSEG_BELNR,B04_BSEG_BUKRS,B04_BSEG_GJAHR,B04_BSEG_EBELN,B04_BSEG_EBELP  
FROM B25A_02_IT_GET_BSEG_INV WHERE B04_BSEG_KOART='S') AS B
ON A.B04_BSEG_BELNR=B.B04_BSEG_BELNR AND 
A.B04_BSEG_BUKRS=B.B04_BSEG_BUKRS AND 
A.B04_BSEG_GJAHR=B.B04_BSEG_GJAHR

END
 
GO
