USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[remove_dup]
--ALTER PROCEDURE [dbo].[SP_CHECK_A_AM_TABLE] 

AS
BEGIN

EXEC SP_DROPTABLE '#TABLE_NAME'
EXEC SP_DROPTABLE '#LIST_OF_TABLE_COLUMN'
CREATE TABLE #LIST_OF_TABLE_COLUMN (TABLE_NAME VARCHAR(255),TABLE_FIELD VARCHAR(255), DATA_TYPE VARCHAR(255),CHARACTER_MAXIMUM_LENGTH INT)

SELECT TABLE_NAME INTO #TABLE_NAME FROM INFORMATION_SCHEMA.TABLES 
		WHERE  LEFT(TABLE_NAME,5) <> 'A_SAP' AND LEFT(TABLE_NAME,6) <> 'A_QLIK' 
			  AND LEFT(TABLE_NAME,2) = 'A_'


			
DECLARE  @TABLE_NAME_VALUE VARCHAR(50);
DECLARE LIST_CURSOR CURSOR FOR

	SELECT dbo.SPLIT_STRING_POSITION_NTH_VALUE(TABLE_NAME,'_',2)  
	FROM #TABLE_NAME 
	


OPEN LIST_CURSOR

FETCH NEXT FROM LIST_CURSOR
INTO  @TABLE_NAME_VALUE
WHILE @@FETCH_STATUS = 0
BEGIN

--REPLACE(COLUMNNAME, '\T', '')

	
	PRINT @TABLE_NAME_VALUE
	
	exec [dbo].[A_002B_REMOVE_DUPLICATES] @TABLE_NAME_VALUE
	
	FETCH NEXT FROM LIST_CURSOR
	INTO @TABLE_NAME_VALUE -- SIMILAR TO COUNT = COUNT + 1

END
CLOSE LIST_CURSOR
DEALLOCATE LIST_CURSOR


End



GO
