USE [DIVA_MASTER_SCRIPT]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE    PROC [dbo].[B12_PTP_PO_APA_MAPPING](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B12%'

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B12_PTP_PO_APA_MAPPING'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B12_SS01_PAYMENT_INFO'
GO
