USE [DIVA_ASAP_TEST_DATA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<vinh.le@aufinia.com>
-- Create date: <March 5, 2021>
-- Description:	Check create/insert AM tables relate to GL accounts
-- =============================================
CREATE      PROCEDURE [dbo].[A_19_IMPORT_AM_MAPPING_TABLE]
AS


-- Step 1 / Spend category mapping
-- Step 1.1 Back up AM mapping.
SELECT *
INTO AM_SPEND_CATEGORY_BK
FROM AM_SPEND_CATEGORY


-- Step 1.2 Import AM_SPEND_CATEGORY MAPPING

DROP TABLE AM_SPEND_CATEGORY

UPDATE AM_SPEND_CATEGORY
SET SPCAT_SPEND_TYPE = 'Non-Product'


SELECT *
FROM AM_SPEND_CATEGORY
WHERE SPCAT_SPEND_CAT_LEVEL_3 = ''
OR SPCAT_SPEND_CAT_LEVEL_3 IS NULL


-- Step 2 / AM_TANGO account
-- 2.1 Backup AM_TANGO table 

SELECT *
INTO AM_TANGO_BK
FROM AM_TANGO

-- 2.2 Import AM_TANGO table.

DROP TABLE AM_TANGO


-- Step 3. AM_IRGR_GINI_ARDR_MAPPING Done already.


-- Step 4. AM_IRGR_MATERIAL_GROUP_HIERARCH
-- 4.1 Back-up AM_IRGR_MATERIAL_GROUP_HIERARCH

SELECT *
INTO AM_IRGR_MATERIAL_GROUP_HIERARCHY_BK
FROM AM_IRGR_MATERIAL_GROUP_HIERARCHY

-- 4.2 Import AM_IRGR_MATERIAL_GROUP_HIERARCHY table.

DROP TABLE AM_IRGR_MATERIAL_GROUP_HIERARCHY


-- 4.3 Import AM_VEN_E

DROP TABLE AM_VENDOR_EXCEPTION_LIST

SELECT 
	*
FROM AM_COUNTRY_MAPPING
where COUNTRY_MAPPING_CODE = 'HK'



DELETE FROM AM_COUNTRY_MAPPING
WHERE COUNTRY_MAPPING_CODE = 'HK'
AND COUNTRY_MAPPING_DESC = 'CHN'





GO
