USE [DIVA_ASAP_TEST_DATA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,> CREATE/UPDATE value for AM_COPA_FILTER_MAPPING mapping table.
-- =============================================
CREATE    PROCEDURE [dbo].[A_016_CREATE/UPDATE_AM_COPA_FILTER_MAPPING]
AS
BEGIN
	
-- Step 1 / Create AM_FSMC table
	EXEC SP_REMOVE_TABLES 'AM_COPA_FILTER_MAPPING'

	CREATE TABLE [dbo].[AM_COPA_FILTER_MAPPING](
	[COPA_SAP_FIELD] [nvarchar](max) NULL,
	[COPA_FILTER] [nvarchar](max) NULL,
	[COPA_FIELD_DESC] [nvarchar](max) NULL
	) 
-- Step 2 / Update value for RUSSIA and TURKEY
	
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[COPA_VKORG] + '' - '' + [TVKOT_VTEXT]', N'ZF_COPA_ORGANISATION', N'ORGANISATION')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[COPA_VTWEG] + '' - '' + [TVTWT_VTEXT]', N'ZF_COPA_DISTRIBUTION_CHANNEL', N'DISTRIBUTION CHANNEL')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[COPA_SPART] + '' - '' + [TSPAT_VTEXT]', N'ZF_COPA_DIVISION', N'DIVISION')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[COPA_PRCTR] + '' - '' + [ZF_CEPCT_MCTXT_NAME]', N'ZF_COPA_PROFIT_CENTER', N'PROFIT CENTER')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[KNA1_NAME1] + '' - '' + [COPA_KNDNR]', N'ZF_COPA_CUSTOMER', N'CUSTOMER')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[KNA1_BRAN1]', N'ZF_COPA_ECOT1', N'ECOT CODE 1')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[KNA1_BRAN2]', N'ZF_COPA_ECOT2', N'ECOT CODE 2')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[KNA1_BRAN3]', N'ZF_COPA_ECOT3', N'ECOT CODE 3')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[KNA1_BRAN4]', N'ZF_COPA_ECOT4', N'ECOT CODE 4')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[KNA1_BRAN5]', N'ZF_COPA_ECOT5', N'ECOT CODE 5')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[KNA1_NAME1] + '' - '' + [COPA_KUNWE]', N'ZF_COPA_SHIP_TO_PARTY', N'SHIP-TO PARTY')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[KNA1_NAME1] + '' - '' + [COPA_KUNWE]', N'ZF_COPA_BILL_TO_PARTY', N'BILL-TO PARTY')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'ZF_KNB1_AKONT_INTER_COM', N'ZF_COPA_SALE_TYPE', N'SALES TYPE')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[COPA_ARTNR] + '' - '' + [MAKT_MAKTX]', N'ZF_COPA_MATERIAL', N'MATERIAL')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[MARA_MATKL] + '' - '' + [T023T_WGBEZ]', N'ZF_COPA_MATERIAL_GROUP', N'MATERIAL GROUP')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'MARA_MATKL', N'ZF_TOKYO_4_DIGIT', N'TOKYO 4 DIGIT')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'SUBSTRING(COPA_PRCTR,1,6)', N'ZF_TOKYO_6_DIGIT', N'TOKYO 6 DIGIT')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'COPA_EAN11', N'ZF_TOKYO_8_DIGIT', N'TOKYO 8 DIGIT')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'SUBSTRING(COPA_WWBD5,1,4)', N'ZF_COPA_PROD_L1', N'PRODUCT_HIERARCHY_L1')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'SUBSTRING(COPA_WWBD5,5,3)', N'ZF_COPA_PROD_L2', N'PRODUCT_HIERARCHY_L2')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'SUBSTRING(COPA_WWBD5,8,3)', N'ZF_COPA_PROD_L3', N'PRODUCT_HIERARCHY_L3')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'SUBSTRING(COPA_WWBD5,11,4)', N'ZF_COPA_PROD_L4', N'PRODUCT_HIERARCHY_L4')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'SUBSTRING(COPA_WWBD5,15,4)', N'ZF_COPA_PROD_L5', N'PRODUCT_HIERARCHY_L5')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[COPA_FKART] + '' - '' + [TVFKT_VTEXT]', N'ZF_COPA_BILLING_DOC', N'BILLING DOCUMENT')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'COPA_VRGAR', N'ZF_COPA_RECORD_TYPE', N'RECORD TYPE')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'TVFKT_VTEXT', N'ZF_COPA_ACC_GRP', N'ACCOUNT ASSIGNMENT GROUP')
	INSERT [dbo].[AM_COPA_FILTER_MAPPING] ([COPA_SAP_FIELD], [COPA_FILTER], [COPA_FIELD_DESC]) VALUES (N'[VBAK_AUART] + '' - '' + [TVAKT_BEZEI]', N'ZF_COPA_SALE_DOC_TYPE', N'SALES DOCUMENT TYPE')

END
GO
