USE [DIVA_SAP_USAGE_ECC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE          PROCEDURE [dbo].[script_C04_GRIR_WITH_MAN_POSTING]
WITH EXECUTE AS CALLER
AS

BEGIN

--Step 1/ Filter journal entry lines on those that are for an account that is considered to be a GR/IR account
EXEC SP_REMOVE_TABLES 'C04_%'

EXEC SP_DROPTABLE 'C04_01_RT_GL_ACC_IN_GRIR_AM'

SELECT B04_11_IT_FIN_GL.*
INTO C04_01_RT_GL_ACC_IN_GRIR_AM
FROM B04_11_IT_FIN_GL
INNER JOIN AM_IRGR_GINI_ARDR_MAPPING
ON AM_IRGR_GINI_ARDR_MAPPING.IRGR_GL_ACCT = B04_11_IT_FIN_GL.B04_BSEG_HKONT


--Step 2/ Filter the GR/IR journal entry lines on those that are manual and also not containing accounts
-- that can only be posted to manually (according to the master data)
-- SKB1_XINTB = X means that the account can only be posted to automatically

EXEC SP_DROPTABLE 'C04_02_XT_GRIR_MAN_POSTING'

SELECT DISTINCT B04_11_IT_FIN_GL.*,
	   A_T001.T001_BUTXT,
	   A_T001.T001_KTOPL,
	   A_T001.T001_WAERS,
	   TSTCT_TTEXT,
	   A_V_USERNAME.V_USERNAME_NAME_TEXT,
	   A_SKB1.SKB1_XINTB,
	   A_T003T.T003T_LTEXT,
	   A_TBSLT.TBSLT_LTEXT,
	   A_MARA.MARA_MATNR,
	   A_MARA.MARA_MTART,
	   A_MARA.MARA_MATKL,
	   A_T134T.T134T_MTBEZ,
	   A_T023T.T023T_WGBEZ,
	   CASE
			WHEN AM_IRGR_GINI_ARDR_MAPPING.IRGR_GL_ACCT IS NOT NULL THEN 'Yes' ELSE 'No' END AS ZF_IRGR_GL_ACCT_FLAG,
	   B00_SKAT.SKAT_TXT20, 
	   B00_SKAT.SKAT_TXT50 
INTO C04_02_XT_GRIR_MAN_POSTING
FROM -- List of documents relating to GR/IR accounts
(
	SELECT DISTINCT B04_BSEG_BUKRS, 
					B04_BSEG_GJAHR, 
					B04_BSEG_BELNR
	FROM C04_01_RT_GL_ACC_IN_GRIR_AM
) A
LEFT JOIN B04_11_IT_FIN_GL --Add all JE lines from the original cube, keep the lines relating to GR/IR accounts 
ON B04_11_IT_FIN_GL.B04_BSEG_BUKRS = A.B04_BSEG_BUKRS
	AND B04_11_IT_FIN_GL.B04_BSEG_GJAHR = A.B04_BSEG_GJAHR
	AND B04_11_IT_FIN_GL.B04_BSEG_BELNR = A.B04_BSEG_BELNR
LEFT JOIN A_T001 
ON B04_11_IT_FIN_GL.B04_BSEG_BUKRS=T001_BUKRS
LEFT JOIN A_V_USERNAME
ON B04_11_IT_FIN_GL.B04_BKPF_USNAM=V_USERNAME_BNAME
LEFT JOIN A_SKB1 
ON A_SKB1.SKB1_BUKRS = B04_11_IT_FIN_GL.B04_BSEG_BUKRS 
	AND A_SKB1.SKB1_SAKNR = B04_11_IT_FIN_GL.B04_BSEG_HKONT 
LEFT JOIN A_T003T
ON T003T_BLART = B04_BKPF_BLART
LEFT JOIN A_TBSLT
ON TBSLT_BSCHL = B04_BSEG_BSCHL
AND TBSLT_UMSKZ = B04_BSEG_UMSKZ
LEFT JOIN A_MARA
ON MARA_MATNR = B04_BSEG_MATNR
LEFT JOIN A_T023T
ON T023T_MATKL = MARA_MATKL
LEFT JOIN A_T134T
ON T134T_MTART = MARA_MTART
-- Add chart fo accounts description
LEFT JOIN A_SKAT B00_SKAT                                             
		ON       
        B00_SKAT.SKAT_KTOPL = A_T001.T001_KTOPL AND               
        B00_SKAT.SKAT_SAKNR = B04_11_IT_FIN_GL.B04_BSEG_HKONT
LEFT JOIN AM_IRGR_GINI_ARDR_MAPPING -- join to list of GR/IR accounts to flag where there is an account relating to GR/IR
ON AM_IRGR_GINI_ARDR_MAPPING.IRGR_GL_ACCT = B04_11_IT_FIN_GL.B04_BSEG_HKONT
LEFT JOIN A_TSTCT  ON  A_TSTCT.TSTCT_SPRSL IN ('E', 'EN') AND -- Language Key is english. 
		A_TSTCT.TSTCT_TCODE = B04_BKPF_TCODE
WHERE B04_ZF_ENTRY_TYPE = 'Manual' AND SKB1_XINTB <> 'X' -- Get manual postings only


-- Step 3/ Change request: Would be nice to know what the accounting scheme is - so that we can see what htey are manually using the GINI account for
-- Step 3.1/ Make GL detail accounti scheme summary table

EXEC SP_DROPTABLE 'C04_03_XT_GRIR_MAN_POSTING_ACC_SCHEMES'

SELECT DISTINCT 
A.B04_BSEG_BUKRS,
A.B04_BSEG_GJAHR,
A.B04_BSEG_BELNR,
A.B04_ZF_BKPF_GJAHR_MONAT,
CONCAT('Debit: ', ZF_DEBIT_ACCOUNT_TYPES, 'Credit: ', ZF_CREDIT_ACCOUNT_TYPES) AS ZF_DB_CR_ACCOUNT_TYPE_LIST_COMBINE,
CONCAT('Debit: ', ZF_DEBIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, 'Credit: ', ZF_CREDIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST) AS ZF_DB_CR_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST_COMBINE,
CONCAT('Debit: ', ZF_DEBIT_HKONT_LIST, 'Credit: ', ZF_CREDIT_HKONT_LIST) AS ZF_DB_CR_BSEG_HKONT_LIST_COMBINE,
CONCAT('Debit: ', ZF_DEBIT_SKAT_TXT20_LIST, 'Credit: ', ZF_CREDIT_SKAT_TXT20_LIST) AS ZF_DB_CR_SKAT_TXT20_LIST_COMBINE,
CONCAT('Debit: ', ZF_DEBIT_SKA1_GVTYP_FLAG_LIST, 'Credit: ', ZF_CREDIT_SKA1_GVTYP_FLAG_LIST) AS ZF_DB_CR_SKA1_GVTYP_FLAG_LIST_COMBINE,
/*
Comment out the fields below as they are no longer in the script BC40/B04
B.ZF_BSEG_DMBTR_S,
B.ZF_BSEG_DMBTR_DB,
B.ZF_BSEG_DMBTR_S_ABS,
B.ZF_BSEG_DMBTR_S_DB_CUC,
B.ZF_BSEG_DMBTR_S_CR_CUC,
B.ZF_BSEG_DMBE2_S,
B.ZF_BSEG_DMBE3_S
*/
B.ZF_BSEG_DMBTR_S_CR,
B.ZF_BSEG_DMBTR_S_CUC_CR,
B.ZF_BSEG_DMBTR_S_DB,
B.ZF_BSEG_DMBTR_S_CUC_DB
INTO C04_03_XT_GRIR_MAN_POSTING_ACC_SCHEMES
FROM C04_02_XT_GRIR_MAN_POSTING A
INNER JOIN B04_07_IT_BSEG_BKPF_ACC_SCH B
ON A.B04_BSEG_BUKRS = B.BSEG_BUKRS
AND A.B04_BSEG_GJAHR = B.BSEG_GJAHR
AND A.B04_BSEG_BELNR = B.BSEG_BELNR


--/*Drop temporary tables*/

EXEC SP_UNNAME_FIELD 'B04_', 'C04_01_RT_GL_ACC_IN_GRIR_AM'
EXEC SP_UNNAME_FIELD 'B04_', 'C04_02_XT_GRIR_MAN_POSTING'
EXEC SP_UNNAME_FIELD 'B04_', 'C04_03_XT_GRIR_MAN_POSTING_ACC_SCHEMES'
EXEC SP_RENAME_FIELD 'C04_02_', 'C04_02_XT_GRIR_MAN_POSTING'
EXEC SP_RENAME_FIELD 'C04_03_', 'C04_03_XT_GRIR_MAN_POSTING_ACC_SCHEMES'



END

GO
