USE [DIVA_SAP_USAGE_ECC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_SU43_Identify storage locations that allow negative stock]
AS
--DYNAMIC_SCRIPT_START

---Check if any storage location that allows negative stock. 


EXEC SP_REMOVE_TABLES 'SU34%'
EXEC SP_DROPTABLE SU43_01_RT_T001L;
SELECT T001L_MANDT,
       ZF_T001L_WERKS_DESC,
	   T001L_WERKS,
	   T001L_LGORT,
	   T001L_LGOBE,
	   T001L_SPART,
	   T001L_XLONG,
	   (CASE WHEN T001L_XLONG='X' THEN 'Yes'
	   ELSE 'No' END) AS ZF_T001L_XLONG_DESC
INTO SU43_01_RT_T001L
FROM BC28_01_IT_T001L_T001W;

---Phase 2:---Storage locations that had negative stock during the period

EXEC SP_DROPTABLE SU43_02_XT_MSEG_MKPF_LBKUM_SALK3;
SELECT DISTINCT *
INTO SU43_02_XT_MSEG_MKPF_LBKUM_SALK3
FROM B24_01_IT_MATERIAL_MOVEMENT
WHERE MSEG_WERKS IN (SELECT DISTINCT T001L_WERKS 
                      FROM BC28_01_IT_T001L_T001W 
					  WHERE T001L_XLONG LIKE 'X');

EXEC SP_RENAME_FIELD 'SU43_01_','SU43_01_RT_T001L';
EXEC SP_RENAME_FIELD 'SU43_02_','SU43_02_XT_MSEG_MKPF_LBKUM_SALK3';
GO
