USE [DIVA_SAP_USAGE_ECC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_SU32_Identify 1TV not in appropriate account groups]
AS
--DYNAMIC_SCRIPT_START

--Script objective: Identify one time vendor are not assigned to one time vendor group
--Step 1 Get the list of onetime-vendor
EXEC SP_DROPTABLE SU32_01_XT_LFA1_XCPDK_EQ_X
SELECT *
INTO SU32_01_XT_LFA1_XCPDK_EQ_X
FROM BP01_01_IT_SUPP
WHERE BP01_01_LFA1_XCPDK='X'

--STep 2 Rename fields
EXEC SP_UNNAME_FIELD 'BP01_01_', 'SU32_01_XT_LFA1_XCPDK_EQ_X'
EXEC SP_RENAME_FIELD 'SU32_01_', 'SU32_01_XT_LFA1_XCPDK_EQ_X'


--Step 3 Get the payment information relate to one time vendors

EXEC SP_DROPTABLE SU32_02_XT_PTP_PAY_1TV

SELECT DISTINCT B11_08_IT_PTP_PAY.*,
IIF(REGUP_BUKRS IS NOT NULL OR LEN(TRIM(REGUP_BUKRS))>0, 'X','') AS ZF_BSAIK_IN_REGUP_FLAG
INTO SU32_02_XT_PTP_PAY_1TV
FROM B11_08_IT_PTP_PAY
INNER JOIN BP01_01_IT_SUPP 
ON B11E_BSAIK_LIFNR=BP01_01_LFA1_LIFNR
LEFT JOIN A_REGUP
ON B11E_BSAIK_BUKRS=REGUP_BUKRS AND	B11E_BSAIK_GJAHR=REGUP_GJAHR AND B11E_BSAIK_BELNR=REGUP_BELNR AND B11E_BSAIK_BUZEI=REGUP_BUZEI
WHERE BP01_01_LFA1_XCPDK='X'

--Step 4 Rename the fields
EXEC SP_UNNAME_FIELD 'B11E_','SU32_02_XT_PTP_PAY_1TV'
EXEC SP_RENAME_FIELD 'SU32_02_','SU32_02_XT_PTP_PAY_1TV'





GO
