USE [DIVA_SAP_USAGE_ECC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_SU18_Identify if price control indicator and mandatory price control are set]
AS
--DYNAMIC_SCRIPT_START

--Objective: Upload full table to identify if price control indicator and mandatroy price control are set
--Step 1: Load table T134 to identify material types that do not have mandatory price control set
--

EXEC SP_REMOVE_TABLES 'SU18_%'

EXEC SP_DROPTABLE SU18_01_RT_T134_T134_MTART;
SELECT DISTINCT A_T134.*,
                T134T_MTBEZ,
                (CASE 
				     WHEN T134_VPRSV ='S' THEN 'S-Standard costing'
					 WHEN T134_VPRSV ='V' THEN 'V-Moving average costing'
					 WHEN T134_VPRSV =' ' THEN '-No price control value'
					 END) AS ZF_T134_VPRSV_DESC,
			    (CASE WHEN T134_KZVPR ='X' THEN 'Yes'
				     ELSE 'No' END) AS ZF_T134_KZVPR_DESC
INTO SU18_01_RT_T134_T134_MTART
FROM A_T134
LEFT JOIN A_T134T
ON T134_MTART=T134T_MTART;


--Khoi update Phase 2 :
--Get the material movement relate to 2 cases:
--Case 1 : where material type (MSEG_MTART = T134_MTART) 
--is do not have price idicator (T134_VPRSV is blank)
--Case 2: where Identify material numbers that have more than one price control indicator
--(different ones for different valuation areas/ plants)

--------------------------------------------------------------------------------------------

--Case 1 : where material type (MSEG_MTART = T134_MTART) 
--is do not have price idicator (T134_VPRSV is blank)

---Step 2: ---Phase 2: Material movement where material type (MSEG_MTART = T134_MTART) 
--is do not have price idicator (T134_VPRSV is blank)

EXEC SP_DROPTABLE SU18_02_XT_MSEG_MATNR_IN_T134_KZVPR_BLK;
SELECT DISTINCT B24_01_IT_MATERIAL_MOVEMENT.*,
	  IIF(MSEG_SALK3 = 0,'Yes','No') AS ZF_MSEG_SALK3_EQ_0
INTO SU18_02_XT_MSEG_MATNR_IN_T134_KZVPR_BLK
FROM B24_01_IT_MATERIAL_MOVEMENT
WHERE MARA_MTART IN 
             ( SELECT DISTINCT T134_MTART
			   FROM SU18_01_RT_T134_T134_MTART 
			   WHERE LEN(T134_VPRSV)=0);

--Phase 2 : 
--For the same material number,plant,valuation type,company code,
--Sorting base on input date and time
--compare between SALK3 and previous SALK3 + DMBTR
--compare between LBKUM and previous LBKUM + MENGE

--Check the SALK3 and the previous SALK3+DMBTR
----
--Step 3
--Add Row numer,will be use to link the previous line with the recent line
-- group by MSEG_BUKRS,MSEG_WERKS,MSEG_BWTAR,MSEG_MATNR
-- order by MSEG_BUKRS,MSEG_WERKS,MSEG_BWTAR,MSEG_MATNR,MKPF_CPUDT,MKPF_CPUTM

EXEC SP_DROPTABLE SU18_03_TT_MSEG_MATNR_MKPF_CPUDT_LBKUM_SALK3
SELECT DISTINCT ROW_NUMBER() OVER (
				PARTITION BY 
							MSEG_BUKRS,
							MSEG_WERKS,
							MSEG_BWTAR,
							MSEG_MATNR
				ORDER BY MSEG_BUKRS,
						MSEG_WERKS,
						MSEG_BWTAR,
						MSEG_MATNR,
						MKPF_CPUDT,
						MKPF_CPUTM,
						MSEG_MJAHR,
						MSEG_MBLNR ) AS ZF_ROW_NUMER,
				MSEG_BUKRS,
				MSEG_WERKS,
				MSEG_BWTAR,
                MSEG_MATNR,
				MAKT_MAKTX,
				MKPF_CPUDT,
				MKPF_CPUTM,
				MSEG_SHKZG,
				T001W_NAME1,
				ZF_MSEG_SALK3_S,
				ZF_MSEG_SALK3_S_CUC,
				ZF_MSEG_DMBTR_SIGNED,
				ZF_MSEG_DMBTR_SIGNED_CUC
INTO SU18_03_TT_MSEG_MATNR_MKPF_CPUDT_LBKUM_SALK3
FROM 
(
	SELECT 
					MSEG_BUKRS,
					MSEG_WERKS,
					MSEG_BWTAR,
					MSEG_MATNR,
					MAKT_MAKTX,
					MKPF_CPUDT,
					MKPF_CPUTM,
					ZF_MSEG_SALK3_S,
					ZF_MSEG_SALK3_S_CUC,
					MSEG_SHKZG,
					MSEG_MJAHR,
					MSEG_MBLNR,
					T001W_NAME1,
					SUM(ZF_MSEG_DMBTR_SIGNED) AS ZF_MSEG_DMBTR_SIGNED,
					SUM(ZF_MSEG_DMBTR_SIGNED_CUC) AS ZF_MSEG_DMBTR_SIGNED_CUC
	FROM 
	SU18_02_XT_MSEG_MATNR_IN_T134_KZVPR_BLK
	GROUP BY 
					MSEG_BUKRS,
					MSEG_WERKS,
					MSEG_BWTAR,
					MSEG_MATNR,
					MAKT_MAKTX,
					MKPF_CPUDT,
					MKPF_CPUTM,
					ZF_MSEG_SALK3_S,
					ZF_MSEG_SALK3_S_CUC,
					MSEG_SHKZG,
					MSEG_MJAHR,
					MSEG_MBLNR,
					T001W_NAME1
) AS A

--STep 4 For each line, add the  the prior line before input date

EXEC SP_DROPTABLE SU18_04_TT_MSEG_ADD_PRIOR_DATA
SELECT DISTINCT A.*,B.ZF_ROW_NUMER AS ZF_ROW_NUMER_PRIOR,
                B.MSEG_MATNR AS ZF_MSEG_MATNR_PRIOR,
				B.MKPF_CPUDT AS ZF_MKPF_CPUDT_PRIOR,
				B.MKPF_CPUTM AS ZF_MKPF_CPUTM_PRIOR,
				B.ZF_MSEG_SALK3_S AS ZF_MSEG_SALK3_S_PRIOR,
				B.ZF_MSEG_SALK3_S_CUC AS ZF_MSEG_SALK3_S_CUC_PRIOR,
				B.ZF_MSEG_DMBTR_SIGNED AS ZF_MSEG_DMBTR_SIGNED_PRIOR,
				B.ZF_MSEG_DMBTR_SIGNED_CUC AS ZF_MSEG_DMBTR_SIGNED_CUC_PRIOR
INTO SU18_04_TT_MSEG_ADD_PRIOR_DATA
FROM SU18_03_TT_MSEG_MATNR_MKPF_CPUDT_LBKUM_SALK3 AS A
INNER JOIN 
(SELECT DISTINCT * FROM SU18_03_TT_MSEG_MATNR_MKPF_CPUDT_LBKUM_SALK3) AS B
ON A.MSEG_MATNR=B.MSEG_MATNR AND 
	A.MSEG_BUKRS=B.MSEG_BUKRS AND 
	A.MSEG_WERKS=B.MSEG_WERKS AND
	A.MSEG_BWTAR=B.MSEG_BWTAR
AND A.ZF_ROW_NUMER-1=B.ZF_ROW_NUMER

--Step 5 Check if where the movement did not cause the material valuation table to be updated
EXEC SP_DROPTABLE SU18_05_XT_MSEG_SALK3_PRIOR_SALK3_PLUS_DMBTR_CHECK
SELECT B.*,
		T001_BUTXT,

	 IIF(ROUND(ZF_MSEG_SALK3_S,4) = ROUND(ZF_SUM_MSEG_SALK3_PRIOR,4),'Yes','No') AS ZF_MSEG_SALK3_EQ_SALK3_PRIOR_PLUS_DMBTR_CHECK
INTO SU18_05_XT_MSEG_SALK3_PRIOR_SALK3_PLUS_DMBTR_CHECK
FROM 
      (
		SELECT DISTINCT *,
			   ZF_MSEG_SALK3_S_PRIOR + ZF_MSEG_DMBTR_SIGNED_PRIOR AS ZF_SUM_MSEG_SALK3_PRIOR,
			   ZF_MSEG_SALK3_S_CUC_PRIOR + ZF_MSEG_DMBTR_SIGNED_CUC_PRIOR AS ZF_SUM_MSEG_SALK3_CUC_PRIOR
		FROM SU18_04_TT_MSEG_ADD_PRIOR_DATA
		)  AS B
LEFT JOIN A_T001 
ON T001_BUKRS=B.MSEG_BUKRS
-- Drop temporary table

DROP TABLE SU18_03_TT_MSEG_MATNR_MKPF_CPUDT_LBKUM_SALK3;
DROP TABLE SU18_04_TT_MSEG_ADD_PRIOR_DATA;


--Check LBKUM and the previos LBKUM+MENGE

--Step 6 Add Row numer
-- group by MSEG_BUKRS,MSEG_WERKS,MSEG_BWTAR,MSEG_MATNR
-- order by MSEG_BUKRS,MSEG_WERKS,MSEG_BWTAR,MSEG_MATNR,MKPF_CPUDT,MKPF_CPUTM
--Add Row numer,will be use to link the previous line with the recent line
--Filter out the case where DMBTR=0
--Since the LBKUM is not add up-, if the previous line where DMBTR is 0

EXEC SP_DROPTABLE SU18_06_TT_MSEG_MATNR_MKPF_CPUDT_LBKUM
SELECT DISTINCT 
			ROW_NUMBER() OVER (
				PARTITION BY 
							MSEG_BUKRS,
							MSEG_WERKS,
							MSEG_BWTAR,
							MSEG_MATNR
				ORDER BY MSEG_BUKRS,
						MSEG_WERKS,
						MSEG_BWTAR,
						MSEG_MATNR,
						MKPF_CPUDT,
						MKPF_CPUTM,MSEG_MJAHR,MSEG_MBLNR ) AS ZF_ROW_NUMER,
				MSEG_BUKRS,
				MSEG_WERKS,
				MSEG_BWTAR,
                MSEG_MATNR,
				MAKT_MAKTX,
				MKPF_CPUDT,
				MKPF_CPUTM,
				MSEG_SHKZG,
				MSEG_LBKUM,
				MSEG_MEINS,
				ZF_MSEG_MENGE_S
INTO SU18_06_TT_MSEG_MATNR_MKPF_CPUDT_LBKUM
FROM 
(
	SELECT 
					MSEG_BUKRS,
					MSEG_WERKS,
					MSEG_BWTAR,
					MSEG_MATNR,
					MAKT_MAKTX,
					MKPF_CPUDT,
					MKPF_CPUTM,
					MSEG_SHKZG,
					MSEG_MJAHR,
					MSEG_MBLNR,
					MSEG_LBKUM,
					MSEG_MEINS,
					SUM(ZF_MSEG_MENGE_S) AS ZF_MSEG_MENGE_S
	FROM 
	SU18_02_XT_MSEG_MATNR_IN_T134_KZVPR_BLK
	WHERE MSEG_DMBTR<>0
	GROUP BY 
					MSEG_BUKRS,
					MSEG_WERKS,
					MSEG_BWTAR,
					MSEG_MATNR,
					MAKT_MAKTX,
					MKPF_CPUDT,
					MKPF_CPUTM,
					MSEG_SHKZG,
					MSEG_MJAHR,
					MSEG_MBLNR,
					MSEG_LBKUM,
					MSEG_MEINS
) AS A

--STep 7 For each line, add the prior data line for each line 

EXEC SP_DROPTABLE SU18_07_TT_MSEG_ADD_PRIOR_DATA
SELECT DISTINCT A.*,B.ZF_ROW_NUMER AS ZF_ROW_NUMER_PRIOR,
                B.MSEG_MATNR AS ZF_MSEG_MATNR_PRIOR,
				B.MKPF_CPUDT AS ZF_MKPF_CPUDT_PRIOR,
				B.MKPF_CPUTM AS ZF_MKPF_CPUTM_PRIOR,
				B.ZF_MSEG_MENGE_S AS ZF_MSEG_MENGE_S_PRIOR,
				B.MSEG_LBKUM AS ZF_MSEG_LBKUM_PRIOR
INTO SU18_07_TT_MSEG_ADD_PRIOR_DATA
FROM SU18_06_TT_MSEG_MATNR_MKPF_CPUDT_LBKUM AS A
INNER JOIN 
	(SELECT DISTINCT * FROM SU18_06_TT_MSEG_MATNR_MKPF_CPUDT_LBKUM) AS B
ON A.MSEG_MATNR=B.MSEG_MATNR AND 
	A.MSEG_BUKRS=B.MSEG_BUKRS AND 
	A.MSEG_WERKS=B.MSEG_WERKS AND
	A.MSEG_BWTAR=B.MSEG_BWTAR
AND A.ZF_ROW_NUMER-1=B.ZF_ROW_NUMER

--Step 8 Check if LBKUM is equal LBKUM prior+MENGE prior
EXEC SP_DROPTABLE SU18_08_XT_MSEG_LBKUM_PRIOR_LBKUM_PLUS_MENGE_CHECK
SELECT A.*,T001_BUTXT,
	 IIF(ROUND(MSEG_LBKUM,4) = ROUND(ZF_SUM_MSEG_LBKUM_MENGE_PRIOR,4),'Yes','No') AS ZF_MSEG_LBKUM_EQ_PRIOR_LBKUM_MENGE
INTO SU18_08_XT_MSEG_LBKUM_PRIOR_LBKUM_PLUS_MENGE_CHECK
FROM 
      (
		SELECT DISTINCT *,
			   ZF_MSEG_LBKUM_PRIOR + ZF_MSEG_MENGE_S_PRIOR AS ZF_SUM_MSEG_LBKUM_MENGE_PRIOR
		FROM SU18_07_TT_MSEG_ADD_PRIOR_DATA
		) AS A
LEFT JOIN A_T001 ON T001_BUKRS=A.MSEG_BUKRS
--Remove temporary tables
EXEC SP_DROPTABLE SU18_06_TT_MSEG_MATNR_MKPF_CPUDT_LBKUM
EXEC SP_DROPTABLE SU18_07_TT_MSEG_ADD_PRIOR_DATA

--Case 2: where Identify material numbers that have more than one price control indicator
--(different ones for different valuation areas/ plants)

--Step 9: Identify material numbers that have more than one price control indicator
--(different ones for different valuation areas/ plants)

EXEC SP_DROPTABLE SU18_09_XT_MBEW_MATNR_WITH_TWO_VPRSV;
SELECT DISTINCT MBEW_MATNR,MAKT_MAKTX,
				(CASE 
				     WHEN MBEW_VPRSV ='S' THEN 'S-Standard costing'
					 WHEN MBEW_VPRSV ='V' THEN 'V-Moving average costing'
					 WHEN MBEW_VPRSV =' ' THEN '-No price control value'
					 END) AS ZF_MBEW_VPRSV_DESC,
			    (CASE WHEN MBEW_VPRSV ='X' THEN 'Yes'
				     ELSE 'No' END) AS ZF_T134_KZVPR_DESC,
				MBEW_VPRSV,
				MARA_MTART,
	            COUNT( MBEW_BWKEY) OVER (PARTITION BY MBEW_MATNR,MBEW_VPRSV) AS ZF_COUNT_VALUATION_AREA
INTO SU18_09_XT_MBEW_MATNR_WITH_TWO_VPRSV
FROM A_MBEW
LEFT JOIN A_MARA ON MARA_MATNR=MBEW_MATNR
LEFT JOIN A_MAKT ON MAKT_MATNR=MBEW_MATNR
WHERE MBEW_MATNR IN (
                     SELECT DISTINCT MBEW_MATNR
                     FROM A_MBEW
                     GROUP BY MBEW_MATNR
					 HAVING COUNT(DISTINCT MBEW_VPRSV) > 1
					 )---Select material numbers that have more than 1 price control indicator

---Step 6: Phase 2 : get the material movements 
--check for any materials that have a different VPRSV in different records.

EXEC SP_DROPTABLE SU18_10_XT_MSEG_MATNR_WITH_TWO_DIFF_VPRSV;
SELECT DISTINCT B24_01_IT_MATERIAL_MOVEMENT.*
INTO SU18_10_XT_MSEG_MATNR_WITH_TWO_DIFF_VPRSV
FROM B24_01_IT_MATERIAL_MOVEMENT
INNER JOIN SU18_09_XT_MBEW_MATNR_WITH_TWO_VPRSV
ON MBEW_MATNR = MSEG_MATNR; 

--Rename the fields
EXEC SP_RENAME_FIELD 'SU18_01_','SU18_01_RT_T134_T134_MTART';
EXEC SP_RENAME_FIELD 'SU18_02_','SU18_02_XT_MSEG_MATNR_IN_T134_KZVPR_BLK';

EXEC SP_RENAME_FIELD 'SU18_05_','SU18_05_XT_MSEG_SALK3_PRIOR_SALK3_PLUS_DMBTR_CHECK';
EXEC SP_RENAME_FIELD 'SU18_08_','SU18_08_XT_MSEG_LBKUM_PRIOR_LBKUM_PLUS_MENGE_CHECK';

EXEC SP_RENAME_FIELD 'SU18_09_','SU18_09_XT_MBEW_MATNR_WITH_TWO_VPRSV';
EXEC SP_RENAME_FIELD 'SU18_10_','SU18_10_XT_MSEG_MATNR_WITH_TWO_DIFF_VPRSV';

GO
