USE [DIVA_SAP_USAGE_ECC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_SU68_Identify users that are allowed to have multiple logins]
AS
--DYNAMIC_SCRIPT_START

-- Script objective : Identify users that are allowed to have multiple logins
--Step 1 
--Filter out the case where PARNAME='login/multi_login_users'
--Get the latest date

EXEC SP_DROPTABLE SU68_01_XT_PAHI_USERID_MUL_LOGON

SELECT DISTINCT
A.*
INTO SU68_01_XT_PAHI_USERID_MUL_LOGON
FROM BC14_01_IT_PAHI_ADD_AM_PARAMETER_TEST AS A
INNER JOIN 
	(	
		SELECT BC14_01_PAHI_HOSTNAME,BC14_01_PAHI_PARNAME,MAX(BC14_01_PAHI_PARDATE) AS ZF_BC14_01_PAHI_PARDATE_MAX
		FROM BC14_01_IT_PAHI_ADD_AM_PARAMETER_TEST
				WHERE
					BC14_01_PAHI_PARNAME='login/multi_login_users'
		GROUP BY BC14_01_PAHI_HOSTNAME,BC14_01_PAHI_PARNAME
	) AS B
	ON A.BC14_01_PAHI_HOSTNAME=B.BC14_01_PAHI_HOSTNAME 
	AND A.BC14_01_PAHI_PARDATE=B.ZF_BC14_01_PAHI_PARDATE_MAX
	AND A.BC14_01_PAHI_PARNAME=B.BC14_01_PAHI_PARNAME
WHERE 	 
	 A.BC14_01_PAHI_PARNAME='login/multi_login_users'




--Rename the fields
EXEC SP_UNNAME_FIELD 'BC14_01_', 'SU68_01_XT_PAHI_USERID_MUL_LOGON'
EXEC SP_RENAME_FIELD 'SU68_01_','SU68_01_XT_PAHI_USERID_MUL_LOGON'


GO
