USE [DIVA_SAP_USAGE_ECC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_SU62_Check logon parameters]
AS
--DYNAMIC_SCRIPT_START

--Script objective: Identify if user logon parameters are configured in accordance with best practices

--Step 1 Filter from system history cube log on behavior only
--Get the latest date
EXEC SP_DROPTABLE 'SU62_01_XT_PAHI_LOGON_BEHAVIOR'

SELECT DISTINCT
A.*,
CASE WHEN A.BC14_01_PAHI_PARNAME='login/disable_password_logon' AND (CAST(A.BC14_01_PAHI_PARVALUE AS INT )=0 AND CAST(A.BC14_01_AM_PAHI_TEST_VALUE AS INT )=1 ) THEN 'X'
	 WHEN A.BC14_01_PAHI_PARNAME='login/fails_to_session_end' AND (CAST(A.BC14_01_PAHI_PARVALUE AS INT )> CAST(A.BC14_01_AM_PAHI_TEST_VALUE AS INT ) ) THEN 'X'
	 WHEN A.BC14_01_PAHI_PARNAME='login/fails_to_user_lock' AND (CAST(A.BC14_01_PAHI_PARVALUE AS INT )> CAST(A.BC14_01_AM_PAHI_TEST_VALUE AS INT ) ) THEN 'X'
	 WHEN A.BC14_01_PAHI_PARNAME='rdisp/gui_auto_logout' AND (CAST(A.BC14_01_PAHI_PARVALUE AS INT )> CAST(A.BC14_01_AM_PAHI_TEST_VALUE AS INT ) ) THEN 'X'
	 ELSE '' END AS ZF_PAHI_PARVALUE_TEST_WEAKER
INTO SU62_01_XT_PAHI_LOGON_BEHAVIOR
FROM BC14_01_IT_PAHI_ADD_AM_PARAMETER_TEST AS A
INNER JOIN 
	(	
		SELECT BC14_01_PAHI_HOSTNAME,BC14_01_PAHI_PARNAME,MAX(BC14_01_PAHI_PARDATE) AS ZF_BC14_01_PAHI_PARDATE_MAX
		FROM BC14_01_IT_PAHI_ADD_AM_PARAMETER_TEST
				WHERE
					BC14_01_PAHI_PARNAME='login/disable_password_logon' OR
					BC14_01_PAHI_PARNAME='login/fails_to_session_end' OR
					BC14_01_PAHI_PARNAME='login/fails_to_user_lock' OR
					BC14_01_PAHI_PARNAME='rdisp/gui_auto_logout'
		GROUP BY BC14_01_PAHI_HOSTNAME,BC14_01_PAHI_PARNAME
	) AS B
	ON A.BC14_01_PAHI_HOSTNAME=B.BC14_01_PAHI_HOSTNAME 
	AND A.BC14_01_PAHI_PARDATE=B.ZF_BC14_01_PAHI_PARDATE_MAX
	AND A.BC14_01_PAHI_PARNAME=B.BC14_01_PAHI_PARNAME
WHERE 	 
	A.BC14_01_PAHI_PARNAME='login/disable_password_logon' OR
	A.BC14_01_PAHI_PARNAME='login/fails_to_session_end' OR
	A.BC14_01_PAHI_PARNAME='login/fails_to_user_lock' OR
	A.BC14_01_PAHI_PARNAME='rdisp/gui_auto_logout'

--Rename the fields
 EXEC SP_UNNAME_FIELD 'BC14_01_','SU62_01_XT_PAHI_LOGON_BEHAVIOR'
 EXEC SP_RENAME_FIELD 'SU62_01_','SU62_01_XT_PAHI_LOGON_BEHAVIOR'


GO
