USE [DIVA_SAP_USAGE_ECC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_SU28_Identify credit control areas that don't provide default credit limits]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START

-- Script objective: Check default credit limit of Credit control areas
-- Step 1: select credit limit of Credit control areas
EXEC SP_REMOVE_TABLES 'SU28_%'

EXEC SP_REMOVE_TABLES 'SU28_01_RT_T014_CREDIT_CONTROL'
		SELECT DISTINCT
		T014_KKBER,
		T014_WAERS,
		T014_KLIMK,
		T014_CTLPC,
		T691T_RTEXT,
		T014T_KKBTX,
		T001_BUKRS,
		T001_PERIV,
		T001_BUTXT,
		IIF(T001_BUKRS IS NULL OR LEN(TRIM(T001_BUKRS))=0,'','X') AS ZF_T014_HAVE_T001_BUKRS
		INTO SU28_01_RT_T014_CREDIT_CONTROL
		FROM A_T014
		LEFT JOIN A_T014T
		ON T014_KKBER = T014T_KKBER
		LEFT JOIN A_T001
		ON T001_KKBER = T014_KKBER
		--INNER JOIN AM_SCOPE
		--ON T001_BUKRS = SCOPE_CMPNY_CODE
		LEFT JOIN A_T691T
		ON T691T_CTLPC=T014_CTLPC AND T014_KKBER=T691T_KKBER AND T691T_SPRAS='EN'
		WHERE T001_PERIV = 'V3'

-- Step 2: select the companys in AM_SCOPE table
EXEC SP_REMOVE_TABLES 'SU28_02_RT_T001_COMPANY_CODE'
		SELECT DISTINCT
		T001_BUKRS,
		T001_BUTXT,
		T001_KKBER,
		T014T_KKBTX,
		T001_PERIV,
		-- Add flag to check company code has credit control or not
		(
			CASE
				WHEN T001_KKBER IN
					(
						SELECT DISTINCT T014_KKBER FROM A_T014
					)
				THEN 'Yes'
				ELSE 'No'
			END
		) AS ZF_T001_KKBER_IN_T014_KKBER_FLAG
		INTO SU28_02_RT_T001_COMPANY_CODE
		FROM A_T001
		LEFT JOIN A_T014T
		ON T001_KKBER = T014T_KKBER
		WHERE T001_PERIV = 'V3'
		--INNER JOIN AM_SCOPE
		--ON T001_BUKRS = SCOPE_CMPNY_CO
-- Rename the fileds
EXEC SP_RENAME_FIELD 'SU28_01_', 'SU28_01_RT_T014_CREDIT_CONTROL'
EXEC SP_RENAME_FIELD 'SU28_02_', 'SU28_02_RT_T001_COMPANY_CODE'


--Step 3 Get the customer information
--Flag the line relate to Credit control area 
EXEC SP_DROPTABLE SU28_03_RT_CUSTOMER
SELECT DISTINCT 
	BO01_01_KNB1_KUNNR,BO01_01_KNA1_NAME1,KNKK_KKBER,BO01_01_KNB1_BUKRS,
	IIF(KNKK_KUNNR IS NULL OR LEN(TRIM(KNKK_KUNNR))=0, '','X') AS ZF_KNB1_IN_KNKK_FLAG,
	IIF(T014_KKBER IS NULL OR LEN(TRIM(T014_KKBER))=0,'','X') AS ZF_KNKK_IN_T014_FLAG,
	T014_KLIMK,KNKK_KLIMK,
	T001_PERIV,
	BC43_01_IT_T691F.*
INTO SU28_03_RT_CUSTOMER
FROM
	BO01_01_IT_CUSTOMER
LEFT JOIN A_KNKK 
	ON BO01_01_KNB1_KUNNR=KNKK_KUNNR
LEFT JOIN A_T001 
	ON BO01_01_KNB1_BUKRS=T001_BUKRS
LEFT JOIN A_T014
	ON KNKK_KKBER=T014_KKBER
LEFT JOIN A_T014T
	ON T014T_KKBER=T001_KKBER 
LEFT JOIN BC43_01_IT_T691F
	ON T691F_KKBER=KNKK_KKBER AND T691F_CTLPC=KNKK_CTLPC
WHERE T001_PERIV = 'V3'


--Rename field
EXEC SP_UNNAME_FIELD 'BO01_01_', 'SU28_03_RT_CUSTOMER'
EXEC SP_RENAME_FIELD 'SU28_03_', 'SU28_03_RT_CUSTOMER'

--Step 5 Select data from BO05_01_IT_SALE_DOCUMENT (sales document types cube)
--Get customer information from sale document 
EXEC SP_REMOVE_TABLES 'SU28_04_RT_TVAK_CUS_CRE_LIMIT'

SELECT DISTINCT
	TVAK_AUART,
	TVAKT_BEZEI,
	TVAK_KLIMP,
	TVAK_VBTYP,
	ZF_TVAK_VBTYP_DESCRIPTION,
	-- Add check credit limit description
	(
		CASE
			WHEN TVAK_KLIMP = '' THEN 'No credit limit check'
			WHEN TVAK_KLIMP = 'A' THEN 'A - Run simple credit limit check and warning message'
			WHEN TVAK_KLIMP = 'B' THEN 'B - Rund simple redit limit check and error message'
			WHEN TVAK_KLIMP = 'C' THEN 'C - Run simple credit limit check and delivery block'
			WHEN TVAK_KLIMP = 'D' THEN 'D - Credit management: Automatic credit control'
		END
	) AS ZF_TVAK_KLIMP_DESCRIPTION,
	-- Add flag to show sales document types should have a credit check
	(
		CASE
			WHEN LEN(TVAK_KLIMP) = 0 THEN 'Yes'
			ELSE  'No'
		END
	) AS ZF_TVAK_KLIMP_IS_SET,
	B33_VBAK_KUNNR,KNA1_NAME1
INTO SU28_04_RT_TVAK_CUS_CRE_LIMIT
FROM BO05_01_IT_TVAK_SALE_DOCUMENT_TYPE
LEFT JOIN B33_01_IT_SALE_DOCUMENTS
ON B33_VBAK_AUART=TVAK_AUART
LEFT JOIN A_KNA1 
ON KNA1_KUNNR=B33_VBAK_KUNNR

-- Step 6: Create cube for sale orders have no credit limit check

EXEC SP_DROPTABLE 'SU28_05_XT_SALE_ORDER_NO_CRE_LIMIT'
SELECT DISTINCT * 
INTO SU28_05_XT_SALE_ORDER_NO_CRE_LIMIT
FROM B33_01_IT_SALE_DOCUMENTS
WHERE B33_VBAK_VBTYP='C' AND EXISTS
(
	SELECT TOP 1 1 FROM BO05_01_IT_TVAK_SALE_DOCUMENT_TYPE
	WHERE B33_VBAK_AUART=TVAK_AUART
	AND LEN(TVAK_KLIMP) = 0
)


-- Rename the fields
EXEC SP_UNNAME_FIELD 'B33_', 'SU28_04_RT_TVAK_CUS_CRE_LIMIT'
EXEC SP_RENAME_FIELD 'SU28_04_', 'SU28_04_RT_TVAK_CUS_CRE_LIMIT'

EXEC SP_UNNAME_FIELD 'B33_', 'SU28_05_XT_SALE_ORDER_NO_CRE_LIMIT'
EXEC SP_RENAME_FIELD 'SU28_05_', 'SU28_05_XT_SALE_ORDER_NO_CRE_LIMIT'

GO
