USE [DIVA_SAP_USAGE_ECC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_BC34_SKB1_SKAT_T001]
AS
--DYNAMIC_SCRIPT_START

--Script objective : Create cube about G/L account master company code

--Step 1/. Get the information abour GL account master data
--Add the descriptions
EXEC SP_DROPTABLE BC34_01_IT_SKB1_SKAT_T001
SELECT DISTINCT A_SKB1.*,
CASE 
WHEN SKB1_MITKZ='A' THEN 'Assets'
WHEN SKB1_MITKZ='D'	THEN 'Customers'
WHEN SKB1_MITKZ='K'	THEN 'Vendors'
WHEN SKB1_MITKZ='V'	THEN 'Contract accounts receivable'
ELSE 'Not found' END AS ZF_SKB1_MITZ_DESCRIPTION,
T001_KTOPL,
T001_BUTXT,
SKAT_TXT20,
SKAT_TXT50
INTO BC34_01_IT_SKB1_SKAT_T001
FROM A_SKB1
	LEFT JOIN A_T001
		ON T001_BUKRS=SKB1_BUKRS
	LEFT JOIN A_SKAT 
		ON SKAT_KTOPL=T001_KTOPL AND SKB1_SAKNR=SKAT_SAKNR
GO
