USE [DIVA_SAP_USAGE_ECC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[script_BC39_MSEG_MKPF_NEW]
WITH EXECUTE AS CALLER
AS

--DYNAMIC_SCRIPT_START

     DECLARE 	 
			 @currency nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'currency')
			,@date1 nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'date1')
			,@date2 nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'date2')
			,@downloaddate nvarchar(max)		= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'downloaddate')
			,@exchangeratetype nvarchar(max)	= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'exchangeratetype')
			,@language1 nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'language1')
			,@language2 nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'language2')
			,@year nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'year')
			,@id nvarchar(max)					= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'id')
			--,@ZV_LIMIT nvarchar(max)		    = (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'LIMIT_RECORDS')
			,@errormsg NVARCHAR(MAX)
			
DECLARE @dateformat varchar(3)
SET @dateformat   = (SELECT dbo.get_param('dateformat'))
SET DATEFORMAT @dateformat;

--Create the metarial movement cube
-- EXEC SP_REMOVE_TABLES 'BC39_%'

EXEC SP_DROPTABLE BC39_01_IT_MSEG_MKPF_NEW

SELECT DISTINCT
	B24_01_IT_MATERIAL_MOVEMENT.*,
	--A_T156HT.T156HT_BTEXT,
	KNA1_KUNNR,
	KNA1_NAME1,
	KNA1_ERNAM,
	CSKT_LTEXT,
	CSKT_KTEXT,
	CEPCT_LTEXT,
	CEPCT_KTEXT,
	IIF(B24_01_V_USERNAME_NAME_TEXT IS NULL, B24_01_MKPF_USNAM, CONCAT(B24_01_MKPF_USNAM, ' - ', B24_01_V_USERNAME_NAME_TEXT)) AS MKPF_USNAM_AND_NAME_TEXT,
	CASE 
		WHEN DBO.TRIM(B24_01_MSEG_SHKZG)='S' THEN B24_01_MSEG_SALK3*COALESCE(TCURX_FACTOR,1)
		ELSE B24_01_MSEG_SALK3*-1*COALESCE(TCURX_FACTOR,1) 
	END AS ZF_MSEG_SALK3_S,
	CASE 
		WHEN DBO.TRIM(B24_01_MSEG_SHKZG)='S' THEN B24_01_MSEG_SALK3*COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1)*COALESCE(TCURX_FACTOR,1)
		ELSE B24_01_MSEG_SALK3*-1*COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1)*COALESCE(TCURX_FACTOR,1) 
	END AS ZF_MSEG_SALK3_S_CUC --signed amount caculation
INTO BC39_01_IT_MSEG_MKPF_NEW
FROM B24_01_IT_MATERIAL_MOVEMENT
--Get customer name from KNA1 table
LEFT JOIN A_KNA1
	ON A_KNA1.KNA1_KUNNR = B24_01_IT_MATERIAL_MOVEMENT.B24_01_MSEG_KUNNR

-- Add the material type and the material description
LEFT JOIN A_MARA 
	ON B24_01_MSEG_MATNR = MARA_MATNR

--Get material group - desription
LEFT JOIN A_T023T
	ON A_T023T.T023T_MATKL = A_MARA.MARA_MATKL

--Get cost center description
LEFT JOIN B00_CSKT
	ON B00_CSKT.CSKT_KOSTL = B24_01_IT_MATERIAL_MOVEMENT.B24_01_MSEG_KOSTL
	AND B00_CSKT.CSKT_KOKRS = B24_01_IT_MATERIAL_MOVEMENT.B24_01_MSEG_KOKRS

--Get profit center description
LEFT JOIN A_CEPCT
	ON	B24_01_IT_MATERIAL_MOVEMENT.B24_01_MSEG_BUKRS = A_CEPCT.CEPCT_KOKRS AND
		B24_01_IT_MATERIAL_MOVEMENT.B24_01_MSEG_KOKRS = A_CEPCT.CEPCT_KOKRS AND
		B24_01_IT_MATERIAL_MOVEMENT.B24_01_MSEG_PRCTR = A_CEPCT.CEPCT_PRCTR 

----Get movement type - text
--LEFT JOIN A_T156HT
--	ON B24_01_IT_MATERIAL_MOVEMENT.B24_01_MSEG_BWART=A_T156HT.T156HT_BWART AND A_T156HT.T156HT_SPRAS='EN'

-- Add T001_WAERS 
LEFT JOIN A_T001 
	ON B24_01_MSEG_BUKRS=T001_BUKRS

--Add TCURX for T001_WAERS 
LEFT JOIN B00_TCURX 
	ON T001_WAERS=TCURX_CURRKEY

-- Add currency factor from company currency to USD

LEFT JOIN B00_IT_TCURF TCURF_CUC
	ON A_T001.T001_WAERS = TCURF_CUC.TCURF_FCURR
	AND TCURF_CUC.TCURF_TCURR  = @currency  
	AND TCURF_CUC.TCURF_GDATU = (
		SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
		FROM B00_IT_TCURF
		WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
				B00_IT_TCURF.TCURF_TCURR  = @currency  AND
				B00_IT_TCURF.TCURF_GDATU <= B24_01_IT_MATERIAL_MOVEMENT.B24_01_MKPF_BUDAT
		ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
		)
-- Add exchange rate from company currency to USD
LEFT JOIN B00_IT_TCURR TCURR_CUC
	ON A_T001.T001_WAERS = TCURR_CUC.TCURR_FCURR
	AND TCURR_CUC.TCURR_TCURR  = @currency  
	AND TCURR_CUC.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= B24_01_IT_MATERIAL_MOVEMENT.B24_01_MKPF_BUDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 

EXEC SP_UNNAME_FIELD 'B24_01_',BC39_01_IT_MSEG_MKPF_NEW



GO
