USE [DIVA_SAP_USAGE_ECC]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_SU31_Check if GR/IR accounts allow for manual postings]
AS
--DYNAMIC_SCRIPT_START

--Script objective :Check if GR/IR accounts allow for manual postings

--Step1 Get the information for the test
--Add a flag to check if T030_KONTH is found in SKB1 or not

EXEC SP_REMOVE_TABLES 'SU31_%'

EXEC SP_DROPTABLE SU31_01_XT_T030_KTOSL_EQ_WRX
SELECT DISTINCT
BC21_02_IT_T030_ADD_DESC.*,
SKB1_FSTAG,
SKB1_XINTB,
SKB1_SAKNR,
--Add a flag to check if T030_KONTH is found in SKB1 or not
IIF(LEN(SKB1_SAKNR)=0 OR SKB1_SAKNR IS NULL, 'X','') AS ZF_T030_KONTH_NOT_FOUND_SKB1
INTO SU31_01_XT_T030_KTOSL_EQ_WRX
 FROM BC21_02_IT_T030_ADD_DESC
LEFT JOIN 
	(
		SELECT DISTINCT SKB1_SAKNR,SKB1_BUKRS,SKB1_FSTAG,SKB1_XINTB,T001_KTOPL
		FROM A_SKB1
		INNER JOIN A_T001 ON A_SKB1.SKB1_BUKRS = A_T001.T001_BUKRS 
		) AS A
ON T030_KTOPL=A.T001_KTOPL AND ( SKB1_SAKNR=T030_KONTH OR SKB1_SAKNR=T030_KONTS)
AND A.SKB1_BUKRS=BC21_02_IT_T030_ADD_DESC.T001_BUKRS
WHERE T030_KTOSL='WRX'


-- Phase 2 : Get all JEs related to  GR/IR accounts allow for manual postings
-- Step 1 / Get all JEs with GL accounts can found in  GR/IR accounts allow for manual postings

EXEC SP_DROPTABLE SU31_02_IT_JEs_RELATED_GRIR

SELECT
	B.*,
	A_T001.T001_BUTXT,
	A_T001.T001_KTOPL,
	A_T001.T001_WAERS,
	TSTCT_TTEXT,
	A_V_USERNAME.V_USERNAME_NAME_TEXT,
	A_SKB1.SKB1_XINTB,
	A_T003T.T003T_LTEXT,
	A_TBSLT.TBSLT_LTEXT,
	A_MARA.MARA_MATNR,
	A_MARA.MARA_MTART,
	A_T134T.T134T_MTBEZ,
	'No ' AS ZF_IRGR_GL_ACCT_FLAG,
	B00_SKAT.SKAT_TXT20, 
	B00_SKAT.SKAT_TXT50 
INTO SU31_02_IT_JEs_RELATED_GRIR
FROM B04_11_IT_FIN_GL B
INNER JOIN (
		SELECT 
			DISTINCT B04_BSEG_BELNR, B04_BSEG_GJAHR, B04_BSEG_BUKRS
		FROM B04_11_IT_FIN_GL A
		WHERE EXISTS 
		(
			SELECT TOP 1 1 
			FROM SU31_01_XT_T030_KTOSL_EQ_WRX
			WHERE A.B04_BSEG_HKONT = SU31_01_XT_T030_KTOSL_EQ_WRX.T030_KONTS
		)
) AS A ON 		 A.B04_BSEG_BELNR =  B.B04_BSEG_BELNR
		AND A.B04_BSEG_GJAHR = B.B04_BSEG_GJAHR
		AND A.B04_BSEG_BUKRS = B.B04_BSEG_BUKRS

LEFT JOIN A_T001 
ON B.B04_BSEG_BUKRS=T001_BUKRS
LEFT JOIN A_V_USERNAME
ON B.B04_BKPF_USNAM=V_USERNAME_BNAME
LEFT JOIN A_SKB1 
ON A_SKB1.SKB1_BUKRS = B.B04_BSEG_BUKRS 
	AND A_SKB1.SKB1_SAKNR = B.B04_BSEG_HKONT 
LEFT JOIN A_T003T
ON T003T_BLART = B04_BKPF_BLART
LEFT JOIN A_TBSLT
ON TBSLT_BSCHL = B04_BSEG_BSCHL
AND TBSLT_UMSKZ = B04_BSEG_UMSKZ
LEFT JOIN A_MARA
ON MARA_MATNR = B04_BSEG_MATNR
LEFT JOIN A_T023T
ON T023T_MATKL = MARA_MATKL
LEFT JOIN A_T134T
ON T134T_MTART = MARA_MTART
-- Add chart fo accounts description
LEFT JOIN A_SKAT B00_SKAT                                             
ON  B00_SKAT.SKAT_KTOPL = A_T001.T001_KTOPL AND               
B00_SKAT.SKAT_SAKNR = B.B04_BSEG_HKONT
--LEFT JOIN AM_IRGR_GINI_ARDR_MAPPING -- join to list of GR/IR accounts to flag where there is an account relating to GR/IR
--ON AM_IRGR_GINI_ARDR_MAPPING.IRGR_GL_ACCT = B.B04_BSEG_HKONT
LEFT JOIN A_TSTCT  
ON  A_TSTCT.TSTCT_SPRSL IN ('E', 'EN') AND -- Language Key is english. 
	A_TSTCT.TSTCT_TCODE = B04_BKPF_TCODE
WHERE LEN(SKB1_XINTB) = 0


UPDATE SU31_02_IT_JEs_RELATED_GRIR
SET ZF_IRGR_GL_ACCT_FLAG='Yes' WHERE
EXISTS
	(
		SELECT TOP 1 1 
		FROM SU31_01_XT_T030_KTOSL_EQ_WRX
		WHERE B04_BSEG_HKONT = SU31_01_XT_T030_KTOSL_EQ_WRX.T030_KONTS
	)

-- Step 2 / Take GL detail accounti scheme summary table

EXEC SP_DROPTABLE 'SU31_03_IT_GRIR_MAN_POSTING_ACC_SCHEMES'

SELECT DISTINCT 
A.B04_BSEG_BUKRS,
A.B04_BSEG_GJAHR,
A.B04_BSEG_BELNR,
A.B04_ZF_BKPF_GJAHR_MONAT,
CONCAT('Debit: ', ZF_DEBIT_ACCOUNT_TYPES, 'Credit: ', ZF_CREDIT_ACCOUNT_TYPES) AS ZF_DB_CR_ACCOUNT_TYPE_LIST_COMBINE,
CONCAT('Debit: ', ZF_DEBIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, 'Credit: ', ZF_CREDIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST) AS ZF_DB_CR_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST_COMBINE,
CONCAT('Debit: ', ZF_DEBIT_HKONT_LIST, 'Credit: ', ZF_CREDIT_HKONT_LIST) AS ZF_DB_CR_BSEG_HKONT_LIST_COMBINE,
CONCAT('Debit: ', ZF_DEBIT_SKAT_TXT20_LIST, 'Credit: ', ZF_CREDIT_SKAT_TXT20_LIST) AS ZF_DB_CR_SKAT_TXT20_LIST_COMBINE,
CONCAT('Debit: ', ZF_DEBIT_SKA1_GVTYP_FLAG_LIST, 'Credit: ', ZF_CREDIT_SKA1_GVTYP_FLAG_LIST) AS ZF_DB_CR_SKA1_GVTYP_FLAG_LIST_COMBINE,
B.ZF_BSEG_DMBTR_S_CUC_DB,
B.ZF_BSEG_DMBTR_S_CUC_CR

INTO SU31_03_IT_GRIR_MAN_POSTING_ACC_SCHEMES
FROM SU31_02_IT_JEs_RELATED_GRIR A
INNER JOIN B04_07_IT_BSEG_BKPF_ACC_SCH B
ON A.B04_BSEG_BUKRS = B.BSEG_BUKRS
AND A.B04_BSEG_GJAHR = B.BSEG_GJAHR
AND A.B04_BSEG_BELNR = B.BSEG_BELNR

--Rename the fields
EXEC SP_UNNAME_FIELD 'BC08_01_','SU31_01_XT_T030_KTOSL_EQ_WRX'
EXEC SP_RENAME_FIELD 'SU31_01_','SU31_01_XT_T030_KTOSL_EQ_WRX'

EXEC SP_UNNAME_FIELD 'B04_','SU31_02_IT_JEs_RELATED_GRIR'
EXEC SP_RENAME_FIELD 'SU31_02_','SU31_02_IT_JEs_RELATED_GRIR'

EXEC SP_UNNAME_FIELD 'B04_','SU31_03_IT_GRIR_MAN_POSTING_ACC_SCHEMES'
EXEC SP_RENAME_FIELD 'SU31_03_','SU31_03_IT_GRIR_MAN_POSTING_ACC_SCHEMES'
GO
