USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[script_B04_SS01_GENERAL]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START

/*  Change history comments
	Update history 
	-------------------------------------------------------
	Date            | Who   |  Description 
	24-03-2022	| Thuan	| Remove MANDT field in join
*/

/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('_DatabaseLogTable', 'U') IS NULL BEGIN CREATE TABLE [dbo].[_DatabaseLogTable] ([Database] nvarchar(max) NULL,[Object] nvarchar(max) NULL,[Object Type] nvarchar(max) NULL,[User] nvarchar(max) NULL,[Date] date NULL,[Time] time NULL,[Description] nvarchar(max) NULL,[Table] nvarchar(max),[Rows] int) END

--Log start of procedure
INSERT INTO [dbo].[_DatabaseLogTable] ([Database],[Object],[Object Type],[User],[Date],[Time],[Description],[Table],[Rows])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(date,GETDATE()),CONVERT(time,GETDATE()),'Procedure started',NULL,NULL

	/* Initialize parameters from globals table */
    DECLARE  
				@CURRENCY NVARCHAR(3)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
				,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
				,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
				,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
				,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
				,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
				,@LANGUAGE1 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
				,@LANGUAGE2 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
				,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
				,@FISCAL_YEAR_FROM NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_FROM')
				,@FISCAL_YEAR_TO NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_TO')
                 SET DATEFORMAT @DATEFORMAT;
			


/* Create GL and Spend detail table */

EXEC SP_REMOVE_TABLES 'B04_14_TT_LIST_ACCT_FOR_RTR_LINE_CHART'
		SELECT B04_GL_ACDOCA_RCLNT, B04_GL_T001_KTOPL, B04_GL_ACDOCA_RACCT, SUM(B04_GL_ZF_ACDOCA_KSL_S) AS KSL_AMOUNT
		INTO B04_14_TT_LIST_ACCT_FOR_RTR_LINE_CHART
		FROM B04_08_IT_FIN_GL
		WHERE B04_08_IT_FIN_GL.B04_GL_ACDOCA_DRCRK = 'S'
		GROUP BY B04_GL_ACDOCA_RCLNT, B04_GL_T001_KTOPL, B04_GL_ACDOCA_RACCT


		EXEC SP_REMOVE_TABLES 'B04_15_IT_LIST_ACCT_FOR_RTR_LINE_CHART'
		SELECT TOP 2 CONCAT(B04_GL_ACDOCA_RACCT, ' - ', SKAT_TXT50) AS GL_ACCT_LINE_CHART
		INTO B04_15_IT_LIST_ACCT_FOR_RTR_LINE_CHART
		FROM B04_14_TT_LIST_ACCT_FOR_RTR_LINE_CHART
		LEFT JOIN A_SKAT
		ON A_SKAT.SKAT_SPRAS IN ('E', 'EN')
		AND A_SKAT.SKAT_KTOPL = B04_GL_T001_KTOPL
		AND A_SKAT.SKAT_SAKNR = B04_GL_ACDOCA_RACCT
		ORDER BY KSL_AMOUNT DESC

		INSERT INTO B04_15_IT_LIST_ACCT_FOR_RTR_LINE_CHART
		VALUES('')


/* log end of procedure*/


INSERT INTO [dbo].[_DatabaseLogTable] ([Database],[Object],[Object Type],[User],[Date],[Time],[Description],[Table],[Rows])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(date,GETDATE()),CONVERT(time,GETDATE()),'Procedure finished',NULL,NULL
GO
