USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE     PROCEDURE [dbo].[script_B18_SS02_COPA_GL_STR]
  
WITH EXECUTE AS CALLER
AS

--DYNAMIC_SCRIPT_START
/*
	Title: [script_B18_SS01_COPA]
	Description: Update COPA_LINE_FLAG for COPA SPE region

	--------------------------------------------------------------
	Update history
	--------------------------------------------------------------
	Date			| Who |   Description
	14-11-2022	    Thuan	   Update 
*/

/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END

--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL

	/* Initialize parameters from globals table */
    DECLARE  
				@CURRENCY NVARCHAR(3)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
				,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
				,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
				,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
				,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
				,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
				,@LANGUAGE1 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
				,@LANGUAGE2 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
				,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
				,@FISCAL_YEAR_FROM NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_FROM')
				,@FISCAL_YEAR_TO NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_TO')
                 SET DATEFORMAT @DATEFORMAT;

SET ROWCOUNT @LIMIT_RECORDS

	/*Step 1: List of JEs that debit Sales reductions Sell-Thru allowance and credit AR*/

	EXEC SP_DROPTABLE 'B18_SS02_01_TT_ACDOCA_BKPF_ACC_SCH_DEBIT_SR_CREDIT_AR'
	SELECT DISTINCT
		B04_09_ACDOCA_RBUKRS,
		B04_09_ACDOCA_GJAHR,
		B04_09_ACDOCA_BELNR
	INTO B18_SS02_01_TT_ACDOCA_BKPF_ACC_SCH_DEBIT_SR_CREDIT_AR
	FROM B04_09_IT_ACDOCA_BKPF_ACC_SCH
	WHERE B04_09_ZF_CREDIT_ACCOUNTS LIKE '%A014%' -- Account receivables accounts
		AND B04_09_ZF_DEBIT_ACCOUNTS LIKE '%A62242%' -- STR accounts


	/*Step 2: Full GL detail where JEs debit Sales reductions Sell-Thru allowance and credit AR
	-- while filling in tax related rows with the customer number*/

	EXEC SP_DROPTABLE 'B18_SS02_02_IT_FIN_GL_DEBIT_SR_CREDIT_AR'
	SELECT DISTINCT
		B04_08_IT_FIN_GL.*,
		-- Fill missing KUNNR values within each group using FIRST_VALUE
		FIRST_VALUE(B04_GL_ACDOCA_KUNNR) OVER (
			PARTITION BY B04_GL_ACDOCA_RBUKRS, B04_GL_ACDOCA_GJAHR, B04_GL_ACDOCA_BELNR
			ORDER BY (CASE WHEN LEN(B04_GL_ACDOCA_KUNNR) > 0 THEN 1 ELSE 0 END) DESC
		) AS ZF_ACDOCA_KUNNR_FILLED,
		-- Flag the accounts: AR, Gross sales, Sales reductions, COGS...
		CASE
			WHEN LEN(COPA_RACCT_Hierarchy_L3) IS NOT NULL THEN COPA_RACCT_Hierarchy_L1
			WHEN LEN(COPA_RACCT_Hierarchy_L3) IS NULL AND B04_GL_ACDOCA_RACCT LIKE '%A014%' THEN 'Accounts receivables'
			ELSE 'Tax'
		END AS ZF_CATEGORY,
		COPA_RACCT_Hierarchy_L3
	INTO B18_SS02_02_IT_FIN_GL_DEBIT_SR_CREDIT_AR
	FROM B04_08_IT_FIN_GL
	-- Inner join the JE table of which the accounting schemes are debit Sell-thru allowance and credit AR
	INNER JOIN TEMP_B04_09_IT_ACDOCA_BKPF_ACC_SCH_STR_AR
		ON B04_GL_ACDOCA_RBUKRS = B04_09_ACDOCA_RBUKRS
		AND B04_GL_ACDOCA_GJAHR = B04_09_ACDOCA_GJAHR
		AND B04_GL_ACDOCA_BELNR = B04_09_ACDOCA_BELNR
	LEFT JOIN AM_COPA_MAPPING 
		ON COPA_RACCT = B04_GL_ACDOCA_RACCT;



	EXEC SP_UNNAME_FIELD 'B04_GL_', 'B18_SS02_02_IT_FIN_GL_DEBIT_SR_CREDIT_AR'
	EXEC sp_RENAME_FIELD 'B18_SS02_', 'B18_SS02_02_IT_FIN_GL_DEBIT_SR_CREDIT_AR'
GO
