USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE     PROCEDURE [dbo].[script_B11_SS02_ADD_USER_INV_PAY]
AS

--DYNAMIC_SCRIPT_START
/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('_DatabaseLogTable', 'U') IS NULL BEGIN CREATE TABLE [dbo].[_DatabaseLogTable] ([Database] nvarchar(max) NULL,[Object] nvarchar(max) NULL,[Object Type] nvarchar(max) NULL,[User] nvarchar(max) NULL,[Date] date NULL,[Time] time NULL,[Description] nvarchar(max) NULL,[Table] nvarchar(max),[Rows] int) END

--Log start of procedure
INSERT INTO [dbo].[_DatabaseLogTable] ([Database],[Object],[Object Type],[User],[Date],[Time],[Description],[Table],[Rows])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(date,GETDATE()),CONVERT(time,GETDATE()),'Procedure started',NULL,NULL

/* Initialize parameters from globals table */

     DECLARE 	 
			 @currency nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'currency')
			,@date1 nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'date1')
			,@date2 nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'date2')
			,@downloaddate nvarchar(max)		= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'downloaddate')
			,@exchangeratetype nvarchar(max)	= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'exchangeratetype')
			,@language1 nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'language1')
			,@language2 nvarchar(max)			= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'language2')
			,@year nvarchar(max)				= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'year')
			,@id nvarchar(max)					= (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'id')
			,@ZV_LIMIT nvarchar(max)		    = (SELECT [GLOBALS_VALUE] FROM [AM_GLOBALS] WHERE [GLOBALS_PARAMETER] = 'ZV_LIMIT')
			,@LIMIT_RECORDS INT                  = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
			,@errormsg NVARCHAR(MAX)
			
DECLARE @dateformat varchar(3)
SET @dateformat   = (SELECT dbo.get_param('dateformat'))
SET DATEFORMAT @dateformat;

SET ROWCOUNT @LIMIT_RECORDS;

--Step1 Add username,name of the user who create the supplier 
--Add supplier create date,
--Add supplier create date,
EXEC SP_REMOVE_TABLES 'B11_SS02_%'
EXEC SP_REMOVE_TABLES'XTEMP'
SELECT 
B11B_ACDOCA_RCLNT AS ACDOCA_RCLNT,
B11B_ACDOCA_RBUKRS AS ACDOCA_RBUKRS,
B11B_ACDOCA_GJAHR AS ACDOCA_GJAHR,
B11B_ACDOCA_BELNR AS ACDOCA_BELNR,
B11B_ACDOCA_BUZEI AS ACDOCA_BUZEI,
B11B_ACDOCA_DOCLN AS ACDOCA_DOCLN,
B11B_ACDOCA_BSCHL AS ACDOCA_BSCHL,
B11B_ACDOCA_DRCRK AS ACDOCA_DRCRK,
B11B_ACDOCA_BLART AS ACDOCA_BLART,
B11B_ACDOCA_LIFNR AS ACDOCA_LIFNR,
B11B_ACDOCA_RWCUR AS ACDOCA_RWCUR,
B11B_ACDOCA_RHCUR AS ACDOCA_RHCUR,
B11B_ACDOCA_RKCUR AS ACDOCA_RKCUR,
B11B_ACDOCA_ROCUR AS ACDOCA_ROCUR,
B11B_ACDOCA_HSL AS ACDOCA_HSL,
B11B_ACDOCA_KSL AS ACDOCA_KSL,
B11B_ACDOCA_OSL AS ACDOCA_OSL,
B11B_ACDOCA_UMSKZ AS ACDOCA_UMSKZ,
B11B_ACDOCA_AUGDT AS ACDOCA_AUGDT,
B11B_ACDOCA_AUGBL AS ACDOCA_AUGBL,
B11B_ACDOCA_ZUONR AS ACDOCA_ZUONR,
B11B_ACDOCA_BUDAT AS ACDOCA_BUDAT,
B11B_ACDOCA_BLDAT AS ACDOCA_BLDAT,
B11B_ACDOCA_CPUDT AS ACDOCA_CPUDT,
B11B_ACDOCA_XBLNR AS ACDOCA_XBLNR,
B11B_ACDOCA_MONAT AS ACDOCA_MONAT,
B11B_ACDOCA_RBUSA AS ACDOCA_RBUSA,
B11B_ACDOCA_WSL AS ACDOCA_WSL,
B11B_ACDOCA_MWSKZ AS ACDOCA_MWSKZ,
B11B_ACDOCA_SGTXT AS ACDOCA_SGTXT,
B11B_ACDOCA_AUFNR AS ACDOCA_AUFNR,
B11B_ACDOCA_EBELN AS ACDOCA_EBELN,
B11B_ACDOCA_EBELP AS ACDOCA_EBELP,
B11B_ACDOCA_RACCT AS ACDOCA_RACCT,
B11B_ACDOCA_BSTAT AS ACDOCA_BSTAT,
B11B_ACDOCA_PS_POSID AS ACDOCA_PS_POSID,
B11B_ACDOCA_RCNTR AS ACDOCA_RCNTR,
B11B_ACDOCA_PRCTR AS ACDOCA_PRCTR,
B11B_ACDOCA_AUGGJ AS ACDOCA_AUGGJ,
B11B_ZF_ACDOCA_CPUDT_AGE_DAYS AS ZF_ACDOCA_CPUDT_AGE_DAYS,
B11B_ZF_ACDOCA_OPEN_CLOSED AS ZF_ACDOCA_OPEN_CLOSED,
B11B_ZF_ACDOCA_DRCRK_DESC AS ZF_ACDOCA_DRCRK_DESC,
B11B_ZF_ACDOCA_DRCRK_INTEGER AS ZF_ACDOCA_DRCRK_INTEGER,
B11B_ZF_ACDOCA_AUGDT_YEAR_MNTH AS ZF_ACDOCA_AUGDT_YEAR_MNTH,
B11B_T001_WAERS AS T001_WAERS,
B11B_ZF_ACDOCA_HSL_S AS ZF_ACDOCA_HSL_S,
B11B_ZF_ACDOCA_KSL_S AS ZF_ACDOCA_KSL_S,
B11B_ZF_ACDOCA_OSL_S AS ZF_ACDOCA_OSL_S,
B11B_GLOBALS_CURRENCY AS GLOBALS_CURRENCY,
B11B_ZF_ACDOCA_HSL_S_CUC AS ZF_ACDOCA_HSL_S_CUC,
B11B_LFA1_KTOKK AS LFA1_KTOKK,
B11B_T077Y_TXT30 AS T077Y_TXT30,
B11B_T003T_LTEXT AS T003T_LTEXT,
B11B_BKPF_TCODE AS BKPF_TCODE,
B11B_TSTCT_TTEXT AS TSTCT_TTEXT,
B11B_ZF_DEBIT_ACCOUNTS AS ZF_DEBIT_ACCOUNTS,
B11B_ZF_CREDIT_ACCOUNTS AS ZF_CREDIT_ACCOUNTS,
B11B_ZF_DEBIT_ACCOUNT_TEXTS AS ZF_DEBIT_ACCOUNT_TEXTS,
B11B_ZF_CREDIT_ACCOUNT_TEXTS AS ZF_CREDIT_ACCOUNT_TEXTS,
B11B_ZF_ACDOCA_RCNTR AS ZF_ACDOCA_RCNTR,
B11B_ZF_CSKT_LTEXT AS ZF_CSKT_LTEXT,
B11B_ZF_SUPP_INV AS ZF_SUPP_INV,
B11B_ZF_SUPP_INV_CANC AS ZF_SUPP_INV_CANC,
B11B_ZF_SUPP_PAY AS ZF_SUPP_PAY,
B11B_ZF_SUPP_PAY_CANC AS ZF_SUPP_PAY_CANC,
B11B_ZF_OTHERS AS ZF_OTHERS,
B11B_ZF_FLAG_SUMMARY AS ZF_FLAG_SUMMARY,
B11B_ACDOCA_KOKRS AS ACDOCA_KOKRS,
B11B_ACDOCA_KOART AS ACDOCA_KOART,
B11B_TGSBT_GTEXT AS TGSBT_GTEXT,
B11B_SCOPE_BUSINESS_DMN_L1 AS SCOPE_BUSINESS_DMN_L1,
B11B_SCOPE_BUSINESS_DMN_L2 AS SCOPE_BUSINESS_DMN_L2,
B11B_T001_BUTXT AS T001_BUTXT,
B11B_T001_LAND1 AS T001_LAND1,
B11B_LFA1_NAME1 AS LFA1_NAME1,
B11B_LFA1_LAND1 AS LFA1_LAND1,
B11B_LFA1_VBUND AS LFA1_VBUND,
B11B_INTERCO_TXT AS INTERCO_TXT,
B11B_DD07T_DDTEXT AS DD07T_DDTEXT,
B11B_COUNTRY_MAPPING_DESC AS COUNTRY_MAPPING_DESC,
B11B_T001_COUNTRY_MAPPING_DESC AS T001_COUNTRY_MAPPING_DESC,
B11B_TBSLT_LTEXT AS TBSLT_LTEXT,
B11B_ZF_ACDOCA_WSL_S AS ZF_ACDOCA_WSL_S,
B11B_ZF_ACDOCA_WSL_S_CUC AS ZF_ACDOCA_WSL_S_CUC,
B11B_ZF_ACDOCA_HSL_CUC AS ZF_ACDOCA_HSL_CUC,
B11B_ACDOCA_USNAM AS ACDOCA_USNAM,
B11B_V_USERNAME_NAME_TEXT AS V_USERNAME_NAME_TEXT,
B11B_USR02_USTYP AS USR02_USTYP,
B11B_ZF_USR02_USTYP_DESC AS ZF_USR02_USTYP_DESC,
B11B_SKAT_TXT50 AS SKAT_TXT50,
B11B_ZF_ACDOCA_PRCTR AS ZF_ACDOCA_PRCTR,
B11B_ZF_CEPCT_LTEXT AS ZF_CEPCT_LTEXT,
B11B_ZF_ACDOCA_AWTYP_MM_INV AS ZF_ACDOCA_AWTYP_MM_INV,
B11B_ZF_ACDOCA_AWTYP_MM_INV_NUM AS ZF_ACDOCA_AWTYP_MM_INV_NUM,
B11B_ZF_ACDOCA_AWTYP_MM_INV_YEAR AS ZF_ACDOCA_AWTYP_MM_INV_YEAR,
B11B_BKPF_AWKEY AS BKPF_AWKEY,
B11B_ACDOCA_AWTYP AS ACDOCA_AWTYP,
B11B_ZF_ACDOCA_BUDAT_CY AS ZF_ACDOCA_BUDAT_CY,
B11B_ZF_ACDOCA_BUDAT_CY_MNTH AS ZF_ACDOCA_BUDAT_CY_MNTH,
B11B_ZF_ACDOCA_BUDAT_CY_CQ AS ZF_ACDOCA_BUDAT_CY_CQ,
B11B_ZF_ACDOCA_MONAT_FQ AS ZF_ACDOCA_MONAT_FQ,
B11B_ZF_ACDOCA_GJAHR_MONAT AS ZF_ACDOCA_GJAHR_MONAT,
B11B_ZF_ACDOCA_BUDAT_MNTH AS ZF_ACDOCA_BUDAT_MNTH,
B11B_ACDOCA_CPUTM AS ACDOCA_CPUTM,
B11B_BKPF_BKTXT AS BKPF_BKTXT,
B11B_ZF_ACDOCA_AUGDT_LST_DY_CAL AS ZF_ACDOCA_AUGDT_LST_DY_CAL,
B11B_ZF_ACDOCA_AUGDT_CAL_MNTH AS ZF_ACDOCA_AUGDT_CAL_MNTH,
B11B_ZF_ACDOCA_CPUDT_AGE_DAY_RANGE AS ZF_ACDOCA_CPUDT_AGE_DAY_RANGE,
B11B_ZF_BLDAT_MINUS_AUGDT AS ZF_BLDAT_MINUS_AUGDT,
B11B_ZF_BLDAT_MINUS_AUGDT_BUCKET AS ZF_BLDAT_MINUS_AUGDT_BUCKET,
B11B_ZF_BLDAT_MINUS_AUGDT_FLAG AS ZF_BLDAT_MINUS_AUGDT_FLAG,
B11B_ZF_ACDOCA_AUGDT_MINUS_NETDT AS ZF_ACDOCA_AUGDT_MINUS_NETDT, -- Nam: update field name
B11B_ZF_ACDOCA_BUDAT_MINUS_BLDAT AS ZF_ACDOCA_BUDAT_MINUS_BLDAT,
B11B_ZF_ACDOCA_NETDT_AUGDT_EARLY_OR_LATE_DESC AS ZF_ACDOCA_NETDT_AUGDT_EARLY_OR_LATE_DESC, -- Nam: update field name
B11B_ZF_LFA1_VBUND AS ZF_LFA1_VBUND,
B11B_ZF_RSEG_INV_WITH_PO AS ZF_RSEG_INV_WITH_PO,
B11B_ZF_RSEG_INV_WITH_GR AS ZF_RSEG_INV_WITH_GR,
B11B_ZF_ACDOCA_BUDAT_POST_PER AS ZF_ACDOCA_BUDAT_POST_PER,
B11B_ZF_ACDOCA_AUGDT_CLEAR_PER AS ZF_ACDOCA_AUGDT_CLEAR_PER,
B11B_ZF_ACDOCA_BSTAT_DESC AS ZF_ACDOCA_BSTAT_DESC,
B11B_ZF_ACDOCA_MULTIPLE_SUPPS AS ZF_ACDOCA_MULTIPLE_SUPPS,
B11B_ZF_ACDOCA_INV_DESC AS ZF_ACDOCA_INV_DESC,
B11B_ZF_ACDOCA_HSL_DEBIT AS ZF_ACDOCA_HSL_DEBIT,
B11B_ZF_ACDOCA_HSL_CREDIT AS ZF_ACDOCA_HSL_CREDIT,
B11B_ZF_ACDOCA_RBURKS_T001_BUTXT AS ZF_ACDOCA_RBURKS_T001_BUTXT,
B11B_ZF_ACDOCA_LIFNR_NAME1 AS ZF_ACDOCA_LIFNR_NAME1,
B11B_ACDOCA_MONAT_DESC AS ACDOCA_MONAT_DESC,
B11B_ZF_NET_AUGDT_DAYS_LATE_RANGE AS ZF_NET_AUGDT_DAYS_LATE_RANGE, -- Nam: update field name
B11B_ZF_POSTING_BUDAT_MINUS_BLDAT_CATEGORY AS ZF_POSTING_BUDAT_MINUS_BLDAT_CATEGORY,
B11B_ZF_AUGDT_MINUS_NETDT_CATEGORY AS ZF_AUGDT_MINUS_NETDT_CATEGORY, -- Nam: update field name
B11B_ZF_EARLY_PAYMENT_VAL AS ZF_EARLY_PAYMENT_VAL,
B11B_ZF_ONTIME_PAYMENT_VAL AS ZF_ONTIME_PAYMENT_VAL,
B11B_ZF_LATE_PAYMENT_VAL AS ZF_LATE_PAYMENT_VAL,
B11B_ZF_ACDOCA_HSL_CUC_DEBIT AS ZF_ACDOCA_HSL_CUC_DEBIT,
B11B_ZF_ACDOCA_HSL_CUC_CREDIT AS ZF_ACDOCA_HSL_CUC_CREDIT,
B11B_ZF_ACDOCA_BUDAT_YYYYMMM AS ZF_ACDOCA_BUDAT_YYYYMMM,
B11B_ZF_ACDOCA_BUDAT_YYYYMMDD_GROUPED AS ZF_ACDOCA_BUDAT_YYYYMMDD_GROUPED,
		CONCAT(B11B_ACDOCA_RBUKRS,
				'-',B11B_ACDOCA_GJAHR,
				'-',B11B_ACDOCA_BELNR) AS ZF_DOCUMENT_NUMBER,
B11B_ACDOCA_MATNR AS ACDOCA_MATNR,
BUKRS_MAPPING  ACDOCA_BUKRS_MAPPING 
INTO XTEMP
FROM B11_04_IT_PTP_APA

/*
WHERE B11_04_IT_PTP_APA.B11B_ACDOCA_RBUKRS IN
(
	SELECT DISTINCT COMPANY_CODE FROM AM_COMPANY_CODE
) AND (B11B_ZF_SUPP_INV='X' OR B11B_ZF_SUPP_PAY='X')
 */
 
 INNER JOIN AM_COMPANY_CODE ON B11_04_IT_PTP_APA.B11B_ACDOCA_RBUKRS=COMPANY_CODE
 WHERE (B11B_ZF_SUPP_INV='X' OR B11B_ZF_SUPP_PAY='X')
		   
EXEC SP_DROPTABLE 'B11_SS02_01_IT_PTP_APA'
SELECT 
		XTEMP.*,
		B08_LFA1_ERNAM AS LFA1_ERNAM,--User who create the supplier
		B08_LFA1_ERDAT AS LFA1_ERDAT,--Supplier create date
		A_V_USERNAME.V_USERNAME_NAME_TEXT AS V_USERNAME_NAME_TEXT_LFA1,--Name of the supplier,
		B04_09_ZF_CREDIT_ACCOUNTS_DESC_COMBINE AS ZF_CREDIT_ACCOUNTS_DESC_COMBINE,
		B04_09_ZF_DEBIT_ACCOUNTS_DESC_COMBINE AS ZF_DEBIT_ACCOUNTS_DESC_COMBINE,
		B04_09_ZF_DEBIT_ACDOCA_RCNTR_AND_DESC AS ZF_DEBIT_ACDOCA_RCNTR_AND_DESC,
		B04_09_ZF_CREDIT_ACDOCA_RCNTR_AND_DESC AS ZF_CREDIT_ACDOCA_RCNTR_AND_DESC,
		B04_09_ZF_DEBIT_ACDOCA_PRCTR_AND_DESC AS ZF_DEBIT_ACDOCA_PRCTR_AND_DESC,
		B04_09_ZF_CREDIT_ACDOCA_PRCTR_AND_DESC AS ZF_CREDIT_ACDOCA_PRCTR_AND_DESC,
		T134T_MTBEZ,
		MARA_MTART,
		MAKT_MAKTX
INTO B11_SS02_01_IT_PTP_APA
FROM XTEMP
LEFT JOIN B08_02_IT_PTP_SMD
	 ON XTEMP.ACDOCA_LIFNR = B08_02_IT_PTP_SMD.B08_EKKO_LIFNR
LEFT JOIN A_V_USERNAME
    ON B08_LFA1_ERNAM=V_USERNAME_BNAME
LEFT JOIN B04_09_IT_ACDOCA_BKPF_ACC_SCH
	ON B04_09_ACDOCA_RBUKRS=ACDOCA_RBUKRS AND
       B04_09_ACDOCA_GJAHR=ACDOCA_GJAHR AND
       B04_09_ACDOCA_BELNR=ACDOCA_BELNR
LEFT JOIN B00_MAKT
	ON MAKT_MATNR=ACDOCA_MATNR
LEFT JOIN A_MARA
	ON MARA_MATNR=ACDOCA_MATNR
LEFT JOIN B00_T134T
	ON MARA_MTART=T134T_MTART
	
--Create 2 --Separete invoice and payment table
--EXEC SP_DROPTABLE 'B11_SS02_01_IT_PTP_APA_INV'
/*EXEC SP_REMOVE_TABLES 'B11_SS02_01_IT_PTP_APA_INV'

SELECT * INTO B11_SS02_01_IT_PTP_APA_INV
FROM B11_SS02_01_IT_PTP_APA
WHERE ZF_SUPP_INV='X'*/

EXEC SP_REMOVE_TABLES 'B11_SS02_02_IT_PTP_APA_PAY'

SELECT * INTO B11_SS02_02_IT_PTP_APA_PAY
FROM B11_SS02_01_IT_PTP_APA
WHERE ZF_SUPP_PAY='X'

--Step 3
--For Process ming ,Add BVTYP to the payment cube

EXEC SP_DROPTABLE B11_SS02_03_TT_PTP_APA_PAY_ADD_FIELD
SELECT DISTINCT 
B11_SS02_02_IT_PTP_APA_PAY.*,
BSEG_BVTYP AS ACDOCA_BSEG_BVTYP
INTO B11_SS02_03_TT_PTP_APA_PAY_ADD_FIELD
FROM B11_SS02_02_IT_PTP_APA_PAY
LEFT JOIN
(
	SELECT DISTINCT BSEG_BUKRS,BSEG_GJAHR,BSEG_BELNR,BSEG_BUZEI,BSEG_BVTYP FROM A_BSEG
) AS A ON 
ACDOCA_RBUKRS=BSEG_BUKRS AND
ACDOCA_GJAHR=BSEG_GJAHR AND
ACDOCA_BELNR=BSEG_BELNR AND
ACDOCA_BUZEI=BSEG_BUZEI

--Step 4 Join to LFBK to get Bank account number
-- and join to REGUH to gert REGUH_ZBNKN
EXEC SP_DROPTABLE B11_SS02_04_TT_PTP_APA_PAY_ADD_LFBK

SELECT DISTINCT
B11_SS02_03_TT_PTP_APA_PAY_ADD_FIELD.*,
ZF_LFBK_BANKN_LIST AS LFBK_BANKN,
ZF_REGUH_ZBNKN_LIST AS REGUH_ZBNKN
INTO B11_SS02_04_TT_PTP_APA_PAY_ADD_LFBK
FROM B11_SS02_03_TT_PTP_APA_PAY_ADD_FIELD
LEFT JOIN 
(
	SELECT A.LFBK_LIFNR,
		A.LFBK_BVTYP,
		STUFF((SELECT DISTINCT '_' + B.LFBK_BANKN
							 FROM A_LFBK B
							 WHERE (B.LFBK_LIFNR = A.LFBK_LIFNR  
								   AND B.LFBK_BVTYP = A.LFBK_BVTYP)
							 GROUP BY LFBK_BANKN
							 FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
							 ,1,1,'') AS ZF_LFBK_BANKN_LIST
		FROM A_LFBK AS A
		GROUP BY LFBK_LIFNR,LFBK_BVTYP
) AS D
ON ACDOCA_LIFNR=D.LFBK_LIFNR AND ACDOCA_BSEG_BVTYP=D.LFBK_BVTYP
LEFT JOIN 
(
		SELECT A.REGUH_ZBUKR,
		YEAR(A.REGUH_LAUFD) AS ZF_REGUH_LAUFD_YEAR,
		A.REGUH_VBLNR,
		STUFF((SELECT DISTINCT '_' + B.REGUH_ZBNKN
							 FROM A_REGUH B
							 WHERE (B.REGUH_ZBUKR = A.REGUH_ZBUKR  
								   AND YEAR(B.REGUH_LAUFD) = YEAR(A.REGUH_LAUFD)
								   AND B.REGUH_VBLNR = A.REGUH_VBLNR)
							 GROUP BY REGUH_ZBNKN
							 FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
							 ,1,1,'') AS ZF_REGUH_ZBNKN_LIST
		FROM A_REGUH AS A
		WHERE A.REGUH_ZBUKR IN
		( SELECT DISTINCT COMPANY_CODE FROM AM_COMPANY_CODE )
		GROUP BY A.REGUH_ZBUKR,
		YEAR(A.REGUH_LAUFD),
		A.REGUH_VBLNR
) AS C
ON 
	ACDOCA_RBUKRS=C.REGUH_ZBUKR AND 
	ACDOCA_GJAHR=C.ZF_REGUH_LAUFD_YEAR AND
	ACDOCA_BELNR=C.REGUH_VBLNR

--Step 5 ----Group by the payment , to caculate the total line item value

EXEC SP_DROPTABLE B11_SS02_05_IT_PTP_APA_PAY_GROUP
SELECT DISTINCT ACDOCA_RBUKRS,
				ACDOCA_GJAHR,
				ACDOCA_BELNR,
				ACDOCA_USNAM,
				V_USERNAME_NAME_TEXT,
				ACDOCA_BLDAT,
				ACDOCA_LIFNR,
				LFA1_ERNAM,T001_WAERS,
				SUM(ZF_ACDOCA_HSL_S) AS ZF_ACDOCA_HSL_S,
				SUM(ZF_ACDOCA_HSL_S_CUC) AS ZF_ACDOCA_HSL_S_CUC,
				SUM(ZF_ACDOCA_KSL_S) AS ZF_ACDOCA_KSL_S, 
				SUM(ZF_ACDOCA_OSL_S) AS ZF_ACDOCA_OSL_S,
				T003T_LTEXT,
				ACDOCA_AUGDT,
				ACDOCA_AUGBL,
				ACDOCA_CPUDT,ACDOCA_CPUTM,
				LFBK_BANKN,REGUH_ZBNKN,
				ACDOCA_BUKRS_MAPPING 
INTO B11_SS02_05_IT_PTP_APA_PAY_GROUP
FROM B11_SS02_04_TT_PTP_APA_PAY_ADD_LFBK
GROUP BY
		ACDOCA_RBUKRS,
		ACDOCA_GJAHR,
		ACDOCA_BELNR,
		ACDOCA_USNAM,
		V_USERNAME_NAME_TEXT,
		ACDOCA_BLDAT,
		ACDOCA_LIFNR,
		LFA1_ERNAM,
		T003T_LTEXT,
		ACDOCA_AUGDT,
		ACDOCA_AUGBL,
		ACDOCA_CPUDT,ACDOCA_CPUTM,
		LFBK_BANKN,REGUH_ZBNKN,
		ACDOCA_BUKRS_MAPPING ,T001_WAERS

--Step 6 Get the list of banks per JE number
-- Create this cube to check in the PTP process mining flow if it has change to bank or not

EXEC SP_DROPTABLE 'B11_SS02_06_IT_PTP_APA_PAY_ACCOUNT_LINE'

SELECT DISTINCT
ACDOCA_RBUKRS,
ACDOCA_GJAHR,
ACDOCA_BELNR,
 LFBK_BANKN,
 REGUH_ZBNKN
INTO B11_SS02_06_IT_PTP_APA_PAY_ACCOUNT_LINE
FROM B11_SS02_03_TT_PTP_APA_PAY_ADD_FIELD
LEFT JOIN 
 A_LFBK AS  D
ON ACDOCA_LIFNR=D.LFBK_LIFNR AND ACDOCA_BSEG_BVTYP=D.LFBK_BVTYP
LEFT JOIN  A_REGUH AS  C
ON 
	ACDOCA_RBUKRS=C.REGUH_ZBUKR AND 
	ACDOCA_GJAHR=YEAR(REGUH_LAUFD) AND
	ACDOCA_BELNR=C.REGUH_VBLNR


--Step 2 Rename the field
EXEC SP_RENAME_FIELD 'B11B_SS02_' ,B11_SS02_01_IT_PTP_APA
EXEC SP_RENAME_FIELD 'B11B_SS02_01_' ,B11_SS02_01_IT_PTP_APA_INV
EXEC SP_RENAME_FIELD 'B11B_SS02_02_' ,B11_SS02_02_IT_PTP_APA_PAY
EXEC SP_RENAME_FIELD 'B11B_SS02_05_' ,B11_SS02_05_IT_PTP_APA_PAY_GROUP
EXEC SP_DROPTABLE XTEMP


GO
