USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[B15_OTC_ARE_changes](@DBNAME as NVARCHAR(MAX))
AS
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B15_%'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B15_OTC_ARE_changes'
GO
