USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[B03_FIN_TRIAL_BALANCE](@DBNAME NVARCHAR(MAX))
AS
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B03_SS01_%'
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B03_SS02_%'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B03_FIN_TRIAL_BALANCE'
	IF @DBNAME LIKE '%SIE%' 
		BEGIN
			EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B03_S001_FIN_TRIAL_BALANCE_SUMMARY_SIE'
		END
	ELSE
		BEGIN
			EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B03_S001_FIN_TRIAL_BALANCE_SUMMARY'
		END
	
	
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B03_SS01_TRIAL_BALANCE_RATIO'
	--EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B03_SS02_M_SCORE'
	
GO
