USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROC [dbo].[DV13_QLIK_AR_OVERVIEW_VS_SAP_FBL5N](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_DV13_QLIK_AR_OVERVIEW_VS_SAP_FBL5N'
GO
