USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[SP_AR_ML_PRED]

AS

--DYNAMIC_SCRIPT_START
DECLARE @output_data_1_name NVARCHAR(128)  
DECLARE @inquery NVARCHAR(MAX)    
DECLARE @python_script NVARCHAR(MAX)
DECLARE @ML_package NVARCHAR(50)

EXEC SP_DROPTABLE 'B07_11_AR_PRED_OUTPUT'

SELECT *,  
		ROW_NUMBER ( ) OVER (ORDER BY ZF_AR_DOC_TYPE_BUCKET) AS ID,     
		IIF(1 < 0, ZF_AR_DOC_TYPE_BUCKET, '') ZF_FLAG_SUMMARY_PREDICT  
		--IIF(1 < 0, ZF_AR_DOC_TYPE_BUCKET, '') ML_BASED  
INTO B07_11_AR_PRED_OUTPUT  
FROM B07_01_RT_FIN_AR_INV_PAY_FLAGS    
WHERE ZF_AR_DOC_TYPE_BUCKET = '' OR ML_BASED = 'Y'

EXEC SP_DROPTABLE 'B07_11_RT_PRED'  

SELECT TOP 0 ID, ZF_FLAG_SUMMARY_PREDICT 
	INTO B07_11_RT_PRED 
FROM B07_11_AR_PRED_OUTPUT    

SET @inquery= 'SELECT ID, BSAID_BUKRS + '' '' + BSAID_BSCHL + '' '' + BSAID_BLART AS MERGE_FEATURES, BSAID_BUKRS, BSAID_BSCHL, BSAID_BLART FROM B07_11_AR_PRED_OUTPUT'

IF DB_NAME() like '%SOLA%' SET @ML_package = 'SOLA_AR_ML_PACKAGE.pkl'
ELSE SET @ML_package = 'GENERIC_AR_ML_PACKAGE.pkl'

SET @python_script = N'
import pickle

import sys
sys.path.insert(0, "F:\\09_MACHINE_LEARNING_MATERIAL")
import support_class_def

class CustomUnpickler(pickle.Unpickler):
	def find_class(self, module, name):
		if name == "ColumnSelector":
			from support_class_def import ColumnSelector
			return ColumnSelector
		if name == "preprocessor":
			from support_class_def import preprocessor
			return preprocessor.preprocessor
		if name == "tokenizer_porter":
			from support_class_def import preprocessor
			return preprocessor.tokenizer_porter
		return super().find_class(module, name)


pipeline = CustomUnpickler(open("F:\\09_MACHINE_LEARNING_MATERIAL\\' + @ML_package +'", "rb")).load()  
X = InputDataSet[["MERGE_FEATURES", "BSAID_BUKRS", "BSAID_BSCHL", "BSAID_BLART"]]  
y_pred = pipeline.predict(X)  
print(y_pred)  
InputDataSet["ZF_FLAG_SUMMARY_PREDICT"] = y_pred  
InputDataSet.fillna("")  
OutputDataSet = InputDataSet[["ID", "ZF_FLAG_SUMMARY_PREDICT"]]'

INSERT INTO B07_11_RT_PRED(ID, ZF_FLAG_SUMMARY_PREDICT)
EXEC sp_execute_external_script
  @language = N'Python',
  @script = @python_script,
@input_data_1 = @inquery,    
@input_data_1_name = N'InputDataSet'

UPDATE B07_11_AR_PRED_OUTPUT  
SET ZF_FLAG_SUMMARY_PREDICT = B07_11_RT_PRED.ZF_FLAG_SUMMARY_PREDICT,   
ZF_AR_DOC_TYPE_BUCKET = B07_11_RT_PRED.ZF_FLAG_SUMMARY_PREDICT,   
ML_BASED = 'Y'
FROM B07_11_AR_PRED_OUTPUT  
LEFT JOIN B07_11_RT_PRED ON B07_11_RT_PRED.ID = B07_11_AR_PRED_OUTPUT.ID


DELETE AM_B07_03_RT
WHERE ZF_AR_DOC_TYPE_BUCKET = '' OR ML_BASED = 'Y'

INSERT INTO AM_B07_03_RT
			(ZF_AR_DOC_TYPE_BUCKET, ML_BASED, BSAID_BUKRS, BSAID_SHKZG, BSAID_BSCHL, BSAID_BLART ,T003T_LTEXT, BKPF_TCODE, TSTCT_TTEXT, ZF_DEBIT_ACCOUNTS,
			ZF_CREDIT_ACCOUNTS,ZF_DEBIT_ACCOUNT_TEXTS, ZF_CREDIT_ACCOUNT_TEXTS, ZF_BANK_DEBIT_ACCOUNTS, ZF_BANK_CREDIT_ACCOUNTS,
			ZF_BS_DEBIT_ACCOUNTS, ZF_BS_CREDIT_ACCOUNTS, ZF_PL_DEBIT_ACCOUNTS, ZF_PL_CREDIT_ACCOUNTS, ZF_SU_DEBIT_ACCOUNTS, ZF_SU_CREDIT_ACCOUNTS,
			ZF_CU_DEBIT_ACCOUNTS, ZF_CU_CREDIT_ACCOUNTS, ZF_LIST_CSKT_KOSTL, ZF_LIST_CSKT_KTEXT)

SELECT ZF_FLAG_SUMMARY_PREDICT, ML_BASED, BSAID_BUKRS, BSAID_SHKZG, BSAID_BSCHL, BSAID_BLART ,T003T_LTEXT, BKPF_TCODE, TSTCT_TTEXT, ZF_DEBIT_ACCOUNTS,
			ZF_CREDIT_ACCOUNTS, ZF_DEBIT_ACCOUNT_TEXTS, ZF_CREDIT_ACCOUNT_TEXTS, ZF_BANK_DEBIT_ACCOUNTS, ZF_BANK_CREDIT_ACCOUNTS,
			ZF_BS_DEBIT_ACCOUNTS, ZF_BS_CREDIT_ACCOUNTS, ZF_PL_DEBIT_ACCOUNTS, ZF_PL_CREDIT_ACCOUNTS, ZF_SU_DEBIT_ACCOUNTS, ZF_SU_CREDIT_ACCOUNTS,
			ZF_CU_DEBIT_ACCOUNTS, ZF_CU_CREDIT_ACCOUNTS, ZF_LIST_CSKT_KOSTL, ZF_LIST_CSKT_KTEXT

FROM B07_11_AR_PRED_OUTPUT


UPDATE AM_B07_03_RT
SET ZF_AP_DOCUMENT = IIF(ZF_AR_DOC_TYPE_BUCKET = 'AP document', 'X', ''),
ZF_ADVANCE_PAYMENT = IIF(ZF_AR_DOC_TYPE_BUCKET = 'Advance payment', 'X', ''),
ZF_UNALLOCATED_CASH = IIF(ZF_AR_DOC_TYPE_BUCKET = 'Unallocated cash', 'X', ''),
ZF_CREDIT_NOTE = IIF(ZF_AR_DOC_TYPE_BUCKET = 'Credit note', 'X', ''),
ZF_INVOICE = IIF(ZF_AR_DOC_TYPE_BUCKET = 'Invoice', 'X', ''),
ZF_PARTIAL_INVOICE = IIF(ZF_AR_DOC_TYPE_BUCKET = 'Partially settled invoice', 'X', ''),
ZF_OTHERS = IIF(ZF_AR_DOC_TYPE_BUCKET = 'Others', 'X', ''),
ZF_NO_FLAG = IIF(ZF_AR_DOC_TYPE_BUCKET = 'No flag', 'X', '')

UPDATE AM_B07_03_RT
SET ZF_AR_LIFE_CYCLE_BUCKET_TYPE = (SELECT TOP 1 B.ZF_AR_LIFE_CYCLE_BUCKET_TYPE FROM AM_B07_03_RT B WHERE B.ZF_AP_DOCUMENT = AM_B07_03_RT.ZF_AP_DOCUMENT AND B.ZF_AR_LIFE_CYCLE_BUCKET_TYPE IS NOT NULL),
ZF_AR_LIFE_CYCLE_MAPPING_LABEL  = (SELECT TOP 1 B.ZF_AR_LIFE_CYCLE_MAPPING_LABEL FROM AM_B07_03_RT B WHERE B.ZF_AP_DOCUMENT = AM_B07_03_RT.ZF_AP_DOCUMENT AND B.ZF_AR_LIFE_CYCLE_MAPPING_LABEL IS NOT NULL)
FROM AM_B07_03_RT
WHERE AM_B07_03_RT.ZF_AR_LIFE_CYCLE_BUCKET_TYPE IS NULL
GO
