USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Object:  StoredProcedure [dbo].[script_B07_FIN_AR_AUTOMAPPING]    Script Date: 8/18/2023 8:18:36 PM ******/
CREATE   PROCEDURE [dbo].[script_B07_FIN_AR_AUTOMAPPING]

AS

--DYNAMIC_SCRIPT_START

/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END

--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL

	/* Initialize parameters from globals table */
    DECLARE  
				@CURRENCY NVARCHAR(3)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
				,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
				,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
				,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
				,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
				,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
				,@LANGUAGE1 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
				,@LANGUAGE2 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
				,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
				,@FISCAL_YEAR_FROM NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_FROM')
				,@FISCAL_YEAR_TO NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_TO')
                 SET DATEFORMAT @DATEFORMAT;

  /*Change history comments*/

  /*
    Title     : [B07B_FIN_AP_DOC_TYPES_FILL_BUCKET]
    Description     : Table updated by this script: B07_02_RT_FIN_AP_INV_PAY_FLAGS
              - DV06 should be reloaded after running this script
              Table produced by this script: B07_02_IT
              Table is used to create the P2P cube
    
    --------------------------------------------------------------
    Update history
    --------------------------------------------------------------
    Date          | Who     | Description
    DD-MM-YYYY        Initials    Initial version
    27-11-2020        Vinh Le     Create first version of AR mapping automatically
	15-08-2024		  Nam		  Remove fields from BSEG

	
  */


			
	  /*Test mode*/

	  SET ROWCOUNT @LIMIT_RECORDS


	  /*
		  Step 1: Create a summary table before we flag the AP document with categories to we can check the mapping easier because it have less record than full AR documents tables.
	  */
	  EXEC SP_REMOVE_TABLES 'B07_01_TT_FIN_AR_INV_PAY_FLAGS'
	  SELECT DISTINCT
			B04_13_IT_AR_ACC_SCH.BKPF_TCODE,
			B04_13_IT_AR_ACC_SCH.ACDOCA_AWTYP,
			B04_13_IT_AR_ACC_SCH.KNA1_KTOKD,
            B04_13_IT_AR_ACC_SCH.ZF_DOC_CLEARING_FLAG,
			B04_13_IT_AR_ACC_SCH.ZF_DEBIT_ACCOUNT_TYPES,
			B04_13_IT_AR_ACC_SCH.ZF_CREDIT_ACCOUNT_TYPES,
			B04_13_IT_AR_ACC_SCH.ZF_DEBIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST,
			B04_13_IT_AR_ACC_SCH.ZF_CREDIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST,
			B04_13_IT_AR_ACC_SCH.ZF_DEBIT_SKA1_GVTYP_FLAG_LIST,
			B04_13_IT_AR_ACC_SCH.ZF_CREDIT_SKA1_GVTYP_FLAG_LIST,
			B04_13_IT_AR_ACC_SCH.ZF_LIFNR_KUNNR_IS_SAME_FLAG,
			ZF_DEBIT_ACCT_IS_AR_CLEARING,
			ZF_CREDIT_ACCT_IS_AR_CLEARING,
		    SUBSTRING(ZF_CREDIT_ACCOUNTS,1, IIF(CHARINDEX('_',ZF_CREDIT_ACCOUNTS)=0,LEN(ZF_CREDIT_ACCOUNTS),CHARINDEX('_',ZF_CREDIT_ACCOUNTS)-1)) AS ZF_FIRST_CREDIT_ACCOUNT,
	        SUBSTRING(ZF_DEBIT_ACCOUNTS,1, IIF(CHARINDEX('_',ZF_DEBIT_ACCOUNTS)=0,LEN(ZF_DEBIT_ACCOUNTS),CHARINDEX('_',ZF_DEBIT_ACCOUNTS)-1)) AS ZF_FIRST_DEBIT_ACCOUNT,
			'Y' AS UNCLASSIFIED_FLAG
	  INTO B07_01_TT_FIN_AR_INV_PAY_FLAGS
	  FROM B04_13_IT_AR_ACC_SCH



	  /*
		Step 2: Add AR document type columns with default value is "Other". It will be update later
	  */

		ALTER TABLE B07_01_TT_FIN_AR_INV_PAY_FLAGS ADD ZF_AR_LIFE_CYCLE_BUCKET_TYPE NVARCHAR(1) DEFAULT 'G' WITH VALUES;
		ALTER TABLE B07_01_TT_FIN_AR_INV_PAY_FLAGS ADD ZF_AR_LIFE_CYCLE_MAPPING_LABEL NVARCHAR(100) DEFAULT 'Others' WITH VALUES;
		ALTER TABLE B07_01_TT_FIN_AR_INV_PAY_FLAGS ADD ZF_AR_DOC_TYPE_BUCKET NVARCHAR(100) DEFAULT 'Others' WITH  VALUES;
		ALTER TABLE B07_01_TT_FIN_AR_INV_PAY_FLAGS ADD ZF_CUS_INV NVARCHAR(1) DEFAULT '' WITH VALUES;
		ALTER TABLE B07_01_TT_FIN_AR_INV_PAY_FLAGS ADD ZF_CUS_INV_CANC NVARCHAR(1) DEFAULT '' WITH VALUES;
		ALTER TABLE B07_01_TT_FIN_AR_INV_PAY_FLAGS ADD ZF_CUS_PYMT NVARCHAR(1) DEFAULT '' WITH VALUES;
		ALTER TABLE B07_01_TT_FIN_AR_INV_PAY_FLAGS ADD ZF_CUS_PYMT_CANC NVARCHAR(1) DEFAULT '' WITH VALUES;
		ALTER TABLE B07_01_TT_FIN_AR_INV_PAY_FLAGS ADD ZF_OTHERS NVARCHAR(1) DEFAULT '' WITH VALUES;

	  /*
		Step 3: Update the AR document type base on ACL logic from Claire
		Khoi-- Add 2 AM tables, 
		-- AM_OTHER_ACCOUTS: These account should be used as Other
		--AM_AR_ACCOUNT : Jesper said some account actually AR, but the account type can be S, for these accoutn should see them as D
	  */
		  /*
			Step 3.1: Flag ar documents which have document type (BLART = ___ ) to Others bucket
		  */
			--Wating condition

		  /*
			Step 3.2: Flag all documents found in AM_OTHER_ACCOUTS tables
						 to "Others" bucket 
		  */
		  UPDATE B07_01_TT_FIN_AR_INV_PAY_FLAGS
		  SET ZF_AR_DOC_TYPE_BUCKET = 'Others', ZF_OTHERS = 'X', UNCLASSIFIED_FLAG = ''
		  WHERE UNCLASSIFIED_FLAG = 'Y' AND
						  (
			 ZF_FIRST_CREDIT_ACCOUNT IN ( SELECT SKAT_SAKNR FROM AM_OTHER_ACCOUTS)
			 OR
			 ZF_FIRST_DEBIT_ACCOUNT IN ( SELECT SKAT_SAKNR FROM AM_OTHER_ACCOUTS)
		  )
		  



		  /*
			Step 3.4: Flag all documents have
							Credit on (SKA1_GVTYP_BSEG <> "" OR  BSEG_KOART = S) AND NOT(ZF_BSEG_HKONT_PAYFLAG) AND BSAK_XANET ="" 
							Debit on account type 'D'
							BELNR <> AUGBL
							AWTYP = 'VBRK'
						  to Customer invoice
		  */
		  UPDATE B07_01_TT_FIN_AR_INV_PAY_FLAGS
		  SET ZF_AR_DOC_TYPE_BUCKET = 'Customer invoice',
			  ZF_CUS_INV = 'X',
			  UNCLASSIFIED_FLAG = '',
			  ZF_AR_LIFE_CYCLE_BUCKET_TYPE = 'B',
			  ZF_AR_LIFE_CYCLE_MAPPING_LABEL = 'Open Invoices'
		  WHERE UNCLASSIFIED_FLAG = 'Y'
				AND (
						(
							LEFT(ZF_CREDIT_SKA1_GVTYP_FLAG_LIST, 1) <> '_' OR
							(
								LEFT(ZF_CREDIT_ACCOUNT_TYPES, 1) = 'S' AND
							    ZF_FIRST_CREDIT_ACCOUNT NOT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT)
							)

						)
						AND (
								LEFT(ZF_CREDIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, 1) <> 'Y'
							AND LEFT(ZF_CREDIT_ACCT_IS_AR_CLEARING,1) <>'Y' 
							)
						AND 
							( 
								LEFT(ZF_DEBIT_ACCOUNT_TYPES, 1) = 'D' OR
								(
									ZF_FIRST_DEBIT_ACCOUNT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT WHERE ZF_AR_ACCOUNT='X') AND
									LEFT(ZF_DEBIT_ACCOUNT_TYPES, 1) <> 'D'
								)
							)
						AND ACDOCA_AWTYP = 'VBRK'
				 )


		  UPDATE B07_01_TT_FIN_AR_INV_PAY_FLAGS
		  SET ZF_AR_DOC_TYPE_BUCKET = 'Customer invoice',
			  ZF_CUS_INV = 'X',
			  UNCLASSIFIED_FLAG = '',
			  ZF_AR_LIFE_CYCLE_BUCKET_TYPE = 'B',
			  ZF_AR_LIFE_CYCLE_MAPPING_LABEL = 'Open Invoices'
		  WHERE UNCLASSIFIED_FLAG = 'Y'
				AND (
			          (  ZF_DEBIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST NOT LIKE '%Y%'
						AND ZF_CREDIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST NOT LIKE '%Y%' )
				AND
					(
						ZF_DEBIT_ACCT_IS_AR_CLEARING NOT LIKE '%Y%' AND
						ZF_CREDIT_ACCT_IS_AR_CLEARING NOT LIKE '%Y%'
					)
						AND 
							(
								LEFT(ZF_DEBIT_ACCOUNT_TYPES, 1) = 'D' OR
								(
									ZF_FIRST_DEBIT_ACCOUNT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT WHERE ZF_AR_ACCOUNT='X')
									AND LEFT(ZF_DEBIT_ACCOUNT_TYPES, 1) <> 'D'
								)
							 )
						AND ACDOCA_AWTYP = 'VBRK'
					
				 )



		  /*
			Step 3.5: Flag all documents have
							Credit on account type 'D'
							Debit on (SKA1_GVTYP_BSEG<> "" OR  BSEG_KOART = S) AND NOT(ZF_BSEG_HKONT_PAYFLAG) AND BSAK_XANET ="" 
							AUGBL <> BELNR
							AWTYP = VBRK
						  to Customer invoice cancellation/Credit note
		  */
		  UPDATE B07_01_TT_FIN_AR_INV_PAY_FLAGS
		  SET ZF_AR_DOC_TYPE_BUCKET = 'Credit note',
			  ZF_CUS_INV_CANC = 'X',
			  UNCLASSIFIED_FLAG = '',
			  ZF_AR_LIFE_CYCLE_BUCKET_TYPE = 'E',
			  ZF_AR_LIFE_CYCLE_MAPPING_LABEL = 'Credit note'
		  WHERE UNCLASSIFIED_FLAG = 'Y'
				AND (
						(
							LEFT(ZF_CREDIT_ACCOUNT_TYPES, 1) = 'D' OR
							(
								ZF_FIRST_CREDIT_ACCOUNT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT WHERE ZF_AR_ACCOUNT='X') AND 
								LEFT(ZF_CREDIT_ACCOUNT_TYPES, 1) <> 'D'
							)
						)
						AND (
							LEFT(ZF_DEBIT_SKA1_GVTYP_FLAG_LIST, 1) <> '_' OR
							(
								LEFT(ZF_DEBIT_ACCOUNT_TYPES, 1) = 'S' AND
								ZF_FIRST_DEBIT_ACCOUNT NOT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT WHERE ZF_AR_ACCOUNT='X')
							)
						)
			           AND 
						(
							(
								ZF_DEBIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST NOT LIKE '%Y%' AND
						        ZF_CREDIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST NOT LIKE '%Y%'
							) AND
							(
								ZF_DEBIT_ACCT_IS_AR_CLEARING NOT LIKE '%Y%' AND
								ZF_CREDIT_ACCT_IS_AR_CLEARING NOT LIKE '%Y%'								
							)
						)
						AND ACDOCA_AWTYP = 'VBRK'
						)


		  /*
			Step 3.6: Flag all documents have
							Credit on BSEG_KOART = D
							Debit on ZF_BSEG_HKONT_PAYFLAG OR BSAK_XANET <> ""
							AWTYP <> VBRK
						  to Supplier payment
		  */
		  UPDATE B07_01_TT_FIN_AR_INV_PAY_FLAGS
		  SET ZF_AR_DOC_TYPE_BUCKET = 'Customer payment',
		      ZF_CUS_PYMT = 'X',
			  UNCLASSIFIED_FLAG = '',
			  ZF_AR_LIFE_CYCLE_BUCKET_TYPE = 'D',
			  ZF_AR_LIFE_CYCLE_MAPPING_LABEL = 'Cash payment'
		  WHERE UNCLASSIFIED_FLAG = 'Y'
				AND (
						(
							LEFT(ZF_CREDIT_ACCOUNT_TYPES, 1) = 'D' OR
							(
								LEFT(ZF_CREDIT_ACCOUNT_TYPES, 1) <> 'D' OR
								ZF_FIRST_CREDIT_ACCOUNT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT WHERE ZF_AR_ACCOUNT='X')
							)
						)
					AND (
							LEFT(ZF_DEBIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, 1) = 'Y'
							OR LEFT(ZF_DEBIT_ACCT_IS_AR_CLEARING,1)='Y'
						)
					AND ACDOCA_AWTYP <> 'VBRK'
					
				)

		  /*
			Step 3.7: Flag all documents have
							Credit on ZF_BSEG_HKONT_PAYFLAG OR BSAK_XANET <> "" 
							Debit on BSEG_KOART = D
							AWTYP <> VBRK
						  to Customer payment cancellation
		  */
		  UPDATE B07_01_TT_FIN_AR_INV_PAY_FLAGS
		  SET ZF_AR_DOC_TYPE_BUCKET = 'Customer payment cancellation',
		      ZF_CUS_PYMT_CANC = 'X',
			  UNCLASSIFIED_FLAG = '',
			  ZF_AR_LIFE_CYCLE_BUCKET_TYPE = 'F',
			  ZF_AR_LIFE_CYCLE_MAPPING_LABEL = 'Deductions'
		  WHERE UNCLASSIFIED_FLAG = 'Y'
				AND (
					    (
							LEFT(ZF_CREDIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, 1) = 'Y'
							OR LEFT(ZF_CREDIT_ACCT_IS_AR_CLEARING,1)='Y'
						)
						AND
							(
								LEFT(ZF_DEBIT_ACCOUNT_TYPES, 1 ) = 'D' OR
								(
									LEFT(ZF_DEBIT_ACCOUNT_TYPES, 1) <> 'D' OR
									ZF_FIRST_DEBIT_ACCOUNT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT WHERE ZF_AR_ACCOUNT='X')
								)
							)
						AND ACDOCA_AWTYP <> 'VBRK'					
				)
		  /*
			Step 3.8: Flag all documents have
							Credit on (SKA1_GVTYP_BSEG <> "" OR  BSEG_KOART = S) AND NOT(ZF_BSEG_HKONT_PAYFLAG) AND BSAK_XANET ="" 
							Debit on account type 'D'
						  to Customer invoice
		  */
		  UPDATE B07_01_TT_FIN_AR_INV_PAY_FLAGS
		  SET ZF_AR_DOC_TYPE_BUCKET = 'Customer invoice',
		      ZF_CUS_INV = 'X',
			  UNCLASSIFIED_FLAG = '',
			  ZF_AR_LIFE_CYCLE_BUCKET_TYPE = 'B',
		      ZF_AR_LIFE_CYCLE_MAPPING_LABEL = 'Open Invoices'
		  WHERE UNCLASSIFIED_FLAG = 'Y'
				AND (
						(
							LEFT(ZF_CREDIT_SKA1_GVTYP_FLAG_LIST, 1) <> '_' OR
							(
								LEFT(ZF_CREDIT_ACCOUNT_TYPES, 1) = 'S' AND
								ZF_FIRST_CREDIT_ACCOUNT NOT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT WHERE ZF_AR_ACCOUNT='X')
								)
						)
						AND LEFT(ZF_CREDIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, 1) <> 'Y'
						AND LEFT(ZF_CREDIT_ACCT_IS_AR_CLEARING,1)<>'Y'
						AND 
							(
								LEFT(ZF_DEBIT_ACCOUNT_TYPES, 1) = 'D' OR
								(
									LEFT(ZF_DEBIT_ACCOUNT_TYPES, 1) <> 'D' OR
									ZF_FIRST_DEBIT_ACCOUNT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT WHERE ZF_AR_ACCOUNT='X')
								)
								
							)
				 )

		  /*
			Step 3.5: Flag all documents have
							Credit on account type 'D'
							Debit on (SKA1_GVTYP_BSEG<> "" OR  BSEG_KOART = S) AND NOT(ZF_BSEG_HKONT_PAYFLAG) AND BSAK_XANET ="" 
						  to Customer invoice cancellation/Credit note
		  */
		  UPDATE B07_01_TT_FIN_AR_INV_PAY_FLAGS
		  SET ZF_AR_DOC_TYPE_BUCKET = 'Credit note',
		      ZF_CUS_INV_CANC = 'X',
			  UNCLASSIFIED_FLAG = '',
			  ZF_AR_LIFE_CYCLE_BUCKET_TYPE = 'E',
		      ZF_AR_LIFE_CYCLE_MAPPING_LABEL = 'Credit note'
		  WHERE UNCLASSIFIED_FLAG = 'Y'
				AND (
						(
							LEFT(ZF_CREDIT_ACCOUNT_TYPES, 1) = 'D' OR
							(
									LEFT(ZF_CREDIT_ACCOUNT_TYPES, 1) <> 'D' OR
									ZF_FIRST_CREDIT_ACCOUNT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT WHERE ZF_AR_ACCOUNT='X')
							)
						)
						AND (
							LEFT(ZF_DEBIT_SKA1_GVTYP_FLAG_LIST, 1) <> '_' OR
							(
								LEFT(ZF_DEBIT_ACCOUNT_TYPES, 1) = 'S' AND
								ZF_FIRST_DEBIT_ACCOUNT NOT IN (SELECT ACDOCA_RACCT FROM AM_AR_ACCOUNT WHERE ZF_AR_ACCOUNT='X')
							)
						)
						AND LEFT(ZF_DEBIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, 1) <> 'Y'
						AND LEFT(ZF_DEBIT_ACCT_IS_AR_CLEARING,1)<>'Y'
				 )

		  /*
			Step 3.10: Flag the rest documents to others
		  */
		  UPDATE B07_01_TT_FIN_AR_INV_PAY_FLAGS
		  SET ZF_AR_DOC_TYPE_BUCKET = 'Others', ZF_OTHERS = 'X'
		  WHERE  UNCLASSIFIED_FLAG = 'Y'


	/*
		Step 4: Join the summary table after flaged all AR docuement to categories back to full AR document cube.
	*/

	EXEC SP_REMOVE_TABLES 'B07_03_IT_FIN_AR_INV_PAY_FLAGS'

	SELECT 
			B04_13_IT_AR_ACC_SCH.*,
			B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_AR_LIFE_CYCLE_BUCKET_TYPE,
			B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_AR_LIFE_CYCLE_MAPPING_LABEL,
			B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_AR_DOC_TYPE_BUCKET,
			B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_CUS_INV,
			B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_CUS_INV_CANC,
			B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_CUS_PYMT,
			B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_CUS_PYMT_CANC,
			B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_OTHERS
	INTO B07_03_IT_FIN_AR_INV_PAY_FLAGS
	FROM B04_13_IT_AR_ACC_SCH
	LEFT JOIN B07_01_TT_FIN_AR_INV_PAY_FLAGS
	ON 
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.BKPF_TCODE, '') = ISNULL(B04_13_IT_AR_ACC_SCH.BKPF_TCODE, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ACDOCA_AWTYP, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ACDOCA_AWTYP, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.KNA1_KTOKD, '') = ISNULL(B04_13_IT_AR_ACC_SCH.KNA1_KTOKD, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_DOC_CLEARING_FLAG, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ZF_DOC_CLEARING_FLAG, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_DEBIT_ACCOUNT_TYPES, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ZF_DEBIT_ACCOUNT_TYPES, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_CREDIT_ACCOUNT_TYPES, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ZF_CREDIT_ACCOUNT_TYPES, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_DEBIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ZF_DEBIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_CREDIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ZF_CREDIT_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_DEBIT_SKA1_GVTYP_FLAG_LIST, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ZF_DEBIT_SKA1_GVTYP_FLAG_LIST, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_CREDIT_SKA1_GVTYP_FLAG_LIST, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ZF_CREDIT_SKA1_GVTYP_FLAG_LIST, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_LIFNR_KUNNR_IS_SAME_FLAG, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ZF_LIFNR_KUNNR_IS_SAME_FLAG, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_DEBIT_ACCT_IS_AR_CLEARING, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ZF_DEBIT_ACCT_IS_AR_CLEARING, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_CREDIT_ACCT_IS_AR_CLEARING, '') = ISNULL(B04_13_IT_AR_ACC_SCH.ZF_CREDIT_ACCT_IS_AR_CLEARING, '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_FIRST_CREDIT_ACCOUNT, '') = ISNULL(  SUBSTRING(ZF_CREDIT_ACCOUNTS,1, IIF(CHARINDEX('_',ZF_CREDIT_ACCOUNTS)=0,LEN(ZF_CREDIT_ACCOUNTS),CHARINDEX('_',ZF_CREDIT_ACCOUNTS)-1)), '') AND
		ISNULL(B07_01_TT_FIN_AR_INV_PAY_FLAGS.ZF_FIRST_DEBIT_ACCOUNT, '') = ISNULL(SUBSTRING(ZF_DEBIT_ACCOUNTS,1, IIF(CHARINDEX('_',ZF_DEBIT_ACCOUNTS)=0,LEN(ZF_DEBIT_ACCOUNTS),CHARINDEX('_',ZF_DEBIT_ACCOUNTS)-1)), '')

	EXEC SP_RENAME_FIELD 'B07D_', 'B07_03_IT_FIN_AR_INV_PAY_FLAGS'
	EXEC SP_REMOVE_TABLES '%_TT_%'
	
GO
