USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_DC14_SALE_ORDER_CUBE]
AS

--DYNAMIC_SCRIPT_START
/* Initiate the log */ 
----Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END
 
--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL
 
/* Initialize parameters from globals table */


DECLARE  
                      @CURRENCY NVARCHAR(MAX)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
                     ,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
                     ,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
                     ,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
                     ,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
                     ,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
                     ,@LANGUAGE1 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
                     ,@LANGUAGE2 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
                     ,@YEAR NVARCHAR(MAX)                     = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
                     ,@ID NVARCHAR(MAX)                       = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
                     ,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
					 ,@ZV_SAME_QUARTER_BY_BLDAT NVARCHAR(MAX) = ISNULL((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'ZV_SAME_QUARTER_BY_BLDAT'), '')



EXEC SP_DROPTABLE 'DC14_01_IT_SALE_DOCUMENTS'

SELECT 
	A.B28_VBAK_VBELN,
	A.B28_VBAP_POSNR,
	A.B28_TVKO_BUKRS,
	T001_WAERS,
	SUM(B.B28_ZF_VBAP_NETPR_S) AS B28_ZF_VBAP_NETPR_S,
	SUM(B.B28_ZF_VBAP_NETPR_S_CUC) AS B28_ZF_VBAP_NETPR_S_CUC_OLD,
	SUM(A.B28_ZF_VBAP_NETPR_S_CUC) AS B28_ZF_VBAP_NETPR_S_CUC_NEW,
	MAX(A.B28_VBAP_ERDAT) AS B28_VBAP_ERDAT,
	MAX(ISNULL(AM_EXCHNG.EXCHNG_RATIO, 1)) AS EXCH_RATE_NETPR_S_CUC_OLD,
	MAX(A_VBAP.VBAP_STCUR * COALESCE(TCURF_COC.TCURF_TFACT,1)/COALESCE(TCURF_COC.TCURF_FFACT,1) * COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1)) AS EXCH_RATE_NETPR_S_CUC_NEW,
	SUM(B.B28_ZF_VBAP_NETWR_S) AS B28_ZF_VBAP_NETWR_S,
	SUM(B.B28_ZF_VBAP_NETWR_S_CUC) AS B28_ZF_VBAP_NETWR_S_CUC_OLD,
	SUM(A.B28_ZF_VBAP_NETWR_S_CUC) AS B28_ZF_VBAP_NETWR_S_CUC_NEW,
	MAX(ISNULL(AM_EXCHNG.EXCHNG_RATIO, 1)) AS EXCH_RATE_NETWR_S_CUC_OLD,
	MAX(A_VBAP.VBAP_STCUR * COALESCE(TCURF_COC.TCURF_TFACT,1)/COALESCE(TCURF_COC.TCURF_FFACT,1) * COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1)) AS EXCH_RATE_NETWR_S_CUC_NEW
INTO DC14_01_IT_SALE_DOCUMENTS
FROM 
(
SELECT B28_VBAK_VBELN,
       B28_VBAP_POSNR,
	   B28_TVKO_BUKRS,
	   MAX(B28_VBAP_ERDAT) AS B28_VBAP_ERDAT,
	   MAX(B28_VBAP_WAERK) AS B28_VBAP_WAERK,
	   SUM(B28_ZF_VBAP_NETPR_S) AS B28_ZF_VBAP_NETPR_S,
	   SUM(B28_ZF_VBAP_NETPR_S_CUC) AS B28_ZF_VBAP_NETPR_S_CUC,
	   SUM(B28_ZF_VBAP_NETWR_S) AS B28_ZF_VBAP_NETWR_S,
	   SUM(B28_ZF_VBAP_NETWR_S_CUC) AS B28_ZF_VBAP_NETWR_S_CUC
FROM B28_01_IT_SALE_DOCUMENTS_NEW
GROUP BY B28_VBAK_VBELN,
       B28_VBAP_POSNR,
	   B28_TVKO_BUKRS
) A

INNER JOIN 
(
SELECT B28_VBAK_VBELN,
       B28_VBAP_POSNR,
	   B28_TVKO_BUKRS,
	   MAX(B28_VBAP_ERDAT) AS B28_VBAP_ERDAT,
	   SUM(B28_ZF_VBAP_NETPR_S) AS B28_ZF_VBAP_NETPR_S,
	   SUM(B28_ZF_VBAP_NETPR_S_CUC) AS B28_ZF_VBAP_NETPR_S_CUC,
	   SUM(B28_ZF_VBAP_NETWR_S) AS B28_ZF_VBAP_NETWR_S,
	   SUM(B28_ZF_VBAP_NETWR_S_CUC) AS B28_ZF_VBAP_NETWR_S_CUC
FROM B28_01_IT_SALE_DOCUMENTS 	 
GROUP BY B28_VBAK_VBELN,
       B28_VBAP_POSNR,
	   B28_TVKO_BUKRS
) B
	ON 
	A.B28_VBAP_POSNR = B.B28_VBAP_POSNR AND 
	A.B28_VBAK_VBELN = B.B28_VBAK_VBELN AND 
	A.B28_TVKO_BUKRS = B.B28_TVKO_BUKRS

LEFT JOIN A_VBAP
ON A.B28_VBAK_VBELN = VBAP_VBELN

LEFT JOIN A_T001
ON  A.B28_TVKO_BUKRS = A_T001.T001_BUKRS
--Get exchange rate to USD
LEFT JOIN AM_EXCHNG
ON A.B28_VBAP_WAERK = AM_EXCHNG.EXCHNG_FROM
AND AM_EXCHNG.EXCHNG_TO = @CURRENCY

LEFT JOIN AM_EXCHNG AM_EXCHNG_COC
ON T001_WAERS = AM_EXCHNG_COC.EXCHNG_FROM
AND AM_EXCHNG_COC.EXCHNG_TO = @CURRENCY

LEFT JOIN B00_IT_TCURF TCURF_CUC
ON A_T001.T001_WAERS = TCURF_CUC.TCURF_FCURR
AND TCURF_CUC.TCURF_TCURR  = @currency  
AND TCURF_CUC.TCURF_GDATU = (
	SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
	FROM B00_IT_TCURF
	WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
			B00_IT_TCURF.TCURF_TCURR  = @currency  AND
			B00_IT_TCURF.TCURF_GDATU <= A.B28_VBAP_ERDAT
	ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
	)
-- Add exchange rate from company currency to USD
LEFT JOIN B00_IT_TCURR TCURR_CUC
	ON A_T001.T001_WAERS = TCURR_CUC.TCURR_FCURR
	AND TCURR_CUC.TCURR_TCURR  = @currency  
	AND TCURR_CUC.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.B28_VBAP_ERDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 

-- Add currency factor from document currency to local currency

LEFT JOIN B00_IT_TCURF TCURF_COC
ON A.B28_VBAP_WAERK = TCURF_COC.TCURF_FCURR
AND TCURF_COC.TCURF_TCURR  = T001_WAERS  
AND TCURF_COC.TCURF_GDATU = (
	SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
	FROM B00_IT_TCURF
	WHERE A.B28_VBAP_WAERK = B00_IT_TCURF.TCURF_FCURR AND 
			B00_IT_TCURF.TCURF_TCURR  = T001_WAERS  AND
			B00_IT_TCURF.TCURF_GDATU <= A.B28_VBAP_ERDAT
	ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
	)
GROUP BY 
	A.B28_VBAK_VBELN,
	A.B28_VBAP_POSNR,
	A.B28_TVKO_BUKRS,
	T001_WAERS



EXEC SP_UNNAME_FIELD 'B28_',DC14_01_SALE_DOCUMENTS
EXEC SP_RENAME_FIELD 'DC14_01_',DC14_01_SALE_DOCUMENTS


GO
