USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROC [dbo].[DC10_OPEN_POs_GR_INV](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_DC10_OPEN_POs_GR_INV'
GO
