USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[script_DC02_FIN_GENERAL_LEDGER]

WITH EXECUTE AS CALLER
AS

--DYNAMIC_SCRIPT_START
/* Initiate the log */ 
----Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END
 
--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL
 
/* Initialize parameters from globals table */
    DECLARE  
				@CURRENCY NVARCHAR(3)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
				,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
				,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
				,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
				,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
				,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
				,@LANGUAGE1 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
				,@LANGUAGE2 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
				,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
				,@FISCAL_YEAR_FROM NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_FROM')
				,@FISCAL_YEAR_TO NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_TO')
                 SET DATEFORMAT @DATEFORMAT;


--Step 1/ Compare values (USD) between table B04_08_IT_FIN_GL_NEW (use TCURR and TCURF) and table B04_08_IT_FIN_GL (use AM_EXCHNG)


EXEC SP_DROPTABLE 'DC02_01_IT_FIN_GL'
SELECT 
       A.B04_GL_ACDOCA_RBUKRS AS B04_GL_ACDOCA_RBUKRS,
	   A.B04_GL_ACDOCA_GJAHR AS B04_GL_ACDOCA_GJAHR,
	   A.B04_GL_ACDOCA_BELNR AS B04_GL_ACDOCA_BELNR,
	   MAX(A.B04_GL_ACDOCA_RHCUR) AS B04_GL_ACDOCA_RHCUR,
	   MAX(A.B04_GL_ACDOCA_BUDAT) AS B04_GL_ACDOCA_BUDAT,
	   SUM(B.B04_GL_ZF_ACDOCA_HSL_S) AS B04_GL_ZF_ACDOCA_HSL_S,
	   ROUND(SUM(A.B04_GL_ZF_ACDOCA_HSL_S_CUC),3) AS B04_GL_ZF_ACDOCA_HSL_S_CUC_NEW,
	   SUM(B.B04_GL_ZF_ACDOCA_HSL_S_CUC) AS B04_GL_ZF_ACDOCA_HSL_S_CUC_OLD,
	   MAX(EXCHNG_RATIO) AS EXCHNG_RATE_OLD,
	   MAX(COALESCE(CAST(B00_IT_TCURR.TCURR_UKURS AS FLOAT),1) * COALESCE(B00_IT_TCURF.TCURF_TFACT,1) / COALESCE(B00_IT_TCURF.TCURF_FFACT,1)) AS EXCHNG_RATE_NEW 
INTO DC02_01_IT_FIN_GL
FROM (SELECT
		    B04_GL_ACDOCA_RBUKRS,
		    B04_GL_ACDOCA_GJAHR,
		    B04_GL_ACDOCA_BELNR,
		    MAX(B04_GL_ACDOCA_RHCUR) AS B04_GL_ACDOCA_RHCUR,
		    MAX(B04_GL_ACDOCA_BUDAT) AS B04_GL_ACDOCA_BUDAT,
			SUM(B04_GL_ZF_ACDOCA_HSL_S) AS B04_GL_ZF_ACDOCA_HSL_S,
			SUM(B04_GL_ZF_ACDOCA_HSL_S_CUC) AS B04_GL_ZF_ACDOCA_HSL_S_CUC
     FROM B04_08_IT_FIN_GL_NEW
	 GROUP BY	    B04_GL_ACDOCA_RBUKRS,
					B04_GL_ACDOCA_GJAHR,
					B04_GL_ACDOCA_BELNR) A

INNER JOIN (SELECT
		    B04_GL_ACDOCA_RBUKRS,
		    B04_GL_ACDOCA_GJAHR,
		    B04_GL_ACDOCA_BELNR,
		    MAX(B04_GL_ACDOCA_RHCUR) AS B04_GL_ACDOCA_RHCUR,
		    MAX(B04_GL_ACDOCA_BUDAT) AS B04_GL_ACDOCA_BUDAT,
			SUM(B04_GL_ZF_ACDOCA_HSL_S) AS B04_GL_ZF_ACDOCA_HSL_S,
			SUM(B04_GL_ZF_ACDOCA_HSL_S_CUC) AS B04_GL_ZF_ACDOCA_HSL_S_CUC
     FROM B04_08_IT_FIN_GL
	 GROUP BY	    B04_GL_ACDOCA_RBUKRS,
					B04_GL_ACDOCA_GJAHR,
					B04_GL_ACDOCA_BELNR) B
ON A.B04_GL_ACDOCA_RBUKRS = B.B04_GL_ACDOCA_RBUKRS
AND A.B04_GL_ACDOCA_GJAHR = B.B04_GL_ACDOCA_GJAHR
AND A.B04_GL_ACDOCA_BELNR = B.B04_GL_ACDOCA_BELNR
        
LEFT JOIN A_T001
	ON  A_T001.T001_BUKRS = A.B04_GL_ACDOCA_RBUKRS
        
--Add exchange rate for house currency
LEFT JOIN AM_EXCHNG
ON     (a.B04_GL_ACDOCA_RHCUR = AM_EXCHNG.EXCHNG_FROM) AND
        (AM_EXCHNG.EXCHNG_TO = @currency)

-- Add currency factor from company currency to USD

LEFT JOIN B00_IT_TCURF
ON A.B04_GL_ACDOCA_RHCUR = B00_IT_TCURF.TCURF_FCURR
AND B00_IT_TCURF.TCURF_TCURR  = @currency  
AND B00_IT_TCURF.TCURF_GDATU = (
	SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
	FROM B00_IT_TCURF
	WHERE A.B04_GL_ACDOCA_RHCUR = B00_IT_TCURF.TCURF_FCURR AND 
			B00_IT_TCURF.TCURF_TCURR  = @currency  AND
			B00_IT_TCURF.TCURF_GDATU <= A.B04_GL_ACDOCA_BUDAT
	ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
	)
-- Add exchange rate from company currency to USD
LEFT JOIN B00_IT_TCURR
ON A.B04_GL_ACDOCA_RHCUR = B00_IT_TCURR.TCURR_FCURR
AND B00_IT_TCURR.TCURR_TCURR  = @currency  
AND B00_IT_TCURR.TCURR_GDATU = (
	SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
	FROM B00_IT_TCURR
	WHERE A.B04_GL_ACDOCA_RHCUR = B00_IT_TCURR.TCURR_FCURR AND 
			B00_IT_TCURR.TCURR_TCURR  = @currency  AND
			B00_IT_TCURR.TCURR_GDATU <= A.B04_GL_ACDOCA_BUDAT
	ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
	) 
GROUP BY A.B04_GL_ACDOCA_RBUKRS,
	   A.B04_GL_ACDOCA_GJAHR,
	   A.B04_GL_ACDOCA_BELNR


EXEC SP_UNNAME_FIELD 'B04_GL_',DC02_01_IT_FIN_GL

EXEC SP_RENAME_FIELD 'DC02_01_',DC02_01_IT_FIN_GL

--Step 2/ Compare values (USD) between table B04_11_IT_AP_ACC_SCH_NEW (use TCURR and TCURF) and table B04_11_IT_AP_ACC_SCH (use AM_EXCHNG)
 
EXEC SP_DROPTABLE 'DC02_02_IT_AR_ACC_SCH'

SELECT 
		A.ACDOCA_RBUKRS,
		A.ACDOCA_GJAHR,
		A.ACDOCA_BELNR,
		MAX(A.ACDOCA_RHCUR) AS ACDOCA_RHCUR,
		MAX(A.ACDOCA_BUDAT) AS ACDOCA_BUDAT,
		MAX(COALESCE (EXCHNG_RATIO,1)) AS EXCHNG_RATE_OLD,
		MAX(COALESCE(CAST(B00_IT_TCURR.TCURR_UKURS AS FLOAT),1) * COALESCE(B00_IT_TCURF.TCURF_TFACT,1) / COALESCE(B00_IT_TCURF.TCURF_FFACT,1)) AS EXCHNG_RATE_NEW,
		SUM(A.ZF_ACDOCA_HSL_S) AS ZF_ACDOCA_HSL_S,
		SUM(B.ZF_ACDOCA_HSL_S_CUC) AS ZF_ACDOCA_HSL_S_CUC_OLD,
		ROUND(SUM(A.ZF_ACDOCA_HSL_S_CUC),3) AS ZF_ACDOCA_HSL_S_CUC_NEW
INTO DC02_02_IT_AR_ACC_SCH
FROM
(
	SELECT
		ACDOCA_RBUKRS,
		ACDOCA_GJAHR,
		ACDOCA_BELNR,
		MAX(ACDOCA_BUDAT) AS ACDOCA_BUDAT,
		MAX(ACDOCA_RHCUR) AS ACDOCA_RHCUR,
		SUM(ZF_ACDOCA_HSL_S) AS ZF_ACDOCA_HSL_S,
		SUM(ZF_ACDOCA_HSL_S_CUC) AS ZF_ACDOCA_HSL_S_CUC
	FROM B04_13_IT_AR_ACC_SCH_NEW
	GROUP BY ACDOCA_RBUKRS,
		ACDOCA_GJAHR,
		ACDOCA_BELNR
) A
INNER JOIN 
(
	SELECT
		ACDOCA_RBUKRS,
		ACDOCA_GJAHR,
		ACDOCA_BELNR,
		MAX(ACDOCA_BUDAT) AS ACDOCA_BUDAT,
		MAX(ACDOCA_RHCUR) AS ACDOCA_RHCUR,
		SUM(ZF_ACDOCA_HSL_S) AS ZF_ACDOCA_HSL_S,
		SUM(ZF_ACDOCA_HSL_S_CUC) AS ZF_ACDOCA_HSL_S_CUC
	FROM B04_13_IT_AR_ACC_SCH
	GROUP BY ACDOCA_RBUKRS,
		ACDOCA_GJAHR,
		ACDOCA_BELNR
) B

ON A.ACDOCA_RBUKRS = B.ACDOCA_RBUKRS
AND A.ACDOCA_GJAHR = B.ACDOCA_GJAHR
AND A.ACDOCA_BELNR = B.ACDOCA_BELNR

-- Get house currency 

LEFT JOIN A_T001
ON A.ACDOCA_RBUKRS = A_T001.T001_BUKRS

-- Add manual exchange rates 

LEFT JOIN AM_EXCHNG
        ON A_T001.T001_WAERS = AM_EXCHNG.EXCHNG_FROM
        AND AM_EXCHNG.EXCHNG_TO = @currency

-- Add currency factor from company currency to USD

LEFT JOIN B00_IT_TCURF
ON A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR
AND B00_IT_TCURF.TCURF_TCURR  = @currency  
AND B00_IT_TCURF.TCURF_GDATU = (
	SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
	FROM B00_IT_TCURF
	WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
			B00_IT_TCURF.TCURF_TCURR  = @currency  AND
			B00_IT_TCURF.TCURF_GDATU <= A.ACDOCA_BUDAT
	ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
	)
-- Add exchange rate from company currency to USD
LEFT JOIN B00_IT_TCURR
	ON A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR
	AND B00_IT_TCURR.TCURR_TCURR  = @currency  
	AND B00_IT_TCURR.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.ACDOCA_BUDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 
GROUP BY A.ACDOCA_RBUKRS,
A.ACDOCA_GJAHR,
A.ACDOCA_BELNR

EXEC SP_RENAME_FIELD 'DC02_02_',DC02_02_IT_AR_ACC_SCH


--Step 3/ Compare values (USD) between table B04_11_IT_AP_ACC_SCH_NEW (use TCURR and TCURF) and table B04_11_IT_AP_ACC_SCH (use AM_EXCHNG)

EXEC SP_DROPTABLE 'DC02_03_IT_AP_ACC_SCH'

SELECT 
		A.ACDOCA_RBUKRS,
		A.ACDOCA_GJAHR,
		A.ACDOCA_BELNR,
		MAX(A.ACDOCA_RHCUR) AS ACDOCA_RHCUR,
		MAX(A.ACDOCA_BUDAT) AS ACDOCA_BUDAT,
		MAX(COALESCE (EXCHNG_RATIO,1)) AS EXCHNG_RATE_OLD,
		MAX(COALESCE(CAST(B00_IT_TCURR.TCURR_UKURS AS FLOAT),1) * COALESCE(B00_IT_TCURF.TCURF_TFACT,1) / COALESCE(B00_IT_TCURF.TCURF_FFACT,1)) AS EXCHNG_RATE_NEW,
		SUM(A.ZF_ACDOCA_HSL_S) AS ZF_ACDOCA_HSL_S,
		SUM(B.ZF_ACDOCA_HSL_S_CUC) AS ZF_ACDOCA_HSL_S_CUC_OLD,
		SUM(A.ZF_ACDOCA_HSL_S_CUC) AS ZF_ACDOCA_HSL_S_CUC_NEW
INTO DC02_03_IT_AP_ACC_SCH
FROM
(
	SELECT
		ACDOCA_RBUKRS,
		ACDOCA_GJAHR,
		ACDOCA_BELNR,
		MAX(ACDOCA_BUDAT) AS ACDOCA_BUDAT,
		MAX(ACDOCA_RHCUR) AS ACDOCA_RHCUR,
		SUM(ZF_ACDOCA_HSL_S) AS ZF_ACDOCA_HSL_S,
		SUM(ZF_ACDOCA_HSL_S_CUC) AS ZF_ACDOCA_HSL_S_CUC
	FROM B04_11_IT_AP_ACC_SCH_NEW
	GROUP BY ACDOCA_RBUKRS,
		ACDOCA_GJAHR,
		ACDOCA_BELNR
) A
INNER JOIN 
(
	SELECT
		ACDOCA_RBUKRS,
		ACDOCA_GJAHR,
		ACDOCA_BELNR,
		MAX(ACDOCA_BUDAT) AS ACDOCA_BUDAT,
		MAX(ACDOCA_RHCUR) AS ACDOCA_RHCUR,
		SUM(ZF_ACDOCA_HSL_S) AS ZF_ACDOCA_HSL_S,
		SUM(ZF_ACDOCA_HSL_S_CUC) AS ZF_ACDOCA_HSL_S_CUC
	FROM B04_11_IT_AP_ACC_SCH
	GROUP BY ACDOCA_RBUKRS,
		ACDOCA_GJAHR,
		ACDOCA_BELNR
) B

ON A.ACDOCA_RBUKRS = B.ACDOCA_RBUKRS
AND A.ACDOCA_GJAHR = B.ACDOCA_GJAHR
AND A.ACDOCA_BELNR = B.ACDOCA_BELNR

-- Get house currency 

LEFT JOIN A_T001
ON A.ACDOCA_RBUKRS = A_T001.T001_BUKRS

-- Add manual exchange rates 

LEFT JOIN AM_EXCHNG
        ON A_T001.T001_WAERS = AM_EXCHNG.EXCHNG_FROM
        AND AM_EXCHNG.EXCHNG_TO = @currency

-- Add currency factor from company currency to USD

LEFT JOIN B00_IT_TCURF
ON A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR
AND B00_IT_TCURF.TCURF_TCURR  = @currency  
AND B00_IT_TCURF.TCURF_GDATU = (
	SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
	FROM B00_IT_TCURF
	WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
			B00_IT_TCURF.TCURF_TCURR  = @currency  AND
			B00_IT_TCURF.TCURF_GDATU <= A.ACDOCA_BUDAT
	ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
	)
-- Add exchange rate from company currency to USD
LEFT JOIN B00_IT_TCURR
	ON A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR
	AND B00_IT_TCURR.TCURR_TCURR  = @currency  
	AND B00_IT_TCURR.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.ACDOCA_BUDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 
GROUP BY A.ACDOCA_RBUKRS,
A.ACDOCA_GJAHR,
A.ACDOCA_BELNR

EXEC SP_RENAME_FIELD 'DC02_03_',DC02_03_IT_AP_ACC_SCH

GO
