USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROC [dbo].[B21_OPEN_POs](@DBNAME as NVARCHAR(MAX))
AS
EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B21_%'

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B21_OPEN_POs_GR_INV'
GO
