USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROC [dbo].[DV01_DIVAQLTB_VERSUS_SAPTB](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_DV01_DIVAQLTB_VERSUS_SAPTB'
GO
