USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[B12B_REDUCTION_AGING] @DBNAME NVARCHAR(MAX)
AS
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B12B_SALE_REDUCTION_AGING'
GO
