USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE  PROCEDURE [dbo].[B00_CREATE_ESSENTIAL_MODULE] (@DBname as NVARCHAR(50))
AS

PRINT 'USE ' + @DBNAME
PRINT 'GO'


EXEC SP_PRINT_DYNAMIC 'SP_REMOVE_DUP_ON_TABLE'

EXEC SP_PRINT_DYNAMIC 'A_005D_CREATE_PROCUREMENT_CATEGORY_STRUCTURE_EXE'

EXEC [SP_PRINT_DYNAMIC] 'REMOVE_LEADING_ZEROES'

EXEC [SP_PRINT_DYNAMIC] 'GET_PARAM'

EXEC [SP_PRINT_DYNAMIC] 'ADD_LEADING_ZEROES'

EXEC [SP_PRINT_DYNAMIC] 'ALPHA_NUMERIC_COMPARE'

EXEC [SP_PRINT_DYNAMIC] 'ALNR_ONLY'

EXEC [SP_PRINT_DYNAMIC] 'SP_DROPTABLE'

EXEC [SP_PRINT_DYNAMIC] 'SP_REMOVE_TABLES'

EXEC [SP_PRINT_DYNAMIC] 'SP_CREATE_INDEX' 

EXEC [SP_PRINT_DYNAMIC] 'SP_UNNAME_FIELD' 

EXEC [SP_PRINT_DYNAMIC] 'SP_RENAME_FIELD' 

EXEC [SP_PRINT_DYNAMIC] 'SP_RENAME_SUFFIX_FIELD' 

EXEC [SP_PRINT_DYNAMIC] 'SP_WHERE_USED' 

EXEC [SP_PRINT_DYNAMIC] 'SP_TEST_DUP_KEY_FIELDS' 

EXEC [SP_PRINT_DYNAMIC] 'SP_TEST_DUPS_FOR_EACH_TABLE' 

EXEC [SP_PRINT_DYNAMIC] 'SP_REPLACE_NAME_FIELD' 

EXEC [SP_PRINT_DYNAMIC] 'SP_WHERE_USED' 

EXEC [SP_PRINT_DYNAMIC] 'SP_CREATE_INDEX' 

EXEC [SP_PRINT_DYNAMIC] 'SP_SAP_REPORT_FIELD_TO_STANDARD' 

EXEC [SP_PRINT_DYNAMIC] 'SP_SET_GLOBAL_LIMIT' 


--EXEC [SP_PRINT_DYNAMIC] 'A_002A_IMPORT_DATA_FILES_EXE' 

--EXEC [SP_PRINT_DYNAMIC] 'A_002B_REMOVE_DUPLICATES_EXE' 
GO
