USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[B10_PTP_PO_HISTORY](@DBNAME as NVARCHAR(MAX))
AS
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B10_%'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B10_PTP_PO_HISTORY'
GO
