USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROC [dbo].[DC08_BANK_CHANGE](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_DC08_BANK_CHANGE'
GO
