USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[script_DC09_SOD_OTC]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START
/* Initiate the log */ 
----Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END
 
--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL
 
/* Initialize parameters from globals table */
 
     DECLARE  
                      @CURRENCY NVARCHAR(MAX)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
                     ,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
                     ,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
                     ,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
                     ,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
                     ,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
                     ,@LANGUAGE1 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
                     ,@LANGUAGE2 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
                     ,@YEAR NVARCHAR(MAX)                     = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
                     ,@ID NVARCHAR(MAX)                       = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
                     ,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
					 ,@ZV_SAME_QUARTER_BY_BLDAT NVARCHAR(MAX) = ISNULL((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'ZV_SAME_QUARTER_BY_BLDAT'), '')

--Step 1/ Compare values (USD) between table B20_08_IT_MATERIAL_DOCS_NEW (use TCURR and TCURF) and table B20_08_IT_MATERIAL_DOCS (use AM_EXCHNG)
EXEC SP_DROPTABLE 	'DC09_01_IT_MATERIAL_DOCS' 

SELECT 
	A.B20_08_MKPF_MBLNR,
	A.B20_08_MSEG_BUKRS,
	A.B20_08_MKPF_MJAHR,
	A.B20_08_MSEG_ZEILE,
	A_T001.T001_WAERS,
	A.B20_08_MKPF_BUDAT AS B20_08_MKPF_BUDAT,
	B.B20_08_ZF_MSEG_DMBTR_S AS B20_08_ZF_MSEG_DMBTR_S,
	B.B20_08_ZF_MSEG_DMBTR_S_CUC AS B20_08_ZF_MSEG_DMBTR_S_CUC_OLD,
	A.B20_08_ZF_MSEG_DMBTR_S_CUC AS B20_08_ZF_MSEG_DMBTR_S_CUC_NEW,
	ISNULL(EXCHNG_RATIO,1) AS EXCH_RATE_OLD,
	COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1) AS EXCH_RATE_NEW
INTO DC09_01_IT_MATERIAL_DOCS
FROM (SELECT DISTINCT  B20_08_MKPF_MBLNR,
			   B20_08_MSEG_BUKRS,
			   B20_08_MKPF_MJAHR,
			   B20_08_MSEG_ZEILE,
			   MAX(B20_08_MSEG_WAERS) AS B20_08_MSEG_WAERS,
			   MAX(B20_08_MKPF_BUDAT) AS B20_08_MKPF_BUDAT,
			   SUM(B20_08_ZF_MSEG_DMBTR_S_CUC) AS B20_08_ZF_MSEG_DMBTR_S_CUC
       FROM B20_08_IT_MATERIAL_DOCS_NEW
	   GROUP BY B20_08_MKPF_MBLNR,
			   B20_08_MSEG_BUKRS,
			   B20_08_MKPF_MJAHR,
			   B20_08_MSEG_ZEILE) A

INNER JOIN (SELECT DISTINCT B20_08_MKPF_MBLNR,
			   B20_08_MSEG_BUKRS,
			   B20_08_MKPF_MJAHR,
			   B20_08_MSEG_ZEILE,
			   SUM(B20_08_ZF_MSEG_DMBTR_S) AS B20_08_ZF_MSEG_DMBTR_S,
			   SUM(B20_08_ZF_MSEG_DMBTR_S_CUC) AS B20_08_ZF_MSEG_DMBTR_S_CUC
		   FROM B20_08_IT_MATERIAL_DOCS
		   GROUP BY B20_08_MKPF_MBLNR,
					B20_08_MSEG_BUKRS,
					B20_08_MKPF_MJAHR,
					B20_08_MSEG_ZEILE) B
	ON A.B20_08_MKPF_MBLNR = B.B20_08_MKPF_MBLNR
	AND A.B20_08_MSEG_BUKRS = B.B20_08_MSEG_BUKRS
	AND A.B20_08_MKPF_MJAHR = B.B20_08_MKPF_MJAHR
	AND A.B20_08_MSEG_ZEILE = B.B20_08_MSEG_ZEILE
LEFT JOIN A_T001
	ON  A.B20_08_MSEG_BUKRS = A_T001.T001_BUKRS
LEFT JOIN B00_T014T 
      ON (A_T001.T001_KKBER = B00_T014T.T014T_KKBER) 	   
-- Exchange rates 
LEFT JOIN AM_EXCHNG
	ON A.B20_08_MSEG_WAERS = EXCHNG_FROM
	AND EXCHNG_TO = @CURRENCY

-- Get factor for amount in local currency
LEFT JOIN B00_TCURX
ON TCURX_CURRKEY = T001_WAERS

-- Add currency factor from company currency to USD

LEFT JOIN B00_IT_TCURF TCURF_CUC
ON A_T001.T001_WAERS = TCURF_CUC.TCURF_FCURR
AND TCURF_CUC.TCURF_TCURR  = @currency  
AND TCURF_CUC.TCURF_GDATU = (
	SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
	FROM B00_IT_TCURF
	WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
			B00_IT_TCURF.TCURF_TCURR  = @currency  AND
			B00_IT_TCURF.TCURF_GDATU <= A.B20_08_MKPF_BUDAT
	ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
	)
-- Add exchange rate from company currency to USD
LEFT JOIN B00_IT_TCURR TCURR_CUC
	ON A_T001.T001_WAERS = TCURR_CUC.TCURR_FCURR
	AND TCURR_CUC.TCURR_TCURR  = @currency  
	AND TCURR_CUC.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.B20_08_MKPF_BUDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 

		
EXEC SP_UNNAME_FIELD 'B20_08_',DC09_01_IT_MATERIAL_DOCS
EXEC SP_RENAME_FIELD 'DC09_01_',DC09_01_IT_MATERIAL_DOCS



--Step 2/ Compare values (USD) between table B20_09_IT_INVOICE_DOCS_NEW (use TCURR and TCURF) and table B20_09_IT_INVOICE_DOCS (use AM_EXCHNG)

EXEC SP_DROPTABLE 	'DC09_02_IT_INVOICE_DOCS' 

SELECT 
	A_VBRK.VBRK_BUKRS,
	A_VBRK.VBRK_GJAHR,
	A.B20_09_VBRK_VBELN,
	A.B20_09_VBRP_POSNR,
	A.B20_09_VBRK_FKDAT,
	A.B20_09_VBRK_WAERK,
	A_T001.T001_WAERS,
	B.B20_09_ZF_VBRP_NETWR_S AS B20_09_ZF_VBRP_NETWR_S,
	B.B20_09_ZF_VBRP_NETWR_S_CUC AS B20_09_ZF_VBRP_NETWR_S_CUC_OLD,
	A.B20_09_ZF_VBRP_NETWR_S_CUC AS B20_09_ZF_VBRP_NETWR_S_CUC_NEW,
	ISNULL(EXCHNG_RATIO,1) AS EXCH_RATE_OLD,
	VBRP_KURSK * COALESCE(TCURF_COC.TCURF_TFACT,1)/COALESCE(TCURF_COC.TCURF_FFACT,1) * COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1) AS EXCH_RATE_NEW
INTO DC09_02_IT_INVOICE_DOCS
FROM (SELECT DISTINCT B20_09_VBRK_VBELN,
					 B20_09_VBRP_POSNR,
			         B20_09_VBRK_FKDAT,
					 MAX(B20_09_VBRK_WAERK) AS B20_09_VBRK_WAERK,
					 SUM(B20_09_ZF_VBRP_NETWR_S) AS B20_09_ZF_VBRP_NETWR_S,
					 SUM(B20_09_ZF_VBRP_NETWR_S_CUC) AS B20_09_ZF_VBRP_NETWR_S_CUC
            FROM B20_09_IT_INVOICE_DOCS_NEW
			GROUP BY B20_09_VBRK_VBELN,
					 B20_09_VBRP_POSNR,
			         B20_09_VBRK_FKDAT ) A

INNER JOIN (SELECT DISTINCT B20_09_VBRK_VBELN,
					 B20_09_VBRP_POSNR,
			         B20_09_VBRK_FKDAT,
					 MAX(B20_09_VBRK_WAERK) AS B20_09_VBRK_WAERK,
					 SUM(B20_09_ZF_VBRP_NETWR_S) AS B20_09_ZF_VBRP_NETWR_S,
					 SUM(B20_09_ZF_VBRP_NETWR_S_CUC) AS B20_09_ZF_VBRP_NETWR_S_CUC
            FROM B20_09_IT_INVOICE_DOCS
			GROUP BY B20_09_VBRK_VBELN,
					 B20_09_VBRP_POSNR,
			         B20_09_VBRK_FKDAT) B
	ON A.B20_09_VBRK_VBELN = B.B20_09_VBRK_VBELN
	AND A.B20_09_VBRP_POSNR = B.B20_09_VBRP_POSNR
	AND A.B20_09_VBRK_FKDAT = B.B20_09_VBRK_FKDAT

INNER JOIN A_VBRP
	ON A.B20_09_VBRK_VBELN = A_VBRP.VBRP_VBELN
	AND A.B20_09_VBRP_POSNR = A_VBRP.VBRP_POSNR

INNER JOIN A_VBRK
	ON A.B20_09_VBRK_VBELN = A_VBRK.VBRK_VBELN

LEFT JOIN A_T001
	ON  A_VBRK.VBRK_BUKRS = A_T001.T001_BUKRS	   
-- Exchange rates 
LEFT JOIN AM_EXCHNG
	ON A.B20_09_VBRK_WAERK = EXCHNG_FROM
	AND EXCHNG_TO = @CURRENCY

-- Add currency factor from company currency to USD

LEFT JOIN B00_IT_TCURF TCURF_CUC
ON A_T001.T001_WAERS = TCURF_CUC.TCURF_FCURR
AND TCURF_CUC.TCURF_TCURR  = @currency  
AND TCURF_CUC.TCURF_GDATU = (
	SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
	FROM B00_IT_TCURF
	WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
			B00_IT_TCURF.TCURF_TCURR  = @currency  AND
			B00_IT_TCURF.TCURF_GDATU <= A.B20_09_VBRK_FKDAT
	ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
	)
-- Add exchange rate from company currency to USD
LEFT JOIN B00_IT_TCURR TCURR_CUC
	ON A_T001.T001_WAERS = TCURR_CUC.TCURR_FCURR
	AND TCURR_CUC.TCURR_TCURR  = @currency  
	AND TCURR_CUC.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.B20_09_VBRK_FKDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 

-- Add currency factor from document currency to local currency

LEFT JOIN B00_IT_TCURF TCURF_COC
ON A.B20_09_VBRK_WAERK = TCURF_COC.TCURF_FCURR
AND TCURF_COC.TCURF_TCURR  = T001_WAERS  
AND TCURF_COC.TCURF_GDATU = (
	SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
	FROM B00_IT_TCURF
	WHERE A.B20_09_VBRK_WAERK = B00_IT_TCURF.TCURF_FCURR AND 
			B00_IT_TCURF.TCURF_TCURR  = T001_WAERS  AND
			B00_IT_TCURF.TCURF_GDATU <= A.B20_09_VBRK_FKDAT
	ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
	)



EXEC SP_UNNAME_FIELD 'B20_09_',DC09_02_IT_INVOICE_DOCS
EXEC SP_RENAME_FIELD 'DC09_02_',DC09_02_IT_INVOICE_DOCS

GO
