USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[script_DC06_OTC_ARE]
WITH EXECUTE AS CALLER
AS

--DYNAMIC_SCRIPT_START
/* Initiate the log */ 
----Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END
 
--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL
 

/* Initialize parameters from globals table */
 
     DECLARE  
                      @CURRENCY NVARCHAR(MAX)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
                     ,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
                     ,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
                     ,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
                     ,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
                     ,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
                     ,@LANGUAGE1 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
                     ,@LANGUAGE2 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
                     ,@YEAR NVARCHAR(MAX)                     = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
                     ,@ID NVARCHAR(MAX)                       = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
                     ,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
					 ,@ZV_SAME_QUARTER_BY_BLDAT NVARCHAR(MAX) = ISNULL((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'ZV_SAME_QUARTER_BY_BLDAT'), '')


-- Step 1/ Compare values (USD) between table B14_06_IT_ARE_NEW (use TCURR and TCURF) and table B14_06_IT_ARE (use AM_EXCHNG)

EXEC SP_DROPTABLE 	'DC06_01_IT_ARE' 

SELECT 
	A.B14_ACDOCA_RBUKRS,
	A.B14_ACDOCA_GJAHR,
	A.B14_ACDOCA_RACCT, 
	A.B14_ACDOCA_MONAT,
	MAX(A.B14_ACDOCA_RHCUR) AS B14_ACDOCA_RHCUR,
	MAX(A.B14_ACDOCA_BUDAT) AS  B14_ACDOCA_BUDAT,
	SUM(A.B14_ZF_ACDOCA_HSL_COC) AS B14_ZF_ACDOCA_HSL_COC,
	SUM(B.B14_ZF_ACDOCA_HSL_CUC) AS B14_ZF_ACDOCA_HSL_CUC_OLD,
	SUM(A.B14_ZF_ACDOCA_HSL_CUC) AS B14_ZF_ACDOCA_HSL_CUC_NEW,
	MAX(ISNULL(AM_EXCHNG.EXCHNG_RATIO,1)) AS EXCH_RATE_OLD,
	MAX(COALESCE(CAST(B00_IT_TCURR.TCURR_UKURS AS FLOAT),1) * COALESCE(B00_IT_TCURF.TCURF_TFACT,1) / COALESCE(B00_IT_TCURF.TCURF_FFACT,1)) AS EXCH_RATE_NEW
INTO DC06_01_IT_ARE
FROM (
		SELECT DISTINCT
			B14_ACDOCA_RBUKRS,
			B14_ACDOCA_GJAHR,
			B14_ACDOCA_RACCT,
			B14_ACDOCA_MONAT,
			MAX(B14_ACDOCA_RHCUR) AS B14_ACDOCA_RHCUR,
			MAX(B14_ACDOCA_BUDAT) AS  B14_ACDOCA_BUDAT,
			SUM(B14_ZF_ACDOCA_HSL_COC) AS B14_ZF_ACDOCA_HSL_COC,
			SUM(B14_ZF_ACDOCA_HSL_CUC) AS B14_ZF_ACDOCA_HSL_CUC
		FROM B14_06_IT_ARE_NEW
		WHERE B14_ZF_ACDOCA_DRCRK_DESC='Debit'
		GROUP BY 
			B14_ACDOCA_RBUKRS,
			B14_ACDOCA_GJAHR,
			B14_ACDOCA_RACCT,
			B14_ACDOCA_MONAT

	) A
INNER JOIN (
		SELECT DISTINCT
			B14_ACDOCA_RBUKRS,
			B14_ACDOCA_GJAHR,
			B14_ACDOCA_RACCT,
			B14_ACDOCA_MONAT,
			MAX(B14_ACDOCA_RHCUR) AS B14_ACDOCA_RHCUR,
			MAX( B14_ACDOCA_BUDAT) AS  B14_ACDOCA_BUDAT,
			SUM(B14_ZF_ACDOCA_HSL_CUC) AS B14_ZF_ACDOCA_HSL_CUC
		FROM B14_06_IT_ARE
				WHERE B14_ZF_ACDOCA_DRCRK_DESC='Debit'
		GROUP BY 
			B14_ACDOCA_RBUKRS,
			B14_ACDOCA_GJAHR,
			B14_ACDOCA_RACCT,
			B14_ACDOCA_MONAT

	) B

	ON A.B14_ACDOCA_RBUKRS = B.B14_ACDOCA_RBUKRS
	AND A.B14_ACDOCA_RACCT = B.B14_ACDOCA_RACCT
	AND A.B14_ACDOCA_GJAHR = B.B14_ACDOCA_GJAHR
	AND A.B14_ACDOCA_MONAT = B.B14_ACDOCA_MONAT

LEFT JOIN AM_EXCHNG
	ON  AM_EXCHNG.EXCHNG_FROM = A.B14_ACDOCA_RHCUR
	AND AM_EXCHNG.EXCHNG_TO   =  @currency

LEFT JOIN B00_IT_TCURF
	ON A.B14_ACDOCA_RHCUR = B00_IT_TCURF.TCURF_FCURR
	AND B00_IT_TCURF.TCURF_TCURR  = @currency  
	AND B00_IT_TCURF.TCURF_GDATU = (
		SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
		FROM B00_IT_TCURF
		WHERE A.B14_ACDOCA_RHCUR = B00_IT_TCURF.TCURF_FCURR AND 
				B00_IT_TCURF.TCURF_TCURR  = @currency  AND
				B00_IT_TCURF.TCURF_GDATU <= A.B14_ACDOCA_BUDAT
		ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
		)

LEFT JOIN B00_IT_TCURR
	ON A.B14_ACDOCA_RHCUR = B00_IT_TCURR.TCURR_FCURR
	AND B00_IT_TCURR.TCURR_TCURR  = @currency  
	AND B00_IT_TCURR.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A.B14_ACDOCA_RHCUR = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.B14_ACDOCA_BUDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 


GROUP BY A.B14_ACDOCA_RBUKRS,
		 A.B14_ACDOCA_GJAHR,
		 A.B14_ACDOCA_RACCT,
		 A.B14_ACDOCA_MONAT
		 


EXEC SP_UNNAME_FIELD 'B14_',DC06_01_IT_ARE
EXEC SP_RENAME_FIELD 'DC06_01_',DC06_01_IT_ARE

-- Step 2/ Compare values (USD) between table B14_19_IT_T4_OUTPUT_NEW (use TCURR and TCURF) and table B14_19_IT_T4_OUTPUT (use AM_EXCHNG)

EXEC SP_DROPTABLE 	'DC06_02_IT_T4_OUTPUT' 

SELECT A.B14B_ACDOCA_RBUKRS,
	   A.B14B_ACDOCA_KUNNR,
	   A.B14B_ACDOCA_BELNR,
	   A.B14B_ACDOCA_BUZEI,
	   A.B14B_T001_WAERS,
	   MAX(A.B14B_ACDOCA_BUDAT) AS B14B_ACDOCA_BUDAT,
	   MAX(COALESCE(TCURX_FACTOR,1)*ISNULL(AM_EXCHNG.EXCHNG_RATIO,1)) AS EXCH_RATE_OLD,
	   MAX(COALESCE(TCURX_FACTOR,1)*COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1)) AS EXCH_RATE_NEW,
	   SUM(A.B14B_ACDOCA_HSL) AS B14B_ACDOCA_HSL,
	   SUM(B.B14B_ZF_ACDOCA_HSL_CUC) AS B14B_ZF_ACDOCA_HSL_CUC_OLD,
	   SUM(A.B14B_ZF_ACDOCA_HSL_CUC) AS B14B_ZF_ACDOCA_HSL_CUC_NEW
INTO DC06_02_IT_T4_OUTPUT
FROM 
(
	SELECT B14B_ACDOCA_RBUKRS,
		   B14B_ACDOCA_KUNNR,
		   B14B_ACDOCA_BELNR,
		   B14B_ACDOCA_BUZEI,
		   MAX(B14B_T001_WAERS) AS B14B_T001_WAERS,
		   MAX(B14B_ACDOCA_BUDAT) AS B14B_ACDOCA_BUDAT,
		   SUM(B14B_ACDOCA_HSL) AS B14B_ACDOCA_HSL,
		   SUM(B14B_ZF_ACDOCA_HSL_CUC) AS B14B_ZF_ACDOCA_HSL_CUC
	FROM B14_19_IT_T4_OUTPUT_NEW
	GROUP BY B14B_ACDOCA_RBUKRS,
		   B14B_ACDOCA_KUNNR,
		   B14B_ACDOCA_BELNR,
		   B14B_ACDOCA_BUZEI
) AS A
INNER JOIN 
(
	SELECT B14B_ACDOCA_RBUKRS,
		   B14B_ACDOCA_KUNNR,
		   B14B_ACDOCA_BELNR,
		   B14B_ACDOCA_BUZEI,
		   MAX(B14B_T001_WAERS) AS B14B_T001_WAERS,
		   MAX(B14B_ACDOCA_BUDAT) AS B14B_ACDOCA_BUDAT,
		   SUM(B14B_ACDOCA_HSL) AS B14B_ACDOCA_HSL,
		   SUM(B14B_ZF_ACDOCA_HSL_CUC) AS B14B_ZF_ACDOCA_HSL_CUC
	FROM B14_19_IT_T4_OUTPUT
	GROUP BY B14B_ACDOCA_RBUKRS,
		   B14B_ACDOCA_KUNNR,
		   B14B_ACDOCA_BELNR,
		   B14B_ACDOCA_BUZEI
) AS B
ON A.B14B_ACDOCA_RBUKRS = B.B14B_ACDOCA_RBUKRS AND 
   A.B14B_ACDOCA_KUNNR = B.B14B_ACDOCA_KUNNR AND 
   A.B14B_ACDOCA_BELNR = B.B14B_ACDOCA_BELNR AND
   A.B14B_ACDOCA_BUZEI = B.B14B_ACDOCA_BUZEI
	
	--Get local currency informatiom

LEFT JOIN A_T001
	ON A.B14B_ACDOCA_RBUKRS = A_T001.T001_BUKRS

LEFT JOIN B00_TCURX
	ON B00_TCURX.TCURX_CURRKEY = A_T001.T001_WAERS

	--Get custom currency exchage rate
LEFT JOIN AM_EXCHNG
ON AM_EXCHNG.EXCHNG_FROM = T001_WAERS AND AM_EXCHNG.EXCHNG_TO = @CURRENCY

LEFT JOIN B00_IT_TCURF TCURF_CUC
	ON A_T001.T001_WAERS = TCURF_CUC.TCURF_FCURR
	AND TCURF_CUC.TCURF_TCURR  = @currency  
	AND TCURF_CUC.TCURF_GDATU = (
		SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
		FROM B00_IT_TCURF
		WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
				B00_IT_TCURF.TCURF_TCURR  = @currency  AND
				B00_IT_TCURF.TCURF_GDATU <= A.B14B_ACDOCA_BUDAT
		ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
		)
	-- Add exchange rate from company currency to USD
LEFT JOIN B00_IT_TCURR TCURR_CUC
	ON A_T001.T001_WAERS = TCURR_CUC.TCURR_FCURR
	AND TCURR_CUC.TCURR_TCURR  = @currency  
	AND TCURR_CUC.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.B14B_ACDOCA_BUDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 
GROUP BY A.B14B_ACDOCA_RBUKRS,
	   A.B14B_ACDOCA_KUNNR,
	   A.B14B_ACDOCA_BELNR,
	   A.B14B_ACDOCA_BUZEI,
	   A.B14B_T001_WAERS

EXEC SP_UNNAME_FIELD 'B14B_',DC06_02_IT_T4_OUTPUT
EXEC SP_RENAME_FIELD 'DC06_02_',DC06_02_IT_T4_OUTPUT
GO
