USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PM_PTP_PROCESS_MINING] 	 @DBNAME as NVARCHAR(MAX)
AS
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B26_%'
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B24_%'
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME,  'B11_SS02_%'

	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B24_CHANGE_CUBE_V2'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B26_MATERIAL_MOVEMENT_CUBE'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B25_PTP_PURCHASE_REQUEST'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B09_SS02_ADD_USER_PO'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B11_SS02_ADD_USER_INV_PAY'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B27A_BSEG_BKPF_INVOICES'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B27_PTP_GLOBAL_CUBES'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_PM01_PROCESS_MINING_NEW'
GO
