USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_B03_SS01_TRIAL_BALANCE_RATIO]
WITH EXECUTE AS CALLER
AS

--DYNAMIC_SCRIPT_START

/* Initiate the log */  
--Create database log table if it does not exist

IF OBJECT_ID('_DatabaseLogTable', 'U') IS NULL BEGIN CREATE TABLE [dbo].[_DatabaseLogTable] ([Database] nvarchar(max) NULL,[Object] nvarchar(max) NULL,[Object Type] nvarchar(max) NULL,[User] nvarchar(max) NULL,[Date] date NULL,[Time] time NULL,[Description] nvarchar(max) NULL,[Table] nvarchar(max),[Rows] int) END

--Log start of procedure
INSERT INTO [dbo].[_DatabaseLogTable] ([Database],[Object],[Object Type],[User],[Date],[Time],[Description],[Table],[Rows])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(date,GETDATE()),CONVERT(time,GETDATE()),'Procedure started',NULL,NULL


	/* Initialize parameters from globals table */
    DECLARE  
				@CURRENCY NVARCHAR(3)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
				,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
				,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
				,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
				,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
				,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
				,@LANGUAGE1 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
				,@LANGUAGE2 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
				,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
				,@FISCAL_YEAR_FROM NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_FROM')
				,@FISCAL_YEAR_TO NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_TO')
                 SET DATEFORMAT @DATEFORMAT;


/*Change history comments*/


--Step 1 Add the tango account category to the monthly trial blanace
--Add the necessary text descriotion
EXEC SP_REMOVE_TABLES 'B03_SS01_%'


EXEC SP_DROPTABLE 'B03_SS01_01_RT_TB_ADD_CATEGORY'
SELECT DISTINCT B03_04_IT_TB_SUMMARY_FULL.*,[Tango accounts],
B03_01_IT_FIN_TB.B03_ACDOCA_RKCUR,
B03_01_IT_FIN_TB.B03_GLOBALS_PARAMETER_CURR,
CASE  
	WHEN [Cash]='X' THEN 'Cash'
	WHEN [Fixed assets]='X' THEN 'Fixed assets'
	WHEN [Inventory]='X' THEN 'Inventory'
	WHEN [Other assets]='X' THEN 'Other assets'
	WHEN [Short term loans]='X' THEN 'Short term loans(asset)'
	WHEN [Loans (asset)]='X' THEN 'Loans (asset)'
	WHEN [Receivables (AR)]='X' THEN 'Accounts receivables (AR)'
	WHEN [Accrual: Deferred income]='X' THEN 'Accrual: Deferred income'
	WHEN [Accounts payable (AP)]='X' THEN 'Accounts payable (AP)'
	WHEN [Accrued expense/ deferred liabilities]='X' THEN 'Accrued expense/ deferred liabilities'
	WHEN [Provision liability]='X' THEN 'Provision liability'
	WHEN [Other liabilities]='X' THEN 'Other liabilities'
	WHEN [Short term loans1]='X' THEN 'Short term loans (liability)'
	WHEN [Loans (liability)]='X' THEN 'Loans (liability)'
	WHEN [Revenue/ Gross sales]='X' THEN 'Revenue/ Gross sales'
	WHEN [Discounts/ reductions/ adjustments]='X' THEN 'Discounts/ reductions/ adjustments'
	WHEN [COGS]='X' THEN 'COGS'
	WHEN [Other revenue/ other operating revenue]='X' THEN 'Other revenue/ other operating revenue'
	WHEN [Expenditure]='X' THEN 'Expenditure'
	WHEN [Equity/ securities]='X' THEN 'Equity/ securities'
	WHEN [Common stock (shares)]='X' THEN 'Common stock (shares)'
	WHEN [Capital]='X' THEN 'Capital'
	WHEN [Retained earnings]='X' THEN 'Retained earnings'
	WHEN [Other adjustments (FX adj# etc)]='X' THEN 'Other adjustments (FX adj# etc)'
	WHEN [Right-of-use assets]='X' THEN 'Right-of-use assets'
	WHEN [Depreciation/ amortization P&L]='X' THEN 'Depreciation/ amortization P&L'
	WHEN [Production costs]='X' THEN 'Production costs'
ELSE 'Not found'
END AS ZF_CATEGORY
INTO B03_SS01_01_RT_TB_ADD_CATEGORY
FROM 
B03_04_IT_TB_SUMMARY_FULL
LEFT JOIN DIVA_MASTER_SCRIPT_S4HANA..AM_TANGO_ACCT_CATEGORY
ON CAST(AM_TANGO_ACCT_CATEGORY.[Tango accounts] AS NVARCHAR)=CAST(B03_04_TANGO_ACCT AS NVARCHAR) --Khoi new update, we need to change to the same format, so they can link together
LEFT JOIN B03_01_IT_FIN_TB
ON	B03_01_IT_FIN_TB.B03_ACDOCA_RBUKRS=B03_04_IT_TB_SUMMARY_FULL.B03_04_ACDOCA_RBUKRS
AND B03_01_IT_FIN_TB.B03_ACDOCA_RACCT=B03_04_IT_TB_SUMMARY_FULL.B03_04_ACDOCA_RACCT
AND B03_01_IT_FIN_TB.B03_ACDOCA_RYEAR=B03_04_IT_TB_SUMMARY_FULL.B03_04_ACDOCA_RYEAR
AND B03_01_IT_FIN_TB.B03_ACDOCA_MONAT=B03_04_IT_TB_SUMMARY_FULL.B03_04_ACDOCA_MONAT


--Step 2 Caculation the total balance , and movement
--Group bye the Singular_category and Compound category
--FIscal year, and month 
	--
	EXEC SP_DROPTABLE B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH

	SELECT 
		ZF_CATEGORY,
		B03_04_ACDOCA_RYEAR,
		B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		B03_04_ZF_ACDOCA_POPER_MONTH,
		B03_04_T001_BUTXT,
		IIF(ZF_CATEGORY IN
				('Cash',
				'Fixed assets',	
				'Inventory',
				'Other assets',
				'Short term loans (asset)',
				'Loans (asset)',
				'Accounts receivables (AR)',
				'Accrual: Deferred income',	
				'Accounts payable (AP)'	,
				'Accrued expense/ deferred liabilities',
				'Provision liability',
				'Other liabilities',	
				'Short term loans (liability)',
				'Loans (liability)',
				'Equity/ securities',	
				'Common stock (shares)',	
				'Capital',	
				'Retained earnings',
				'Right-of-use assets',
				'Other adjustments (FX adj. etc)'),'Balance','Net') AS ZF_BALANCE_NET_FLAG,
		SUM(B03_04_ZF_ACDOCA_HSL_TOT_END)	 AS ZF_BALANCE_ACDOCA_HSL,
		SUM(B03_04_ZF_ACDOCA_HSL_TOT_END_CUC)	 AS ZF_BALANCE_ACDOCA_HSL_CUC,
		SUM(B03_04_ZF_ACDOCA_KSL_TOT_END)	AS ZF_BALANCE_ACDOCA_KSL,
		SUM(B03_04_ZF_ACDOCA_OSL_TOT_END) AS  ZF_BALANCE_ACDOCA_OSL,
		SUM(B03_04_ZF_ACDOCA_HSL_TOT_MOV) AS ZF_MOV_ACDOCA_HSL,
		SUM(B03_04_ZF_ACDOCA_HSL_TOT_MOV_CUC) AS ZF_MOV_ACDOCA_HSL_CUC,
		SUM(B03_04_ZF_ACDOCA_KSL_TOT_MOV) AS ZF_MOV_ACDOCA_KSL,
		SUM(B03_04_ZF_ACDOCA_OSL_TOT_MOV) AS ZF_MOV_ACDOCA_OSL
	INTO B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	FROM B03_SS01_01_RT_TB_ADD_CATEGORY
	GROUP BY
		ZF_CATEGORY,
		B03_04_ACDOCA_RYEAR,
		B03_04_ACDOCA_MONAT,
		B03_04_ACDOCA_RBUKRS,
		B03_04_ZF_ACDOCA_POPER_MONTH,
		B03_04_T001_BUTXT

--Step 3 Change the total caculation result to pivot table
--Replace the null value with 0, to avoid errors when do other caculation
EXEC SP_DROPTABLE 'B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT'

SELECT DISTINCT
		B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR,
		B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT,
		B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS,
		B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ZF_ACDOCA_POPER_MONTH,
		B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_T001_BUTXT,
		--Cash
		ISNULL(ZF_CASH_BAL_HSL,0) AS ZF_CASH_BAL_HSL,
		ISNULL(ZF_CASH_BAL_CUC,0) AS ZF_CASH_BAL_CUC ,
		ISNULL(ZF_CASH_BAL_KSL,0) AS ZF_CASH_BAL_KSL,
		ISNULL(ZF_CASH_BAL_OSL,0) AS ZF_CASH_BAL_OSL,
		ISNULL(ZF_CASH_MOV_HSL,0) AS ZF_CASH_MOV_HSL,
		ISNULL(ZF_CASH_MOV_CUC,0) AS ZF_CASH_MOV_CUC,
		ISNULL(ZF_CASH_MOV_KSL,0) AS ZF_CASH_MOV_KSL,
		ISNULL(ZF_CASH_MOV_OSL,0) AS ZF_CASH_MOV_OSL,
		--fixed asset
		ISNULL(ZF_FIX_ASSET_BAL_HSL,0) AS ZF_FIX_ASSET_BAL_HSL,
		ISNULL(ZF_FIX_ASSET_BAL_CUC,0) AS ZF_FIX_ASSET_BAL_CUC,
		ISNULL(ZF_FIX_ASSET_BAL_KSL,0) AS ZF_FIX_ASSET_BAL_KSL,
		ISNULL(ZF_FIX_ASSET_BAL_OSL,0) AS ZF_FIX_ASSET_BAL_OSL,
		ISNULL(ZF_FIX_ASSET_MOV_HSL,0) AS ZF_FIX_ASSET_MOV_HSL,
		ISNULL(ZF_FIX_ASSET_MOV_CUC,0) AS ZF_FIX_ASSET_MOV_CUC,
		ISNULL(ZF_FIX_ASSET_MOV_KSL,0) AS ZF_FIX_ASSET_MOV_KSL,
		ISNULL(ZF_FIX_ASSET_MOV_OSL,0) AS ZF_FIX_ASSET_MOV_OSL,
		--Inventory
		ISNULL(ZF_INVENTORY_BAL_HSL,0) AS ZF_INVENTORY_BAL_HSL,
		ISNULL(ZF_INVENTORY_BAL_CUC,0) AS ZF_INVENTORY_BAL_CUC,
		ISNULL(ZF_INVENTORY_BAL_KSL,0) AS ZF_INVENTORY_BAL_KSL,
		ISNULL(ZF_INVENTORY_BAL_OSL,0) AS ZF_INVENTORY_BAL_OSL,
		ISNULL(ZF_INVENTORY_MOV_HSL,0) AS ZF_INVENTORY_MOV_HSL,
		ISNULL(ZF_INVENTORY_MOV_CUC,0) AS ZF_INVENTORY_MOV_CUC,
		ISNULL(ZF_INVENTORY_MOV_KSL,0) AS ZF_INVENTORY_MOV_KSL,
		ISNULL(ZF_INVENTORY_MOV_OSL,0) AS ZF_INVENTORY_MOV_OSL,
		--Other asset
		ISNULL(ZF_OTHER_ASS_BAL_HSL,0) AS ZF_OTHER_ASS_BAL_HSL,
		ISNULL(ZF_OTHER_ASS_BAL_CUC,0) AS ZF_OTHER_ASS_BAL_CUC,
		ISNULL(ZF_OTHER_ASS_BAL_KSL,0) AS ZF_OTHER_ASS_BAL_KSL,
		ISNULL(ZF_OTHER_ASS_BAL_OSL,0) AS ZF_OTHER_ASS_BAL_OSL,
		ISNULL(ZF_OTHER_ASS_MOV_HSL,0) AS ZF_OTHER_ASS_MOV_HSL,
		ISNULL(ZF_OTHER_ASS_MOV_CUC,0) AS ZF_OTHER_ASS_MOV_CUC,
		ISNULL(ZF_OTHER_ASS_MOV_KSL,0) AS ZF_OTHER_ASS_MOV_KSL,
		ISNULL(ZF_OTHER_ASS_MOV_OSL,0) AS ZF_OTHER_ASS_MOV_OSL,
		--Short loan asset
		ISNULL(ZF_SHORT_LOAN_ASS_BAL_HSL,0) AS ZF_SHORT_LOAN_ASS_BAL_HSL,
		ISNULL(ZF_SHORT_LOAN_ASS_BAL_CUC,0) AS ZF_SHORT_LOAN_ASS_BAL_CUC,
		ISNULL(ZF_SHORT_LOAN_ASS_BAL_KSL,0) AS ZF_SHORT_LOAN_ASS_BAL_KSL,
		ISNULL(ZF_SHORT_LOAN_ASS_BAL_OSL,0) AS ZF_SHORT_LOAN_ASS_BAL_OSL,
		ISNULL(ZF_SHORT_LOAN_ASS_MOV_HSL,0) AS ZF_SHORT_LOAN_ASS_MOV_HSL,
		ISNULL(ZF_SHORT_LOAN_ASS_MOV_CUC,0) AS ZF_SHORT_LOAN_ASS_MOV_CUC,
		ISNULL(ZF_SHORT_LOAN_ASS_MOV_KSL,0) AS ZF_SHORT_LOAN_ASS_MOV_KSL,
		ISNULL(ZF_SHORT_LOAN_ASS_MOV_OSL,0) AS ZF_SHORT_LOAN_ASS_MOV_OSL,
		--Loans (asset)
		ISNULL(ZF_LOAN_ASS_BAL_HSL,0) AS ZF_LOAN_ASS_BAL_HSL,
		ISNULL(ZF_LOAN_ASS_BAL_CUC,0) AS ZF_LOAN_ASS_BAL_CUC,
		ISNULL(ZF_LOAN_ASS_BAL_KSL,0) AS ZF_LOAN_ASS_BAL_KSL,
		ISNULL(ZF_LOAN_ASS_BAL_OSL,0) AS ZF_LOAN_ASS_BAL_OSL,
		ISNULL(ZF_LOAN_ASS_MOV_HSL,0) AS ZF_LOAN_ASS_MOV_HSL,
		ISNULL(ZF_LOAN_ASS_MOV_CUC,0) AS ZF_LOAN_ASS_MOV_CUC,
		ISNULL(ZF_LOAN_ASS_MOV_KSL,0) AS ZF_LOAN_ASS_MOV_KSL,
		ISNULL(ZF_LOAN_ASS_MOV_OSL,0) AS ZF_LOAN_ASS_MOV_OSL,
		--AR
		ISNULL(ZF_AR_BAL_HSL,0) AS ZF_AR_BAL_HSL,
		ISNULL(ZF_AR_BAL_CUC,0) AS ZF_AR_BAL_CUC,
		ISNULL(ZF_AR_BAL_KSL,0) AS ZF_AR_BAL_KSL,
		ISNULL(ZF_AR_BAL_OSL,0) AS ZF_AR_BAL_OSL,
		ISNULL(ZF_AR_MOV_HSL,0) AS ZF_AR_MOV_HSL,
		ISNULL(ZF_AR_MOV_CUC,0) AS ZF_AR_MOV_CUC,
		ISNULL(ZF_AR_MOV_KSL,0) AS ZF_AR_MOV_KSL,
		ISNULL(ZF_AR_MOV_OSL,0) AS ZF_AR_MOV_OSL,
		--Accrual: Deferred income,0) AS --Accrual: Deferred income,
		ISNULL(ZF_ACCRUAl_DEF_INCOM_BAL_HSL,0) AS ZF_ACCRUAl_DEF_INCOM_BAL_HSL,
		ISNULL(ZF_ACCRUAl_DEF_INCOM_BAL_CUC,0) AS ZF_ACCRUAl_DEF_INCOM_BAL_CUC,
		ISNULL(ZF_ACCRUAl_DEF_INCOM_BAL_KSL,0) AS ZF_ACCRUAl_DEF_INCOM_BAL_KSL,
		ISNULL(ZF_ACCRUAl_DEF_INCOM_BAL_OSL,0) AS ZF_ACCRUAl_DEF_INCOM_BAL_OSL,
		ISNULL(ZF_ACCRUAl_DEF_INCOM_MOV_HSL,0) AS ZF_ACCRUAl_DEF_INCOM_MOV_HSL,
		ISNULL(ZF_ACCRUAl_DEF_INCOM_MOV_CUC,0) AS ZF_ACCRUAl_DEF_INCOM_MOV_CUC,
		ISNULL(ZF_ACCRUAl_DEF_INCOM_MOV_KSL,0) AS ZF_ACCRUAl_DEF_INCOM_MOV_KSL,
		ISNULL(ZF_ACCRUAl_DEF_INCOM_MOV_OSL,0) AS ZF_ACCRUAl_DEF_INCOM_MOV_OSL,
		--AP
		ISNULL(ZF_AP_BAL_HSL,0) AS ZF_AP_BAL_HSL,
		ISNULL(ZF_AP_BAL_CUC,0) AS ZF_AP_BAL_CUC,
		ISNULL(ZF_AP_BAL_KSL,0) AS ZF_AP_BAL_KSL,
		ISNULL(ZF_AP_BAL_OSL,0) AS ZF_AP_BAL_OSL,
		ISNULL(ZF_AP_MOV_HSL,0) AS ZF_AP_MOV_HSL,
		ISNULL(ZF_AP_MOV_CUC,0) AS ZF_AP_MOV_CUC,
		ISNULL(ZF_AP_MOV_KSL,0) AS ZF_AP_MOV_KSL,
		ISNULL(ZF_AP_MOV_OSL,0) AS ZF_AP_MOV_OSL,
		--Accrued expense/ Deferred liabilities
		ISNULL(ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_HSL,0) AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_HSL,
		ISNULL(ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_CUC,0) AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_CUC,
		ISNULL(ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_KSL,0) AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_KSL,
		ISNULL(ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_OSL,0) AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_OSL,
		ISNULL(ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_HSL,0) AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_HSL,
		ISNULL(ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_CUC,0) AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_CUC,
		ISNULL(ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_KSL,0) AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_KSL,
		ISNULL(ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_OSL,0) AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_OSL,
		--Provision liability
		ISNULL(ZF_PROVI_LIABILITY_BAL_HSL,0) AS ZF_PROVI_LIABILITY_BAL_HSL,
		ISNULL(ZF_PROVI_LIABILITY_BAL_CUC,0) AS ZF_PROVI_LIABILITY_BAL_CUC,
		ISNULL(ZF_PROVI_LIABILITY_BAL_KSL,0) AS ZF_PROVI_LIABILITY_BAL_KSL,
		ISNULL(ZF_PROVI_LIABILITY_BAL_OSL,0) AS ZF_PROVI_LIABILITY_BAL_OSL,
		ISNULL(ZF_PROVI_LIABILITY_MOV_HSL,0) AS ZF_PROVI_LIABILITY_MOV_HSL,
		ISNULL(ZF_PROVI_LIABILITY_MOV_CUC,0) AS ZF_PROVI_LIABILITY_MOV_CUC,
		ISNULL(ZF_PROVI_LIABILITY_MOV_KSL,0) AS ZF_PROVI_LIABILITY_MOV_KSL,
		ISNULL(ZF_PROVI_LIABILITY_MOV_OSL,0) AS ZF_PROVI_LIABILITY_MOV_OSL,
		--Other liabilities
		ISNULL(ZF_OTHER_LIABILITY_BAL_HSL,0) AS ZF_OTHER_LIABILITY_BAL_HSL,
		ISNULL(ZF_OTHER_LIABILITY_BAL_CUC,0) AS ZF_OTHER_LIABILITY_BAL_CUC,
		ISNULL(ZF_OTHER_LIABILITY_BAL_KSL,0) AS ZF_OTHER_LIABILITY_BAL_KSL,
		ISNULL(ZF_OTHER_LIABILITY_BAL_OSL,0) AS ZF_OTHER_LIABILITY_BAL_OSL,
		ISNULL(ZF_OTHER_LIABILITY_MOV_HSL,0) AS ZF_OTHER_LIABILITY_MOV_HSL,
		ISNULL(ZF_OTHER_LIABILITY_MOV_CUC,0) AS ZF_OTHER_LIABILITY_MOV_CUC,
		ISNULL(ZF_OTHER_LIABILITY_MOV_KSL,0) AS ZF_OTHER_LIABILITY_MOV_KSL,
		ISNULL(ZF_OTHER_LIABILITY_MOV_OSL,0) AS ZF_OTHER_LIABILITY_MOV_OSL,
		--Short term Loans (liability)
		ISNULL(ZF_SHORT_TERM_LOAN_LIABILITY_BAL_HSL,0) AS ZF_SHORT_TERM_LOAN_LIABILITY_BAL_HSL,
		ISNULL(ZF_SHORT_TERM_LOAN_LIABILITY_BAL_CUC,0) AS ZF_SHORT_TERM_LOAN_LIABILITY_BAL_CUC,
		ISNULL(ZF_SHORT_TERM_LOAN_LIABILITY_BAL_KSL,0) AS ZF_SHORT_TERM_LOAN_LIABILITY_BAL_KSL,
		ISNULL(ZF_SHORT_TERM_LOAN_LIABILITY_BAL_OSL,0) AS ZF_SHORT_TERM_LOAN_LIABILITY_BAL_OSL,
		ISNULL(ZF_SHORT_TERM_LOAN_LIABILITY_MOV_HSL,0) AS ZF_SHORT_TERM_LOAN_LIABILITY_MOV_HSL,
		ISNULL(ZF_SHORT_TERM_LOAN_LIABILITY_MOV_CUC,0) AS ZF_SHORT_TERM_LOAN_LIABILITY_MOV_CUC,
		ISNULL(ZF_SHORT_TERM_LOAN_LIABILITY_MOV_KSL,0) AS ZF_SHORT_TERM_LOAN_LIABILITY_MOV_KSL,
		ISNULL(ZF_SHORT_TERM_LOAN_LIABILITY_MOV_OSL,0) AS ZF_SHORT_TERM_LOAN_LIABILITY_MOV_OSL,
		--Loans (liability)
		ISNULL(ZF_LOAN_LIABILITY_BAL_HSL,0) AS ZF_LOAN_LIABILITY_BAL_HSL,
		ISNULL(ZF_LOAN_LIABILITY_BAL_CUC,0) AS ZF_LOAN_LIABILITY_BAL_CUC,
		ISNULL(ZF_LOAN_LIABILITY_BAL_KSL,0) AS ZF_LOAN_LIABILITY_BAL_KSL,
		ISNULL(ZF_LOAN_LIABILITY_BAL_OSL,0) AS ZF_LOAN_LIABILITY_BAL_OSL,
		ISNULL(ZF_LOAN_LIABILITY_MOV_HSL,0) AS ZF_LOAN_LIABILITY_MOV_HSL,
		ISNULL(ZF_LOAN_LIABILITY_MOV_CUC,0) AS ZF_LOAN_LIABILITY_MOV_CUC,
		ISNULL(ZF_LOAN_LIABILITY_MOV_KSL,0) AS ZF_LOAN_LIABILITY_MOV_KSL,
		ISNULL(ZF_LOAN_LIABILITY_MOV_OSL,0) AS ZF_LOAN_LIABILITY_MOV_OSL,
		--Revenue/ Gross sales
		ISNULL(ZF_REVENUE_GROSS_SALE_BAL_HSL,0) AS ZF_REVENUE_GROSS_SALE_BAL_HSL,
		ISNULL(ZF_REVENUE_GROSS_SALE_BAL_CUC,0) AS ZF_REVENUE_GROSS_SALE_BAL_CUC,
		ISNULL(ZF_REVENUE_GROSS_SALE_BAL_KSL,0) AS ZF_REVENUE_GROSS_SALE_BAL_KSL,
		ISNULL(ZF_REVENUE_GROSS_SALE_BAL_OSL,0) AS ZF_REVENUE_GROSS_SALE_BAL_OSL,
		ISNULL(ZF_REVENUE_GROSS_SALE_MOV_HSL,0) AS ZF_REVENUE_GROSS_SALE_MOV_HSL,
		ISNULL(ZF_REVENUE_GROSS_SALE_MOV_CUC,0) AS ZF_REVENUE_GROSS_SALE_MOV_CUC,
		ISNULL(ZF_REVENUE_GROSS_SALE_MOV_KSL,0) AS ZF_REVENUE_GROSS_SALE_MOV_KSL,
		ISNULL(ZF_REVENUE_GROSS_SALE_MOV_OSL,0) AS ZF_REVENUE_GROSS_SALE_MOV_OSL,
		--Discounts/ reductions/ adjustments
		ISNULL(ZF_DISCOUNT_REDUCTION_ADJ_BAL_HSL,0) AS ZF_DISCOUNT_REDUCTION_ADJ_BAL_HSL,
		ISNULL(ZF_DISCOUNT_REDUCTION_ADJ_BAL_CUC,0) AS ZF_DISCOUNT_REDUCTION_ADJ_BAL_CUC,
		ISNULL(ZF_DISCOUNT_REDUCTION_ADJ_BAL_KSL,0) AS ZF_DISCOUNT_REDUCTION_ADJ_BAL_KSL,
		ISNULL(ZF_DISCOUNT_REDUCTION_ADJ_BAL_OSL,0) AS ZF_DISCOUNT_REDUCTION_ADJ_BAL_OSL,
		ISNULL(ZF_DISCOUNT_REDUCTION_ADJ_MOV_HSL,0) AS ZF_DISCOUNT_REDUCTION_ADJ_MOV_HSL,
		ISNULL(ZF_DISCOUNT_REDUCTION_ADJ_MOV_CUC,0) AS ZF_DISCOUNT_REDUCTION_ADJ_MOV_CUC,
		ISNULL(ZF_DISCOUNT_REDUCTION_ADJ_MOV_KSL,0) AS ZF_DISCOUNT_REDUCTION_ADJ_MOV_KSL,
		ISNULL(ZF_DISCOUNT_REDUCTION_ADJ_MOV_OSL,0) AS ZF_DISCOUNT_REDUCTION_ADJ_MOV_OSL,
		--COGS
		ISNULL(ZF_COGS_BAL_HSL,0) AS ZF_COGS_BAL_HSL,
		ISNULL(ZF_COGS_BAL_CUC,0) AS ZF_COGS_BAL_CUC,
		ISNULL(ZF_COGS_BAL_KSL,0) AS ZF_COGS_BAL_KSL,
		ISNULL(ZF_COGS_BAL_OSL,0) AS ZF_COGS_BAL_OSL,
		ISNULL(ZF_COGS_MOV_HSL,0) AS ZF_COGS_MOV_HSL,
		ISNULL(ZF_COGS_MOV_CUC,0) AS ZF_COGS_MOV_CUC,
		ISNULL(ZF_COGS_MOV_KSL,0) AS ZF_COGS_MOV_KSL,
		ISNULL(ZF_COGS_MOV_OSL,0) AS ZF_COGS_MOV_OSL,
		--Other Revenue/ Other operating Revenue
		ISNULL(ZF_OTHER_REVENUE_BAL_HSL,0) AS ZF_OTHER_REVENUE_BAL_HSL,
		ISNULL(ZF_OTHER_REVENUE_BAL_CUC,0) AS ZF_OTHER_REVENUE_BAL_CUC,
		ISNULL(ZF_OTHER_REVENUE_BAL_KSL,0) AS ZF_OTHER_REVENUE_BAL_KSL,
		ISNULL(ZF_OTHER_REVENUE_BAL_OSL,0) AS ZF_OTHER_REVENUE_BAL_OSL,
		ISNULL(ZF_OTHER_REVENUE_MOV_HSL,0) AS ZF_OTHER_REVENUE_MOV_HSL,
		ISNULL(ZF_OTHER_REVENUE_MOV_CUC,0) AS ZF_OTHER_REVENUE_MOV_CUC,
		ISNULL(ZF_OTHER_REVENUE_MOV_KSL,0) AS ZF_OTHER_REVENUE_MOV_KSL,
		ISNULL(ZF_OTHER_REVENUE_MOV_OSL,0) AS ZF_OTHER_REVENUE_MOV_OSL,
		--Expenditure
		ISNULL(ZF_EXPENDITURE_BAL_HSL,0) AS ZF_EXPENDITURE_BAL_HSL,
		ISNULL(ZF_EXPENDITURE_BAL_CUC,0) AS ZF_EXPENDITURE_BAL_CUC,
		ISNULL(ZF_EXPENDITURE_BAL_KSL,0) AS ZF_EXPENDITURE_BAL_KSL,
		ISNULL(ZF_EXPENDITURE_BAL_OSL,0) AS ZF_EXPENDITURE_BAL_OSL,
		ISNULL(ZF_EXPENDITURE_MOV_HSL,0) AS ZF_EXPENDITURE_MOV_HSL,
		ISNULL(ZF_EXPENDITURE_MOV_CUC,0) AS ZF_EXPENDITURE_MOV_CUC,
		ISNULL(ZF_EXPENDITURE_MOV_KSL,0) AS ZF_EXPENDITURE_MOV_KSL,
		ISNULL(ZF_EXPENDITURE_MOV_OSL,0) AS ZF_EXPENDITURE_MOV_OSL,
		-- euiqty/securitty
		ISNULL(ZF_EQUITY_SECURITY_BAL_HSL,0) AS ZF_EQUITY_SECURITY_BAL_HSL,
		ISNULL(ZF_EQUITY_SECURITY_BAL_CUC,0) AS ZF_EQUITY_SECURITY_BAL_CUC,
		ISNULL(ZF_EQUITY_SECURITY_BAL_KSL,0) AS ZF_EQUITY_SECURITY_BAL_KSL,
		ISNULL(ZF_EQUITY_SECURITY_BAL_OSL,0) AS ZF_EQUITY_SECURITY_BAL_OSL,
		ISNULL(ZF_EQUITY_SECURITY_MOV_HSL,0) AS ZF_EQUITY_SECURITY_MOV_HSL,
		ISNULL(ZF_EQUITY_SECURITY_MOV_CUC,0) AS ZF_EQUITY_SECURITY_MOV_CUC,
		ISNULL(ZF_EQUITY_SECURITY_MOV_KSL,0) AS ZF_EQUITY_SECURITY_MOV_KSL,
		ISNULL(ZF_EQUITY_SECURITY_MOV_OSL,0) AS ZF_EQUITY_SECURITY_MOV_OSL,
		--Common stock (shares)
		ISNULL(ZF_COMMON_STOCK_BAL_HSL,0) AS ZF_COMMON_STOCK_BAL_HSL,
		ISNULL(ZF_COMMON_STOCK_BAL_CUC,0) AS ZF_COMMON_STOCK_BAL_CUC,
		ISNULL(ZF_COMMON_STOCK_BAL_KSL,0) AS ZF_COMMON_STOCK_BAL_KSL,
		ISNULL(ZF_COMMON_STOCK_BAL_OSL,0) AS ZF_COMMON_STOCK_BAL_OSL,
		ISNULL(ZF_COMMON_STOCK_MOV_HSL,0) AS ZF_COMMON_STOCK_MOV_HSL,
		ISNULL(ZF_COMMON_STOCK_MOV_CUC,0) AS ZF_COMMON_STOCK_MOV_CUC,
		ISNULL(ZF_COMMON_STOCK_MOV_KSL,0) AS ZF_COMMON_STOCK_MOV_KSL,
		ISNULL(ZF_COMMON_STOCK_MOV_OSL,0) AS ZF_COMMON_STOCK_MOV_OSL,
		--Capital
		ISNULL(ZF_CAPITAL_BAL_HSL,0) AS ZF_CAPITAL_BAL_HSL,
		ISNULL(ZF_CAPITAL_BAL_CUC,0) AS ZF_CAPITAL_BAL_CUC,
		ISNULL(ZF_CAPITAL_BAL_KSL,0) AS ZF_CAPITAL_BAL_KSL,
		ISNULL(ZF_CAPITAL_BAL_OSL,0) AS ZF_CAPITAL_BAL_OSL,
		ISNULL(ZF_CAPITAL_MOV_HSL,0) AS ZF_CAPITAL_MOV_HSL,
		ISNULL(ZF_CAPITAL_MOV_CUC,0) AS ZF_CAPITAL_MOV_CUC,
		ISNULL(ZF_CAPITAL_MOV_KSL,0) AS ZF_CAPITAL_MOV_KSL,
		ISNULL(ZF_CAPITAL_MOV_OSL,0) AS ZF_CAPITAL_MOV_OSL,
		--Retained earnings
		ISNULL(ZF_RETAIN_EARNING_BAL_HSL,0) AS ZF_RETAIN_EARNING_BAL_HSL,
		ISNULL(ZF_RETAIN_EARNING_BAL_CUC,0) AS ZF_RETAIN_EARNING_BAL_CUC,
		ISNULL(ZF_RETAIN_EARNING_BAL_KSL,0) AS ZF_RETAIN_EARNING_BAL_KSL,
		ISNULL(ZF_RETAIN_EARNING_BAL_OSL,0) AS ZF_RETAIN_EARNING_BAL_OSL,
		ISNULL(ZF_RETAIN_EARNING_MOV_HSL,0) AS ZF_RETAIN_EARNING_MOV_HSL,
		ISNULL(ZF_RETAIN_EARNING_MOV_CUC,0) AS ZF_RETAIN_EARNING_MOV_CUC,
		ISNULL(ZF_RETAIN_EARNING_MOV_KSL,0) AS ZF_RETAIN_EARNING_MOV_KSL,
		ISNULL(ZF_RETAIN_EARNING_MOV_OSL,0) AS ZF_RETAIN_EARNING_MOV_OSL,
		--Other adjustments (FX adj# etc)
		ISNULL(ZF_OTHER_ADJ_BAL_HSL,0) AS ZF_OTHER_ADJ_BAL_HSL,
		ISNULL(ZF_OTHER_ADJ_BAL_CUC,0) AS ZF_OTHER_ADJ_BAL_CUC,
		ISNULL(ZF_OTHER_ADJ_BAL_KSL,0) AS ZF_OTHER_ADJ_BAL_KSL,
		ISNULL(ZF_OTHER_ADJ_BAL_OSL,0) AS ZF_OTHER_ADJ_BAL_OSL,
		ISNULL(ZF_OTHER_ADJ_MOV_HSL,0) AS ZF_OTHER_ADJ_MOV_HSL,
		ISNULL(ZF_OTHER_ADJ_MOV_CUC,0) AS ZF_OTHER_ADJ_MOV_CUC,
		ISNULL(ZF_OTHER_ADJ_MOV_KSL,0) AS ZF_OTHER_ADJ_MOV_KSL,
		ISNULL(ZF_OTHER_ADJ_MOV_OSL,0) AS ZF_OTHER_ADJ_MOV_OSL,
		--RIght to use asset
		ISNULL(ZF_RIGHT_ASSET_BAL_HSL,0) AS ZF_RIGHT_ASSET_BAL_HSL,
		ISNULL(ZF_RIGHT_ASSET_BAL_CUC,0) AS ZF_RIGHT_ASSET_BAL_CUC,
		ISNULL(ZF_RIGHT_ASSET_BAL_KSL,0) AS ZF_RIGHT_ASSET_BAL_KSL,
		ISNULL(ZF_RIGHT_ASSET_BAL_OSL,0) AS ZF_RIGHT_ASSET_BAL_OSL,
		ISNULL(ZF_RIGHT_ASSET_MOV_HSL,0) AS ZF_RIGHT_ASSET_MOV_HSL,
		ISNULL(ZF_RIGHT_ASSET_MOV_CUC,0) AS ZF_RIGHT_ASSET_MOV_CUC,
		ISNULL(ZF_RIGHT_ASSET_MOV_KSL,0) AS ZF_RIGHT_ASSET_MOV_KSL,
		ISNULL(ZF_RIGHT_ASSET_MOV_OSL,0) AS ZF_RIGHT_ASSET_MOV_OSL,
--[Depreciation/ amortization P&L]	
		ISNULL(ZF_DEPRECIATION_BAL_HSL,0) AS ZF_DEPRECIATION_BAL_HSL,
		ISNULL(ZF_DEPRECIATION_BAL_CUC,0) AS ZF_DEPRECIATION_BAL_CUC,
		ISNULL(ZF_DEPRECIATION_BAL_KSL,0) AS ZF_DEPRECIATION_BAL_KSL,
		ISNULL(ZF_DEPRECIATION_BAL_OSL,0) AS ZF_DEPRECIATION_BAL_OSL,
		ISNULL(ZF_DEPRECIATION_MOV_HSL,0) AS ZF_DEPRECIATION_MOV_HSL,
		ISNULL(ZF_DEPRECIATION_MOV_CUC,0) AS ZF_DEPRECIATION_MOV_CUC,
		ISNULL(ZF_DEPRECIATION_MOV_KSL,0) AS ZF_DEPRECIATION_MOV_KSL,
		ISNULL(ZF_DEPRECIATION_MOV_OSL,0) AS ZF_DEPRECIATION_MOV_OSL,
--[Production costs] 
		ISNULL(ZF_PRODUCTION_COST_BAL_HSL,0) AS ZF_PRODUCTION_COST_BAL_HSL,
		ISNULL(ZF_PRODUCTION_COST_BAL_CUC,0) AS ZF_PRODUCTION_COST_BAL_CUC,
		ISNULL(ZF_PRODUCTION_COST_BAL_KSL,0) AS ZF_PRODUCTION_COST_BAL_KSL,
		ISNULL(ZF_PRODUCTION_COST_BAL_OSL,0) AS ZF_PRODUCTION_COST_BAL_OSL,
		ISNULL(ZF_PRODUCTION_COST_MOV_HSL,0) AS ZF_PRODUCTION_COST_MOV_HSL,
		ISNULL(ZF_PRODUCTION_COST_MOV_CUC,0) AS ZF_PRODUCTION_COST_MOV_CUC,
		ISNULL(ZF_PRODUCTION_COST_MOV_KSL,0) AS ZF_PRODUCTION_COST_MOV_KSL,
		ISNULL(ZF_PRODUCTION_COST_MOV_OSL,0) AS ZF_PRODUCTION_COST_MOV_OSL

INTO B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT
FROM
B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
LEFT JOIN 
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_CASH_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_CASH_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_CASH_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_CASH_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_CASH_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_CASH_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_CASH_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_CASH_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Cash'
) AS A ON  B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=A.B03_04_ACDOCA_RYEAR
		AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=A.B03_04_ACDOCA_MONAT
		AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=A.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_FIX_ASSET_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_FIX_ASSET_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_FIX_ASSET_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_FIX_ASSET_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_FIX_ASSET_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_FIX_ASSET_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_FIX_ASSET_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_FIX_ASSET_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Fixed assets'
) AS B ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B.B03_04_ACDOCA_RYEAR 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B.B03_04_ACDOCA_RBUKRS

LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_INVENTORY_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_INVENTORY_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_INVENTORY_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_INVENTORY_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_INVENTORY_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_INVENTORY_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_INVENTORY_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_INVENTORY_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Inventory'
) AS B1 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B1.B03_04_ACDOCA_RYEAR 
    AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B1.B03_04_ACDOCA_MONAT
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B1.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_OTHER_ASS_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_OTHER_ASS_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_OTHER_ASS_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_OTHER_ASS_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_OTHER_ASS_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_OTHER_ASS_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_OTHER_ASS_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_OTHER_ASS_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Other assets'
) AS B2 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B2.B03_04_ACDOCA_RYEAR
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B2.B03_04_ACDOCA_MONAT
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B2.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_SHORT_LOAN_ASS_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_SHORT_LOAN_ASS_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_SHORT_LOAN_ASS_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_SHORT_LOAN_ASS_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_SHORT_LOAN_ASS_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_SHORT_LOAN_ASS_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_SHORT_LOAN_ASS_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_SHORT_LOAN_ASS_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Short term loans(asset)'
) AS B3 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B3.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B3.B03_04_ACDOCA_MONAT
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B3.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_LOAN_ASS_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_LOAN_ASS_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_LOAN_ASS_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_LOAN_ASS_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_LOAN_ASS_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_LOAN_ASS_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_LOAN_ASS_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_LOAN_ASS_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Loans (asset)'
) AS B4 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B4.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B4.B03_04_ACDOCA_MONAT
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B4.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_AR_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_AR_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_AR_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_AR_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_AR_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_AR_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_AR_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_AR_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Accounts receivables (AR)'
) AS B5 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B5.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B5.B03_04_ACDOCA_MONAT
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B5.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_ACCRUAl_DEF_INCOM_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_ACCRUAl_DEF_INCOM_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_ACCRUAl_DEF_INCOM_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_ACCRUAl_DEF_INCOM_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_ACCRUAl_DEF_INCOM_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_ACCRUAl_DEF_INCOM_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_ACCRUAl_DEF_INCOM_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_ACCRUAl_DEF_INCOM_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Accrual: Deferred income'
) AS B6 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B6.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B6.B03_04_ACDOCA_MONAT
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B6.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_AP_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_AP_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_AP_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_AP_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_AP_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_AP_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_AP_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_AP_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Accounts payable (AP)'
) AS B7 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B7.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B7.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B7.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Accrued expense/ deferred liabilities'
) AS B8 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B8.B03_04_ACDOCA_RYEAR AND
B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B8.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B8.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_PROVI_LIABILITY_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_PROVI_LIABILITY_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_PROVI_LIABILITY_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_PROVI_LIABILITY_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_PROVI_LIABILITY_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_PROVI_LIABILITY_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_PROVI_LIABILITY_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_PROVI_LIABILITY_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Provision liability'
) AS B9 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B9.B03_04_ACDOCA_RYEAR AND 
B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B9.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B9.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_OTHER_LIABILITY_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_OTHER_LIABILITY_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_OTHER_LIABILITY_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_OTHER_LIABILITY_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_OTHER_LIABILITY_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_OTHER_LIABILITY_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_OTHER_LIABILITY_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_OTHER_LIABILITY_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Other liabilities'
) AS B10 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B10.B03_04_ACDOCA_RYEAR AND 
B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B10.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B10.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_SHORT_TERM_LOAN_LIABILITY_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_SHORT_TERM_LOAN_LIABILITY_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_SHORT_TERM_LOAN_LIABILITY_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_SHORT_TERM_LOAN_LIABILITY_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_SHORT_TERM_LOAN_LIABILITY_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_SHORT_TERM_LOAN_LIABILITY_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_SHORT_TERM_LOAN_LIABILITY_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_SHORT_TERM_LOAN_LIABILITY_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Short term loans (liability)'
) AS B11 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B11.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B11.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B11.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_LOAN_LIABILITY_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_LOAN_LIABILITY_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_LOAN_LIABILITY_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_LOAN_LIABILITY_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_LOAN_LIABILITY_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_LOAN_LIABILITY_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_LOAN_LIABILITY_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_LOAN_LIABILITY_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Loans (liability)'
) AS B12 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B12.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B12.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B12.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_REVENUE_GROSS_SALE_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_REVENUE_GROSS_SALE_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_REVENUE_GROSS_SALE_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_REVENUE_GROSS_SALE_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_REVENUE_GROSS_SALE_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_REVENUE_GROSS_SALE_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_REVENUE_GROSS_SALE_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_REVENUE_GROSS_SALE_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Revenue/ Gross sales'
) AS B13 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B13.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B13.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B13.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_DISCOUNT_REDUCTION_ADJ_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_DISCOUNT_REDUCTION_ADJ_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_DISCOUNT_REDUCTION_ADJ_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_DISCOUNT_REDUCTION_ADJ_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_DISCOUNT_REDUCTION_ADJ_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_DISCOUNT_REDUCTION_ADJ_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_DISCOUNT_REDUCTION_ADJ_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_DISCOUNT_REDUCTION_ADJ_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Discounts/ reductions/ adjustments'
) AS B14 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B14.B03_04_ACDOCA_RYEAR
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B14.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B14.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_COGS_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_COGS_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_COGS_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_COGS_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_COGS_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_COGS_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_COGS_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_COGS_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='COGS'
) AS B15 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B15.B03_04_ACDOCA_RYEAR AND
B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B15.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B15.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_OTHER_REVENUE_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_OTHER_REVENUE_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_OTHER_REVENUE_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_OTHER_REVENUE_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_OTHER_REVENUE_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_OTHER_REVENUE_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_OTHER_REVENUE_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_OTHER_REVENUE_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Other revenue/ other operating revenue'
) AS B16 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B16.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B16.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B16.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_EXPENDITURE_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_EXPENDITURE_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_EXPENDITURE_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_EXPENDITURE_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_EXPENDITURE_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_EXPENDITURE_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_EXPENDITURE_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_EXPENDITURE_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Expenditure'
) AS B17 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B17.B03_04_ACDOCA_RYEAR AND
B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B17.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B17.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_EQUITY_SECURITY_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_EQUITY_SECURITY_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_EQUITY_SECURITY_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_EQUITY_SECURITY_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_EQUITY_SECURITY_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_EQUITY_SECURITY_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_EQUITY_SECURITY_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_EQUITY_SECURITY_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Equity/ securities'
) AS B18 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B18.B03_04_ACDOCA_RYEAR AND
B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B18.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B18.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_COMMON_STOCK_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_COMMON_STOCK_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_COMMON_STOCK_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_COMMON_STOCK_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_COMMON_STOCK_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_COMMON_STOCK_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_COMMON_STOCK_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_COMMON_STOCK_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Common stock (shares)'
) AS B19 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B19.B03_04_ACDOCA_RYEAR
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B19.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B19.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_CAPITAL_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_CAPITAL_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_CAPITAL_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_CAPITAL_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_CAPITAL_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_CAPITAL_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_CAPITAL_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_CAPITAL_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Capital'
) AS B20 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B20.B03_04_ACDOCA_RYEAR AND
B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B20.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B20.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_RETAIN_EARNING_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_RETAIN_EARNING_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_RETAIN_EARNING_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_RETAIN_EARNING_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_RETAIN_EARNING_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_RETAIN_EARNING_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_RETAIN_EARNING_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_RETAIN_EARNING_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Retained earnings'
) AS B21 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B21.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B21.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B21.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_OTHER_ADJ_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_OTHER_ADJ_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_OTHER_ADJ_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_OTHER_ADJ_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_OTHER_ADJ_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_OTHER_ADJ_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_OTHER_ADJ_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_OTHER_ADJ_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Other adjustments (FX adj# etc)'
) AS B22 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B22.B03_04_ACDOCA_RYEAR
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B22.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B22.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_RIGHT_ASSET_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_RIGHT_ASSET_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_RIGHT_ASSET_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_RIGHT_ASSET_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_RIGHT_ASSET_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_RIGHT_ASSET_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_RIGHT_ASSET_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_RIGHT_ASSET_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Right-of-use assets'
) AS B23 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B23.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B23.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B23.B03_04_ACDOCA_RBUKRS
LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_DEPRECIATION_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_DEPRECIATION_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_DEPRECIATION_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_DEPRECIATION_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_DEPRECIATION_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_DEPRECIATION_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_DEPRECIATION_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_DEPRECIATION_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Depreciation/ amortization P&L'
) AS B24 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B24.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B24.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B24.B03_04_ACDOCA_RBUKRS

 

LEFT JOIN
(
	SELECT DISTINCT 
		B03_04_ACDOCA_RYEAR,B03_04_ACDOCA_MONAT,B03_04_ACDOCA_RBUKRS,
		ZF_BALANCE_ACDOCA_HSL AS ZF_PRODUCTION_COST_BAL_HSL,
		ZF_BALANCE_ACDOCA_HSL_CUC AS ZF_PRODUCTION_COST_BAL_CUC ,
		ZF_BALANCE_ACDOCA_KSL AS ZF_PRODUCTION_COST_BAL_KSL,
		ZF_BALANCE_ACDOCA_OSL AS ZF_PRODUCTION_COST_BAL_OSL,
		ZF_MOV_ACDOCA_HSL AS ZF_PRODUCTION_COST_MOV_HSL,
		ZF_MOV_ACDOCA_HSL_CUC AS ZF_PRODUCTION_COST_MOV_CUC,
		ZF_MOV_ACDOCA_KSL AS ZF_PRODUCTION_COST_MOV_KSL,
		ZF_MOV_ACDOCA_OSL AS ZF_PRODUCTION_COST_MOV_OSL
	FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
	WHERE ZF_CATEGORY='Production costs'
) AS B25 ON B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RYEAR=B25.B03_04_ACDOCA_RYEAR 
AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_MONAT=B25.B03_04_ACDOCA_MONAT 
	AND B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH.B03_04_ACDOCA_RBUKRS=B25.B03_04_ACDOCA_RBUKRS
--Step 6 Caculate the compound category

--Step 6.1 Create the compound category fields
ALTER TABLE B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT
ADD ZF_TOTAL_LIABILITY_NET_HSL  MONEY ,
ZF_TOTAL_LIABILITY_NET_HSL_CUC  MONEY ,
ZF_TOTAL_LIABILITY_NET_KSL  MONEY ,
ZF_TOTAL_LIABILITY_NET_OSL  MONEY ,
ZF_TOTAL_LIABILITY_BAL_HSL  MONEY ,
ZF_TOTAL_LIABILITY_BAL_HSL_CUC  MONEY ,
ZF_TOTAL_LIABILITY_BAL_OSL  MONEY ,
ZF_TOTAL_LIABILITY_BAL_KSL  MONEY ,
ZF_EQUITY_NET_HSL  MONEY ,
ZF_EQUITY_NET_HSL_CUC  MONEY ,
ZF_EQUITY_NET_OSL  MONEY ,
ZF_EQUITY_NET_KSL  MONEY ,
ZF_EQUITY_BAL_HSL  MONEY ,
ZF_EQUITY_BAL_HSL_CUC  MONEY ,
ZF_EQUITY_BAL_OSL  MONEY ,
ZF_EQUITY_BAL_KSL  MONEY ,
ZF_CURRENT_ASSET_NET_HSL  MONEY ,
ZF_CURRENT_ASSET_NET_HSL_CUC  MONEY ,
ZF_CURRENT_ASSET_NET_OSL  MONEY ,
ZF_CURRENT_ASSET_NET_KSL  MONEY ,
ZF_CURRENT_ASSET_BAL_HSL  MONEY ,
ZF_CURRENT_ASSET_BAL_HSL_CUC  MONEY ,
ZF_CURRENT_ASSET_BAL_OSL  MONEY ,
ZF_CURRENT_ASSET_BAL_KSL  MONEY ,
ZF_CURRENT_LIABILITY_NET_HSL  MONEY ,
ZF_CURRENT_LIABILITY_NET_HSL_CUC   MONEY ,
ZF_CURRENT_LIABILITY_NET_OSL  MONEY ,
ZF_CURRENT_LIABILITY_NET_KSL  MONEY ,
ZF_CURRENT_LIABILITY_BAL_HSL  MONEY ,
ZF_CURRENT_LIABILITY_BAL_HSL_CUC  MONEY ,
ZF_CURRENT_LIABILITY_BAL_OSL  MONEY ,
ZF_CURRENT_LIABILITY_BAL_KSL  MONEY ,
ZF_NET_SALE_NET_HSL  MONEY ,
ZF_NET_SALE_NET_HSL_CUC  MONEY ,
ZF_NET_SALE_NET_OSL  MONEY ,
ZF_NET_SALE_NET_KSL  MONEY ,
ZF_NET_SAL_BAL_HSL  MONEY,
ZF_NET_SAL_BAL_HSL_CUC  MONEY,
ZF_NET_SAL_BAL_OSL  MONEY,
ZF_NET_SAL_BAL_KSL  MONEY,
--EBIT
ZF_EBIT_NET_HSL  MONEY ,
ZF_EBIT_NET_HSL_CUC  MONEY ,
ZF_EBIT_NET_OSL  MONEY ,
ZF_EBIT_NET_KSL  MONEY ,
ZF_EBIT_SAL_BAL_HSL  MONEY,
ZF_EBIT_SAL_BAL_HSL_CUC  MONEY,
ZF_EBIT_SAL_BAL_OSL  MONEY,
ZF_EBIT_SAL_BAL_KSL  MONEY,
--Gross profit- new update
ZF_GROSS_PROFIT_NET_HSL  MONEY ,
ZF_GROSS_PROFIT_NET_HSL_CUC  MONEY ,
ZF_GROSS_PROFIT_NET_OSL  MONEY ,
ZF_GROSS_PROFIT_NET_KSL  MONEY ,
ZF_GROSS_PROFIT_BAL_HSL  MONEY,
ZF_GROSS_PROFIT_BAL_HSL_CUC  MONEY,
ZF_GROSS_PROFIT_BAL_OSL  MONEY,
ZF_GROSS_PROFIT_BAL_KSL  MONEY

--Update the value of each field, caculate in both movment and balance
--Method for caculation:
--Total liabilities =   (Accounts payable (AP)+Accrued expense/ deferred liabilities+Provision liability	+Other liabilities+Short term loans(liability)+	Loans (liability))
--Current liabilities =   (Accounts payable (AP)+Accrued expense/ deferred liabilities+Provision liability	+Other liabilities+Short term loans(liability))
--Equity = (Equity/ securities+Common stock (shares)+Retained earnings)
--Current assets =(Cash+Fixed assets+Inventory+Short term loans+Accounts receivables (AR)+Accrual: Deferred income)
--Gross profit =( Revenue/ Gross sales)+COGS+Discounts/ reductions/ adjustments
--Net sales =( Revenue/ Gross sales)+Discounts/ reductions/ adjustments
--EBIT=net sale +(COGS+expenditure)

UPDATE  B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT
SET 
--Total liabilities
	ZF_TOTAL_LIABILITY_NET_HSL=(ZF_AP_MOV_HSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_HSL+ZF_PROVI_LIABILITY_MOV_HSL+ZF_OTHER_LIABILITY_MOV_HSL+ZF_LOAN_LIABILITY_MOV_HSL+ZF_SHORT_TERM_LOAN_LIABILITY_MOV_HSL),
	ZF_TOTAL_LIABILITY_NET_HSL_CUC=(ZF_AP_MOV_CUC+ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_CUC+ZF_PROVI_LIABILITY_MOV_CUC+ZF_OTHER_LIABILITY_MOV_CUC+ZF_LOAN_LIABILITY_MOV_CUC+ZF_SHORT_TERM_LOAN_LIABILITY_MOV_CUC ),
	ZF_TOTAL_LIABILITY_NET_KSL=(ZF_AP_MOV_KSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_KSL+ZF_PROVI_LIABILITY_MOV_KSL+ZF_OTHER_LIABILITY_MOV_KSL+ZF_LOAN_LIABILITY_MOV_KSL+ZF_SHORT_TERM_LOAN_LIABILITY_MOV_KSL),
	ZF_TOTAL_LIABILITY_NET_OSL=(ZF_AP_MOV_OSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_OSL+ZF_PROVI_LIABILITY_MOV_OSL+ZF_OTHER_LIABILITY_MOV_OSL+ZF_LOAN_LIABILITY_MOV_OSL+ZF_SHORT_TERM_LOAN_LIABILITY_MOV_OSL) ,
	ZF_TOTAL_LIABILITY_BAL_HSL=(ZF_AP_BAL_HSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_HSL+ZF_PROVI_LIABILITY_BAL_HSL+ZF_OTHER_LIABILITY_BAL_HSL+ZF_LOAN_LIABILITY_BAL_HSL+ZF_SHORT_TERM_LOAN_LIABILITY_BAL_HSL) ,
	ZF_TOTAL_LIABILITY_BAL_HSL_CUC=(ZF_AP_BAL_CUC+ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_CUC+ZF_PROVI_LIABILITY_BAL_CUC+ZF_OTHER_LIABILITY_BAL_CUC+ZF_LOAN_LIABILITY_BAL_CUC+ZF_SHORT_TERM_LOAN_LIABILITY_BAL_CUC) ,
	ZF_TOTAL_LIABILITY_BAL_OSL=(ZF_AP_BAL_OSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_OSL+ZF_PROVI_LIABILITY_BAL_OSL+ZF_OTHER_LIABILITY_BAL_OSL+ZF_LOAN_LIABILITY_BAL_OSL+ZF_SHORT_TERM_LOAN_LIABILITY_BAL_OSL) ,
	ZF_TOTAL_LIABILITY_BAL_KSL=(ZF_AP_BAL_KSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_KSL+ZF_PROVI_LIABILITY_BAL_KSL+ZF_OTHER_LIABILITY_BAL_KSL+ZF_LOAN_LIABILITY_BAL_KSL+ZF_SHORT_TERM_LOAN_LIABILITY_BAL_KSL) ,
--Equity
	ZF_EQUITY_NET_HSL= ZF_EQUITY_SECURITY_MOV_HSL+ZF_COMMON_STOCK_MOV_HSL+ZF_RETAIN_EARNING_MOV_HSL ,
	ZF_EQUITY_NET_HSL_CUC= ZF_EQUITY_SECURITY_MOV_CUC+ZF_COMMON_STOCK_MOV_CUC+ZF_RETAIN_EARNING_MOV_CUC,
	ZF_EQUITY_NET_OSL= ZF_EQUITY_SECURITY_MOV_OSL+ZF_COMMON_STOCK_MOV_OSL+ZF_RETAIN_EARNING_MOV_OSL ,
	ZF_EQUITY_NET_KSL= ZF_EQUITY_SECURITY_MOV_KSL+ZF_COMMON_STOCK_MOV_KSL+ZF_RETAIN_EARNING_MOV_KSL,
	ZF_EQUITY_BAL_HSL= ZF_EQUITY_SECURITY_BAL_HSL+ZF_COMMON_STOCK_BAL_HSL+ZF_RETAIN_EARNING_BAL_HSL,
	ZF_EQUITY_BAL_HSL_CUC= ZF_EQUITY_SECURITY_BAL_CUC+ZF_COMMON_STOCK_BAL_CUC+ZF_RETAIN_EARNING_BAL_CUC,
	ZF_EQUITY_BAL_OSL= ZF_EQUITY_SECURITY_BAL_OSL+ZF_COMMON_STOCK_BAL_OSL+ZF_RETAIN_EARNING_BAL_OSL,
	ZF_EQUITY_BAL_KSL= ZF_EQUITY_SECURITY_BAL_KSL+ZF_COMMON_STOCK_BAL_KSL+ZF_RETAIN_EARNING_BAL_KSL ,
--Current assets
	ZF_CURRENT_ASSET_NET_HSL=ZF_CASH_MOV_HSL+ZF_FIX_ASSET_MOV_HSL+ZF_INVENTORY_MOV_HSL+ZF_SHORT_LOAN_ASS_MOV_HSL+ZF_AR_MOV_HSL+ZF_ACCRUAl_DEF_INCOM_MOV_HSL,
	ZF_CURRENT_ASSET_NET_HSL_CUC=ZF_CASH_MOV_CUC+ZF_FIX_ASSET_MOV_CUC+ZF_INVENTORY_MOV_CUC+ZF_SHORT_LOAN_ASS_MOV_CUC+ZF_AR_MOV_CUC+ZF_ACCRUAl_DEF_INCOM_MOV_CUC,
	ZF_CURRENT_ASSET_NET_OSL=ZF_CASH_MOV_OSL+ZF_FIX_ASSET_MOV_OSL+ZF_INVENTORY_MOV_OSL+ZF_SHORT_LOAN_ASS_MOV_OSL+ZF_AR_MOV_OSL+ZF_ACCRUAl_DEF_INCOM_MOV_OSL,
	ZF_CURRENT_ASSET_NET_KSL=ZF_CASH_MOV_KSL+ZF_FIX_ASSET_MOV_KSL+ZF_INVENTORY_MOV_KSL+ZF_SHORT_LOAN_ASS_MOV_KSL+ZF_AR_MOV_KSL+ZF_ACCRUAl_DEF_INCOM_MOV_KSL,
	ZF_CURRENT_ASSET_BAL_HSL=ZF_CASH_BAL_HSL+ZF_FIX_ASSET_BAL_HSL+ZF_INVENTORY_BAL_HSL+ZF_SHORT_LOAN_ASS_BAL_HSL+ZF_AR_BAL_HSL+ZF_ACCRUAl_DEF_INCOM_BAL_HSL,
	ZF_CURRENT_ASSET_BAL_HSL_CUC=ZF_CASH_BAL_CUC+ZF_FIX_ASSET_BAL_CUC+ZF_INVENTORY_BAL_CUC+ZF_SHORT_LOAN_ASS_BAL_CUC +ZF_AR_BAL_CUC+ZF_ACCRUAl_DEF_INCOM_BAL_CUC,
	ZF_CURRENT_ASSET_BAL_OSL=ZF_CASH_BAL_OSL+ZF_FIX_ASSET_BAL_OSL+ZF_INVENTORY_BAL_OSL+ZF_SHORT_LOAN_ASS_BAL_OSL+ZF_AR_BAL_OSL+ZF_ACCRUAl_DEF_INCOM_BAL_OSL,
	ZF_CURRENT_ASSET_BAL_KSL=ZF_CASH_BAL_KSL+ZF_FIX_ASSET_BAL_KSL+ZF_INVENTORY_BAL_KSL+ZF_SHORT_LOAN_ASS_BAL_KSL+ZF_AR_BAL_KSL+ZF_ACCRUAl_DEF_INCOM_BAL_KSL,
--Current liabilities
	ZF_CURRENT_LIABILITY_NET_HSL=(ZF_AP_MOV_HSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_HSL+ZF_PROVI_LIABILITY_MOV_HSL+ZF_OTHER_LIABILITY_MOV_HSL+ZF_SHORT_TERM_LOAN_LIABILITY_MOV_HSL),
	ZF_CURRENT_LIABILITY_NET_HSL_CUC =(ZF_AP_MOV_CUC+ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_CUC+ZF_PROVI_LIABILITY_MOV_CUC+ZF_OTHER_LIABILITY_MOV_CUC+ZF_SHORT_TERM_LOAN_LIABILITY_MOV_CUC),
	ZF_CURRENT_LIABILITY_NET_OSL=(ZF_AP_MOV_OSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_OSL+ZF_PROVI_LIABILITY_MOV_OSL+ZF_OTHER_LIABILITY_MOV_OSL+ZF_SHORT_TERM_LOAN_LIABILITY_MOV_OSL),
	ZF_CURRENT_LIABILITY_NET_KSL=(ZF_AP_MOV_KSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_MOV_KSL+ZF_PROVI_LIABILITY_MOV_KSL+ZF_OTHER_LIABILITY_MOV_KSL+ZF_SHORT_TERM_LOAN_LIABILITY_MOV_KSL),
	ZF_CURRENT_LIABILITY_BAL_HSL=(ZF_AP_BAL_HSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_HSL+ZF_PROVI_LIABILITY_BAL_HSL+ZF_OTHER_LIABILITY_BAL_HSL+ZF_SHORT_TERM_LOAN_LIABILITY_BAL_HSL),
	ZF_CURRENT_LIABILITY_BAL_HSL_CUC=(ZF_AP_BAL_CUC+ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_CUC+ZF_PROVI_LIABILITY_BAL_CUC+ZF_OTHER_LIABILITY_BAL_CUC+ZF_SHORT_TERM_LOAN_LIABILITY_BAL_CUC),
	ZF_CURRENT_LIABILITY_BAL_OSL=(ZF_AP_BAL_OSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_OSL+ZF_PROVI_LIABILITY_BAL_OSL+ZF_OTHER_LIABILITY_BAL_OSL+ZF_SHORT_TERM_LOAN_LIABILITY_BAL_OSL),
	ZF_CURRENT_LIABILITY_BAL_KSL=(ZF_AP_BAL_KSL+ZF_ACCR_EXPENSE_DEFF_LIABILITY_BAL_KSL+ZF_PROVI_LIABILITY_BAL_KSL+ZF_OTHER_LIABILITY_BAL_KSL+ZF_SHORT_TERM_LOAN_LIABILITY_BAL_KSL),
--Gross profit
	ZF_GROSS_PROFIT_NET_HSL=(ZF_REVENUE_GROSS_SALE_MOV_HSL)+ZF_COGS_MOV_HSL+ZF_DISCOUNT_REDUCTION_ADJ_MOV_HSL,
	ZF_GROSS_PROFIT_NET_HSL_CUC= ZF_REVENUE_GROSS_SALE_MOV_CUC+ZF_COGS_MOV_CUC+ZF_DISCOUNT_REDUCTION_ADJ_MOV_CUC,
	ZF_GROSS_PROFIT_NET_OSL=( ZF_REVENUE_GROSS_SALE_MOV_OSL)+ZF_COGS_MOV_OSL+ZF_DISCOUNT_REDUCTION_ADJ_MOV_OSL,
	ZF_GROSS_PROFIT_NET_KSL=( ZF_REVENUE_GROSS_SALE_MOV_KSL)+ZF_COGS_MOV_KSL+ZF_DISCOUNT_REDUCTION_ADJ_MOV_KSL,
	ZF_GROSS_PROFIT_BAL_HSL=( ZF_REVENUE_GROSS_SALE_BAL_HSL)+ZF_COGS_BAL_HSL+ZF_DISCOUNT_REDUCTION_ADJ_BAL_HSL,
	ZF_GROSS_PROFIT_BAL_HSL_CUC=( ZF_REVENUE_GROSS_SALE_BAL_CUC)+ZF_COGS_BAL_CUC+ZF_DISCOUNT_REDUCTION_ADJ_BAL_CUC,
	ZF_GROSS_PROFIT_BAL_OSL=( ZF_REVENUE_GROSS_SALE_BAL_OSL)+ZF_COGS_BAL_OSL+ZF_DISCOUNT_REDUCTION_ADJ_BAL_OSL,
	ZF_GROSS_PROFIT_BAL_KSL=( ZF_REVENUE_GROSS_SALE_BAL_KSL)+ZF_COGS_BAL_KSL+ZF_DISCOUNT_REDUCTION_ADJ_BAL_KSL,
--Net sale
	ZF_NET_SALE_NET_HSL=( ZF_REVENUE_GROSS_SALE_MOV_HSL)+ZF_DISCOUNT_REDUCTION_ADJ_MOV_HSL,
	ZF_NET_SALE_NET_HSL_CUC=( ZF_REVENUE_GROSS_SALE_MOV_CUC)+ZF_DISCOUNT_REDUCTION_ADJ_MOV_CUC,
	ZF_NET_SALE_NET_OSL=( ZF_REVENUE_GROSS_SALE_MOV_OSL)+ZF_DISCOUNT_REDUCTION_ADJ_MOV_OSL,
	ZF_NET_SALE_NET_KSL=( ZF_REVENUE_GROSS_SALE_MOV_KSL)+ZF_DISCOUNT_REDUCTION_ADJ_MOV_KSL,
	ZF_NET_SAL_BAL_HSL=( ZF_REVENUE_GROSS_SALE_BAL_HSL)+ZF_DISCOUNT_REDUCTION_ADJ_BAL_HSL,
	ZF_NET_SAL_BAL_HSL_CUC=( ZF_REVENUE_GROSS_SALE_BAL_CUC)+ZF_DISCOUNT_REDUCTION_ADJ_BAL_CUC,
	ZF_NET_SAL_BAL_OSL=( ZF_REVENUE_GROSS_SALE_BAL_OSL)+ZF_DISCOUNT_REDUCTION_ADJ_BAL_OSL,
	ZF_NET_SAL_BAL_KSL=( ZF_REVENUE_GROSS_SALE_BAL_KSL)+ZF_DISCOUNT_REDUCTION_ADJ_BAL_KSL
--EBIT --Khoi update
UPDATE  B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT
SET 
	ZF_EBIT_NET_HSL=ZF_NET_SALE_NET_HSL+ZF_COGS_MOV_HSL+ZF_EXPENDITURE_MOV_HSL,
	ZF_EBIT_NET_HSL_CUC=ZF_NET_SALE_NET_HSL_CUC+ZF_COGS_MOV_CUC+ZF_EXPENDITURE_MOV_CUC,
	ZF_EBIT_NET_OSL=ZF_NET_SALE_NET_OSL+ZF_COGS_MOV_OSL+ZF_EXPENDITURE_MOV_OSL,
	ZF_EBIT_NET_KSL=ZF_NET_SALE_NET_KSL+ZF_COGS_MOV_KSL+ZF_EXPENDITURE_MOV_KSL,
	ZF_EBIT_SAL_BAL_HSL=ZF_NET_SAL_BAL_HSL+ZF_COGS_BAL_HSL +ZF_EXPENDITURE_BAL_HSL,
	ZF_EBIT_SAL_BAL_HSL_CUC=ZF_NET_SAL_BAL_HSL_CUC+ZF_COGS_BAL_CUC +ZF_EXPENDITURE_BAL_CUC,
	ZF_EBIT_SAL_BAL_OSL=ZF_NET_SAL_BAL_OSL+ZF_COGS_BAL_OSL+ZF_EXPENDITURE_BAL_OSL,
	ZF_EBIT_SAL_BAL_KSL=ZF_NET_SAL_BAL_KSL+ZF_COGS_BAL_KSL + ZF_EXPENDITURE_BAL_KSL

--Step 7 Append the compound category to singula category
--The category will have both singular and compound
-- For Total liabilities,Equity,Current asset,Current liabilities will flag as Balance
-- For Net sales will flag as Net 
EXEC SP_DROPTABLE B03_SS01_04_RT_APPEND_SINGULAR_COMPOUND_CATEGORY

SELECT 
	ZF_CATEGORY,
	B03_04_ACDOCA_RYEAR,
	B03_04_ACDOCA_MONAT,
	B03_04_ACDOCA_RBUKRS,
	ZF_BALANCE_NET_FLAG,
	B03_04_ZF_ACDOCA_POPER_MONTH,
	B03_04_T001_BUTXT,
	ZF_BALANCE_ACDOCA_HSL,	
	ZF_BALANCE_ACDOCA_HSL_CUC,
	ZF_BALANCE_ACDOCA_KSL,
	ZF_BALANCE_ACDOCA_OSL,
	ZF_MOV_ACDOCA_HSL,
	ZF_MOV_ACDOCA_HSL_CUC,
	ZF_MOV_ACDOCA_KSL,
	ZF_MOV_ACDOCA_OSL
INTO B03_SS01_04_RT_APPEND_SINGULAR_COMPOUND_CATEGORY
FROM B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH
UNION ALL
SELECT DISTINCT 
	'Total liabilities' AS ZF_CATEGORY,
	B03_04_ACDOCA_RYEAR,
	B03_04_ACDOCA_MONAT,
	B03_04_ACDOCA_RBUKRS,
	'Balance' AS ZF_BALANCE_NET_FLAG,
	B03_04_ZF_ACDOCA_POPER_MONTH,
	B03_04_T001_BUTXT,
	ZF_TOTAL_LIABILITY_BAL_HSL AS ZF_BALANCE_ACDOCA_HSL,	
	ZF_TOTAL_LIABILITY_BAL_HSL_CUC AS ZF_BALANCE_ACDOCA_HSL_CUC,
	ZF_TOTAL_LIABILITY_BAL_KSL AS ZF_BALANCE_ACDOCA_KSL,
	ZF_TOTAL_LIABILITY_BAL_OSL AS ZF_BALANCE_ACDOCA_OSL,
	ZF_TOTAL_LIABILITY_NET_HSL AS ZF_MOV_ACDOCA_HSL,
	ZF_TOTAL_LIABILITY_NET_HSL_CUC AS ZF_MOV_ACDOCA_HSL_CUC,
	ZF_TOTAL_LIABILITY_NET_KSL AS ZF_MOV_ACDOCA_KSL,
	ZF_TOTAL_LIABILITY_NET_OSL AS ZF_MOV_ACDOCA_OSL
FROM B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT
UNION ALL
SELECT DISTINCT 
	'Equity' AS ZF_CATEGORY,
	B03_04_ACDOCA_RYEAR,
	B03_04_ACDOCA_MONAT,
	B03_04_ACDOCA_RBUKRS,
	'Balance' AS ZF_BALANCE_NET_FLAG,
	B03_04_ZF_ACDOCA_POPER_MONTH,
	B03_04_T001_BUTXT,
	ZF_EQUITY_BAL_HSL AS ZF_BALANCE_ACDOCA_HSL,	
	ZF_EQUITY_BAL_HSL_CUC AS ZF_BALANCE_ACDOCA_HSL_CUC,
	ZF_EQUITY_BAL_KSL AS ZF_BALANCE_ACDOCA_KSL,
	ZF_EQUITY_BAL_OSL AS ZF_BALANCE_ACDOCA_OSL,
	ZF_EQUITY_NET_HSL AS ZF_MOV_ACDOCA_HSL,
	ZF_EQUITY_NET_HSL_CUC AS ZF_MOV_ACDOCA_HSL_CUC,
	ZF_EQUITY_NET_KSL AS ZF_MOV_ACDOCA_KSL,
	ZF_EQUITY_NET_OSL AS ZF_MOV_ACDOCA_OSL
FROM B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT						
UNION ALL
SELECT DISTINCT 
	'Current asset' AS ZF_CATEGORY,
	B03_04_ACDOCA_RYEAR,
	B03_04_ACDOCA_MONAT,
	B03_04_ACDOCA_RBUKRS,
	'Balance' AS ZF_BALANCE_NET_FLAG,
	B03_04_ZF_ACDOCA_POPER_MONTH,
	B03_04_T001_BUTXT,
	ZF_CURRENT_ASSET_BAL_HSL AS ZF_BALANCE_ACDOCA_HSL,	
	ZF_CURRENT_ASSET_BAL_HSL_CUC AS ZF_BALANCE_ACDOCA_HSL_CUC,
	ZF_CURRENT_ASSET_BAL_KSL AS ZF_BALANCE_ACDOCA_KSL,
	ZF_CURRENT_ASSET_BAL_OSL AS ZF_BALANCE_ACDOCA_OSL,
	ZF_CURRENT_ASSET_NET_HSL AS ZF_MOV_ACDOCA_HSL,
	ZF_CURRENT_ASSET_NET_HSL_CUC AS ZF_MOV_ACDOCA_HSL_CUC,
	ZF_CURRENT_ASSET_NET_KSL AS ZF_MOV_ACDOCA_KSL,
	ZF_CURRENT_ASSET_NET_OSL AS ZF_MOV_ACDOCA_OSL
FROM B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT
UNION ALL
SELECT DISTINCT 
	'Current liabilities' AS ZF_CATEGORY,
	B03_04_ACDOCA_RYEAR,
	B03_04_ACDOCA_MONAT,
	B03_04_ACDOCA_RBUKRS,
	'Balance' AS ZF_BALANCE_NET_FLAG,
	B03_04_ZF_ACDOCA_POPER_MONTH,
	B03_04_T001_BUTXT,
	ZF_CURRENT_LIABILITY_BAL_HSL AS ZF_BALANCE_ACDOCA_HSL,	
	ZF_CURRENT_LIABILITY_BAL_HSL_CUC AS ZF_BALANCE_ACDOCA_HSL_CUC,
	ZF_CURRENT_LIABILITY_BAL_KSL AS ZF_BALANCE_ACDOCA_KSL,
	ZF_CURRENT_LIABILITY_BAL_OSL AS ZF_BALANCE_ACDOCA_OSL,
	ZF_CURRENT_LIABILITY_NET_HSL AS ZF_MOV_ACDOCA_HSL,
	ZF_CURRENT_LIABILITY_NET_HSL_CUC AS ZF_MOV_ACDOCA_HSL_CUC,
	ZF_CURRENT_LIABILITY_NET_KSL AS ZF_MOV_ACDOCA_KSL,
	ZF_CURRENT_LIABILITY_NET_OSL AS ZF_MOV_ACDOCA_OSL
FROM B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT
UNION ALL
SELECT DISTINCT 
	'Net sales' AS ZF_CATEGORY,
	B03_04_ACDOCA_RYEAR,
	B03_04_ACDOCA_MONAT,
	B03_04_ACDOCA_RBUKRS,
	'Net' AS ZF_BALANCE_NET_FLAG,
	B03_04_ZF_ACDOCA_POPER_MONTH,
	B03_04_T001_BUTXT,
	ZF_NET_SAL_BAL_HSL AS ZF_BALANCE_ACDOCA_HSL,	
	ZF_NET_SAL_BAL_OSL AS ZF_BALANCE_ACDOCA_HSL_CUC,
	ZF_NET_SAL_BAL_KSL AS ZF_BALANCE_ACDOCA_KSL,
	ZF_NET_SAL_BAL_OSL AS ZF_BALANCE_ACDOCA_OSL,
	ZF_NET_SALE_NET_HSL AS ZF_MOV_ACDOCA_HSL,
	ZF_NET_SALE_NET_HSL_CUC AS ZF_MOV_ACDOCA_HSL_CUC,
	ZF_NET_SALE_NET_KSL AS ZF_MOV_ACDOCA_KSL,
	ZF_NET_SALE_NET_OSL AS ZF_MOV_ACDOCA_OSL
FROM B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT
UNION ALL
SELECT DISTINCT --Khoi update
	'EBIT' AS ZF_CATEGORY,
	B03_04_ACDOCA_RYEAR,
	B03_04_ACDOCA_MONAT,
	B03_04_ACDOCA_RBUKRS,
	'Net' AS ZF_BALANCE_NET_FLAG,
	B03_04_ZF_ACDOCA_POPER_MONTH,
	B03_04_T001_BUTXT,
	ZF_EBIT_SAL_BAL_HSL AS ZF_BALANCE_ACDOCA_HSL,	
	ZF_EBIT_SAL_BAL_HSL_CUC AS ZF_BALANCE_ACDOCA_HSL_CUC,
	ZF_EBIT_SAL_BAL_KSL AS ZF_BALANCE_ACDOCA_KSL,
	ZF_EBIT_SAL_BAL_OSL AS ZF_BALANCE_ACDOCA_OSL,
	ZF_EBIT_NET_HSL AS ZF_MOV_ACDOCA_HSL,
	ZF_EBIT_NET_HSL_CUC AS ZF_MOV_ACDOCA_HSL_CUC,
	 ZF_EBIT_NET_KSL AS ZF_MOV_ACDOCA_KSL,
	ZF_EBIT_NET_OSL AS ZF_MOV_ACDOCA_OSL
FROM B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT
--Khoi update
UNION ALL
SELECT DISTINCT 
	'Gross profit' AS ZF_CATEGORY,
	B03_04_ACDOCA_RYEAR,
	B03_04_ACDOCA_MONAT,
	B03_04_ACDOCA_RBUKRS,
	'Net' AS ZF_BALANCE_NET_FLAG,
	B03_04_ZF_ACDOCA_POPER_MONTH,
	B03_04_T001_BUTXT,
	ZF_GROSS_PROFIT_BAL_HSL AS ZF_BALANCE_ACDOCA_HSL,	
	ZF_GROSS_PROFIT_BAL_HSL_CUC AS ZF_BALANCE_ACDOCA_HSL_CUC,
	ZF_GROSS_PROFIT_BAL_KSL AS ZF_BALANCE_ACDOCA_KSL,
	ZF_GROSS_PROFIT_BAL_OSL AS ZF_BALANCE_ACDOCA_OSL,
	ZF_GROSS_PROFIT_NET_HSL AS ZF_MOV_ACDOCA_HSL,
	ZF_GROSS_PROFIT_NET_HSL_CUC AS ZF_MOV_ACDOCA_HSL_CUC,
	ZF_GROSS_PROFIT_NET_KSL AS ZF_MOV_ACDOCA_KSL,
	ZF_GROSS_PROFIT_NET_OSL AS ZF_MOV_ACDOCA_OSL
FROM B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT

--Step 8 Remove temporary tables

EXEC SP_DROPTABLE B03_SS01_02_TT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH

--Step 9 Remove 00 period

DELETE FROM B03_SS01_01_RT_TB_ADD_CATEGORY WHERE B03_04_ACDOCA_MONAT='00'
DELETE FROM B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT WHERE B03_04_ACDOCA_MONAT='00'
DELETE FROM B03_SS01_04_RT_APPEND_SINGULAR_COMPOUND_CATEGORY WHERE B03_04_ACDOCA_MONAT='00'

--Step 10 Add the sign for the value chart
----Khoi update
ALTER TABLE B03_SS01_04_RT_APPEND_SINGULAR_COMPOUND_CATEGORY
ADD ZF_CHART_SIGN FLOAT

UPDATE B03_SS01_04_RT_APPEND_SINGULAR_COMPOUND_CATEGORY
SET ZF_CHART_SIGN='1'

UPDATE B03_SS01_04_RT_APPEND_SINGULAR_COMPOUND_CATEGORY
SET ZF_CHART_SIGN='-1' 
WHERE ZF_CATEGORY IN 
		('Accounts payable (AP)',
		'Accrued expense/ deferred liabilities',
		'Provision liability',
		'Other liabilities',
		'Short term loans (liability)',
		'Loans (liability)',
		'Revenue/ Gross sales',
		'Other revenue/ other operating revenue',
		'Common stock (shares)',
		'Capital',
		'Retained earnings',
		'Total liabilities',
		'Equity',
		'Current liabilities',
		'Net sales',
		'Gross profit')


-- Step 11 Create the cube to store only movement for AR,AP and PL tango accounts.
EXEC SP_DROPTABLE B03_SS01_05_RT_AR_AP_PL_RELATE_MOVEMENT

SELECT B03_01_IT_FIN_TB.*,T001_WAERS,
CASE

	WHEN [Receivables (AR)]='X' THEN 'Accounts receivables (AR)' 
	WHEN [Accounts payable (AP)]='X' THEN 'Accounts payable (AP)'
	WHEN [Revenue/ Gross sales]='X' THEN 'Revenue/ Gross sales'
	WHEN [Discounts/ reductions/ adjustments]='X' THEN 'Discounts/ reductions/ adjustments'
	WHEN [COGS]='X' THEN 'COGS'
	WHEN [Other revenue/ other operating revenue]='X' THEN 'Other revenue/ other operating revenue'
	WHEN [Expenditure]='X' THEN 'Expenditure'
	WHEN [Production costs]='X' THEN 'Production costs'
    END AS ZF_CATEGORY
INTO B03_SS01_05_RT_AR_AP_PL_RELATE_MOVEMENT
FROM B03_01_IT_FIN_TB
INNER JOIN DIVA_MASTER_SCRIPT_S4HANA..AM_TANGO_ACCT_CATEGORY
ON AM_TANGO_ACCT_CATEGORY.[Tango accounts]=B03_TANGO_ACCT
LEFT JOIN A_T001
ON T001_BUKRS=B03_ACDOCA_RBUKRS
	WHERE B03_ACDOCA_MONAT<>'00'

DELETE FROM  B03_SS01_05_RT_AR_AP_PL_RELATE_MOVEMENT
	WHERE ZF_CATEGORY IS NULL

	 

--Rename all the fields

EXEC SP_UNNAME_FIELD  'B03_04_','B03_SS01_01_RT_TB_ADD_CATEGORY'
EXEC SP_RENAME_FIELD  'B03_SS01_01_','B03_SS01_01_RT_TB_ADD_CATEGORY'

EXEC SP_UNNAME_FIELD  'B03_04_','B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT'
EXEC SP_RENAME_FIELD  'B03_SS01_03_','B03_SS01_03_RT_CACULATED_NET_MOV_BALANCE_MAPPING_YEAR_MONTH_PIVOT'

EXEC SP_UNNAME_FIELD  'B03_04_','B03_SS01_04_RT_APPEND_SINGULAR_COMPOUND_CATEGORY'
EXEC SP_RENAME_FIELD  'B03_SS01_04_','B03_SS01_04_RT_APPEND_SINGULAR_COMPOUND_CATEGORY'

EXEC SP_UNNAME_FIELD 'B03_','B03_SS01_05_RT_AR_AP_PL_RELATE_MOVEMENT'
EXEC SP_RENAME_FIELD 'B03_SS01_05_','B03_SS01_05_RT_AR_AP_PL_RELATE_MOVEMENT'

GO
