USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[PM_OTC_PROCESS_MINING] @DBNAME NVARCHAR(MAX)
AS 
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B00_SS02_OTC_INFO_TABLE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B14_SS01_INVOICE_PAYMENT_CUBE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B24_SS01_OTC_PROCESS_MINING_CHANGE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B28_SALE_ORDER_CUBE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B29_DELIVERY_CUBE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B30_INVOICE_DOCS'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B31_OTC_GLOBAL_TABLE'
EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_PM02_OTC_PROCESS_MINING'
GO
