USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[script_B00_REPLACE_VIEW_BY_TABLE]
WITH EXECUTE AS CALLER 
AS 
--DYNAMIC_SCRIPT_START
/*  Change history comments
	Update history 
	-------------------------------------------------------
	Date            | Who   |  Description 
	24-03-2022	    | Thuan	|  Remove MANDT field in join
	22-06-2022		| Khoa	|  Replace A_ACDOCA to B00_ACDOCA
	15-08-2024		| Nam	|  Remove field from BSEG
*/

	/* Initialize parameters from globals table */
    DECLARE  
				@CURRENCY NVARCHAR(3)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
				,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
				,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
				,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
				,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
				,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
				,@LANGUAGE1 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
				,@LANGUAGE2 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
				,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
				,@FISCAL_YEAR_FROM NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_FROM')
				,@FISCAL_YEAR_TO NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_TO')
                 SET DATEFORMAT @DATEFORMAT;
			

/*Test mode*/

SET ROWCOUNT @LIMIT_RECORDS

EXEC SP_DROPTABLE 'B00_CEPCT'

SELECT 
	DISTINCT A.*
INTO B00_CEPCT
FROM A_CEPCT A
INNER JOIN 
	(
		SELECT CEPCT_MANDT, CEPCT_KOKRS, CEPCT_PRCTR, MAX(CEPCT_DATBI) AS ZF_CEPCT_DATBI_MAX
		FROM A_CEPCT
		WHERE CEPCT_SPRAS IN 
			(
				SELECT dbo.GET_PARAM('language1')
				UNION 
				SELECT dbo.GET_PARAM('language2')
			)
		GROUP BY CEPCT_MANDT, CEPCT_KOKRS, CEPCT_PRCTR
	) B
ON A.CEPCT_KOKRS = B.CEPCT_KOKRS
AND A.CEPCT_PRCTR = B.CEPCT_PRCTR
AND A.CEPCT_DATBI = B.ZF_CEPCT_DATBI_MAX
WHERE A.CEPCT_SPRAS IN 
			(
				SELECT dbo.GET_PARAM('language1')
				UNION 
				SELECT dbo.GET_PARAM('language2')
			)

EXEC SP_CREATE_INDEX B00_CEPCT, 'B00_CEPCT_IDX', 'CEPCT_KOKRS, CEPCT_PRCTR'

EXEC SP_DROPTABLE 'B00_CSKT'

SELECT 
	DISTINCT A.*
INTO B00_CSKT
FROM A_CSKT A
INNER JOIN 
	(
		SELECT CSKT_MANDT, CSKT_KOKRS, CSKT_KOSTL, MAX(CSKT_DATBI) AS ZF_CSKT_DATBI_MAX
		FROM A_CSKT
		WHERE CSKT_SPRAS IN 
			(
				SELECT dbo.GET_PARAM('language1')
				UNION 
				SELECT dbo.GET_PARAM('language2')
			)
		GROUP BY CSKT_MANDT, CSKT_KOKRS, CSKT_KOSTL
	) B
ON A.CSKT_KOKRS = B.CSKT_KOKRS
AND A.CSKT_KOSTL = B.CSKT_KOSTL
AND A.CSKT_DATBI = B.ZF_CSKT_DATBI_MAX
WHERE A.CSKT_SPRAS IN 
			(
				SELECT dbo.GET_PARAM('language1')
				UNION 
				SELECT dbo.GET_PARAM('language2')
			)

EXEC SP_CREATE_INDEX B00_CSKT, 'B00_CSKT_IDX', 'CSKT_MANDT, CSKT_KOSTL'

EXEC SP_REMOVE_TABLES 'B00_DD07T'

SELECT 
		A_DD07T.DD07T_DOMNAME,
		A_DD07T.DD07T_VALPOS,
		DD07T_language1.DD07T_DDLANGUAGE,
		DD07T_language1.DD07T_DDTEXT,
		A_DD07T.DD07T_DOMVALUE_L,
		LEFT(A_DD07T.DD07T_DOMVALUE_L,1) DD07T_DOMVALUE_L_LEFT_1
INTO B00_DD07T
FROM     (SELECT DISTINCT  DD07T_DOMNAME, DD07T_VALPOS, DD07T_DOMVALUE_L
                  FROM      dbo.A_DD07T) AS A_DD07T LEFT OUTER JOIN
                      (SELECT  DD07T_DOMNAME, DD07T_VALPOS, DD07T_DDLANGUAGE, MAX(DD07T_DDTEXT) AS DD07T_DDTEXT
                       FROM      dbo.A_DD07T
                       WHERE   (DD07T_DDLANGUAGE = dbo.GET_PARAM('language1'))
                       GROUP BY DD07T_DOMNAME, DD07T_VALPOS, DD07T_DDLANGUAGE) AS DD07T_language1 ON A_DD07T.DD07T_VALPOS = DD07T_language1.DD07T_VALPOS AND 
                  A_DD07T.DD07T_DOMNAME = DD07T_language1.DD07T_DOMNAME

EXEC SP_CREATE_INDEX B00_DD07T, 'B00_DD07T_IDX', ' DD07T_DOMVALUE_L_LEFT_1'





EXEC SP_REMOVE_TABLES 'B00_MAKT'

SELECT 
	A_MAKT.MAKT_MANDT,
	A_MAKT.MAKT_MATNR,
	ISNULL(MAKT_1.MAKT_SPRAS, MAKT_2.MAKT_SPRAS) AS MAKT_SPRAS,
	ISNULL(MAKT_1.MAKT_MAKTX, MAKT_2.MAKT_MAKTX) AS MAKT_MAKTX
INTO B00_MAKT
FROM     (SELECT MAKT_MANDT, MAKT_MATNR
                  FROM      dbo.A_MAKT AS MAKT_5
                  GROUP BY MAKT_MANDT, MAKT_MATNR) AS A_MAKT LEFT OUTER JOIN
                      (SELECT MAKT_MANDT, MAKT_MATNR, MAKT_SPRAS, MAX(MAKT_MAKTX) AS MAKT_MAKTX
                       FROM      dbo.A_MAKT AS MAKT_4
                       WHERE   (MAKT_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY MAKT_MANDT, MAKT_MATNR, MAKT_SPRAS) AS MAKT_1 ON A_MAKT.MAKT_MATNR = MAKT_1.MAKT_MATNR  LEFT OUTER JOIN
                      (SELECT MAKT_MANDT, MAKT_MATNR, MAKT_SPRAS, MAX(MAKT_MAKTX) AS MAKT_MAKTX
                       FROM      dbo.A_MAKT AS MAKT_3
                       WHERE   (MAKT_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY MAKT_MANDT, MAKT_MATNR, MAKT_SPRAS) AS MAKT_2 ON  A_MAKT.MAKT_MATNR = MAKT_2.MAKT_MATNR

EXEC SP_CREATE_INDEX B00_MAKT, 'B00_MAKT_IDX', 'MAKT_MANDT, MAKT_MATNR'

EXEC SP_REMOVE_TABLES 'B00_SKAT'
SELECT A_SKAT.SKAT_MANDT, A_SKAT.SKAT_KTOPL, A_SKAT.SKAT_SAKNR, ISNULL(SKAT_1.SKAT_TXT20, SKAT_2.SKAT_TXT20) AS SKAT_TXT20, ISNULL(SKAT_1.SKAT_TXT50, SKAT_2.SKAT_TXT50) AS SKAT_TXT50, 
                  ISNULL(SKAT_1.SKAT_MCOD1, SKAT_2.SKAT_MCOD1) AS SKAT_MCOD1, ISNULL(SKAT_1.SKAT_SPRAS, SKAT_2.SKAT_SPRAS) AS SKAT_SPRAS
INTO B00_SKAT
FROM     (SELECT DISTINCT SKAT_MANDT, SKAT_KTOPL, SKAT_SAKNR
                  FROM      dbo.A_SKAT) AS A_SKAT LEFT OUTER JOIN
                      (SELECT SKAT_MANDT, SKAT_KTOPL, SKAT_SAKNR, SKAT_SPRAS, MAX(SKAT_TXT20) AS SKAT_TXT20, MAX(SKAT_TXT50) AS SKAT_TXT50, MAX(SKAT_MCOD1) AS SKAT_MCOD1
                       FROM      dbo.A_SKAT
                       WHERE   (SKAT_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY SKAT_MANDT, SKAT_KTOPL, SKAT_SAKNR, SKAT_SPRAS) AS SKAT_1 ON  A_SKAT.SKAT_KTOPL = SKAT_1.SKAT_KTOPL AND 
                  A_SKAT.SKAT_SAKNR = SKAT_1.SKAT_SAKNR LEFT OUTER JOIN
                      (SELECT SKAT_MANDT, SKAT_KTOPL, SKAT_SAKNR, SKAT_SPRAS, MAX(SKAT_TXT20) AS SKAT_TXT20, MAX(SKAT_TXT50) AS SKAT_TXT50, MAX(SKAT_MCOD1) AS SKAT_MCOD1
                       FROM      dbo.A_SKAT
                       WHERE   (SKAT_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY SKAT_MANDT, SKAT_KTOPL, SKAT_SAKNR, SKAT_SPRAS) AS SKAT_2 ON  A_SKAT.SKAT_KTOPL = SKAT_2.SKAT_KTOPL AND 
                  A_SKAT.SKAT_SAKNR = SKAT_2.SKAT_SAKNR

EXEC SP_CREATE_INDEX B00_SKAT, 'B00_SKAT_IDX', 'SKAT_MANDT, SKAT_SAKNR, SKAT_KTOPL'

EXEC SP_REMOVE_TABLES 'B00_T003T'
SELECT A_T003T.T003T_MANDT, A_T003T.T003T_BLART, ISNULL(T003T_language1.T003T_SPRAS, T003T_language2.T003T_SPRAS) AS T003T_SPRAS, ISNULL(T003T_language1.T003T_LTEXT, T003T_language2.T003T_LTEXT) 
                  AS T003T_LTEXT
INTO B00_T003T
FROM     (SELECT DISTINCT T003T_MANDT, T003T_BLART
                  FROM      dbo.A_T003T) AS A_T003T LEFT OUTER JOIN
                      (SELECT T003T_MANDT, T003T_BLART, T003T_SPRAS, MAX(T003T_LTEXT) AS T003T_LTEXT
                       FROM      dbo.A_T003T
                       WHERE   (T003T_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T003T_MANDT, T003T_BLART, T003T_SPRAS) AS T003T_language1 ON A_T003T.T003T_BLART = T003T_language1.T003T_BLART  LEFT OUTER JOIN
                      (SELECT T003T_MANDT, T003T_BLART, T003T_SPRAS, MAX(T003T_LTEXT) AS T003T_LTEXT
                       FROM      dbo.A_T003T
                       WHERE   (T003T_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T003T_MANDT, T003T_BLART, T003T_SPRAS) AS T003T_language2 ON A_T003T.T003T_BLART = T003T_language2.T003T_BLART

EXEC SP_CREATE_INDEX B00_T003T, 'B00_T003T', 'T003T_MANDT, T003T_BLART'

EXEC SP_REMOVE_TABLES 'B00_T014T'
SELECT A_T014T.T014T_MANDT, A_T014T.T014T_KKBER, ISNULL(T014T_language1.T014T_SPRAS, T014T_language2.T014T_SPRAS) AS T014T_SPRAS, ISNULL(T014T_language1.T014T_KKBTX, T014T_language2.T014T_KKBTX) 
                  AS T014T_KKBTX
INTO B00_T014T
FROM     (SELECT DISTINCT T014T_MANDT, T014T_KKBER, T014T_KKBTX
                  FROM      dbo.A_T014T) AS A_T014T LEFT OUTER JOIN
                      (SELECT T014T_MANDT, T014T_KKBER, T014T_SPRAS, MAX(T014T_KKBTX) AS T014T_KKBTX
                       FROM      dbo.A_T014T
                       WHERE   (T014T_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T014T_MANDT, T014T_KKBER, T014T_SPRAS) AS T014T_language1 ON A_T014T.T014T_KKBER = T014T_language1.T014T_KKBER  LEFT OUTER JOIN
                      (SELECT T014T_MANDT, T014T_KKBER, T014T_SPRAS, MAX(T014T_KKBTX) AS T014T_KKBTX
                       FROM      dbo.A_T014T
                       WHERE   (T014T_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T014T_MANDT, T014T_KKBER, T014T_SPRAS) AS T014T_language2 ON A_T014T.T014T_KKBER = T014T_language2.T014T_KKBER 

EXEC SP_CREATE_INDEX B00_T014T, 'B00_T014T_IDX', 'T014T_MANDT, T014T_KKBER'

EXEC SP_REMOVE_TABLES 'B00_T023T'

SELECT A_T023T.T023T_MANDT, A_T023T.T023T_MATKL, ISNULL(T023T_language1.T023T_SPRAS, T023T_language2.T023T_SPRAS) AS T023T_SPRAS, ISNULL(T023T_language1.T023T_WGBEZ, T023T_language2.T023T_WGBEZ) 
                  AS T023T_WGBEZ
INTO B00_T023T
FROM     (SELECT DISTINCT T023T_MANDT, T023T_MATKL
                  FROM      dbo.A_T023T AS T023T_3) AS A_T023T LEFT OUTER JOIN
                      (SELECT T023T_MANDT, T023T_MATKL, T023T_SPRAS, MAX(T023T_WGBEZ) AS T023T_WGBEZ
                       FROM      dbo.A_T023T AS T023T_2
                       WHERE   (T023T_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T023T_MANDT, T023T_MATKL, T023T_SPRAS) AS T023T_language1 ON A_T023T.T023T_MATKL = T023T_language1.T023T_MATKL LEFT OUTER JOIN
                      (SELECT T023T_MANDT, T023T_MATKL, T023T_SPRAS, MAX(T023T_WGBEZ) AS T023T_WGBEZ
                       FROM      dbo.A_T023T AS T023T_1
                       WHERE   (T023T_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T023T_MANDT, T023T_MATKL, T023T_SPRAS) AS T023T_language2 ON A_T023T.T023T_MATKL = T023T_language2.T023T_MATKL

EXEC SP_CREATE_INDEX B00_T023T, 'B00_T009B_IDX', 'T023T_MANDT, T023T_MATKL'



EXEC SP_REMOVE_TABLES 'B00_T052U'

SELECT A_T052U.T052U_MANDT, A_T052U.T052U_ZTERM, ISNULL(T052U_lang1.T052U_TEXT1, T052U_lang2.T052U_TEXT1) AS T052U_TEXT1
INTO B00_T052U
FROM     (SELECT DISTINCT T052U_MANDT, T052U_ZTERM
                  FROM      dbo.A_T052U AS T052U_3) AS A_T052U LEFT OUTER JOIN
                      (SELECT T052U_MANDT, T052U_ZTERM, MAX(T052U_TEXT1) AS T052U_TEXT1
                       FROM      dbo.A_T052U AS T052U_2
                       WHERE   (T052U_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T052U_MANDT, T052U_ZTERM) AS T052U_lang1 ON A_T052U.T052U_ZTERM = T052U_lang1.T052U_ZTERM  LEFT OUTER JOIN
                      (SELECT T052U_MANDT, T052U_ZTERM, MAX(T052U_TEXT1) AS T052U_TEXT1
                       FROM      dbo.A_T052U AS T052U_1
                       WHERE   (T052U_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T052U_MANDT, T052U_ZTERM) AS T052U_lang2 ON A_T052U.T052U_ZTERM = T052U_lang2.T052U_ZTERM 
EXEC SP_CREATE_INDEX B00_T052U, 'B00_T052U_IDX', 'T052U_MANDT, T052U_ZTERM'


EXEC SP_REMOVE_TABLES 'B00_T077X'

SELECT A_T077X.T077X_MANDT, A_T077X.T077X_KTOKD, ISNULL(T077X_language1.T077X_SPRAS, T077X_language2.T077X_SPRAS) AS T077X_SPRAS, ISNULL(T077X_language1.T077X_TXT30, T077X_language2.T077X_TXT30) 
                  AS T077X_TXT30
INTO B00_T077X
FROM     (SELECT DISTINCT T077X_MANDT, T077X_KTOKD, T077X_TXT30
                  FROM      dbo.A_T077X) AS A_T077X LEFT OUTER JOIN
                      (SELECT T077X_MANDT, T077X_KTOKD, T077X_SPRAS, MAX(T077X_TXT30) AS T077X_TXT30
                       FROM      dbo.A_T077X
                       WHERE   (T077X_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T077X_MANDT, T077X_KTOKD, T077X_SPRAS) AS T077X_language1 ON A_T077X.T077X_KTOKD = T077X_language1.T077X_KTOKD  LEFT OUTER JOIN
                      (SELECT T077X_MANDT, T077X_KTOKD, T077X_SPRAS, MAX(T077X_TXT30) AS T077X_TXT30
                       FROM      dbo.A_T077X
                       WHERE   (T077X_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T077X_MANDT, T077X_KTOKD, T077X_SPRAS) AS T077X_language2 ON A_T077X.T077X_KTOKD = T077X_language2.T077X_KTOKD

EXEC SP_CREATE_INDEX B00_T077X, 'B00_T077X_IDX', 'T077X_MANDT, T077X_KTOKD'


EXEC SP_REMOVE_TABLES 'B00_T077Y'

SELECT A_T077Y.T077Y_MANDT, A_T077Y.T077Y_KTOKK, ISNULL(T077Y_language1.T077Y_SPRAS, T077Y_language2.T077Y_SPRAS) AS T077Y_SPRAS, ISNULL(T077Y_language1.T077Y_TXT30, T077Y_language2.T077Y_TXT30) 
                  AS T077Y_TXT30
INTO B00_T077Y
FROM     (SELECT DISTINCT T077Y_MANDT, T077Y_KTOKK
                  FROM      dbo.A_T077Y) AS A_T077Y LEFT OUTER JOIN
                      (SELECT T077Y_MANDT, T077Y_KTOKK, T077Y_SPRAS, MAX(T077Y_TXT30) AS T077Y_TXT30
                       FROM      dbo.A_T077Y
                       WHERE   (T077Y_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T077Y_MANDT, T077Y_KTOKK, T077Y_SPRAS) AS T077Y_language1 ON A_T077Y.T077Y_KTOKK = T077Y_language1.T077Y_KTOKK  LEFT OUTER JOIN
                      (SELECT T077Y_MANDT, T077Y_KTOKK, T077Y_SPRAS, MAX(T077Y_TXT30) AS T077Y_TXT30
                       FROM      dbo.A_T077Y
                       WHERE   (T077Y_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T077Y_MANDT, T077Y_KTOKK, T077Y_SPRAS) AS T077Y_language2 ON  A_T077Y.T077Y_KTOKK = T077Y_language2.T077Y_KTOKK

EXEC SP_CREATE_INDEX B00_T077Y, 'B00_T077Y_IDX', 'T077Y_MANDT, T077Y_KTOKK'



EXEC SP_REMOVE_TABLES 'B00_T134T'

SELECT A_T134T.T134T_MANDT, A_T134T.T134T_MTART, ISNULL(T134T_language1.T134T_SPRAS, T134T_language2.T134T_SPRAS) AS T134T_SPRAS, ISNULL(T134T_language1.T134T_MTBEZ, T134T_language2.T134T_MTBEZ) 
                  AS T134T_MTBEZ
INTO B00_T134T
FROM     (SELECT DISTINCT T134T_MANDT, T134T_MTART
                  FROM      dbo.A_T134T) AS A_T134T LEFT OUTER JOIN
                      (SELECT T134T_MANDT, T134T_MTART, T134T_SPRAS, MAX(T134T_MTBEZ) AS T134T_MTBEZ
                       FROM      dbo.A_T134T
                       WHERE   (T134T_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T134T_MANDT, T134T_MTART, T134T_SPRAS) AS T134T_language1 ON A_T134T.T134T_MTART = T134T_language1.T134T_MTART  LEFT OUTER JOIN
                      (SELECT T134T_MANDT, T134T_MTART, T134T_SPRAS, MAX(T134T_MTBEZ) AS T134T_MTBEZ
                       FROM      dbo.A_T134T
                       WHERE   (T134T_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T134T_MANDT, T134T_MTART, T134T_SPRAS) AS T134T_language2 ON  A_T134T.T134T_MTART = T134T_language2.T134T_MTART

EXEC SP_CREATE_INDEX B00_T134T, 'B00_T134T_IDX', 'T134T_MANDT, T134T_MTART'

EXEC SP_REMOVE_TABLES 'B00_T163Y'

SELECT A_T163Y.T163Y_MANDT, A_T163Y.T163Y_PSTYP, ISNULL(T163Y_language1.T163Y_SPRAS, T163Y_language2.T163Y_SPRAS) AS T163Y_SPRAS, ISNULL(T163Y_language1.T163Y_PTEXT, T163Y_language2.T163Y_PTEXT) 
                  AS T163Y_PTEXT
INTO B00_T163Y
FROM     (SELECT DISTINCT T163Y_MANDT, T163Y_PSTYP
                  FROM      dbo.A_T163Y) AS A_T163Y LEFT OUTER JOIN
                      (SELECT T163Y_MANDT, T163Y_PSTYP, T163Y_SPRAS, MAX(T163Y_PTEXT) AS T163Y_PTEXT
                       FROM      dbo.A_T163Y
                       WHERE   (T163Y_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY T163Y_MANDT, T163Y_PSTYP, T163Y_SPRAS) AS T163Y_language1 ON A_T163Y.T163Y_PSTYP = T163Y_language1.T163Y_PSTYP LEFT OUTER JOIN
                      (SELECT T163Y_MANDT, T163Y_PSTYP, T163Y_SPRAS, MAX(T163Y_PTEXT) AS T163Y_PTEXT
                       FROM      dbo.A_T163Y
                       WHERE   (T163Y_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY T163Y_MANDT, T163Y_PSTYP, T163Y_SPRAS) AS T163Y_language2 ON  A_T163Y.T163Y_PSTYP = T163Y_language2.T163Y_PSTYP

EXEC SP_CREATE_INDEX B00_T163Y, 'B00_T163Y_IDX', 'T163Y_MANDT, T163Y_PSTYP'


EXEC SP_REMOVE_TABLES 'B00_TBSLT'

SELECT A_TBSLT.TBSLT_MANDT, A_TBSLT.TBSLT_BSCHL, A_TBSLT.TBSLT_UMSKZ, ISNULL(TBSLT_1.TBSLT_SPRAS, TBSLT_2.TBSLT_SPRAS) AS TBSLT_SPRAS, ISNULL(TBSLT_1.TBSLT_LTEXT, TBSLT_2.TBSLT_LTEXT) 
                  AS TBSLT_LTEXT
INTO B00_TBSLT
FROM     (SELECT TBSLT_MANDT, TBSLT_BSCHL, ISNULL(TBSLT_UMSKZ, '') AS TBSLT_UMSKZ
                  FROM      dbo.A_TBSLT
                  GROUP BY TBSLT_MANDT, TBSLT_BSCHL, TBSLT_UMSKZ) AS A_TBSLT LEFT OUTER JOIN
                      (SELECT TBSLT_MANDT, TBSLT_BSCHL, ISNULL(TBSLT_UMSKZ, '') AS TBSLT_UMSKZ, TBSLT_SPRAS, MAX(TBSLT_LTEXT) AS TBSLT_LTEXT
                       FROM      dbo.A_TBSLT
                       WHERE   (TBSLT_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY TBSLT_MANDT, TBSLT_BSCHL, TBSLT_UMSKZ, TBSLT_SPRAS) AS TBSLT_1 ON A_TBSLT.TBSLT_UMSKZ = TBSLT_1.TBSLT_UMSKZ AND A_TBSLT.TBSLT_BSCHL = TBSLT_1.TBSLT_BSCHL LEFT OUTER JOIN
                      (SELECT TBSLT_MANDT, TBSLT_BSCHL, ISNULL(TBSLT_UMSKZ, '') AS TBSLT_UMSKZ, TBSLT_SPRAS, MAX(TBSLT_LTEXT) AS TBSLT_LTEXT
                       FROM      dbo.A_TBSLT
                       WHERE   (TBSLT_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY TBSLT_MANDT, TBSLT_BSCHL, TBSLT_UMSKZ, TBSLT_SPRAS) AS TBSLT_2 ON A_TBSLT.TBSLT_UMSKZ = TBSLT_2.TBSLT_UMSKZ AND A_TBSLT.TBSLT_BSCHL = TBSLT_2.TBSLT_BSCHL 

EXEC SP_CREATE_INDEX B00_TBSLT, 'B00_TBSLT_IDX', 'TBSLT_MANDT, TBSLT_UMSKZ, TBSLT_BSCHL'

EXEC SP_REMOVE_TABLES 'B00_TCURX'

SELECT TCURX_CURRKEY, POWER(CAST(10 AS real), 2 - TCURX_CURRDEC) AS TCURX_FACTOR
INTO B00_TCURX
FROM     dbo.A_TCURX

EXEC SP_CREATE_INDEX B00_TCURX, 'B00_TCURX_IDX', ' TCURX_CURRKEY'

EXEC SP_REMOVE_TABLES 'B00_TKUKT'

SELECT A_TKUKT.TKUKT_MANDT, A_TKUKT.TKUKT_KUKLA, ISNULL(TKUKT_language1.TKUKT_SPRAS, TKUKT_language2.TKUKT_SPRAS) AS TKUKT_SPRAS, ISNULL(TKUKT_language1.TKUKT_VTEXT, TKUKT_language2.TKUKT_VTEXT) 
                  AS TKUKT_VTEXT
INTO B00_TKUKT
FROM     (SELECT DISTINCT TKUKT_MANDT, TKUKT_KUKLA, TKUKT_VTEXT
                  FROM      dbo.A_TKUKT) AS A_TKUKT LEFT OUTER JOIN
                      (SELECT TKUKT_MANDT, TKUKT_KUKLA, TKUKT_SPRAS, MAX(TKUKT_VTEXT) AS TKUKT_VTEXT
                       FROM      dbo.A_TKUKT
                       WHERE   (TKUKT_SPRAS = dbo.GET_PARAM('language1'))
                       GROUP BY TKUKT_MANDT, TKUKT_KUKLA, TKUKT_SPRAS) AS TKUKT_language1 ON A_TKUKT.TKUKT_KUKLA = TKUKT_language1.TKUKT_KUKLA  LEFT OUTER JOIN
                      (SELECT TKUKT_MANDT, TKUKT_KUKLA, TKUKT_SPRAS, MAX(TKUKT_VTEXT) AS TKUKT_VTEXT
                       FROM      dbo.A_TKUKT
                       WHERE   (TKUKT_SPRAS = dbo.GET_PARAM('language2'))
                       GROUP BY TKUKT_MANDT, TKUKT_KUKLA, TKUKT_SPRAS) AS TKUKT_language2 ON A_TKUKT.TKUKT_KUKLA = TKUKT_language2.TKUKT_KUKLA 

EXEC SP_CREATE_INDEX B00_TKUKT, 'B00_TKUKT_IDX', 'TKUKT_MANDT, TKUKT_KUKLA'


EXEC SP_REMOVE_TABLES 'B00_TSTCT'

SELECT A_TSTCT.TSTCT_TCODE, ISNULL(TSTCT_language1.TSTCT_SPRSL, TSTCT_language2.TSTCT_SPRSL) AS TSTCT_SPRSL, ISNULL(TSTCT_language1.TSTCT_TTEXT, TSTCT_language2.TSTCT_TTEXT) 
                  AS TSTCT_TTEXT
INTO B00_TSTCT
FROM     (SELECT DISTINCT TSTCT_TCODE
                  FROM      dbo.A_TSTCT AS TSTCT_3) AS A_TSTCT LEFT OUTER JOIN
                      (SELECT TSTCT_TCODE, TSTCT_SPRSL, MAX(TSTCT_TTEXT) AS TSTCT_TTEXT
                       FROM      dbo.A_TSTCT AS TSTCT_2
                       WHERE   (TSTCT_SPRSL = dbo.GET_PARAM('language1'))
                       GROUP BY TSTCT_TCODE, TSTCT_SPRSL) AS TSTCT_language1 ON A_TSTCT.TSTCT_TCODE = TSTCT_language1.TSTCT_TCODE LEFT OUTER JOIN
                      (SELECT TSTCT_TCODE, TSTCT_SPRSL, MAX(TSTCT_TTEXT) AS TSTCT_TTEXT
                       FROM      dbo.A_TSTCT AS TSTCT_1
                       WHERE   (TSTCT_SPRSL = dbo.GET_PARAM('language2'))
                       GROUP BY TSTCT_TCODE, TSTCT_SPRSL) AS TSTCT_language2 ON A_TSTCT.TSTCT_TCODE = TSTCT_language2.TSTCT_TCODE

EXEC SP_CREATE_INDEX B00_TSTCT, 'B00_TSTCT_IDX', 'TSTCT_TCODE'


EXEC SP_REMOVE_TABLES 'B00_TUTYP'

SELECT A_TUTYP.TUTYP_USERTYP, ISNULL(TUTYP_language1.TUTYP_LANGU, TUTYP_language2.TUTYP_LANGU) AS TUTYP_LANGU, ISNULL(TUTYP_language1.TUTYP_UTYPTEXT, 
                  TUTYP_language2.TUTYP_UTYPTEXT) AS TUTYP_UTYPTEXT
INTO B00_TUTYP
FROM     (SELECT DISTINCT TUTYP_USERTYP
                  FROM      dbo.A_TUTYP AS TUTYP_3) AS A_TUTYP LEFT OUTER JOIN
                      (SELECT TUTYP_USERTYP, TUTYP_LANGU, MAX(TUTYP_UTYPTEXT) AS TUTYP_UTYPTEXT
                       FROM      dbo.A_TUTYP AS TUTYP_2
                       WHERE   (TUTYP_LANGU = dbo.GET_PARAM('language1'))
                       GROUP BY TUTYP_USERTYP, TUTYP_LANGU) AS TUTYP_language1 ON A_TUTYP.TUTYP_USERTYP = TUTYP_language1.TUTYP_USERTYP LEFT OUTER JOIN
                      (SELECT TUTYP_USERTYP, TUTYP_LANGU, MAX(TUTYP_UTYPTEXT) AS TUTYP_UTYPTEXT
                       FROM      dbo.A_TUTYP AS TUTYP_1
                       WHERE   (TUTYP_LANGU = dbo.GET_PARAM('language2'))
                       GROUP BY TUTYP_USERTYP, TUTYP_LANGU) AS TUTYP_language2 ON A_TUTYP.TUTYP_USERTYP = TUTYP_language2.TUTYP_USERTYP

EXEC SP_CREATE_INDEX B00_TUTYP, 'B00_TUTYP_IDX', 'TUTYP_USERTYP'


EXEC SP_REMOVE_TABLES 'B00_TVKOT'

SELECT A_TVKOT.TVKOT_MANDT, A_TVKOT.TVKOT_VKORG, ISNULL(TVKOT_language1.TVKOT_SPRAS, TVKOT_language2.TVKOT_SPRAS) AS TVKOT_SPRAS, ISNULL(TVKOT_language1.TVKOT_VTEXT, TVKOT_language2.TVKOT_VTEXT) 
                  AS TVKOT_VTEXT
INTO B00_TVKOT
FROM     (SELECT DISTINCT TVKOT_MANDT, TVKOT_VKORG
                  FROM      dbo.A_TVKOT) AS A_TVKOT LEFT OUTER JOIN
                      (SELECT TVKOT_MANDT, TVKOT_VKORG, TVKOT_SPRAS, MAX(TVKOT_VTEXT) AS TVKOT_VTEXT
                       FROM      dbo.A_TVKOT
                       WHERE   (TVKOT_SPRAS =
                                             (SELECT GLOBALS_VALUE
                                              FROM      dbo.AM_GLOBALS
                                              WHERE   (GLOBALS_PARAMETER = 'language1')))
                       GROUP BY TVKOT_MANDT, TVKOT_VKORG, TVKOT_SPRAS) AS TVKOT_language1 ON A_TVKOT.TVKOT_VKORG = TVKOT_language1.TVKOT_VKORG  LEFT OUTER JOIN
                      (SELECT TVKOT_MANDT, TVKOT_VKORG, TVKOT_SPRAS, MAX(TVKOT_VTEXT) AS TVKOT_VTEXT
                       FROM      dbo.A_TVKOT
                       WHERE   (TVKOT_SPRAS =
                                             (SELECT GLOBALS_VALUE
                                              FROM      dbo.AM_GLOBALS
                                              WHERE   (GLOBALS_PARAMETER = 'language2')))
                       GROUP BY TVKOT_MANDT, TVKOT_VKORG, TVKOT_SPRAS) AS TVKOT_language2 ON A_TVKOT.TVKOT_VKORG = TVKOT_language2.TVKOT_VKORG

EXEC SP_CREATE_INDEX B00_TVKOT, 'B00_TVKOT_IDX', 'TVKOT_MANDT, TVKOT_VKORG'


EXEC SP_REMOVE_TABLES 'B00_USR02'

SELECT USR02_MANDT, USR02_BNAME, USR02_BCODE, USR02_GLTGV, USR02_GLTGB, USR02_USTYP, USR02_CLASS, USR02_LOCNT, USR02_UFLAG, USR02_ACCNT, USR02_ANAME, USR02_ERDAT, USR02_TRDAT, USR02_LTIME, 
                  USR02_CODVN, USR02_TZONE, USR02_PASSCODE, USR02_PWDCHGDATE
INTO B00_USR02
FROM     dbo.A_USR02

EXEC SP_CREATE_INDEX B00_USR02, 'B00_USR02_IDX', 'USR02_BNAME'


EXEC SP_REMOVE_TABLES 'B00_T161T'


SELECT A_T161T.T161T_MANDT, A_T161T.T161T_BSART, A_T161T.T161T_BSTYP, 
  ISNULL([T161T_language1].[T161T_SPRAS],[T161T_language2].[T161T_SPRAS]) AS T161T_SPRAS,
  ISNULL([T161T_language1].[T161T_BATXT],[T161T_language2].[T161T_BATXT]) AS T161T_BATXT
INTO B00_T161T
  FROM ((SELECT DISTINCT T161T_MANDT, T161T_BSART, T161T_BSTYP FROM A_T161T)  AS A_T161T 

  LEFT JOIN (SELECT T161T_MANDT, T161T_BSART, T161T_BSTYP,T161T_SPRAS,MAX(T161T_BATXT) as T161T_BATXT FROM A_T161T WHERE T161T_SPRAS=dbo.get_param('language1') GROUP BY T161T_MANDT, T161T_BSART, T161T_BSTYP,T161T_SPRAS)  AS T161T_language1 ON (A_T161T.T161T_BSART = T161T_language1.T161T_BSART) AND (A_T161T.T161T_BSTYP = T161T_language1.T161T_BSTYP)) 

  LEFT JOIN (SELECT T161T_MANDT, T161T_BSART, T161T_BSTYP,T161T_SPRAS,MAX(T161T_BATXT) as T161T_BATXT FROM A_T161T WHERE T161T_SPRAS=dbo.get_param('language2') GROUP BY T161T_MANDT, T161T_BSART, T161T_BSTYP,T161T_SPRAS)  AS T161T_language2 ON (A_T161T.T161T_BSART = T161T_language2.T161T_BSART) AND (A_T161T.T161T_BSTYP = T161T_language2.T161T_BSTYP)

EXEC SP_CREATE_INDEX B00_T161T, 'B00_T161T_IDX', 'T161T_BSTYP,T161T_SPRAS,T161T_BATXT'


--Step XX: Table text descrption

	EXEC SP_REMOVE_TABLES 'B00_DD02T_ENGLISH'
	SELECT DD02T_TABNAME, MAX(DD02T_DDTEXT) AS DD02T_DDTEXT
	INTO B00_DD02T_ENGLISH
	FROM A_DD02T
	WHERE (DD02T_DDLANGUAGE = @LANGUAGE1 OR DD02T_DDLANGUAGE = @LANGUAGE2) AND DD02T_AS4LOCAL = 'A'
	GROUP BY DD02T_TABNAME

--Step XX: Field text descrption


	EXEC SP_REMOVE_TABLES 'B00_DDFTX_ENGLISH'
	SELECT DDFTX_TABNAME, DDFTX_FIELDNAME, DDFTX_DDLANGUAGE, MAX(DDFTX_SCRTEXT_L) DDFTX_SCRTEXT_L
	INTO B00_DDFTX_ENGLISH
	FROM A_DDFTX
	WHERE (DDFTX_DDLANGUAGE = @LANGUAGE1 OR DDFTX_DDLANGUAGE = @LANGUAGE2) 
	GROUP BY DDFTX_TABNAME, DDFTX_FIELDNAME, DDFTX_DDLANGUAGE

--Step XX: User type description

	EXEC SP_REMOVE_TABLES 'B00_DD07T_XUUSTYP_ENGLISH'
	SELECT  DD07T_DOMNAME, DD07T_DOMVALUE_L, MAX(DD07T_DDTEXT) AS DD07T_DDTEXT
	INTO B00_DD07T_XUUSTYP_ENGLISH
	FROM A_DD07T
	WHERE DD07T_DOMNAME = 'XUUSTYP' AND (DD07T_DDLANGUAGE = @LANGUAGE1 OR DD07T_DDLANGUAGE = @LANGUAGE2) AND DD07T_AS4LOCAL = 'A'
	GROUP BY  DD07T_DOMNAME, DD07T_DOMVALUE_L


-- Nam: 15-08-2024 : Remove field get from BSEG

	EXEC SP_REMOVE_TABLES 'B00_ACDOCA'
	SELECT *
	INTO B00_ACDOCA
	FROM A_ACDOCA
	WHERE ACDOCA_BSTAT IN ('','L','U','J','C','T') --S/4HANA logic
		--AND ACDOCA_BSTAT IN ('', 'A', 'B', 'C', 'D', 'J', 'U') --From Jesper
		AND ACDOCA_AWTYP <> N'GLYEC'

-- Thuan : 22-06-2022 : For Japan replace value from VSL to OSL. For other region use OSL.
	UPDATE B00_ACDOCA
	SET ACDOCA_OSL = 
	(
			CASE
				WHEN DB_NAME() LIKE '%JPN%' THEN ACDOCA_VSL
				ELSE ACDOCA_OSL
			END
	)
	UPDATE B00_ACDOCA
	SET ACDOCA_ROCUR = 
	(
			CASE
				WHEN DB_NAME() LIKE '%JPN%' THEN ACDOCA_RVCUR
				ELSE ACDOCA_ROCUR
			END
	)

	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_DOCLN_IDX', 'ACDOCA_RBUKRS, ACDOCA_GJAHR, ACDOCA_BELNR, ACDOCA_BUZEI, ACDOCA_DOCLN'
	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_BUZEI_IDX', 'ACDOCA_RBUKRS, ACDOCA_GJAHR, ACDOCA_BELNR, ACDOCA_BUZEI'
	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_BELNR_IDX', 'ACDOCA_RBUKRS, ACDOCA_GJAHR, ACDOCA_BELNR'
	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_GJAHR_BELNR_IDX', 'ACDOCA_GJAHR, ACDOCA_BELNR'
	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_RBUKRS_IDX', 'ACDOCA_RBUKRS'
	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_ACCT_IDX', 'ACDOCA_RACCT'
	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_GJAHR_IDX', 'ACDOCA_GJAHR'
	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_RBUKRS_RACCT_IDX', 'ACDOCA_RBUKRS, ACDOCA_RACCT'
	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_RCNTR_IDX', 'ACDOCA_KOKRS, ACDOCA_RCNTR'
	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_PRCTR_IDX', 'ACDOCA_KOKRS, ACDOCA_PRCTR'
	EXEC SP_CREATE_INDEX B00_ACDOCA, 'B00_ACDOCA_AP_AR_IDX', 'ACDOCA_BSTAT, ACDOCA_BUZEI, ACDOCA_KOART, ACDOCA_UMSKZ'

--Create T247 system table which contains month description
	EXEC SP_REMOVE_TABLES 'A_T247'
	CREATE TABLE A_T247 (
		T247_SPRAS NVARCHAR(1) DEFAULT '' NOT NULL , 
		T247_MNR NVARCHAR(2) DEFAULT '00' NOT NULL , 
		T247_KTX NVARCHAR(4) DEFAULT '' NOT NULL , 
		T247_LTX NVARCHAR(10) DEFAULT '' NOT NULL , 
		CONSTRAINT PK_T247 PRIMARY KEY (T247_SPRAS, T247_MNR)
	)

	INSERT INTO A_T247 VALUES ('E','00','OPEN','Open')
	INSERT INTO A_T247 VALUES ('E','01','JAN','January')
	INSERT INTO A_T247 VALUES ('E','02','FEB','February')
	INSERT INTO A_T247 VALUES ('E','03','MAR','March')
	INSERT INTO A_T247 VALUES ('E','04','APR','April')
	INSERT INTO A_T247 VALUES ('E','05','MAY','May')
	INSERT INTO A_T247 VALUES ('E','06','JUN','June')
	INSERT INTO A_T247 VALUES ('E','07','JUL','July')
	INSERT INTO A_T247 VALUES ('E','08','AUG','August')
	INSERT INTO A_T247 VALUES ('E','09','SEP','September')
	INSERT INTO A_T247 VALUES ('E','10','OCT','October')
	INSERT INTO A_T247 VALUES ('E','11','NOV','November')
	INSERT INTO A_T247 VALUES ('E','12','DEC','December')


	--Create T009B view and add month description from T247
	EXEC SP_REMOVE_TABLES 'B00_T009B'

	SELECT DISTINCT 
		DBO.REMOVE_LEADING_ZEROES(T009B_MANDT) T009B_MANDT,
		DBO.REMOVE_LEADING_ZEROES(T009B_PERIV) T009B_PERIV,
		DBO.REMOVE_LEADING_ZEROES(T009B_BUMON) T009B_BUMON,
		DBO.REMOVE_LEADING_ZEROES(T009B_POPER) T009B_POPER,
		T009B_RELJR,
		A_T247.T247_KTX,
		A_T247.T247_LTX
	INTO B00_T009B
	FROM A_T009B
	INNER JOIN A_T001 
		ON  (A_T001.T001_PERIV = T009B_PERIV)
	-- Thuan : Update 06_02_2023 : INNER JOIN AM_SCOPE
	INNER JOIN AM_SCOPE 
		ON T001_BUKRS = AM_SCOPE.SCOPE_CMPNY_CODE
	LEFT JOIN A_T247
		ON (A_T247.T247_SPRAS = 'E' OR A_T247.T247_SPRAS = 'EN') AND 
		   (CAST(A_T247.T247_MNR AS INT) = CAST(A_T009B.T009B_BUMON AS INT))
-- Thuan : Update 07_02_2023 : For SPE need to remove line 13 (duplicate)
	DELETE B00_T009B
	WHERE T009B_PERIV+T009B_BUMON+T009B_POPER IN
	(
		SELECT DISTINCT
			T009B_PERIV+T009B_BUMON+CAST(MAX(CAST(T009B_POPER AS INT))AS VARCHAR) AS ZF_T009B_POPER
		FROM B00_T009B
		GROUP BY T009B_PERIV, T009B_BUMON
		HAVING COUNT(*) > 1
	)

	--Create MATDOCT table filter MATDOC_RECORD_TYPE = 'MDOC'	
	EXEC SP_REMOVE_TABLES 'B00_MATDOC'
	SELECT 
		*
	INTO B00_MATDOC
	FROM A_MATDOC 
	WHERE MATDOC_RECORD_TYPE = 'MDOC'	


-- Step 1 / Get list of company code we used in EKKO, MSEG, RSEG and TVKO tables

	EXEC SP_REMOVE_TABLES 'B00_01_TT_LIST_COMPANY_CODE'
	SELECT 
	DISTINCT
		A.EKKO_BUKRS AS ZF_COMPANY_CODE,
		BUKRS_MAPPING
	INTO B00_01_TT_LIST_COMPANY_CODE
	FROM A_EKKO A
	INNER JOIN AM_COMPANY_CODE B ON A.EKKO_BUKRS = COMPANY_CODE
	UNION 
	SELECT 
	DISTINCT
		A.MSEG_BUKRS AS ZF_COMPANY_CODE,
		BUKRS_MAPPING
	FROM A_MSEG A
	INNER JOIN AM_COMPANY_CODE B ON A.MSEG_BUKRS = COMPANY_CODE
	UNION 
	SELECT 
	DISTINCT
		A.RSEG_BUKRS AS ZF_COMPANY_CODE,
		BUKRS_MAPPING
	FROM A_RSEG A
	INNER JOIN AM_COMPANY_CODE B ON A.RSEG_BUKRS = COMPANY_CODE
	UNION 
	SELECT 
	DISTINCT
		A.TVKO_BUKRS AS ZF_COMPANY_CODE,
		BUKRS_MAPPING
	FROM A_TVKO A
	INNER JOIN AM_COMPANY_CODE B ON A.TVKO_BUKRS = COMPANY_CODE

-- Step 2/ Limit company code in T001 and add company code from list of company code into T001

	EXEC SP_REMOVE_TABLES 'B00_02_TT_T001_ADD_BUKRS'
	SELECT 
		DISTINCT 
			A.T001_BUKRS,
			A.T001_WAERS,
			A.T001_PERIV,
			A.T001_KTOPL,
			A.T001_BUTXT,
			B.BUKRS_MAPPING,
			C.ZF_COMPANY_CODE
	INTO B00_02_TT_T001_ADD_BUKRS
	FROM A_T001 A 
	INNER JOIN AM_COMPANY_CODE B ON A.T001_BUKRS = B.COMPANY_CODE
	INNER JOIN B00_01_TT_LIST_COMPANY_CODE C ON C.BUKRS_MAPPING = B.BUKRS_MAPPING

-- Step 3 / Group by to see how many line have same BUKRS_MAPPING

-- Step 3.1/ Get all BUKRS_MAPPING have 1 line

	EXEC SP_REMOVE_TABLES 'B00_03_IT_T001_RMV_DUP'
	SELECT *
	INTO B00_03_IT_T001_RMV_DUP
	FROM B00_02_TT_T001_ADD_BUKRS
	WHERE BUKRS_MAPPING IN 
		(
			SELECT DISTINCT BUKRS_MAPPING 
			FROM B00_02_TT_T001_ADD_BUKRS 
			GROUP BY BUKRS_MAPPING 
			HAVING COUNT(*) = 1
		)

-- Step 3.2/ For BUKRS_MAPPING have mutiple line, just get line have ZF_COMPANY <> T001_BUKRS

	INSERT INTO B00_03_IT_T001_RMV_DUP
	SELECT *
	FROM B00_02_TT_T001_ADD_BUKRS A
	WHERE BUKRS_MAPPING IN 
		(
			SELECT DISTINCT BUKRS_MAPPING 
			FROM B00_02_TT_T001_ADD_BUKRS 
			GROUP BY BUKRS_MAPPING 
			HAVING COUNT(*) > 1
		) 
	AND T001_BUKRS IN
		(
			SELECT T001_BUKRS
			FROM B00_02_TT_T001_ADD_BUKRS 
			WHERE ZF_COMPANY_CODE <> T001_BUKRS
		)

	EXEC SP_REMOVE_TABLES 'B00_01_TT_LIST_COMPANY_CODE'
	EXEC SP_REMOVE_TABLES 'B00_02_TT_T001_ADD_BUKRS'


	SELECT * FROM B00_03_IT_T001_RMV_DUP
GO
