USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_B24_SS01_OTC_PROCESS_MINING_CHANGE]
AS
--DYNAMIC_SCRIPT_START
/*  Change history comments
	Update history 
	-------------------------------------------------------
	Date            | Who   |  Description 
	24-03-2022	| Thuan	| Remove MANDT field in join
*/


--Change table relate to OTC process mining
--Step 1.8 Objectclas is DEBI

--Step 1.8.1 Join CDPOS and CDHDR, add change description and get only neccesary changes
EXEC SP_DROPTABLE 'B24_18_TT_CDHDR_CDPOS_DEBI'
	SELECT DISTINCT A_CDHDR.*,A_CDPOS.*,
	CASE 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'KEY' THEN SUBSTRING('Create customer',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'AUFSD' AND dbo.TRIM(CDPOS_VALUE_OLD) = '' AND dbo.TRIM(CDPOS_VALUE_NEW) <> '' THEN SUBSTRING('Central customer block',1, 100)
		WHEN dbo.TRIM(CDPOS_FNAME) = 'AUFSD' AND dbo.TRIM(CDPOS_VALUE_OLD) <> '' AND dbo.TRIM(CDPOS_VALUE_NEW) = '' THEN SUBSTRING('Central customer unblock',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'CASSD' AND dbo.TRIM(CDPOS_VALUE_OLD) = '' AND dbo.TRIM(CDPOS_VALUE_NEW) <> '' THEN SUBSTRING('Central customer sales block',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'CASSD' AND dbo.TRIM(CDPOS_VALUE_OLD) <> '' AND dbo.TRIM(CDPOS_VALUE_NEW) = '' THEN SUBSTRING('Central customer sales unblock',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'FAKSD' AND dbo.TRIM(CDPOS_VALUE_OLD) = '' AND dbo.TRIM(CDPOS_VALUE_NEW) <> '' THEN SUBSTRING('Central customer billing block',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'FAKSD' AND dbo.TRIM(CDPOS_VALUE_OLD) <> '' AND dbo.TRIM(CDPOS_VALUE_NEW) = '' THEN SUBSTRING('Central customer billing unblock',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'LIFSD' AND dbo.TRIM(CDPOS_VALUE_OLD) = '' AND dbo.TRIM(CDPOS_VALUE_NEW) <> '' THEN SUBSTRING('Central customer delivery block',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'LIFSD' AND dbo.TRIM(CDPOS_VALUE_OLD) <> '' AND dbo.TRIM(CDPOS_VALUE_NEW) = '' THEN SUBSTRING('Central customer delivery unblock',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'LOEVM' AND dbo.TRIM(CDPOS_VALUE_OLD) = '' AND dbo.TRIM(CDPOS_VALUE_NEW) <> '' THEN SUBSTRING('Central customer delete flag',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'LOEVM' AND dbo.TRIM(CDPOS_VALUE_OLD) <> '' AND dbo.TRIM(CDPOS_VALUE_NEW) = '' THEN SUBSTRING('Central customer undelete flag',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'SPERR' AND dbo.TRIM(CDPOS_VALUE_OLD) = '' AND dbo.TRIM(CDPOS_VALUE_NEW) <> '' THEN SUBSTRING('Central customer posting block',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'SPERR' AND dbo.TRIM(CDPOS_VALUE_OLD) <> '' AND dbo.TRIM(CDPOS_VALUE_NEW) = '' THEN SUBSTRING('Central customer posting unblock',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'NODEL' AND dbo.TRIM(CDPOS_VALUE_OLD) = '' AND dbo.TRIM(CDPOS_VALUE_NEW) <> '' THEN SUBSTRING('Central customer deletion block',1, 100) 
		WHEN dbo.TRIM(CDPOS_FNAME) = 'NODEL' AND dbo.TRIM(CDPOS_VALUE_OLD) <> '' AND dbo.TRIM(CDPOS_VALUE_NEW) = '' THEN SUBSTRING('Central customer deletion unblock',1, 100) 
	 END AS ZF_CHANGE_DESC,
	1 AS ZF_STAGE
	INTO B24_18_TT_CDHDR_CDPOS_DEBI
	FROM A_CDHDR 
	INNER JOIN A_CDPOS
	ON	CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS AND
		CDHDR_OBJECTID=CDPOS_OBJECTID AND
		CDHDR_CHANGENR=CDPOS_CHANGENR
	WHERE CDHDR_OBJECTCLAS='DEBI'
		AND CDPOS_FNAME IN ('KEY','AUFSD','CASSD','FAKSD','LIFSD','LOEVM','SPERR','NODEL') 
		AND CDHDR_CHANGE_IND='U'
--Step 1.8.2 Add other informaion

EXEC SP_DROPTABLE B24_19_IT_CDHDR_CDPOS_DEBI

		 SELECT B24_18_TT_CDHDR_CDPOS_DEBI.*,
				V_USERNAME_NAME_TEXT,	
				DDFTX_SCRTEXT_L,	--field name
				DD02T_DDTEXT		--table name
	INTO B24_19_IT_CDHDR_CDPOS_DEBI
	FROM B24_18_TT_CDHDR_CDPOS_DEBI
	LEFT JOIN A_V_USERNAME
	ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME
	WHERE ZF_CHANGE_DESC IS NOT NULL 
--Step 1.9 Objectclas is VERBELEG
EXEC SP_DROPTABLE B24_20_TT_CHANGE_VERBELEG

	SELECT DISTINCT A_CDHDR.*,A_CDPOS.*, 
	CASE
		WHEN dbo.TRIM(CDPOS_TABNAME) = 'VBAK' AND dbo.TRIM(CDPOS_FNAME) = 'ABRVW' THEN SUBSTRING('Change SO usage indicator',1, 100)
		WHEN dbo.TRIM(CDPOS_TABNAME) = 'VBAK' AND dbo.TRIM(CDPOS_FNAME) = 'AMTBL' THEN SUBSTRING('SO release credit value',1, 100)
		WHEN dbo.TRIM(CDPOS_TABNAME) = 'VBAK' AND dbo.TRIM(CDPOS_FNAME) = 'CMFRE' THEN SUBSTRING('SO release date',1, 100)
		WHEN dbo.TRIM(CDPOS_TABNAME) = 'VBAK' AND dbo.TRIM(CDPOS_FNAME) = 'LIFSK' AND CDPOS_VALUE_OLD = '' AND CDPOS_VALUE_NEW <> '' THEN SUBSTRING('SO block deliveries',1, 100)
		WHEN dbo.TRIM(CDPOS_TABNAME) = 'VBAK' AND dbo.TRIM(CDPOS_FNAME) = 'LIFSK' AND CDPOS_VALUE_OLD <> '' AND CDPOS_VALUE_NEW = '' THEN SUBSTRING('SO unblock deliveries',1, 100) 
		WHEN dbo.TRIM(CDPOS_TABNAME) = 'VBAK' AND dbo.TRIM(CDPOS_FNAME) = 'FAKSK' AND CDPOS_VALUE_OLD = '' AND CDPOS_VALUE_NEW <> '' THEN SUBSTRING('SO block billing',1, 100)
		WHEN dbo.TRIM(CDPOS_TABNAME) = 'VBAK' AND dbo.TRIM(CDPOS_FNAME) = 'FAKSK' AND CDPOS_VALUE_OLD <> '' AND CDPOS_VALUE_NEW = '' THEN SUBSTRING('SO unblock billing',1, 100)
		WHEN dbo.TRIM(CDPOS_TABNAME) = 'VBAP' AND dbo.TRIM(CDPOS_FNAME) = 'FAKSP' AND CDPOS_VALUE_OLD = '' AND CDPOS_VALUE_NEW <> '' THEN SUBSTRING('SO item block billing',1, 100)
		WHEN dbo.TRIM(CDPOS_TABNAME) = 'VBAP' AND dbo.TRIM(CDPOS_FNAME) = 'FAKSP' AND CDPOS_VALUE_OLD <> '' AND CDPOS_VALUE_NEW = '' THEN SUBSTRING('SO item unblock billing',1, 100)
		WHEN dbo.TRIM(CDPOS_TABNAME) = 'VBAP' AND dbo.TRIM(CDPOS_FNAME) = 'NETPR' THEN SUBSTRING('SO change price',1, 100) 
		ELSE '' END AS ZF_CHANGE_DESC ,
		3 AS ZF_STAGE
		INTO B24_20_TT_CHANGE_VERBELEG
		FROM A_CDHDR 
		INNER JOIN A_CDPOS
		ON 
			 CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS AND
			 CDHDR_OBJECTID=CDPOS_OBJECTID AND
			 CDHDR_CHANGENR=CDPOS_CHANGENR
		WHERE CDHDR_OBJECTCLAS='VERKBELEG' 
		AND CDPOS_TABNAME IN ('VBAK','VBAP')
		AND CDPOS_FNAME IN ('ABRVW','AMTBL','CMFRE','LIFSK','FAKSK','FAKSP','NETPR')
--Step 1.9.2 Add other information
EXEC SP_DROPTABLE B24_21_IT_CHANGE_VERBELEG

	SELECT DISTINCT B24_20_TT_CHANGE_VERBELEG.*,
	V_USERNAME_NAME_TEXT,
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name	
	INTO B24_21_IT_CHANGE_VERBELEG
	FROM B24_20_TT_CHANGE_VERBELEG 
	LEFT JOIN A_V_USERNAME
		ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME
	WHERE ZF_CHANGE_DESC<>''

--Step 1.10. Objectclas is LIEFERUNG
--Step 1.10.1  Join CDPOS and CDHDR, add change description and get only neccesary changes

EXEC SP_DROPTABLE B24_22_TT_CHANGE_LIEFERUNG

SELECT DISTINCT A_CDHDR.*,A_CDPOS.*,
	CASE 
WHEN dbo.TRIM(CDPOS_TABNAME) = 'LIKP' AND dbo.TRIM(CDPOS_FNAME) = 'AMTBL' THEN SUBSTRING('Delivery release credit val',1, 100)  
WHEN dbo.TRIM(CDPOS_TABNAME) = 'LIKP' AND dbo.TRIM(CDPOS_FNAME) = 'LIFSK' AND CDPOS_VALUE_OLD = '' AND CDPOS_VALUE_NEW <> '' THEN SUBSTRING('Delivery block deliveries',1, 100)  
WHEN dbo.TRIM(CDPOS_TABNAME) = 'LIKP' AND dbo.TRIM(CDPOS_FNAME) = 'LIFSK' AND CDPOS_VALUE_OLD = '' AND CDPOS_VALUE_NEW <> '' THEN SUBSTRING('Delivery unblock deliveries',1, 100)  
WHEN dbo.TRIM(CDPOS_TABNAME) = 'LIKP' AND dbo.TRIM(CDPOS_FNAME) = 'FAKSK' AND CDPOS_VALUE_OLD = '' AND CDPOS_VALUE_NEW <> '' THEN SUBSTRING('Delivery block billing',1, 100)  
WHEN dbo.TRIM(CDPOS_TABNAME) = 'LIKP' AND dbo.TRIM(CDPOS_FNAME) = 'FAKSK' AND CDPOS_VALUE_OLD = '' AND CDPOS_VALUE_NEW <> '' THEN SUBSTRING('Delivery unblock billing',1, 100)  
ELSE '' END AS ZF_CHANGE_DESC,
5 AS ZF_STAGE
INTO B24_22_TT_CHANGE_LIEFERUNG
	FROM A_CDHDR 
	INNER JOIN A_CDPOS
	ON 
		 CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS AND
		 CDHDR_OBJECTID=CDPOS_OBJECTID AND
		 CDHDR_CHANGENR=CDPOS_CHANGENR
	WHERE CDHDR_OBJECTCLAS='LIEFERUNG' AND  CDPOS_TABNAME='LIKP'
	AND CDPOS_FNAME IN ('AMTBL','LIFSK','FAKSK')

--Step 1.10.2 Add other information

EXEC SP_DROPTABLE B24_23_IT_CHANGE_LIEFERUNG


	SELECT DISTINCT B24_22_TT_CHANGE_LIEFERUNG.*,
	V_USERNAME_NAME_TEXT,
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name	
	INTO B24_23_IT_CHANGE_LIEFERUNG
	FROM B24_22_TT_CHANGE_LIEFERUNG 
	LEFT JOIN A_V_USERNAME
		ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME
	WHERE ZF_CHANGE_DESC<>''

--Step 1.11 Objectclas is FAKTBELEG
--Step 1.11.1

EXEC SP_DROPTABLE B24_24_TT_CHANGE_FAKT

SELECT DISTINCT A_CDHDR.*,A_CDPOS.*,
	CASE 
	WHEN dbo.TRIM(CDPOS_FNAME) = 'MPROK' THEN SUBSTRING('Manual price change',1, 100)               
	WHEN dbo.TRIM(CDPOS_FNAME) = 'SKFBP' THEN SUBSTRING('Amount eligible for cash discount',1, 100) 
	WHEN dbo.TRIM(CDPOS_FNAME) = 'CMPRE' THEN SUBSTRING('Item credit price',1, 100)                              
	WHEN dbo.TRIM(CDPOS_FNAME) = 'VKAUS' THEN SUBSTRING('Usage indicator',1, 100)                   
	ELSE '' END AS ZF_CHANGE_DESC ,
7 AS ZF_STAGE
INTO B24_24_TT_CHANGE_FAKT
	FROM A_CDHDR 
	INNER JOIN A_CDPOS
	ON 
		 CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS AND
		 CDHDR_OBJECTID=CDPOS_OBJECTID AND
		 CDHDR_CHANGENR=CDPOS_CHANGENR
	WHERE CDHDR_OBJECTCLAS='FAKTBELEG'
	AND CDPOS_FNAME IN ('MPROK','SKFBP','CMPRE','VKAUS')

--Step 1.11.2 Add other information

EXEC SP_DROPTABLE B24_25_IT_CHANGE_FAKT

	SELECT DISTINCT B24_24_TT_CHANGE_FAKT.*,
	V_USERNAME_NAME_TEXT,
	DDFTX_SCRTEXT_L,	--field name
	DD02T_DDTEXT		--table name	
	INTO B24_25_IT_CHANGE_FAKT
	FROM B24_24_TT_CHANGE_FAKT 
	LEFT JOIN A_V_USERNAME
		ON CDHDR_USERNAME=V_USERNAME_BNAME
	LEFT JOIN B00_DD02T_ENGLISH ON 
		CDPOS_TABNAME = B00_DD02T_ENGLISH.DD02T_TABNAME
	LEFT JOIN B00_DDFTX_ENGLISH ON 
         CDPOS_TABNAME = B00_DDFTX_ENGLISH.DDFTX_TABNAME
        AND CDPOS_FNAME = B00_DDFTX_ENGLISH.DDFTX_FIELDNAME	
	WHERE ZF_CHANGE_DESC<>''

--Step 2 Remove all the tt table
EXEC SP_REMOVE_TABLES 'TEMP1'
EXEC SP_REMOVE_TABLES '%_TT_%'
--Step 3 Rename the fields 
EXEC SP_RENAME_FIELD 'B24_25_',B24_25_IT_CHANGE_FAKT
EXEC SP_RENAME_FIELD 'B24_23_',B24_23_IT_CHANGE_LIEFERUNG
EXEC SP_RENAME_FIELD 'B24_21_',B24_21_IT_CHANGE_VERBELEG
EXEC SP_RENAME_FIELD 'B24_19_',B24_19_IT_CDHDR_CDPOS_DEBI
GO
