USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE      PROCEDURE [dbo].[script_B14_SS01_INVOICE_PAYMENT_CUBE]
AS 

--DYNAMIC_SCRIPT_START
--Create 3 tables which contains information of customer invoice,invoice cancelation and payment
--Extract data from B14_06_IT_ARE 

--Add sale organization
--Limit down the number of company code
EXEC SP_DROPTABLE 'B14_SS01_01A_TT_ADD_SALE_ORG'

		SELECT
		B14_ACDOCA_RCLNT AS ACDOCA_RCLNT,
		B14_SCOPE_BUSINESS_DMN_L1 AS SCOPE_BUSINESS_DMN_L1,
		B14_SCOPE_BUSINESS_DMN_L2 AS SCOPE_BUSINESS_DMN_L2,
		B14_ACDOCA_RBUSA AS ACDOCA_RBUSA,
		B14_TGSBT_GTEXT AS TGSBT_GTEXT,
		B14_ACDOCA_RBUKRS AS ACDOCA_RBUKRS,
		B14_T001_BUTXT AS T001_BUTXT,
		B14_ACDOCA_GJAHR AS ACDOCA_GJAHR,
		B14_ACDOCA_BUDAT AS ACDOCA_BUDAT,
		B14_BKPF_XBLNR AS BKPF_XBLNR,
		B14_ACDOCA_MONAT AS ACDOCA_MONAT,
		B14_ZF_GJAHR_BUDAT_FQ AS ZF_GJAHR_BUDAT_FQ,
		B14_ZF_ACDOCA_MONAT_FQ AS ZF_ACDOCA_MONAT_FQ,
		B14_ZF_GJAHR_MONAT AS ZF_GJAHR_MONAT,
		B14_ZF_ACDOCA_BUDAT_CYM AS ZF_ACDOCA_BUDAT_CYM,
		B14_ZF_ACDOCA_BUDAT_1ST_DAY_MNTH AS ZF_ACDOCA_BUDAT_1ST_DAY_MNTH,
		B14_ZF_ACDOCA_BUDAT_POSTED_IN_PERIOD AS ZF_ACDOCA_BUDAT_POSTED_IN_PERIOD,
		B14_ACDOCA_BLDAT AS ACDOCA_BLDAT,
		B14_ACDOCA_BELNR AS ACDOCA_BELNR,
		B14_ACDOCA_BUZEI AS ACDOCA_BUZEI,
		B14_ACDOCA_DOCLN AS ACDOCA_DOCLN,
		B14_ACDOCA_KUNNR AS ACDOCA_KUNNR,
		B14_ACDOCA_KOKRS AS ACDOCA_KOKRS,
		B14_ACDOCA_AWTYP AS ACDOCA_AWTYP,
		B14_ACDOCA_AWREF AS ACDOCA_AWREF,
		B14_KNA1_NAME1 AS KNA1_NAME1,
		B14_KNA1_LAND1 AS KNA1_LAND1,
		B14_KNA1_KTOKD AS KNA1_KTOKD,
		B14_T077X_TXT30 AS T077X_TXT30,
		B14_KNA1_VBUND AS KNA1_VBUND,
		B14_T880_NAME1 AS T880_NAME1,
		B14_KNB1_AKONT_INTER_COM AS KNB1_AKONT_INTER_COM,
		B14_KNA1_KONZS AS KNA1_KONZS,
		B14_ZF_KNKK_CTLPC_RISK_CAT AS ZF_KNKK_CTLPC_RISK_CAT,
		B14_ZF_KNKK_CTLPC_RISK_CAT_TXT AS ZF_KNKK_CTLPC_RISK_CAT_TXT,
		B14_KNA1_BRAN1 AS KNA1_BRAN1,
		B14_KNA1_BRAN2 AS KNA1_BRAN2,
		B14_KNA1_BRAN3 AS KNA1_BRAN3,
		B14_KNA1_BRAN4 AS KNA1_BRAN4,
		B14_KNA1_BRAN5 AS KNA1_BRAN5,
		B14_ZF_STRATEGIC_ACC AS ZF_STRATEGIC_ACC,
		B14_ZF_STRATEGIC_ACC_TEXT AS ZF_STRATEGIC_ACC_TEXT,
		B14_ACDOCA_BLART AS ACDOCA_BLART,
		B14_T003T_LTEXT AS T003T_LTEXT,
		B14_ACDOCA_BSCHL AS ACDOCA_BSCHL,
		B14_TBSLT_LTEXT AS TBSLT_LTEXT,
		B14_ZF_ACDOCA_DRCRK_DESC AS ZF_ACDOCA_DRCRK_DESC,
		B14_ACDOCA_RWCUR AS ACDOCA_RWCUR,
		B14_ZF_ACDOCA_WSL_DOC AS ZF_ACDOCA_WSL_DOC,
		B14_T001_WAERS AS T001_WAERS,
		B14_ZF_ACDOCA_HSL_COC AS ZF_ACDOCA_HSL_COC,
		B14_GLOBALS_CURRENCY AS GLOBALS_CURRENCY,
		B14_ZF_ACDOCA_HSL_CUC AS ZF_ACDOCA_HSL_CUC,
		B14_ACDOCA_ZUONR AS ACDOCA_ZUONR,
		B14_ACDOCA_SGTXT AS ACDOCA_SGTXT,
		B14_ACDOCA_RACCT AS ACDOCA_RACCT,
		B14_SKAT_TXT50 AS SKAT_TXT50,
		B14_ZF_CREDIT_ACCOUNTS AS ZF_CREDIT_ACCOUNTS,
		B14_ZF_CREDIT_ACCOUNT_TEXTS AS ZF_CREDIT_ACCOUNT_TEXTS,
		B14_ZF_DEBIT_ACCOUNTS AS ZF_DEBIT_ACCOUNTS,
		B14_ZF_DEBIT_ACCOUNT_TEXTS AS ZF_DEBIT_ACCOUNT_TEXTS,
		B14_T052U_TEXT1 AS T052U_TEXT1,
		B14_VBRK_ZTERM AS VBRK_ZTERM,
		B14_T052U_SD_T052U_TEXT1 AS T052U_SD_T052U_TEXT1,
		B14_KNB1_ZTERM AS KNB1_ZTERM,
		B14_T052U_CU_T052U_TEXT1 AS T052U_CU_T052U_TEXT1,
		B14_ZF_VBRK_USED_PMNT_TERM  AS ZF_VBRK_USED_PMNT_TERM, -- Nam: update field name
		B14_ACDOCA_NETDT AS ACDOCA_NETDT, -- Nam: update field name
		B14_ZF_ACDOCA_CPUDT_MINUS_BLDAT AS ZF_ACDOCA_CPUDT_MINUS_BLDAT,
		B14_ZF_ACDOCA_CPUDT_MINUS_BUDAT AS ZF_ACDOCA_CPUDT_MINUS_BUDAT,
		B14_ZF_ACDOCA_BLDAT_MINUS_BUDAT AS ZF_ACDOCA_BLDAT_MINUS_BUDAT,
		B14_ZF_BLDAT_NETDT_DOC_DATE_TO_DUE_DATE AS ZF_BLDAT_NETDT_DOC_DATE_TO_DUE_DATE, -- Nam: update field name
		B14_ZF_AUGBL_AUGDT_DOC_DATE_TO_CLEARING_DATE AS ZF_AUGBL_AUGDT_DOC_DATE_TO_CLEARING_DATE,
		B14_ZF_BUDAT_NETDT_POST_DATE_TO_DUE_DATE AS ZF_BUDAT_NETDT_POST_DATE_TO_DUE_DATE, -- Nam: update field name
		B14_ZF_AUGBL_AUGDT_POST_DATE_TO_CLEAR_DATE AS ZF_AUGBL_AUGDT_POST_DATE_TO_CLEAR_DATE,
		B14_ZF_AUGBL_AUGDT_NETDT_DUE_DATE_TO_CLEAR_DATE AS ZF_AUGBL_AUGDT_NETDT_DUE_DATE_TO_CLEAR_DATE, -- Nam: update field name
		B14_ACDOCA_AUGBL AS ACDOCA_AUGBL,
		B14_ZF_ACDOCA_BLART_CLEARING_DOC_TYPE AS ZF_ACDOCA_BLART_CLEARING_DOC_TYPE,
		B14_CLR_T003T_LTEXT AS CLR_T003T_LTEXT,
		B14_ACDOCA_AUGGJ AS ACDOCA_AUGGJ,
		B14_ACDOCA_AUGDT AS ACDOCA_AUGDT,
		B14_ACDOCA_PRCTR AS ACDOCA_PRCTR,
		B14_ACDOCA_RCNTR AS ACDOCA_RCNTR,
		B14_ZF_AUGGJ_AUGDT_CLR_FYQ AS ZF_AUGGJ_AUGDT_CLR_FYQ,
		B14_ZF_CLR_FP AS ZF_CLR_FP,
		B14_ACDOCA_AUGDT_CLR_CALENDAR_YM AS ACDOCA_AUGDT_CLR_CALENDAR_YM,
		B14_ZF_ACDOCA_AUGDT_CY_1ST_OF_MNTH AS ZF_ACDOCA_AUGDT_CY_1ST_OF_MNTH,
		B14_ZF_ACDOCA_AUGDT_CLR_IN_PER AS ZF_ACDOCA_AUGDT_CLR_IN_PER,
		B14_BKPF_STBLG AS BKPF_STBLG,
		B14_BKPF_STJAH AS BKPF_STJAH,
		B14_ZF_BKPF_STBLG_REVERSED AS ZF_BKPF_STBLG_REVERSED,
		B14_BKPF_GLVOR AS BKPF_GLVOR,
		B14_T022T_TXT AS T022T_TXT,
		B14_BKPF_TCODE AS BKPF_TCODE,
		B14_BKPF_BKTXT AS BKPF_BKTXT,
		B14_TSTCT_TTEXT AS TSTCT_TTEXT,
		B14_ACDOCA_BSTAT AS ACDOCA_BSTAT,
		B14_DD07T_DDTEXT AS DD07T_DDTEXT,
		B14_ZF_ENTRY_TYPE AS ZF_ENTRY_TYPE,
		B14_ZF_CLEARNING_ENTRY_TYPE AS ZF_CLEARNING_ENTRY_TYPE,
		B14_ACDOCA_CPUDT AS ACDOCA_CPUDT,
		B14_ACDOCA_CPUTM AS ACDOCA_CPUTM,
		B14_ACDOCA_USNAM AS ACDOCA_USNAM,
		B14_V_USERNAME_NAME_TEXT AS V_USERNAME_NAME_TEXT,
		B14_USR02_USTYP AS USR02_USTYP,
		B14_ACDOCA_RHCUR AS ACDOCA_RHCUR,
		B14_ACDOCA_RKCUR AS ACDOCA_RKCUR,
		B14_ACDOCA_ROCUR AS ACDOCA_ROCUR,
		B14_ZF_ACDOCA_HSL_S AS ZF_ACDOCA_HSL_S,
		B14_ZF_ACDOCA_HSL_S_CUC AS ZF_ACDOCA_HSL_S_CUC,
		B14_ZF_ACDOCA_KSL_S AS ZF_ACDOCA_KSL_S,
		B14_ZF_ACDOCA_OSL_S AS ZF_ACDOCA_OSL_S,
		B14_ACDOCA_UMSKZ AS ACDOCA_UMSKZ,
		B14_ACDOCA_MATNR AS ACDOCA_MATNR,
		B14_ZF_CUC AS ZF_CUC,
		B14_ZF_AR_DOC_TYPE_BUCKET AS ZF_AR_DOC_TYPE_BUCKET,
		BUKRS_MAPPING ACDOCA_BUKRS_MAPPING,
		B04_09_ZF_CREDIT_ACCOUNTS_DESC_COMBINE AS ZF_CREDIT_ACCOUNTS_DESC_COMBINE,
		B04_09_ZF_DEBIT_ACCOUNTS_DESC_COMBINE AS ZF_DEBIT_ACCOUNTS_DESC_COMBINE,
		B04_09_ZF_DEBIT_ACDOCA_RCNTR_AND_DESC AS ZF_DEBIT_ACDOCA_RCNTR_AND_DESC,
		B04_09_ZF_CREDIT_ACDOCA_RCNTR_AND_DESC AS ZF_CREDIT_ACDOCA_RCNTR_AND_DESC,
		B04_09_ZF_DEBIT_ACDOCA_PRCTR_AND_DESC AS ZF_DEBIT_ACDOCA_PRCTR_AND_DESC,
		B04_09_ZF_CREDIT_ACDOCA_PRCTR_AND_DESC AS ZF_CREDIT_ACDOCA_PRCTR_AND_DESC,
		T134T_MTBEZ,
		MARA_MTART,
		MAKT_MAKTX
INTO B14_SS01_01A_TT_ADD_SALE_ORG
FROM B14_06_IT_ARE
INNER JOIN AM_COMPANY_CODE 
	ON B14_ACDOCA_RBUKRS=COMPANY_CODE
LEFT JOIN B04_09_IT_ACDOCA_BKPF_ACC_SCH
	ON B04_09_ACDOCA_RBUKRS=B14_ACDOCA_RBUKRS AND
       B04_09_ACDOCA_GJAHR=B14_ACDOCA_GJAHR AND
       B04_09_ACDOCA_BELNR=B14_ACDOCA_BELNR
LEFT JOIN B00_MAKT
	ON MAKT_MATNR=B14_ACDOCA_MATNR
LEFT JOIN A_MARA
	ON MARA_MATNR=B14_ACDOCA_MATNR
LEFT JOIN B00_T134T
	ON MARA_MTART=T134T_MTART
	


--Customer invoice
EXEC SP_DROPTABLE 'B14_SS01_01_IT_CUSTOMER_INVOICE'
SELECT *,
CONCAT(
			ACDOCA_RBUKRS,'|',
			ACDOCA_GJAHR,'|',
			ACDOCA_BELNR,'|',
			ACDOCA_BUZEI) AS ZF_CUSTOMER_INVOICE_KEY
			INTO B14_SS01_01_IT_CUSTOMER_INVOICE
FROM B14_SS01_01A_TT_ADD_SALE_ORG
WHERE ZF_AR_DOC_TYPE_BUCKET='Customer invoice'

--Customer canceltion (credit note)
EXEC SP_DROPTABLE 'B14_SS01_02_IT_CREDIT_NOTE'
SELECT *,
CONCAT(
			ACDOCA_RBUKRS,'|',
			ACDOCA_GJAHR,'|',
			ACDOCA_BELNR,'|',
			ACDOCA_BUZEI) AS ZF_CUSTOMER_CREDIT_NOTE,
CONCAT(
			ACDOCA_RBUKRS,'|',
			ACDOCA_AUGBL,'|',
			ACDOCA_AUGDT
		)		ZF_CLEARING_KEY,
			'' AS ZF_CREDIT_IN_INV
			INTO B14_SS01_02_IT_CREDIT_NOTE
FROM B14_SS01_01A_TT_ADD_SALE_ORG
WHERE ZF_AR_DOC_TYPE_BUCKET='Credit note'

--Customer payment
EXEC SP_DROPTABLE 'B14_SS01_03_IT_CUSTOMER_PAYMENT'
SELECT *,
CONCAT(
			ACDOCA_RBUKRS,'|',
			ACDOCA_GJAHR,'|',
			ACDOCA_BELNR,'|',
			ACDOCA_BUZEI) AS  ZF_CUSTOMER_PAYMENT_KEY,
CONCAT(
			ACDOCA_RBUKRS,'|',
			ACDOCA_AUGBL,'|',
			ACDOCA_AUGDT
		)		ZF_CLEARING_KEY,
'' AS ZF_PAY_IN_INV
			INTO B14_SS01_03_IT_CUSTOMER_PAYMENT
FROM B14_SS01_01A_TT_ADD_SALE_ORG
WHERE ZF_AR_DOC_TYPE_BUCKET='Customer payment'

--Payment cancelation Customer payment cancellation
EXEC SP_DROPTABLE 'B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL'
SELECT *,
CONCAT(
			ACDOCA_RBUKRS,'|',
			ACDOCA_GJAHR,'|',
			ACDOCA_BELNR,'|',
			ACDOCA_BUZEI) AS ZF_CUSTOMER_PAYMENT_CANCELLATION,
CONCAT(
			ACDOCA_RBUKRS,'|',
			ACDOCA_AUGBL,'|',
			ACDOCA_AUGDT
		)		ZF_CLEARING_KEY,
			'' AS ZF_CANCLE_PAYMENT_HAS_INV,
			'' AS ZF_CANCLE_PAYMENT_NO_INV,
			'' AS ZF_CANCLE_NO_PAY
INTO B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL
FROM B14_SS01_01A_TT_ADD_SALE_ORG
WHERE ZF_AR_DOC_TYPE_BUCKET='Customer payment cancellation'


--Khoi Update get the Others
EXEC SP_DROPTABLE 'B14_SS01_05_IT_OTHERS'
SELECT *,
CONCAT(
			ACDOCA_RBUKRS,'|',
			ACDOCA_GJAHR,'|',
			ACDOCA_BELNR,'|',
			ACDOCA_BUZEI) AS ZF_OTHERS,
CONCAT(
			ACDOCA_RBUKRS,'|',
			ACDOCA_AUGBL,'|',
			ACDOCA_AUGDT
		)		ZF_CLEARING_KEY,
'' AS ZF_OTHER_IN_INV
INTO B14_SS01_05_IT_OTHERS
FROM B14_SS01_01A_TT_ADD_SALE_ORG
WHERE ZF_AR_DOC_TYPE_BUCKET='Others'


--Update the flag
UPDATE B14_SS01_02_IT_CREDIT_NOTE
SET ZF_CREDIT_IN_INV='X' WHERE EXISTS
(
	SELECT TOP 1 1 
	FROM B14_SS01_01_IT_CUSTOMER_INVOICE AS A
	WHERE B14_SS01_02_IT_CREDIT_NOTE.ACDOCA_AUGBL=A.ACDOCA_AUGBL AND
			B14_SS01_02_IT_CREDIT_NOTE.ACDOCA_AUGDT=A.ACDOCA_AUGDT AND
			B14_SS01_02_IT_CREDIT_NOTE.ACDOCA_RBUKRS=A.ACDOCA_RBUKRS AND
			LEN(B14_SS01_02_IT_CREDIT_NOTE.ACDOCA_AUGBL)>0 AND LEN(A.ACDOCA_AUGBL)>0
)
	
UPDATE B14_SS01_03_IT_CUSTOMER_PAYMENT
SET ZF_PAY_IN_INV='X' WHERE EXISTS
(
	SELECT TOP 1 1 
	FROM B14_SS01_01_IT_CUSTOMER_INVOICE AS A
	WHERE B14_SS01_03_IT_CUSTOMER_PAYMENT.ACDOCA_AUGBL=A.ACDOCA_AUGBL AND
			B14_SS01_03_IT_CUSTOMER_PAYMENT.ACDOCA_AUGDT=A.ACDOCA_AUGDT AND
			B14_SS01_03_IT_CUSTOMER_PAYMENT.ACDOCA_RBUKRS=A.ACDOCA_RBUKRS AND
			LEN(B14_SS01_03_IT_CUSTOMER_PAYMENT.ACDOCA_AUGBL)>0 AND LEN(A.ACDOCA_AUGBL)>0
)

UPDATE B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL
SET ZF_CANCLE_PAYMENT_HAS_INV='X' WHERE EXISTS
(
	SELECT TOP 1 1 
	FROM B14_SS01_01_IT_CUSTOMER_INVOICE AS A
	WHERE B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL.ACDOCA_AUGBL=A.ACDOCA_AUGBL AND
			B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL.ACDOCA_AUGDT=A.ACDOCA_AUGDT AND
			B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL.ACDOCA_RBUKRS=A.ACDOCA_RBUKRS AND
			LEN(B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL.ACDOCA_AUGBL)>0 AND LEN(A.ACDOCA_AUGBL)>0
)

UPDATE B14_SS01_05_IT_OTHERS
SET ZF_OTHER_IN_INV='X' WHERE EXISTS
(
	SELECT TOP 1 1 
	FROM B14_SS01_01_IT_CUSTOMER_INVOICE AS A
	WHERE B14_SS01_05_IT_OTHERS.ACDOCA_AUGBL=A.ACDOCA_AUGBL AND
			B14_SS01_05_IT_OTHERS.ACDOCA_AUGDT=A.ACDOCA_AUGDT AND
			B14_SS01_05_IT_OTHERS.ACDOCA_RBUKRS=A.ACDOCA_RBUKRS AND
			LEN(B14_SS01_05_IT_OTHERS.ACDOCA_AUGBL)>0 AND LEN(A.ACDOCA_AUGBL)>0
)

--Rename the 
EXEC SP_RENAME_FIELD 'B14_01_',B14_SS01_01_IT_CUSTOMER_INVOICE
EXEC SP_RENAME_FIELD 'B14_02_',B14_SS01_02_IT_CREDIT_NOTE
EXEC SP_RENAME_FIELD 'B14_03_',B14_SS01_03_IT_CUSTOMER_PAYMENT
EXEC SP_RENAME_FIELD 'B14_04_',B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL
EXEC SP_RENAME_FIELD 'B14_05_',B14_SS01_05_IT_OTHERS


-- Step 2 Do summary on the cube, to prevent duplications

EXEC SP_DROPTABLE 'B14_SS01_06_IT_CUSTOMER_INVOICE_SUMMARY'

	SELECT
	B14_01_ZF_CUSTOMER_INVOICE_KEY,
	B14_01_ACDOCA_CPUTM,
	B14_01_ACDOCA_CPUDT,
	B14_01_ACDOCA_USNAM,
	B14_01_V_USERNAME_NAME_TEXT,
	 B14_01_ACDOCA_KUNNR,
	B14_01_ACDOCA_RBUKRS,
	B14_01_ACDOCA_BLART,
	B14_01_T003T_LTEXT,
	 B14_01_T001_WAERS,
	 B14_01_ACDOCA_AWREF,
	 B14_01_ACDOCA_AUGBL,
	 B14_01_ACDOCA_AUGDT,
	 B14_01_ACDOCA_BUKRS_MAPPING,
	 SUM(B14_01_ZF_ACDOCA_KSL_S) AS B14_01_ZF_ACDOCA_KSL_S,
	 SUM(B14_01_ZF_ACDOCA_OSL_S)AS B14_01_ZF_ACDOCA_OSL_S,
	 SUM(B14_01_ZF_ACDOCA_HSL_S) AS B14_01_ZF_ACDOCA_HSL_S,
	 SUM(B14_01_ZF_ACDOCA_HSL_S_CUC) AS B14_01_ZF_ACDOCA_HSL_S_CUC
	 INTO B14_SS01_06_IT_CUSTOMER_INVOICE_SUMMARY
	 FROM B14_SS01_01_IT_CUSTOMER_INVOICE
	 GROUP BY 
     B14_01_ZF_CUSTOMER_INVOICE_KEY,
	 B14_01_ACDOCA_BLDAT,
	 B14_01_ACDOCA_USNAM,
	 B14_01_V_USERNAME_NAME_TEXT,
	 B14_01_ACDOCA_KUNNR,
	 B14_01_ACDOCA_RBUKRS,
	 B14_01_ACDOCA_BLART,
 	 B14_01_T003T_LTEXT,
	 B14_01_T001_WAERS,
	 B14_01_ACDOCA_AWREF,
	 B14_01_ACDOCA_AUGBL,
	 B14_01_ACDOCA_AUGDT,
	 B14_01_ACDOCA_BUKRS_MAPPING,
	 B14_01_ACDOCA_CPUTM,
	B14_01_ACDOCA_CPUDT


--Step 7 Summary on credit note,only get the one that are not link to  invoice

EXEC SP_DROPTABLE 'B14_SS01_07_IT_CUSTOMER_CREDIT_NOTE'

	SELECT 
	 B14_02_ACDOCA_USNAM,
	 B14_02_V_USERNAME_NAME_TEXT,
   
	 B14_02_ACDOCA_RBUKRS,
	 B14_02_ACDOCA_BLART,
	 B14_02_T003T_LTEXT,
	 B14_02_T001_WAERS,
	 B14_02_ACDOCA_AUGBL,
	 B14_02_ACDOCA_AUGDT,
	 B14_02_ACDOCA_BUKRS_MAPPING,
	 SUM(B14_02_ZF_ACDOCA_KSL_S) AS B14_02_ZF_ACDOCA_KSL_S,
	 SUM(B14_02_ZF_ACDOCA_OSL_S)AS B14_02_ZF_ACDOCA_OSL_S,
	 SUM(B14_02_ZF_ACDOCA_HSL_S) AS B14_02_ZF_ACDOCA_HSL_S,
	 SUM(B14_02_ZF_ACDOCA_HSL_S_CUC) AS B14_02_ZF_ACDOCA_HSL_S_CUC
	 INTO B14_SS01_07_IT_CUSTOMER_CREDIT_NOTE
	 FROM B14_SS01_02_IT_CREDIT_NOTE
	 GROUP BY 
	B14_02_ACDOCA_USNAM,
	B14_02_V_USERNAME_NAME_TEXT,
 
	B14_02_ACDOCA_RBUKRS,
	B14_02_ACDOCA_BLART,
	B14_02_T003T_LTEXT,
	 B14_02_T001_WAERS,
	 B14_02_ACDOCA_AUGBL,
	 B14_02_ACDOCA_AUGDT,
	 B14_02_ACDOCA_BUKRS_MAPPING

--Step 5 Summary the payment cube, to prevent duplication, only get the one that are not link to  invoice
EXEC SP_DROPTABLE 'B14_SS01_08_IT_CUSTOMER_PAYMENT_SUMMARY'

	SELECT 	
		B14_03_ACDOCA_USNAM,
		B14_03_V_USERNAME_NAME_TEXT,
 
		B14_03_ACDOCA_RBUKRS,
		B14_03_ACDOCA_BLART,
		B14_03_T003T_LTEXT,
		B14_03_T001_WAERS,
		B14_03_ACDOCA_AUGBL,
		B14_03_ACDOCA_AUGDT,
		B14_03_ACDOCA_BUKRS_MAPPING,
		SUM(B14_03_ZF_ACDOCA_KSL_S) AS B14_03_ZF_ACDOCA_KSL_S,
		SUM(B14_03_ZF_ACDOCA_OSL_S)AS B14_03_ZF_ACDOCA_OSL_S,
		SUM(B14_03_ZF_ACDOCA_HSL_S) AS B14_03_ZF_ACDOCA_HSL_S,
		SUM(B14_03_ZF_ACDOCA_HSL_S_CUC) AS B14_03_ZF_ACDOCA_HSL_S_CUC
	INTO B14_SS01_08_IT_CUSTOMER_PAYMENT_SUMMARY
	FROM B14_SS01_03_IT_CUSTOMER_PAYMENT
	GROUP BY 
		B14_03_ACDOCA_USNAM,
		B14_03_V_USERNAME_NAME_TEXT,
 
		B14_03_ACDOCA_RBUKRS,
		B14_03_ACDOCA_BLART,
		B14_03_T003T_LTEXT,
		B14_03_T001_WAERS,
		B14_03_ACDOCA_AUGBL,
		B14_03_ACDOCA_AUGDT,
		B14_03_ACDOCA_BUKRS_MAPPING

--Step 6 Summary the payment cancelation cube, to prevent duplication,only get the one that are not link to  invoice

EXEC SP_DROPTABLE 'B14_SS01_09_IT_CUSTOMER_PAYMENT_CANCEL_SUMMARY'

	SELECT 	
		B14_04_ACDOCA_USNAM,
		B14_04_V_USERNAME_NAME_TEXT,
 
		B14_04_ACDOCA_RBUKRS,
		B14_04_ACDOCA_BLART,
		B14_04_T003T_LTEXT,
		 B14_04_T001_WAERS,
		 B14_04_ACDOCA_AUGBL,
		 B14_04_ACDOCA_AUGDT,
		 B14_04_ACDOCA_BUKRS_MAPPING,
		 SUM(B14_04_ZF_ACDOCA_KSL_S) AS B14_04_ZF_ACDOCA_KSL_S,
		 SUM(B14_04_ZF_ACDOCA_OSL_S)AS B14_04_ZF_ACDOCA_OSL_S,
		 SUM(B14_04_ZF_ACDOCA_HSL_S) AS B14_04_ZF_ACDOCA_HSL_S,
		 SUM(B14_04_ZF_ACDOCA_HSL_S_CUC) AS B14_04_ZF_ACDOCA_HSL_S_CUC
	 INTO B14_SS01_09_IT_CUSTOMER_PAYMENT_CANCEL_SUMMARY
	 FROM B14_SS01_04_IT_CUSTOMER_PAYMENT_CANCEL
	 GROUP BY 
		B14_04_ACDOCA_USNAM,
		B14_04_V_USERNAME_NAME_TEXT,
 
		B14_04_ACDOCA_RBUKRS,
		B14_04_ACDOCA_BLART,
		B14_04_T003T_LTEXT,
		B14_04_T001_WAERS,
		B14_04_ACDOCA_AUGBL,
		B14_04_ACDOCA_AUGDT,
		B14_04_ACDOCA_BUKRS_MAPPING

	 
--Step 6 Summary the OTHER  cube, to prevent duplication,only get the one that are not link to  invoice

	EXEC SP_DROPTABLE 'B14_SS01_10_IT_CUSTOMER_OTHERS_SUMMARY'
	SELECT  
		B14_05_ACDOCA_USNAM,
		B14_05_V_USERNAME_NAME_TEXT,
 
		B14_05_ACDOCA_RBUKRS,
		B14_05_ACDOCA_BLART,
		B14_05_T003T_LTEXT,
		 B14_05_T001_WAERS,
		 B14_05_ACDOCA_AUGBL,
		 B14_05_ACDOCA_AUGDT,
		 B14_05_ACDOCA_BUKRS_MAPPING,
		 SUM(B14_05_ZF_ACDOCA_KSL_S) AS B14_05_ZF_ACDOCA_KSL_S,
		 SUM(B14_05_ZF_ACDOCA_OSL_S)AS B14_05_ZF_ACDOCA_OSL_S,
		 SUM(B14_05_ZF_ACDOCA_HSL_S) AS B14_05_ZF_ACDOCA_HSL_S,
		 SUM(B14_05_ZF_ACDOCA_HSL_S_CUC) AS B14_05_ZF_ACDOCA_HSL_S_CUC
		 INTO B14_SS01_10_IT_CUSTOMER_OTHERS_SUMMARY
		 FROM B14_SS01_05_IT_OTHERS AS A
		 GROUP BY 
		B14_05_ACDOCA_USNAM,
		B14_05_V_USERNAME_NAME_TEXT,
 
		B14_05_ACDOCA_RBUKRS,
		B14_05_ACDOCA_BLART,
		B14_05_T003T_LTEXT,
		B14_05_T001_WAERS,
		B14_05_ACDOCA_AUGBL,
		B14_05_ACDOCA_AUGDT,
		B14_05_ACDOCA_BUKRS_MAPPING


GO
