USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE  PROCEDURE [dbo].[script_D09_BANK_CHANGE]
WITH EXECUTE AS CALLER
AS
/* Initialize parameters from globals table */
 
DECLARE  
                      @CURRENCY NVARCHAR(MAX)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
                     ,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
                     ,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
                     ,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
                     ,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
                     ,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
                     ,@LANGUAGE1 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
                     ,@LANGUAGE2 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
                     ,@YEAR NVARCHAR(MAX)                     = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
                     ,@ID NVARCHAR(MAX)                       = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
                     ,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
					 ,@ZV_SAME_QUARTER_BY_BLDAT NVARCHAR(MAX) = ISNULL((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'ZV_SAME_QUARTER_BY_BLDAT'), '')

EXEC SP_DROPTABLE 'D09_IT_BANK_CHANGE'
SELECT       A.B19H_REGUP_LAUFI,
			 A.B19H_REGUP_ZBUKR,
			 A.B19H_REGUP_KUNNR,
			 A.B19H_REGUP_VBLNR,
			 A.B19H_REGUP_LAUFD,
			 MAX(B.B19H_ZF_REGUP_DMBTR_S) AS B19H_ZF_REGUP_DMBTR_S,
			 MAX(B.B19H_ZF_REGUP_DMBTR_S_CUC) AS B19H_ZF_REGUP_DMBTR_S_CUC_OLD,
			 MAX(A.B19H_ZF_REGUP_DMBTR_S_CUC) AS B19H_ZF_REGUP_DMBTR_S_CUC_NEW,
			 MAX(EXCHNG_RATIO*ISNULL(B00_TCURX.TCURX_FACTOR,1) * (CASE WHEN A.B19H_REGUP_SHKZG = 'S' THEN 1 ELSE -1 END)) AS ZF_OLD_EXCHNG_RATE,
			 MAX(ISNULL(B00_TCURX.TCURX_FACTOR,1)* (CASE WHEN A.B19H_REGUP_SHKZG = 'S' THEN 1 ELSE -1 END) * COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1)) AS NEW_RATE
INTO D09_IT_BANK_CHANGE
FROM (SELECT 
             B19H_REGUP_LAUFI,
			 B19H_REGUP_ZBUKR,
			 B19H_REGUP_KUNNR,
			 B19H_REGUP_VBLNR,
			 MAX(B19H_REGUP_XVORL) AS B19H_REGUP_XVORL,
			 MAX(B19H_REGUP_SHKZG) AS B19H_REGUP_SHKZG,
		     MAX(B19H_REGUP_LAUFD) AS B19H_REGUP_LAUFD,
			 SUM(B19H_ZF_REGUP_DMBTR_S_CUC) AS B19H_ZF_REGUP_DMBTR_S_CUC 
      FROM B19_14_IT_REGUP_DETAIL_NEW
	  GROUP BY B19H_REGUP_LAUFD,
             B19H_REGUP_LAUFI,
			 B19H_REGUP_ZBUKR,
			 B19H_REGUP_KUNNR,
			 B19H_REGUP_VBLNR ) A 
INNER JOIN (SELECT B19H_REGUP_LAUFD,
             B19H_REGUP_LAUFI,
			 B19H_REGUP_ZBUKR,
			 B19H_REGUP_KUNNR,
			 B19H_REGUP_VBLNR,
		     MAX(B19H_REGUP_BUDAT) AS B19H_REGUP_BUDAT,
			 SUM(B19H_ZF_REGUP_DMBTR_S) AS B19H_ZF_REGUP_DMBTR_S,
			 SUM(B19H_ZF_REGUP_DMBTR_S_CUC) AS B19H_ZF_REGUP_DMBTR_S_CUC
      FROM B19_14_IT_REGUP_DETAIL
	  GROUP BY B19H_REGUP_LAUFD ,
             B19H_REGUP_LAUFI,
			 B19H_REGUP_ZBUKR,
			 B19H_REGUP_KUNNR,
			 B19H_REGUP_VBLNR) B 
			ON A.B19H_REGUP_LAUFD = B.B19H_REGUP_LAUFD
			AND A.B19H_REGUP_LAUFI = B.B19H_REGUP_LAUFI
			AND	A.B19H_REGUP_ZBUKR = B.B19H_REGUP_ZBUKR
			AND	A.B19H_REGUP_KUNNR = B.B19H_REGUP_KUNNR
			AND A.B19H_REGUP_VBLNR = B.B19H_REGUP_VBLNR
LEFT JOIN A_T001
		ON  A.B19H_REGUP_ZBUKR = A_T001.T001_BUKRS

	LEFT JOIN B00_TCURX
		ON B00_TCURX.TCURX_CURRKEY = A_T001.T001_WAERS
	-- Add currency factor from company currency to USD

	LEFT JOIN B00_IT_TCURF TCURF_CUC
		ON A_T001.T001_WAERS = TCURF_CUC.TCURF_FCURR
		AND TCURF_CUC.TCURF_TCURR  = @currency 
		AND TCURF_CUC.TCURF_GDATU = (
		SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
		FROM B00_IT_TCURF
		WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
				B00_IT_TCURF.TCURF_TCURR  = @currency  AND
				B00_IT_TCURF.TCURF_GDATU <= A.B19H_REGUP_LAUFD
		ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
		)
	-- Add exchange rate from company currency to USD
	LEFT JOIN B00_IT_TCURR TCURR_CUC
		ON A_T001.T001_WAERS = TCURR_CUC.TCURR_FCURR
		AND TCURR_CUC.TCURR_TCURR  = @currency  
		AND TCURR_CUC.TCURR_GDATU = (
			SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
			FROM B00_IT_TCURR
			WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
					B00_IT_TCURR.TCURR_TCURR  = @currency  AND
					B00_IT_TCURR.TCURR_GDATU <= A.B19H_REGUP_LAUFD
			ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
			) 
	LEFT JOIN AM_EXCHNG
		ON AM_EXCHNG.EXCHNG_FROM = A_T001.T001_WAERS AND
		   AM_EXCHNG.EXCHNG_TO = 'USD'

WHERE A.B19H_REGUP_XVORL = 'X'
GROUP BY  A.B19H_REGUP_LAUFD,
             A.B19H_REGUP_LAUFI,
			 A.B19H_REGUP_ZBUKR,
			 A.B19H_REGUP_KUNNR,
			 A.B19H_REGUP_VBLNR

EXEC SP_UNNAME_FIELD 'B19H_','D09_IT_BANK_CHANGE';
EXEC SP_RENAME_FIELD 'DC09_','D09_IT_BANK_CHANGE';
GO
