USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROC [dbo].[B19_BANK_CHANGE](@DBNAME as NVARCHAR(MAX))
AS
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B19_%'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B19_BANK_CHANGE'
GO
