USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE      PROCEDURE [dbo].[script_B04_SS01_ACCOUNTING_SCHEME]

WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START
/* Initiate the log */ 
--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END
/* Initialize parameters from globals table */
DECLARE  
			@CURRENCY NVARCHAR(3)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
			,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
			,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
			,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
			,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
			,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
			,@LANGUAGE1 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
			,@LANGUAGE2 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
			,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
			,@FISCAL_YEAR_FROM NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_FROM')
			,@FISCAL_YEAR_TO NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_TO')

SET ROWCOUNT @LIMIT_RECORDS
/*Change history comments*/
 
/*
       Title                : [script_B04_SS01_ACCOUNTING_SCHEME]
       Description   : 
    
       --------------------------------------------------------------
       Update history
       --------------------------------------------------------------
       Date                     |      Who                  |      Description
       DD-MM-YYYY                    Initials                      Initial version
       30-05-2023                      Thuan					   Create accounting scheme for S4.

*/
 
-- Step  1 / Create GL B04_S01_04_IT_ACCOUNTING_SCHEMES_SUMMARY cube.
-- From B04_08_IT_FIN_GL : This is cube containt all GL line from ACDOCA.
-- In B04_08_IT_FIN_GL filterd based on  :
-- ACDOCA_BSTAT = '' 
-- ACDOCA_KOART IN ('A', 'D','K', 'M', 'S')
-- ACDOCA_BUZEI <> '000'


EXEC SP_REMOVE_TABLES 'B04_SS01_01_TT_GL_TABLE%'

SELECT 
      B04_GL_ACDOCA_RBUKRS, -- Get company code
      T001_BUTXT, -- Company code description
      B04_GL_ACDOCA_GJAHR, -- Fiscal year
      B04_GL_ACDOCA_BELNR, -- Document number
      RIGHT(B04_GL_ZF_ACDOCA_GJAHR_MONAT,2) AS ZF_ACDOCA_MONAT,
      B04_GL_ACDOCA_BLART, -- Document type
      T003T_LTEXT, -- Document type description.
      B04_GL_ACDOCA_BUDAT, -- Posting date
      B04_GL_ACDOCA_BLDAT, -- Document date
      B04_GL_ACDOCA_CPUDT, -- Day On Which Accounting Document Was Entered
      B04_GL_BKPF_TCODE, -- Transaction code
      TSTCT_TTEXT,  --  Transaction code description
      B04_GL_ACDOCA_AWTYP, -- Reference Transaction
      B04_GL_ACDOCA_RHCUR, -- Company currency
      B04_GL_ACDOCA_RWCUR, -- Transaction currency
      B04_GL_ACDOCA_RKCUR, -- Global currency
      B04_GL_ACDOCA_USNAM, -- User name
      V_USERNAME_NAME_TEXT, -- Full Name of user name
      -- ZF_JE_POSTING_TYPE : Need to check more logic for this field.
      B04_GL_ACDOCA_DRCRK, -- Debit/Credit
      B04_GL_ZF_ACDOCA_KOART_DESC, -- Account type description.
      TANGO_ACCT, -- Get tango account
      TANGO_ACCT_TXT, -- Get tango account description.
      B04_GL_ACDOCA_RACCT , -- Get GL account
      SKAT_TXT50, -- Get GL description.
      B04_GL_ZF_ACDOCA_KSL_S,    -- Company amount
      B04_GL_ZF_ACDOCA_HSL_S, -- Global amount
      B04_GL_ZF_ACDOCA_HSL_S_CUC, -- Comapany amount to USD
      B04_GL_ZF_ACDOCA_WSL_S_DOC, -- Transaction amount
      B04_GL_ACDOCA_LIFNR,
      LFA1_KTOKK,
      T077Y_TXT30,
      B04_GL_ACDOCA_KUNNR,
      KNA1_KTOKD,
      T077X_TXT30,
      B04_GL_ZF_ENTRY_TYPE,
	  SKA1_GVTYP,
	  CASE 
			
			WHEN B04_GL_ACDOCA_KOART <> 'S' THEN B04_GL_ACDOCA_KOART
			WHEN B04_GL_ACDOCA_KOART = 'S' AND  
				(
					ISNULL(SKB1_HBKID,'') <> '' OR ISNULL(SKB1_XGKON,'') <> ''

				)	THEN 'S: Bank'
			WHEN B04_GL_ACDOCA_KOART = 'S' AND  
				(
					ISNULL(SKA1_GVTYP,'') <> ''  
				)	THEN 'S: P&L'
			WHEN B04_GL_ACDOCA_KOART = 'S' AND  
				(
					 ISNULL(SKA1_XBILK,'') <> ''  AND  ( ISNULL(SKB1_HBKID,'') = '' AND ISNULL(SKB1_XGKON,'') = '')
				)	THEN 'S: BS non-bank'
			ELSE 'Other cases' 
	  END AS B04_GL_ACDOCA_KOART
	  
INTO B04_SS01_01_TT_GL_TABLE
FROM B04_08_IT_FIN_GL
INNER JOIN A_T001
      ON B04_GL_ACDOCA_RBUKRS = T001_BUKRS -- Get company code description.
LEFT JOIN B00_T003T
      ON B04_GL_ACDOCA_BLART = T003T_BLART -- Get document type description from B00_T003T : Document type description filtered language key is english
LEFT JOIN A_TSTCT  ON  A_TSTCT.TSTCT_SPRSL IN ('E', 'EN') AND -- Language Key is english. 
		A_TSTCT.TSTCT_TCODE = B04_GL_BKPF_TCODE
LEFT JOIN A_V_USERNAME
          ON B04_GL_ACDOCA_USNAM = A_V_USERNAME.V_USERNAME_BNAME
LEFT JOIN AM_TANGO_20F_MAPPING ON TANGO_GL_ACCT = B04_GL_ACDOCA_RACCT
-- Add chart fo accounts description
LEFT JOIN B00_SKAT                                         
ON    SKAT_KTOPL = T001_KTOPL AND SKAT_SAKNR = B04_GL_ACDOCA_RACCT
LEFT JOIN A_LFA1 ON B04_GL_ACDOCA_LIFNR = LFA1_LIFNR
-- Add INTERCO_TXT for supplier
LEFT JOIN AM_T077Y ON A_LFA1.LFA1_KTOKK = AM_T077Y.T077Y_KTOKK AND
AM_T077Y.T077Y_SPRAS IN ('E', 'EN')
-- Get customer group
LEFT JOIN A_KNA1 ON B04_GL_ACDOCA_KUNNR = KNA1_KUNNR
-- Add INTERCO_TXT for customer
LEFT JOIN AM_T077X ON KNA1_KTOKD = AM_T077X.T077X_KTOKD AND
AM_T077X.T077X_SPRAS IN ('E', 'EN')
-- Add chart of accounts and P&L statement account type	
LEFT JOIN A_SKA1                                            
ON	SKA1_KTOPL = T001_KTOPL AND               
    SKA1_SAKNR = B04_GL_ACDOCA_RACCT    
LEFT JOIN A_SKB1
ON  SKB1_BUKRS = B04_GL_ACDOCA_RBUKRS 
	AND SKB1_SAKNR = B04_GL_ACDOCA_RACCT




ALTER TABLE B04_SS01_01_TT_GL_TABLE ADD ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG NVARCHAR(1) DEFAULT '' WITH VALUES;

UPDATE B04_SS01_01_TT_GL_TABLE
SET ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG = 'Y'
WHERE
-- G/L account exist in the T012K
EXISTS(
      SELECT TOP 1 1
      FROM A_T012K
      WHERE B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS = A_T012K.T012K_BUKRS AND B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RACCT = A_T012K.T012K_HKONT
)
-- OR G/L account exists in the FEBKO
OR    EXISTS(
                    SELECT TOP 1 1
                    FROM A_FEBKO
                    WHERE B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS = A_FEBKO.FEBKO_BUKRS AND  B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RACCT = A_FEBKO.FEBKO_HKONT
)
  
-- OR G/L account which has SKB1_HBKID or SKB1_XGKON not blank

OR EXISTS (
      SELECT TOP 1 1
      FROM A_SKB1
      WHERE B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS = A_SKB1.SKB1_BUKRS AND B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RACCT = A_SKB1.SKB1_SAKNR 
			AND (ISNULL(A_SKB1.SKB1_HBKID, '') <> '' OR  ISNULL(A_SKB1.SKB1_XGKON, '') <> '')

)


-- Step 2 / Make GL detail accounti scheme summary table.


EXEC SP_REMOVE_TABLES 'B04_SS01_02_TT_ACCOUNTING_SCHEME_TEMP%'


SELECT 
	B04_GL_ACDOCA_RBUKRS,
	B04_GL_ACDOCA_GJAHR,
	B04_GL_ACDOCA_BELNR,
	MAX(T001_BUTXT) AS T001_BUTXT,
	MAX(ZF_ACDOCA_MONAT) AS ZF_ACDOCA_MONAT,
	MAX(B04_GL_ACDOCA_BLART) AS B04_GL_ACDOCA_BLART,
	MAX(T003T_LTEXT) AS T003T_LTEXT,
	MAX(B04_GL_ACDOCA_BUDAT) AS B04_GL_ACDOCA_BUDAT,
	MAX(B04_GL_ACDOCA_BLDAT) AS B04_GL_ACDOCA_BLDAT,
	MAX(B04_GL_ACDOCA_CPUDT) AS B04_GL_ACDOCA_CPUDT,
	MAX(B04_GL_BKPF_TCODE) AS B04_GL_BKPF_TCODE,
	MAX(TSTCT_TTEXT) AS TSTCT_TTEXT,
	MAX(B04_GL_ACDOCA_AWTYP) AS B04_GL_ACDOCA_AWTYP,
	MAX(B04_GL_ACDOCA_RHCUR) AS B04_GL_ACDOCA_RHCUR,
	MAX(B04_GL_ACDOCA_RKCUR) AS B04_GL_ACDOCA_RKCUR,
	MAX(B04_GL_ACDOCA_RWCUR) AS B04_GL_ACDOCA_RWCUR,
	MAX(B04_GL_ACDOCA_USNAM) AS B04_GL_ACDOCA_USNAM,
	MAX(V_USERNAME_NAME_TEXT) AS V_USERNAME_NAME_TEXT,
	MAX(B04_GL_ZF_ENTRY_TYPE) AS B04_GL_ZF_ENTRY_TYPE
 --Create a list of debit account types
	,ISNULL(STUFF((SELECT '_' + B.B04_GL_ACDOCA_KOART
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY B.B04_GL_ACDOCA_KOART
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_ACDOCA_KOART_LIST
 --Create a list of credit account types
	,ISNULL(STUFF((SELECT '_' + B.B04_GL_ACDOCA_KOART
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.B04_GL_ACDOCA_KOART
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_ACDOCA_KOART_LIST
	-- ZF_DB_CR_KOART_COMBINE : Concat Debit and Credit account type each other.
--Create a list of debit account types description
	,ISNULL(STUFF((SELECT '_' + B.B04_GL_ZF_ACDOCA_KOART_DESC
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY  B.B04_GL_ZF_ACDOCA_KOART_DESC
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_ZF_ACDOCA_KOART_DESC_LIST
--Create a list of credit account types description
	,ISNULL(STUFF((SELECT '_' + B.B04_GL_ZF_ACDOCA_KOART_DESC
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.B04_GL_ZF_ACDOCA_KOART_DESC
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_ZF_ACDOCA_KOART_DESC_LIST
-- ZF_DB_CR_KOART_DESC_COMBINE
--Create a list of debit tango account.
	,ISNULL(STUFF((SELECT '_' + B.TANGO_ACCT
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY  B.TANGO_ACCT
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_TANGO_ACCT_LIST
--Create a list of credit tango account.
	,ISNULL(STUFF((SELECT '_' + B.TANGO_ACCT
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.TANGO_ACCT
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_TANGO_ACCT_LIST
-- ZF_DB_CR_TANGO_COMBINE : Need to combine tango account to each other.
 --Create a list of Debit GL account
	,ISNULL(STUFF((SELECT '_' + B.B04_GL_ACDOCA_RACCT
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY B.B04_GL_ACDOCA_RACCT
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_ACDOCA_RACCT_LIST
 --Create a list of credit GL account
	,ISNULL(STUFF((SELECT '_' + B.B04_GL_ACDOCA_RACCT
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY B.B04_GL_ACDOCA_RACCT
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_ACDOCA_RACCT_LIST
-- Create a list of Debit GL description
	,ISNULL(STUFF((SELECT '_' + B.SKAT_TXT50
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY B.SKAT_TXT50
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_SKAT_TXT50_LIST
-- Create a list of Credit GL description
	,ISNULL(STUFF((SELECT '_' + B.SKAT_TXT50
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY B.SKAT_TXT50
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_SKAT_TXT50_LIST,

-- Create a list of Debit supplier number
	ISNULL(STUFF((SELECT '_' + B.B04_GL_ACDOCA_LIFNR
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY  B.B04_GL_ACDOCA_LIFNR
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_ACDOCA_LIFNR_LIST
-- Create a list of Credit supplier number
	,ISNULL(STUFF((SELECT '_' + B.B04_GL_ACDOCA_LIFNR
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.B04_GL_ACDOCA_LIFNR
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_ACDOCA_LIFNR_LIST,
-- Create a list of Debit supplier group
	ISNULL(STUFF((SELECT '_' + B.LFA1_KTOKK
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY  B.LFA1_KTOKK
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_LFA1_KTOKK_LIST
-- Create a list of Credit supplier group
	,ISNULL(STUFF((SELECT '_' + B.LFA1_KTOKK
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.LFA1_KTOKK
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_LFA1_KTOKK_LIST,
-- Create a list of Debit supplier interco
	ISNULL(STUFF((SELECT '_' + B.T077Y_TXT30
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY  B.T077Y_TXT30
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_T077Y_TXT30_LIST
-- Create a list of Credit supplier interco
	,ISNULL(STUFF((SELECT '_' + B.T077Y_TXT30
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.T077Y_TXT30
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_T077Y_TXT30_LIST,
-- Create a list of Debit customer
	ISNULL(STUFF((SELECT '_' + B.B04_GL_ACDOCA_KUNNR
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY  B.B04_GL_ACDOCA_KUNNR
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_ACDOCA_KUNNR_LIST
-- Create a list of Credit customer
	,ISNULL(STUFF((SELECT '_' + B.B04_GL_ACDOCA_KUNNR
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.B04_GL_ACDOCA_KUNNR
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_ACDOCA_KUNNR_LIST,
-- Create a list of Debit group
	ISNULL(STUFF((SELECT '_' + B.KNA1_KTOKD
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY B.KNA1_KTOKD
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_KNA1_KTOKD_LIST
-- Create a list of Credit group
	,ISNULL(STUFF((SELECT '_' + B.KNA1_KTOKD
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.KNA1_KTOKD
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_KNA1_KTOKD_LIST,
-- Create a list of Debit group
	ISNULL(STUFF((SELECT '_' + B.T077X_TXT30
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY  B.T077X_TXT30
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_T077X_TXT30_LIST
-- Create a list of Credit group
	,ISNULL(STUFF((SELECT '_' + B.T077X_TXT30
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.T077X_TXT30
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_T077X_TXT30_LIST,
-- Create a list of ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG
	ISNULL(STUFF((SELECT '_' + B.ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY  B.ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST,

-- Create a list of ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG
	ISNULL(STUFF((SELECT '_' + B.ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST,



-- Create a list of ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG
	ISNULL(STUFF((SELECT '_' + IIF(LEN(B.SKA1_GVTYP) > 0, 'Y','')
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'S')
	GROUP BY  B.SKA1_GVTYP
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_DB_ZF_SKA1_GVTYP_FLAG_LIST,

-- Create a list of ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG
	ISNULL(STUFF((SELECT '_' + IIF(LEN(B.SKA1_GVTYP) > 0, 'Y','')
	FROM B04_SS01_01_TT_GL_TABLE B
	WHERE (B.B04_GL_ACDOCA_RBUKRS = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_RBUKRS  
		AND B.B04_GL_ACDOCA_GJAHR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_GJAHR
		AND B.B04_GL_ACDOCA_BELNR = B04_SS01_01_TT_GL_TABLE.B04_GL_ACDOCA_BELNR
		AND    B.B04_GL_ACDOCA_DRCRK = 'H')
	GROUP BY  B.SKA1_GVTYP
	ORDER BY SUM(ABS(B.B04_GL_ZF_ACDOCA_HSL_S)) DESC
	FOR XML PATH(''),TYPE).value('(./text())[1]','VARCHAR(MAX)')
	,1,1,''), '') ZF_CR_ZF_SKA1_GVTYP_FLAG_LIST,
	-- Get list of amount
	SUM(B04_GL_ZF_ACDOCA_HSL_S * (CASE WHEN B04_GL_ACDOCA_DRCRK = 'S' THEN 1 ELSE 0 END) ) AS B04_GL_DB_ZF_ACDOCA_HSL_S,
	SUM(B04_GL_ZF_ACDOCA_HSL_S * (CASE WHEN B04_GL_ACDOCA_DRCRK = 'H' THEN 1 ELSE 0 END) ) AS B04_GL_CR_ZF_ACDOCA_HSL_S,
	SUM(B04_GL_ZF_ACDOCA_HSL_S_CUC * (CASE WHEN B04_GL_ACDOCA_DRCRK = 'S' THEN 1 ELSE 0 END) ) AS B04_GL_DB_ZF_ACDOCA_HSL_S_CUC,
	SUM(B04_GL_ZF_ACDOCA_HSL_S_CUC * (CASE WHEN B04_GL_ACDOCA_DRCRK = 'H' THEN 1 ELSE 0 END) ) AS B04_GL_CR_ZF_ACDOCA_HSL_S_CUC,
	SUM(B04_GL_ZF_ACDOCA_WSL_S_DOC * (CASE WHEN B04_GL_ACDOCA_DRCRK = 'S' THEN 1 ELSE 0 END) ) AS B04_GL_DB_ZF_ACDOCA_WSL_S_DOC,
	SUM(B04_GL_ZF_ACDOCA_WSL_S_DOC * (CASE WHEN B04_GL_ACDOCA_DRCRK = 'H' THEN 1 ELSE 0 END) ) AS B04_GL_CR_ZF_ACDOCA_WSL_S_DOC




INTO B04_SS01_02_TT_ACCOUNTING_SCHEME_TEMP
FROM B04_SS01_01_TT_GL_TABLE
GROUP BY
	B04_GL_ACDOCA_RBUKRS,
	B04_GL_ACDOCA_GJAHR,
	B04_GL_ACDOCA_BELNR


-- Step 3 / For each GL accounting scheme final cube.
-- Combine list of debit and credit each other.

EXEC SP_REMOVE_TABLES 'B04_SS01_03_IT_FINAL_ACCT_SCHEME%'


SELECT 
	ROW_NUMBER() OVER (ORDER BY (SELECT 1)) AS ZF_ROWID	,
	B04_GL_ACDOCA_RBUKRS,
	B04_GL_ACDOCA_GJAHR,
	B04_GL_ACDOCA_BELNR,
	T001_BUTXT,
	ZF_ACDOCA_MONAT,
	B04_GL_ACDOCA_BLART,
	T003T_LTEXT,
	B04_GL_ACDOCA_BUDAT,
	B04_GL_ACDOCA_BLDAT,
	B04_GL_ACDOCA_CPUDT,
	B04_GL_BKPF_TCODE,
	TSTCT_TTEXT,
	B04_GL_ACDOCA_AWTYP,
	B04_GL_ACDOCA_RHCUR,
	B04_GL_ACDOCA_RKCUR,
	B04_GL_ACDOCA_RWCUR,
	B04_GL_ACDOCA_USNAM,
	V_USERNAME_NAME_TEXT,
	ZF_DB_ACDOCA_KOART_LIST,
	ZF_CR_ACDOCA_KOART_LIST,
	B04_GL_ZF_ENTRY_TYPE,
	ZF_DB_ZF_ACDOCA_KOART_DESC_LIST,
	ZF_CR_ZF_ACDOCA_KOART_DESC_LIST,
	ZF_DB_TANGO_ACCT_LIST,
	ZF_CR_TANGO_ACCT_LIST,
	ZF_DB_ACDOCA_RACCT_LIST,
	ZF_CR_ACDOCA_RACCT_LIST,
	ZF_DB_SKAT_TXT50_LIST,
	ZF_CR_SKAT_TXT50_LIST,
	ZF_DB_ACDOCA_LIFNR_LIST,
	ZF_CR_ACDOCA_LIFNR_LIST,
	ZF_DB_LFA1_KTOKK_LIST,
	ZF_CR_LFA1_KTOKK_LIST,
	ZF_DB_T077Y_TXT30_LIST,
	ZF_CR_T077Y_TXT30_LIST,
	ZF_DB_ACDOCA_KUNNR_LIST,
	ZF_CR_ACDOCA_KUNNR_LIST,
	ZF_DB_KNA1_KTOKD_LIST,
	ZF_CR_KNA1_KTOKD_LIST,
	ZF_DB_T077X_TXT30_LIST,
	ZF_CR_T077X_TXT30_LIST,
	ZF_DB_ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST,
	ZF_CR_ZF_T012K_FEBKO_SKB1_HBKID_XGKON_FLAG_LIST,
	ZF_DB_ZF_SKA1_GVTYP_FLAG_LIST,
	ZF_CR_ZF_SKA1_GVTYP_FLAG_LIST,
	B04_GL_DB_ZF_ACDOCA_HSL_S,
	B04_GL_CR_ZF_ACDOCA_HSL_S,
	B04_GL_DB_ZF_ACDOCA_HSL_S_CUC,
	B04_GL_CR_ZF_ACDOCA_HSL_S_CUC,
	B04_GL_DB_ZF_ACDOCA_WSL_S_DOC,
	B04_GL_CR_ZF_ACDOCA_WSL_S_DOC

INTO B04_SS01_03_IT_FINAL_ACCT_SCHEME
FROM B04_SS01_02_TT_ACCOUNTING_SCHEME_TEMP

-- Step 4 / Rename name of table and fields final cube.

EXEC SP_UNNAME_FIELD 'B04_GL_', 'B04_SS01_03_IT_FINAL_ACCT_SCHEME'
EXEC SP_RENAME_FIELD 'B04_SS01_', 'B04_SS01_03_IT_FINAL_ACCT_SCHEME'


GO
