USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--ALTER PROCEDURE dbo.B08_PTP_SMD 
CREATE PROCEDURE [dbo].[script_B08_PTP_SMD]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START


/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END

--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL

	/* Initialize parameters from globals table */
    DECLARE  
				@CURRENCY NVARCHAR(3)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
				,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
				,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
				,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
				,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
				,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
				,@LANGUAGE1 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
				,@LANGUAGE2 NVARCHAR(3)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
				,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
				,@FISCAL_YEAR_FROM NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_FROM')
				,@FISCAL_YEAR_TO NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'FISCAL_YEAR_TO')
                 SET DATEFORMAT @DATEFORMAT;


/*Test mode*/

SET ROWCOUNT @LIMIT_RECORDS

/*Change history comments*/

/*
  Title: CUBE PTP-01-SMD Supplier master data
  Description: Listing of all suppliers and associated master data attributes, at company code level

  --------------------------------------------------------------
  Update history
  --------------------------------------------------------------
  Date		    | Who	|	Description
  31-03-2016	  MW		First version for Sony
  13-04-2016	  MW		Tidy up of field names to align with other cubes
  19-04-2016	  MW		Updated intercompany logic to remove trading partner logic and make ELSE case clearer that this is an error in ETL006
  08-02-20117	  JSM		Added database log for the script and commented all the indexes
  19-03-2017	  CW        Update and standardisation for SID
  28-07-2017      NP        Naming convention
  05-09-2019	  VL		Update with S4HANA script
  24-03-2022	 Thuan	    Remove MANDT field in join
*/
 
/*
	Step 1: Create a list active supplier number from EKKO and ACDOCA 
*/

	EXEC SP_REMOVE_TABLES 'B08_01_TT_ACTV_SUPL1'
	SELECT DISTINCT EKKO_MANDT ,EKKO_LIFNR
	INTO B08_01_TT_ACTV_SUPL1X
	FROM A_EKKO
	UNION
	SELECT ACDOCA_RCLNT, ACDOCA_LIFNR
	FROM B00_ACDOCA

/*--Step 2
	Get supplier information from LFA1, T077Y
*/
	EXEC SP_REMOVE_TABLES 'B08_02_IT_PTP_SMD'
	SELECT 
		B08_01_TT_ACTV_SUPL1X.EKKO_MANDT,
		B08_01_TT_ACTV_SUPL1X.EKKO_LIFNR,
		A_LFA1.LFA1_NAME1,
		A_LFA1.LFA1_LAND1,
		A_LFA1.LFA1_KTOKK,
		A_LFA1.LFA1_VBUND,
		AM_T077Y.T077Y_TXT30,
		AM_T077Y.INTERCO_TXT,
		AM_T077Y.INTERCO_CAT,
		AM_COUNTRY_MAPPING.COUNTRY_MAPPING_DESC,
		A_LFA1.LFA1_ERDAT,
		A_LFA1.LFA1_ERNAM
	INTO B08_02_IT_PTP_SMD
	FROM B08_01_TT_ACTV_SUPL1X
	LEFT JOIN A_LFA1
	ON A_LFA1.LFA1_LIFNR = B08_01_TT_ACTV_SUPL1X.EKKO_LIFNR
	LEFT JOIN AM_T077Y
	ON AM_T077Y.T077Y_KTOKK = A_LFA1.LFA1_KTOKK
	LEFT JOIN AM_COUNTRY_MAPPING
	ON AM_COUNTRY_MAPPING.COUNTRY_MAPPING_CODE = A_LFA1.LFA1_LAND1

/*Rename fields for Qlik*/

EXEC sp_RENAME_FIELD 'B08_', 'B08_02_IT_PTP_SMD'

-- Delete TT TABLE
EXEC SP_REMOVE_TABLES '%_TT_%'
GO
