USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
 
 
--ALTER PROC [dbo].[DV04_GL_DETAILS_TO_AR]
CREATE     PROC [dbo].[script_DV04_DIVASQLGL_VERSUS_DIVASQLAR]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START
BEGIN
 
 /*
    Title            :  DV04: Data Validation dashboard 
    Description      :  Compares the GL cube to the AR cube
       --------------------------------------------------------------
    Update history
    --------------------------------------------------------------
    Date             |      Who |  Description
    19-06-2018         HuyTran        Creation
	01-09-2018			NP				update
	24-03-2022			Thuan		Remove MANDT field in join
*/

--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END

--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL

DECLARE @YEAR1 INT				= (SELECT CAST(LEFT(GLOBALS_VALUE,4) AS INT) FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'date1')
		,@YEAR2 INT				= (SELECT CAST(LEFT(GLOBALS_VALUE,4) AS INT) FROM AM_GLOBALS WHERE GLOBALS_PARAMETER = 'date2')



--Step 1/
-- Create table for send message back to TRIAL_BAL Tool

	EXEC sp_droptable 'DV00_RT_USER_FEEDBACK_MESSAGE'

	CREATE TABLE DV00_RT_USER_FEEDBACK_MESSAGE          
     (old_name NVARCHAR(MAX), new_name NVARCHAR(MAX), _log NVARCHAR(MAX))

-- The following code can be put wherever we want and whenever we want to send a message back to the user
-- that has pressed Java Upload app button for running this script.

--SET @msg = '<Feedback message for user>' --print back status for users
--INSERT INTO DV00_RT_USER_FEEDBACK_MESSAGE VALUES('', '', @msg)


 
-- Step 2/ Get amount per month on GL table per GL account which contain only customer
EXEC SP_DROPTABLE 'DV04_01_TT_GL_CUBE'
		SELECT
            B04_GL_ACDOCA_RCLNT B04_ACDOCA_RCLNT,
            B04_GL_ACDOCA_RBUKRS B04_ACDOCA_RBUKRS,
			B04_GL_ACDOCA_GJAHR B04_ACDOCA_GJAHR,
            B04_GL_ZF_ACDOCA_GJAHR_MONAT B04_ZF_ACDOCA_GJAHR_MONAT,
            B04_GL_ACDOCA_BELNR B04_ACDOCA_BELNR,
            B04_GL_ACDOCA_BUZEI B04_ACDOCA_BUZEI,
			B04_GL_ACDOCA_RACCT B04_ACDOCA_RACCT,
			B04_GL_ZF_ACDOCA_DRCRK_DESC B04_ZF_ACDOCA_DRCRK_DESC,
			SUM(B04_GL_ZF_ACDOCA_HSL_DB) AS B04_ZF_ACDOCA_HSL_DB,
			SUM(B04_GL_ZF_ACDOCA_HSL_CR) AS B04_ZF_ACDOCA_HSL_CR
              
			  
 
	INTO DV04_01_TT_GL_CUBE
      
    FROM B04_08_IT_FIN_GL
 
    WHERE B04_GL_ACDOCA_KOART = 'D'
 
    GROUP BY
            B04_GL_ACDOCA_RCLNT,
            B04_GL_ACDOCA_RBUKRS,
			B04_GL_ACDOCA_GJAHR,
            B04_GL_ZF_ACDOCA_GJAHR_MONAT,
            B04_GL_ACDOCA_BELNR,
            B04_GL_ACDOCA_BUZEI,
			B04_GL_ACDOCA_RACCT,
			B04_GL_ZF_ACDOCA_DRCRK_DESC
			            
 
--Step 2/ Get amount per month on ar table per GL account
EXEC SP_DROPTABLE 'DV04_02_TT_AR_CUBE'
	SELECT
            B14_ACDOCA_RCLNT,
			B14_ACDOCA_RBUKRS,
            B14_ACDOCA_GJAHR,
            B14_ZF_GJAHR_MONAT,
            B14_ACDOCA_BELNR,
            B14_ACDOCA_BUZEI,
			B14_ACDOCA_RACCT,
			B14_ZF_ACDOCA_DRCRK_DESC,
            CASE
				WHEN B14_ZF_ACDOCA_DRCRK_DESC ='Debit' THEN SUM(B14_ZF_ACDOCA_HSL_COC) 
				ELSE 0
			END AS B14_ZF_ACDOCA_HSL_DB,
            CASE
				WHEN B14_ZF_ACDOCA_DRCRK_DESC ='Credit' THEN SUM(B14_ZF_ACDOCA_HSL_COC) 
				ELSE 0
			END AS B14_ZF_ACDOCA_HSL_CR
             
    INTO DV04_02_TT_AR_CUBE
 
    FROM B14_06_IT_ARE
	
	WHERE CAST(B14_ACDOCA_GJAHR AS INT) BETWEEN @YEAR1 AND @YEAR2
	
    GROUP BY
	   B14_ACDOCA_RCLNT
      ,B14_ACDOCA_RBUKRS
      ,B14_ACDOCA_GJAHR
      ,B14_ZF_GJAHR_MONAT
      ,B14_ACDOCA_BELNR
      ,B14_ACDOCA_BUZEI
	  ,B14_ACDOCA_RACCT
	  ,B14_ZF_ACDOCA_DRCRK_DESC


      
--Step 3/ Comparing GL and AR so that we have all data which stored in GL or AR or in both
	EXEC SP_DROPTABLE 'DV04_03_RT_COMP_GL_AND_AR_CUBE'
    SELECT
				B04_ACDOCA_RCLNT
			  ,B14_ACDOCA_RCLNT

			  ,B04_ACDOCA_RBUKRS
			  ,B14_ACDOCA_RBUKRS

			  ,B04_ACDOCA_GJAHR
			  ,B14_ACDOCA_GJAHR

			  ,B04_ZF_ACDOCA_GJAHR_MONAT
			  ,B14_ZF_GJAHR_MONAT


			  ,B04_ACDOCA_BELNR
			  ,B14_ACDOCA_BELNR

			  ,B04_ACDOCA_BUZEI
			  ,B14_ACDOCA_BUZEI

			  ,CASE 
			WHEN ISNULL(B04_ACDOCA_BELNR,'') <> '' AND 
				ISNULL(B14_ACDOCA_BELNR,'') = '' 
			THEN 'DOC IN GL NOT IN AR'
            WHEN ISNULL(B04_ACDOCA_BELNR,'') = '' AND 
				ISNULL(B14_ACDOCA_BELNR,'') <> '' 
			THEN 'DOC IN AR NOT IN GL'
            WHEN ISNULL(B04_ACDOCA_BELNR,'') <> '' AND 
			ISNULL(B14_ACDOCA_BELNR,'') <> ''
			THEN 'DOC IN GL AND AR'
			ELSE 
				'CASE NOT IDENTIFIED'
               
		END AS ZF_CHECK_BELNR_IN_GL_AND_AR
 


			  ,B04_ZF_ACDOCA_HSL_DB
			  ,B14_ZF_ACDOCA_HSL_DB
			  

			 ,(ISNULL(B04_ZF_ACDOCA_HSL_DB, 0)) -  ABS((ISNULL(B14_ZF_ACDOCA_HSL_DB, 0))) AS ZF_GL_DB_MINUS_AR_DB

			  ,B04_ZF_ACDOCA_HSL_CR
			  ,B14_ZF_ACDOCA_HSL_CR
		  
		    ,(ISNULL(B04_ZF_ACDOCA_HSL_CR, 0)) + (ISNULL(B14_ZF_ACDOCA_HSL_CR, 0)) AS ZF_GL_CR_MINUS_AR_CR
 
		
    INTO DV04_03_RT_COMP_GL_AND_AR_CUBE
 
    FROM DV04_01_TT_GL_CUBE	
 
    FULL OUTER JOIN DV04_02_TT_AR_CUBE ON
		DV04_01_TT_GL_CUBE.B04_ACDOCA_RBUKRS = DV04_02_TT_AR_CUBE.B14_ACDOCA_RBUKRS AND
		DV04_01_TT_GL_CUBE.B04_ACDOCA_GJAHR = DV04_02_TT_AR_CUBE.B14_ACDOCA_GJAHR AND
		DBO.REMOVE_LEADING_ZEROES(DV04_01_TT_GL_CUBE.B04_ACDOCA_BELNR) = DBO.REMOVE_LEADING_ZEROES(DV04_02_TT_AR_CUBE.B14_ACDOCA_BELNR) AND
		DV04_01_TT_GL_CUBE.B04_ACDOCA_BUZEI = DV04_02_TT_AR_CUBE.B14_ACDOCA_BUZEI AND  
		DV04_01_TT_GL_CUBE.B04_ZF_ACDOCA_DRCRK_DESC = DV04_02_TT_AR_CUBE.B14_ZF_ACDOCA_DRCRK_DESC


--Step 5/
--Split the comparison into two tables so that we can be able to filter them separately on the QLIK dashboard

-- Step 5.1: GL full table

	EXEC SP_DROPTABLE 'DV04_04_RT_FULL_GL_CUBE'
 
	SELECT
		 *

		 ,B04_ACDOCA_RCLNT + '|' +  B04_ACDOCA_RBUKRS + '|' + B04_ACDOCA_GJAHR  + '|' +  B04_ACDOCA_BELNR + '|' + B04_ACDOCA_BUZEI  AS ZF_KEY_JOIN_GL
	INTO DV04_04_RT_FULL_GL_CUBE
	FROM DV04_03_RT_COMP_GL_AND_AR_CUBE
	WHERE B04_ACDOCA_BELNR IS NOT NULL
	

	-- Step 5.2: AR full table
	

	EXEC SP_DROPTABLE 'DV04_05_RT_FULL_AR_CUBE'
 
	SELECT 
		*
		,B14_ACDOCA_RCLNT + '|' + B14_ACDOCA_RBUKRS + '|' + B14_ACDOCA_GJAHR  + '|' + B14_ACDOCA_BELNR   + '|' + B14_ACDOCA_BUZEI  AS ZF_KEY_JOIN_AR
	INTO DV04_05_RT_FULL_AR_CUBE
	FROM DV04_03_RT_COMP_GL_AND_AR_CUBE
	WHERE B14_ACDOCA_BELNR IS NOT NULL

 
-- Step 6/ Split the comparison into two discrepancy tables so that we can be able to filter them separately

	---- 6.1/ GL discrepancy table 

 	EXEC SP_DROPTABLE 'DV04_06_RT_DISC_GL_CUBE'
 
	SELECT
		 *
		 ,B04_ACDOCA_RCLNT+ '|' + B04_ACDOCA_RBUKRS + '|' + B04_ACDOCA_GJAHR   + '|' +  B04_ACDOCA_BELNR + '|' + B04_ACDOCA_BUZEI  AS ZF_KEY_JOIN_GL
	INTO DV04_06_RT_DISC_GL_CUBE
	FROM DV04_03_RT_COMP_GL_AND_AR_CUBE
	WHERE 
	
	
	
		ABS(ZF_GL_DB_MINUS_AR_DB)>10 AND ZF_CHECK_BELNR_IN_GL_AND_AR = 'DOC IN GL NOT IN AR' 

	---- 6.2/ AR discrepancy table 

	EXEC SP_DROPTABLE 'DV04_07_RT_DISC_AR_CUBE'
	SELECT
		*
		,B14_ACDOCA_RCLNT + '|' + B14_ACDOCA_RBUKRS + '|' + B14_ACDOCA_GJAHR  + '|' + B14_ACDOCA_BELNR   + '|' + B14_ACDOCA_BUZEI  AS ZF_KEY_JOIN_AR
	INTO DV04_07_RT_DISC_AR_CUBE
	FROM DV04_03_RT_COMP_GL_AND_AR_CUBE
	WHERE 

		ABS(ZF_GL_DB_MINUS_AR_DB)>10 AND ZF_CHECK_BELNR_IN_GL_AND_AR = 'DOC IN AR NOT IN GL' OR ZF_CHECK_BELNR_IN_GL_AND_AR = 'Case not identified'

 -- Step 7/ User feedback message 

	INSERT INTO DV00_RT_USER_FEEDBACK_MESSAGE VALUES('', '', 'DV04_DIVASQLGL_VERSUS_DIVASQLAR')


--Step 8/ Delete temporary tables
	EXEC SP_REMOVE_TABLES '%_TT_%'


--Step 9/ Rename fields for QLIK
EXEC SP_RENAME_FIELD  'DV04A_' ,'DV04_03_RT_COMP_GL_AND_AR_CUBE'
EXEC SP_RENAME_FIELD 'DV04B_', 'DV04_04_RT_FULL_GL_CUBE'
EXEC SP_RENAME_FIELD 'DV04C_', 'DV04_05_RT_FULL_AR_CUBE'
EXEC SP_RENAME_FIELD 'DV04D_', 'DV04_06_RT_DISC_GL_CUBE'
EXEC SP_RENAME_FIELD 'DV04E_', 'DV04_07_RT_DISC_AR_CUBE'


	
-- Log cube creation
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV04_03_RT_COMP_GL_AND_AR_CUBE',(SELECT COUNT(*) FROM DV04_03_RT_COMP_GL_AND_AR_CUBE) 
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV04_04_RT_FULL_GL_CUBE',(SELECT COUNT(*) FROM DV04_04_RT_FULL_GL_CUBE) 
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV04_05_RT_FULL_AR_CUBE',(SELECT COUNT(*) FROM DV04_05_RT_FULL_AR_CUBE)      
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV04_06_RT_DISC_GL_CUBE',(SELECT COUNT(*) FROM DV04_06_RT_DISC_GL_CUBE)  
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','DV04_07_RT_DISC_AR_CUBE',(SELECT COUNT(*) FROM DV04_07_RT_DISC_AR_CUBE)  

/* log end of procedure*/
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure finished',NULL,NULL


END


GO
