USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[script_DC05_PTP_APA]
WITH EXECUTE AS CALLER
AS

--DYNAMIC_SCRIPT_START
/* Initiate the log */ 
----Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END
 
--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL
 
/* Initialize parameters from globals table */
 
     DECLARE  
                      @CURRENCY NVARCHAR(MAX)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
                     ,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
                     ,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
                     ,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
                     ,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
                     ,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
                     ,@LANGUAGE1 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
                     ,@LANGUAGE2 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
                     ,@YEAR NVARCHAR(MAX)                     = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
                     ,@ID NVARCHAR(MAX)                       = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
                     ,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
					 ,@ZV_SAME_QUARTER_BY_BLDAT NVARCHAR(MAX) = ISNULL((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'ZV_SAME_QUARTER_BY_BLDAT'), '')


--Step 1/ Compare values (USD) between table B11_04_IT_PTP_APA_NEW (use TCURR and TCURF) and table B11_04_IT_PTP_APA (use AM_EXCHNG)
EXEC SP_DROPTABLE 	'DC05_01_IT_PTP_APA' 

SELECT 
	A.B11B_ACDOCA_RBUKRS,
	A.B11B_ACDOCA_GJAHR, 
	A.B11B_ACDOCA_BELNR, 
	MAX(A.B11B_ACDOCA_RHCUR) AS B11B_ACDOCA_RHCUR,
	MAX(A.B11B_ACDOCA_BUDAT) AS B11B_ACDOCA_BUDAT,
	MAX(ISNULL(AM_EXCHNG.EXCHNG_RATIO,1)) AS EXCH_RATE_OLD,
	MAX(COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1)) AS EXCH_RATE_NEW,
	SUM(A.B11B_ZF_ACDOCA_HSL_S) AS B11B_ZF_ACDOCA_HSL_S,
	SUM(B.B11B_ZF_ACDOCA_HSL_CUC) AS B11B_ZF_ACDOCA_HSL_CUC_OLD,
	SUM(A.B11B_ZF_ACDOCA_HSL_CUC) AS B11B_ZF_ACDOCA_HSL_CUC_NEW
INTO DC05_01_IT_PTP_APA
FROM 
(
	SELECT B11B_ACDOCA_RBUKRS,
		B11B_ACDOCA_GJAHR, 
		B11B_ACDOCA_BELNR,
		MAX(B11B_ACDOCA_RHCUR) AS B11B_ACDOCA_RHCUR,
		MAX(B11B_ACDOCA_BUDAT) AS B11B_ACDOCA_BUDAT,
		SUM(B11B_ZF_ACDOCA_HSL_S) AS B11B_ZF_ACDOCA_HSL_S,
		SUM(B11B_ZF_ACDOCA_HSL_CUC) AS B11B_ZF_ACDOCA_HSL_CUC
	FROM B11_04_IT_PTP_APA_NEW
	WHERE B11B_ZF_ACDOCA_DRCRK_DESC = 'Debit'
	GROUP BY B11B_ACDOCA_RBUKRS,
		B11B_ACDOCA_GJAHR, 
		B11B_ACDOCA_BELNR
) A

INNER JOIN 
(
	SELECT B11B_ACDOCA_RBUKRS,
		B11B_ACDOCA_GJAHR, 
		B11B_ACDOCA_BELNR,
		MAX(B11B_ACDOCA_RHCUR) AS B11B_ACDOCA_RHCUR,
		MAX(B11B_ACDOCA_BUDAT) AS B11B_ACDOCA_BUDAT,
		SUM(B11B_ZF_ACDOCA_HSL_S) AS B11B_ZF_ACDOCA_HSL_S,
		SUM(B11B_ZF_ACDOCA_HSL_CUC) AS B11B_ZF_ACDOCA_HSL_CUC
	FROM B11_04_IT_PTP_APA 
	WHERE B11B_ZF_ACDOCA_DRCRK_DESC = 'Debit'
	GROUP BY B11B_ACDOCA_RBUKRS,
		B11B_ACDOCA_GJAHR, 
		B11B_ACDOCA_BELNR
) B
	ON A.B11B_ACDOCA_RBUKRS = B.B11B_ACDOCA_RBUKRS
	AND A.B11B_ACDOCA_GJAHR = B.B11B_ACDOCA_GJAHR
	AND A.B11B_ACDOCA_BELNR = B.B11B_ACDOCA_BELNR

LEFT JOIN AM_EXCHNG 
	ON A.B11B_ACDOCA_RHCUR = AM_EXCHNG.EXCHNG_FROM
	AND AM_EXCHNG.EXCHNG_TO = @currency


LEFT JOIN B00_IT_TCURF TCURF_CUC
	ON A.B11B_ACDOCA_RHCUR = TCURF_CUC.TCURF_FCURR
	AND TCURF_CUC.TCURF_TCURR  = @currency  
	AND TCURF_CUC.TCURF_GDATU = (
	SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
	FROM B00_IT_TCURF
	WHERE A.B11B_ACDOCA_RHCUR = B00_IT_TCURF.TCURF_FCURR AND 
			B00_IT_TCURF.TCURF_TCURR  = @currency  AND
			B00_IT_TCURF.TCURF_GDATU <=A.B11B_ACDOCA_BUDAT
	ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
	)

LEFT JOIN B00_IT_TCURR TCURR_CUC
	ON A.B11B_ACDOCA_RHCUR = TCURR_CUC.TCURR_FCURR
	AND TCURR_CUC.TCURR_TCURR  = @currency  
	AND TCURR_CUC.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE A.B11B_ACDOCA_RHCUR = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A.B11B_ACDOCA_BUDAT
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 


GROUP BY A.B11B_ACDOCA_RBUKRS,
		 A.B11B_ACDOCA_GJAHR, 
		 A.B11B_ACDOCA_BELNR



EXEC SP_UNNAME_FIELD 'B11B_',DC05_01_IT_PTP_APA
EXEC SP_RENAME_FIELD 'DC05_01_',DC05_01_IT_PTP_APA



GO
