USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_B06_SS01_AR_AP_SAP_CLOSE_DATE_RANGE]
AS

--Step 1 Get the JE numbers, input date, link to date range between AP/AR Close to SAP Domestic Close
--Get only the JE between the date range
-- and entry type is manual and the debit lines
EXEC SP_DROPTABLE 'B06_03_TT_FIN_GL_ADD_DATE_RANGE'
SELECT
	B06_ACDOCA_RBUKRS AS ACDOCA_RBUKRS,
	B06_ACDOCA_GJAHR AS ACDOCA_GJAHR,
	B06_ACDOCA_BELNR AS ACDOCA_BELNR,
	B06_ACDOCA_CPUDT AS ACDOCA_CPUDT,
	B06_ZF_ACDOCA_HSL_S_CUC AS ZF_ACDOCA_HSL_S_CUC,
	AM_DATE_FROM,
	AM_DATE_TO,
	CONCAT( FORMAT(AM_DATE_FROM,'yyyy-MM-dd'), ' to ', FORMAT(AM_DATE_TO,'yyyy-MM-dd')) AS ZF_DATE_RANGE
INTO B06_03_TT_FIN_GL_ADD_DATE_RANGE
FROM B06_02_IT_FIN_GL_SUMMARY
INNER JOIN AM_DATE_RANGE
ON B06_ACDOCA_CPUDT BETWEEN AM_DATE_FROM AND AM_DATE_TO
WHERE
	B06_ZF_ENTRY_TYPE='Manual' AND
	B06_ZF_ACDOCA_DRCRK_DESC='Debit'

--Step 2/ Summarize the JEs, add the amount range for each JEs
EXEC SP_DROPTABLE B06_04_XT_FIN_GL_ADD_DATE_RANGE
SELECT 
	ACDOCA_RBUKRS,
	ACDOCA_GJAHR,
	ACDOCA_BELNR,
	ACDOCA_CPUDT,
	ZF_DATE_RANGE,
	SUM(ZF_ACDOCA_HSL_S_CUC) AS ZF_SUM_ACDOCA_HSL_S_CUC_MANUAL_DEBIT,
	CASE
		WHEN SUM(ZF_ACDOCA_HSL_S_CUC)<25000 THEN '<25000'
		WHEN SUM(ZF_ACDOCA_HSL_S_CUC)>=25000 AND SUM(ZF_ACDOCA_HSL_S_CUC)<=50000 THEN '>=25000 and <=50000'
		WHEN SUM(ZF_ACDOCA_HSL_S_CUC)>50000 THEN '>50000'
	END AS ZF_ACDOCA_HSL_S_CUC_MANUAL_DEBIT_RANGE
INTO B06_04_XT_FIN_GL_ADD_DATE_RANGE
FROM B06_03_TT_FIN_GL_ADD_DATE_RANGE
GROUP BY 
	ACDOCA_RBUKRS,
	ACDOCA_GJAHR, 
	ACDOCA_BELNR,
	ACDOCA_CPUDT,
	ZF_DATE_RANGE

--Remove temporary table
EXEC SP_REMOVE_TABLES 'B06_03_TT_FIN_GL_ADD_DATE_RANGE'
--Rename the fields
EXEC SP_RENAME_FIELD 'B06_04_','B06_04_XT_FIN_GL_ADD_DATE_RANGE'
GO
