USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[B11_PTP_APA_NEW](@DBNAME as NVARCHAR(MAX))
AS
--	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B11_%'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B11_PTP_APA_NEW'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B11_SS01_INVOICE_PATTERN'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_P08_T04_DUPLICATE_INVOICES_OPTIMIZED'
GO
