USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[SP_PRINT_DYNAMIC](
							@SP_NAME AS NVARCHAR(MAX),
							@START_FROM AS NVARCHAR(MAX) = '--DYNAMIC_SCRIPT_START')
AS

DECLARE @SQL_STR varchar(max)

SET @SQL_STR = (SELECT RIGHT(definition, LEN(definition) - CHARINDEX(@START_FROM,definition,1) + 1)  
								FROM sys.sql_modules  
								WHERE object_id = (OBJECT_ID(@SP_NAME)))
SET @SQL_STR = '
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
' + @SQL_STR + '
GO'
SET @SQL_STR = REPLACE(@SQL_STR, 'CREATE PROCEDURE', 'CREATE OR ALTER PROCEDURE')
SET @SQL_STR = REPLACE(@SQL_STR, 'CREATE PROC', 'CREATE OR ALTER PROCEDURE')
SET @SQL_STR = REPLACE(@SQL_STR, 'CREATE FUNCTION', 'CREATE OR ALTER FUNCTION')

PRINT @SQL_STR
--EXEC SP_EXECUTESQL @SQL_STR
GO
