USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[B14_OTC_ARE](@DBNAME as NVARCHAR(MAX))
AS
	EXEC SP_REMOVE_TABLES_MASTER @DBNAME, 'B14_%'
	EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B14_OTC_ARE'
    EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B14B_OTC_ARE_REFERENCE_AGEING'

GO
