USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
 CREATE   PROC [dbo].[B04_SS01_ACCOUNTING_SCHEME] (@DBNAME NVARCHAR(MAX))
AS


EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B04_SS01_ACCOUNTING_SCHEME'
GO
