USE [DIVA_MASTER_SCRIPT_S4HANA]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROC [dbo].[B07_FIN_AR_AUTOMAPPING](@DBNAME as NVARCHAR(MAX))
AS

EXEC SP_EXEC_DYNAMIC @DBNAME, 'script_B07_FIN_AR_AUTOMAPPING'

-- Add extra prediction for missing lines with Machine learning module
--EXEC SP_EXEC_DYNAMIC @DBNAME, 'SP_AR_ML_PRED'
GO
