USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_SU81_Identify transports originate in the development system]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START

-- Script object: Identify transports originate in the development system
-- Step 1: select data from transport cube (BC24_01_IT_TRANSPORT_SYSTEM table)

EXEC SP_REMOVE_TABLES 'SU81_01_RT_E070_TRANSPORT_MIGRATED_TO_PRODUCTION'

SELECT *,
	SUBSTRING(E070_TRKORR,1,3) AS ZF_SOURCE_SYSTEM
INTO SU81_01_RT_E070_TRANSPORT_MIGRATED_TO_PRODUCTION
FROM BC24_01_IT_E070_TRANSPORT_SYSTEM

-- Rename the fields
EXEC SP_RENAME_FIELD 'SU81_01_', 'SU81_01_RT_E070_TRANSPORT_MIGRATED_TO_PRODUCTION'


GO
