USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_B00_SS01_OTC_INFO_TABLE]
AS

--DYNAMIC_SCRIPT_START

	--Create dictionary table for VBTYP value
	EXEC SP_REMOVE_TABLES 'B00_DD07T_VBTYP'
	SELECT DD07T_DOMVALUE_L, DD07T_DDTEXT, DD07T_VALPOS
	INTO B00_DD07T_VBTYP
	FROM A_DD07T
	WHERE DD07T_DDLANGUAGE IN ('EN', 'E') AND DD07T_DOMNAME = 'VBTYP' AND DD07T_DOMVALUE_L <> ''
	ORDER BY DD07T_VALPOS


	--Create dictionary table for XAUTO value
	EXEC SP_REMOVE_TABLES 'B00_DD07T_MB_XAUTO'
	SELECT DD07T_DOMVALUE_L, DD07T_DDTEXT, DD07T_VALPOS
	INTO B00_DD07T_MB_XAUTO
	FROM A_DD07T
	WHERE DD07T_DDLANGUAGE IN ('EN', 'E') AND DD07T_DOMNAME = 'MB_XAUTO' AND DD07T_DOMVALUE_L <> ''
	ORDER BY DD07T_VALPOS

	--Create dictionary table for FKTYP (Billing type) value
	EXEC SP_REMOVE_TABLES 'B00_DD07T_FKTYP'
	SELECT DD07T_DOMVALUE_L, DD07T_DDTEXT, DD07T_VALPOS
	INTO B00_DD07T_FKTYP
	FROM A_DD07T
	WHERE DD07T_DDLANGUAGE IN ('EN', 'E') AND DD07T_DOMNAME = 'FKTYP' AND DD07T_DOMVALUE_L <> ''
	ORDER BY DD07T_VALPOS

	--Create dictionary table for BSTAT value
	EXEC SP_REMOVE_TABLES 'B00_DD07T_BSTAT'
	SELECT DD07T_DOMVALUE_L, DD07T_DDTEXT, DD07T_VALPOS
	INTO B00_DD07T_BSTAT
	FROM A_DD07T
	WHERE DD07T_DDLANGUAGE IN ('EN', 'E') AND DD07T_DOMNAME = 'BSTAT'
	ORDER BY DD07T_VALPOS

	--Create a cude store 
	--all relationship between company code and sale organiztion,
	--to filter the VBAK/VBAP tables because this table do not have company code
	-- 31_12_2021 Thuan : Remove MANDT field (join) 
	EXEC SP_REMOVE_TABLES 'B00_TVKO'
	SELECT TVKO_VKORG,TVKO_BUKRS
	INTO B00_TVKO
	FROM A_TVKO
	WHERE EXISTS(SELECT TOP 1 1 FROM A_BKPF WHERE BKPF_BUKRS = TVKO_BUKRS
	AND BKPF_BUKRS IN (SELECT * FROM AM_SCOPE))
	
GO
