USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_SU49_Identify lockboxes that are not correctly set-up]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START

-- Script objective: Identify dustomer payment document types not defined in lockbox 
-- or lockbox accounts that do not have partial payment flag checked 
EXEC SP_REMOVE_TABLES 'SU49_%'

--Step 1: Identify lockbox accounts are routed
EXEC SP_REMOVE_TABLES 'SU49_01_RT_T049A_LOCKBOX_ACC_ROUTED'

SELECT A_T049A.*,
	IIF(LEN(T049A_ORIGN) > 1,'Yes', 'No' ) AS ZF_T049A_ORIGN_LOCKBOX_HAVE_ROUT_NUM_FLAG,
	A.T003T_LTEXT AS ZF_T049A_BABNK_T003T_LTEXT,
	B.T003T_LTEXT AS ZF_T049A_BADEB_T003T_LTEXT,
	T001_BUTXT,
	C.SKAT_TXT20 AS ZF_T049A_BKKTO_SKAT_TXT20,
	D.SKAT_TXT20 AS ZF_T049A_SEKTO_SKAT_TXT20
INTO SU49_01_RT_T049A_LOCKBOX_ACC_ROUTED
FROM A_T049A
LEFT JOIN A_T003T AS A ON A.T003T_BLART=T049A_BABNK
LEFT JOIN A_T003T AS B ON B.T003T_BLART=T049A_BADEB
LEFT JOIN A_T001 ON T049A_BUKRS=T001_BUKRS
LEFT JOIN A_SKAT AS C ON T049A_BKKTO=C.SKAT_SAKNR AND T001_KTOPL=C.SKAT_KTOPL
LEFT JOIN A_SKAT AS D ON T049A_SEKTO=D.SKAT_SAKNR AND T001_KTOPL=D.SKAT_KTOPL


-- Step 2: Identify Indicators setting
EXEC SP_REMOVE_TABLES 'SU49_02_RT_T049B_INDICATORS_SETTING'

SELECT *,
	-- Add T049B_FB1KZ(type of G/L account posting) description
	(
	CASE T049B_FB1KZ
		WHEN '1' THEN 'One posting per check to the bank account'
		WHEN '2' THEN 'One posting per lockbox to the bank account (check total)'
		WHEN '3' THEN 'One posting per batch number to the bank account'
	END
	) AS ZF_T049B_FB1KZ_DESCRIPTION
INTO SU49_02_RT_T049B_INDICATORS_SETTING
FROM A_T049B

-- Step 3: Check if customers are assigned to lockbox (customer in KNB1 table)
EXEC SP_REMOVE_TABLES 'SU49_03_XT_KNB1_CUS_ASSIGN_LOCKBOX'

SELECT DISTINCT
	KNB1_BUKRS,
	KNB1_KUNNR,
	KNA1_NAME1,
	KNB1_LOCKB,
	KNB1_PERNR,
	KNB1_ERDAT,
	KNB1_ERNAM,
	KNB1_SPERR,
	KNB1_LOEVM,
	KNB1_BEGRU,
	KNB1_KNRZB,
	KNB1_KNRZE,
	IIF(LEN(KNB1_LOCKB) > 1, 'Yes', 'No') AS ZF_KNB1_LOCKB_CUS_ASS_LOCKBOX_FLAG,
	T001_BUTXT,
	V_USERNAME_NAME_TEXT
INTO SU49_03_XT_KNB1_CUS_ASSIGN_LOCKBOX
FROM A_KNB1
LEFT JOIN A_KNA1
ON KNA1_KUNNR = KNB1_KUNNR
LEFT JOIN A_T001
ON T001_BUKRS=KNB1_BUKRS
LEFT JOIN A_V_USERNAME
ON KNB1_ERNAM=V_USERNAME_BNAME
WHERE LEN(TRIM(KNB1_LOCKB))=0
-- Rename the fields
EXEC SP_RENAME_FIELD 'SU49_01_', 'SU49_01_RT_T049A_LOCKBOX_ACC_ROUTED'
EXEC SP_RENAME_FIELD 'SU49_02_', 'SU49_02_RT_T049B_INDICATORS_SETTING'
EXEC SP_RENAME_FIELD 'SU49_03_', 'SU49_03_XT_KNB1_CUS_ASSIGN_LOCKBOX'


GO
