USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_BC12_MARA_VS_MAKT_ADD_MAK_MAKTX ]
AS
--DYNAMIC_SCRIPT_START
---Objective: Create the B phase table for SU04 for material number with description

EXEC SP_DROPTABLE BC12_01_IT_MARA_VS_MAKT_ADD_MAKT_MAKTX;
SELECT DISTINCT MARA_MATNR,
       MARA_MATNR+'-'+MAKT_MAKTX AS ZF_MARA_MATNR_DESC,
	   MAKT_MAKTX,
       MARA_EKWSL
INTO BC12_01_IT_MARA_VS_MAKT_ADD_MAKT_MAKTX
FROM A_MARA
LEFT JOIN 
      (SELECT DISTINCT  MAKT_MATNR,
	                     MAKT_MAKTX
	   FROM A_MAKT) A
ON MARA_MATNR = MAKT_MATNR
WHERE MARA_MATNR <> ' ';

GO
