USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_BC44_CDHDR_CDPOS]
AS
--DYNAMIC_SCRIPT_START
--STep 1 : Get the change information from CDHDR/CDPOS, get only infor relate to payment only
--OBJECTCLAS is INCOMINGINVOICE or BELEG
--CDPOS_FNAME is ZLSPR
--Add 2 flag to check payment block or unblock
--Add table names and fields info
EXEC SP_DROPTABLE 'BC44_01_IT_CDHDR_CDPOS_PAYMENT_BLOCK'

SELECT A_CDHDR.*,A_CDPOS.*,
	IIF(CDPOS_VALUE_OLD='' AND CDPOS_VALUE_NEW<>'','X','') AS ZF_CDPOS_VALUE_NEW_OLD_BLOCK,
	IIF(CDPOS_VALUE_OLD<>'' AND CDPOS_VALUE_NEW='','X','') AS ZF_CDPOS_VALUE_NEW_OLD_UNBLOCK,
	CASE 
		WHEN CDPOS_VALUE_OLD='' AND CDPOS_VALUE_NEW<>'' THEN 'Block'
		WHEN CDPOS_VALUE_OLD<>'' AND CDPOS_VALUE_NEW='' THEN 'Unblock'
	ELSE '' END AS ZF_BLOCK_UNBLOCK_DESC,		
	DD02T_DDTEXT,DDFTX_FIELDTEXT
INTO BC44_01_IT_CDHDR_CDPOS_PAYMENT_BLOCK
FROM A_CDHDR
INNER JOIN A_CDPOS 
ON CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS
	AND CDHDR_OBJECTID=CDPOS_OBJECTID
	AND CDHDR_CHANGENR=CDPOS_CHANGENR
LEFT JOIN A_DD02T
ON CDPOS_TABNAME=DD02T_TABNAME
LEFT JOIN A_DDFTX
ON CDPOS_TABNAME=DDFTX_TABNAME AND CDPOS_FNAME=DDFTX_FIELDNAME
WHERE 
	(CDHDR_OBJECTCLAS ='INCOMINGINVOICE'  OR CDHDR_OBJECTCLAS='BELEG')
	AND CDPOS_FNAME='ZLSPR'

--Step 2 Get the change from CDHDR/CDPOS for KRED
--and field name is 'ZAHLS','SPERM','LOEVM','SPERR','SPERZ'
--Add the text description for table name and table field name
EXEC SP_DROPTABLE BC44_02_IT_CDHDR_CDPOS_KRED
SELECT A_CDHDR.*,A_CDPOS.*,
	DD02T_DDTEXT,DDFTX_FIELDTEXT
INTO BC44_02_IT_CDHDR_CDPOS_KRED
FROM A_CDHDR
INNER JOIN A_CDPOS 
ON CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS
	AND CDHDR_OBJECTID=CDPOS_OBJECTID
	AND CDHDR_CHANGENR=CDPOS_CHANGENR
LEFT JOIN A_DD02T
ON CDPOS_TABNAME=DD02T_TABNAME
LEFT JOIN A_DDFTX
ON CDPOS_TABNAME=DDFTX_TABNAME AND CDPOS_FNAME=DDFTX_FIELDNAME
WHERE 
	CDHDR_OBJECTCLAS ='KRED'  AND CDPOS_TABNAME IN ('LFA1','LFB1') 
	AND CDPOS_FNAME IN ('ZAHLS','SPERM','LOEVM','SPERR','SPERZ','AKONT')

--Step 3 Get the change from CDHDR/CDPOS for DEBI
-- and field name is 'ZAHLS','SPERM','LOEVM','SPERR','SPERZ'
--Add the text description for table name and table field name
EXEC SP_DROPTABLE BC44_03_IT_CDHDR_CDPOS_DEBI
SELECT A_CDHDR.*,A_CDPOS.*,
	DD02T_DDTEXT,DDFTX_FIELDTEXT
INTO BC44_03_IT_CDHDR_CDPOS_DEBI
FROM A_CDHDR
INNER JOIN A_CDPOS 
ON CDHDR_OBJECTCLAS=CDPOS_OBJECTCLAS
	AND CDHDR_OBJECTID=CDPOS_OBJECTID
	AND CDHDR_CHANGENR=CDPOS_CHANGENR
LEFT JOIN A_DD02T
ON CDPOS_TABNAME=DD02T_TABNAME
LEFT JOIN A_DDFTX
ON CDPOS_TABNAME=DDFTX_TABNAME AND CDPOS_FNAME=DDFTX_FIELDNAME
WHERE 
	CDHDR_OBJECTCLAS ='DEBI'  AND CDPOS_TABNAME IN ('KNA1','KNB1')
	AND CDPOS_FNAME IN ('ZAHLS','SPERM','LOEVM','SPERR','SPERZ')

GO
