USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_BC20_SENSITIVE_CUSTOMER_FIELDS]
AS
--DYNAMIC_SCRIPT_START
---Objective: identify if we have any sensitive customer fields are set for dual validation. 
EXEC SP_DROPTABLE BC18_01_IT_SENSITIVE_CUSTOMER_FIELDS;
SELECT *
INTO BC18_01_IT_SENSITIVE_CUSTOMER_FIELDS
FROM A_T055F;
GO
