USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_SU55_Identify one-time customers that are not in correct account group]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START

-- Script object:Check the association of customer records configured for one-time vendor with one-time vendor account group
-- Step 1: select one-time vendor account from BO01_01_IT_CUSTOMER (customer cube)
EXEC SP_REMOVE_TABLES 'SU55_%'


EXEC SP_REMOVE_TABLES 'SU55_01_XT_KNB1_KNA1_ASSOCIATE_ONETIME_CUS_AND_ACCT_GROUP'
SELECT DISTINCT
	BO01_01_KNB1_KUNNR AS KNB1_KUNNR,
	BO01_01_KNA1_LAND1 AS KNA1_LAND1,
	BO01_01_KNA1_NAME1 AS KNA1_NAME1,
	BO01_01_KNA1_XCPDK AS KNA1_XCPDK,
	T077D_KTOKD,
	T077D_XCPDS,
	A_T077X.T077X_TXT30,
	-- Add flag to check the association of customer records configured for one-time vendor with one-time vendor account group
	(
		CASE
			WHEN BO01_01_KNA1_XCPDK <> T077D_XCPDS THEN 'No'
			ELSE 'Yes'
		END
	) AS ZF_KNA1_XCPDK_EQ_T077D_XCPDS_FLAG
INTO SU55_01_XT_KNB1_KNA1_ASSOCIATE_ONETIME_CUS_AND_ACCT_GROUP
FROM BO01_01_IT_CUSTOMER
-- Left join with T007D table to add one-time customer account group
LEFT JOIN A_T077D
ON BO01_01_KNA1_KTOKD = T077D_KTOKD
-- Get account group names
LEFT JOIN A_T077X
ON T077X_KTOKD = T077D_KTOKD
-- Just take customer records configured for one-time vendor
WHERE BO01_01_KNA1_XCPDK = 'X'

-- Rename the fields
EXEC SP_RENAME_FIELD 'SU55_01_', 'SU55_01_XT_KNB1_KNA1_ASSOCIATE_ONETIME_CUS_AND_ACCT_GROUP'

---Minh update phase 2: 
--Step 1: inner join BSAID/BSID with table SU55_01_XT_KNB1_KNA1_ASSOCIATE_ONETIME_VENDOR_AND_ACCT_GROUP to identify the transactions of customers are defined as
--one time customer 


--Minh sript- please recheck
--EXEC SP_DROPTABLE SU55_02_XT_BSEG_BKPF_BSAID_BSID_EXTRACT_KOSTL_TCODE_BLART;
--SELECT DISTINCT  
--       B.*,
--	   C.B04_GL_ACDOCA_RBUKRS,
--	   C.B04_GL_ACDOCA_GJAHR,
--	   C.B04_GL_ACDOCA_BELNR,
--	   C.B04_GL_ACDOCA_BUZEI,
--	   B04_GL_ACDOCA_KOSTL, 
--       B04_GL_BKPF_TCODE,
--	   B04_BKPF_BLART,
--	   B04_ZF_BSEG_DMBTR_S_CUC
--INTO SU55_02_XT_BSEG_BKPF_BSAID_BSID_EXTRACT_KOSTL_TCODE_BLART
--FROM B04_11_TT_BSID_BSAD A 
--JOIN SU55_01_XT_KNB1_KNA1_ASSOCIATE_ONETIME_VENDOR_AND_ACCT_GROUP B
--ON  B.SU55_01_KNB1_KUNNR = A.B04_11_BSAID_KUNNR
--JOIN B04_08_IT_FIN_GL C
--ON A.B04_11_BSAID_BELNR = C.B04_GL_ACDOCA_BELNR AND A.B04_11_BSAID_BUKRS = C.B04_GL_ACDOCA_RBUKRS
--AND A.B04_11_BSAID_GJAHR = C.B04_GL_ACDOCA_GJAHR AND A.B04_11_BSAID_BUZEI = C.B04_GL_ACDOCA_BUZEI
--WHERE A.B04_11_ZF_BSAID_SHKZG_DESC = 'Debit'

--Khoi script
-- Get the data from about AR transactions- only get the lines relate to one-time customer
EXEC SP_DROPTABLE 'SU55_02_XT_BSAID_TRANSACTION_ONE_TIME_CUSTOMER'

SELECT A.*,B04_GL_ACDOCA_KTOSL AS ACDOCA_KTOSL,T030W_LTEXT--,A_KNA1.KNA1_NAME1,A_TSTCT.TSTCT_TTEXT
		,T001_BUTXT,B04_GL_ACDOCA_USNAM,V_USERNAME_NAME_TEXT
INTO SU55_02_XT_BSAID_TRANSACTION_ONE_TIME_CUSTOMER
FROM B04_13_IT_AR_ACC_SCH AS A
LEFT JOIN 
B04_08_IT_FIN_GL AS B
ON B.B04_GL_ACDOCA_RBUKRS=A.ACDOCA_RBUKRS
	AND B.B04_GL_ACDOCA_GJAHR=A.ACDOCA_GJAHR
	AND B.B04_GL_ACDOCA_BELNR= A.ACDOCA_BELNR
	AND B.B04_GL_ACDOCA_BUZEI=A.ACDOCA_BUZEI
LEFT JOIN A_T030W 
	ON B04_GL_ACDOCA_KTOSL=T030W_KTOSL AND T030W_SPRAS='EN'
LEFT JOIN A_TSTCT
	ON A_TSTCT.TSTCT_TCODE=B04_GL_BKPF_TCODE AND A_TSTCT.TSTCT_SPRSL='EN'
LEFT JOIN A_KNA1
	ON ACDOCA_KUNNR= KNA1_KUNNR 
LEFT JOIN A_T001
	ON T001_BUKRS=ACDOCA_RBUKRS
LEFT JOIN A_V_USERNAME
	ON V_USERNAME_BNAME=B04_GL_ACDOCA_USNAM
WHERE ACDOCA_KUNNR IN
(
	SELECT DISTINCT SU55_01_KNB1_KUNNR
	FROM SU55_01_XT_KNB1_KNA1_ASSOCIATE_ONETIME_CUS_AND_ACCT_GROUP
)

--Step 2: sales documents, we need to see some stats on those that are one time customers and a focus on graphs that help us to analyse the ship-to customer in roder to see 
--if there are lots of shippings to the smae customer (shouldn't be because it is supposed to be "one-time")

--Get the sale document relate to one-time customer

EXEC SP_DROPTABLE SU55_03_XT_VBAK_VBAP_ONE_TIME_CUSTOMER

SELECT B28_01_IT_SALE_DOCUMENTS.*,
	B29_LIKP_KUNNR  --delivery ship to
	,B29_ZF_KNA1_NAME1_SHIP_TO
INTO SU55_03_XT_VBAK_VBAP_ONE_TIME_CUSTOMER
FROM 
B28_01_IT_SALE_DOCUMENTS
--Add the ship to from delivery, if it has delivery
LEFT JOIN B29_01_IT_DELIVERY_DOCS
ON B28_VBAK_VBELN=B29_LIKP_VBELN AND B28_VBAP_POSNR=B29_LIPS_POSNR
WHERE B28_VBAK_KUNNR IN
(
	SELECT DISTINCT SU55_01_KNB1_KUNNR
	FROM SU55_01_XT_KNB1_KNA1_ASSOCIATE_ONETIME_CUS_AND_ACCT_GROUP
)

--Step 3 Get the delivery relate to sale order that have one-time vendor

EXEC SP_DROPTABLE SU55_04_XT_DELIVERY_ONE_TIME_CUSTOMER

SELECT B29_01_IT_DELIVERY_DOCS.*
INTO SU55_04_XT_DELIVERY_ONE_TIME_CUSTOMER
FROM B29_01_IT_DELIVERY_DOCS
INNER JOIN SU55_03_XT_VBAK_VBAP_ONE_TIME_CUSTOMER
ON B28_VBAK_VBELN=B29_LIKP_VBELN AND B28_VBAP_POSNR=B29_LIPS_POSNR


--Rename all the field
EXEC SP_UNNAME_FIELD 'B04B_','SU55_02_XT_BSAID_TRANSACTION_ONE_TIME_CUSTOMER'
EXEC SP_UNNAME_FIELD 'B04_GL_','SU55_02_XT_BSAID_TRANSACTION_ONE_TIME_CUSTOMER'
EXEC SP_UNNAME_FIELD 'B28_','SU55_03_XT_VBAK_VBAP_ONE_TIME_CUSTOMER'
EXEC SP_UNNAME_FIELD 'B29_','SU55_03_XT_VBAK_VBAP_ONE_TIME_CUSTOMER'
EXEC SP_UNNAME_FIELD 'B29_','SU55_04_XT_DELIVERY_ONE_TIME_CUSTOMER'


EXEC SP_RENAME_FIELD 'SU55_02_','SU55_02_XT_BSAID_TRANSACTION_ONE_TIME_CUSTOMER'
EXEC SP_RENAME_FIELD 'SU55_03_','SU55_03_XT_VBAK_VBAP_ONE_TIME_CUSTOMER'
EXEC SP_RENAME_FIELD 'SU55_04_','SU55_04_XT_DELIVERY_ONE_TIME_CUSTOMER'


GO
