USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_SU20_Identify billing document types that prevent auto GL posting]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START

    DECLARE  
			@CURRENCY NVARCHAR(MAX)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
			,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
			,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
			,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
			,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
			,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
			,@LANGUAGE1 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
			,@LANGUAGE2 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
			,@YEAR NVARCHAR(MAX)                     = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
			,@ID NVARCHAR(MAX)                       = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
			,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
			,@ZV_SAME_QUARTER_BY_BLDAT NVARCHAR(MAX) = ISNULL((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'ZV_SAME_QUARTER_BY_BLDAT'), '')
 
-- Script objective: Check  billing document have Account determination procedure or not
-- Step 1: Select data from billing document types 
EXEC SP_REMOVE_TABLES 'SU20_%'

EXEC SP_REMOVE_TABLES 'SU20_01_RT_TVFK_BILL_DOC_POSTING_BLOCK'
	SELECT DISTINCT
	TVFK_FKART,
	TVFKT_VTEXT,
	TVFK_KALSMC,
	TVFK_RFBFK,
	T683U_VTEXT,
	-- Add flag to check billing document have account determination procedure or not
	(
		CASE
			WHEN LEN(TVFK_KALSMC) < 1 THEN 'No'
			ELSE 'Yes'
		END
	) AS ZF_TVFK_KALSMC_ACC_DET_PR_SET,
	-- Add flag to check billing document blocked for transfer to accounting or not
	IIF(LEN(TVFK_RFBFK)>0,'Yes','No') AS ZF_TVFK_RFBFK_BLCK_TR_ACC
	INTO SU20_01_RT_TVFK_BILL_DOC_POSTING_BLOCK
	FROM A_TVFK
	-- Get billing: document types description
	LEFT JOIN A_TVFKT
	ON TVFKT_FKART = TVFK_FKART
	-- Get determination procedure description
	LEFT JOIN A_T683U
	ON TVFK_KALSMC = T683U_KALSM
	AND TVFK_KAPPL = T683U_KAPPL

-- Step 2 Find the items that are in VBRP/VBRK and that are not found in BSAD/BSID

	EXEC SP_REMOVE_TABLES 'SU20_02_XT_TVFK_IN_VBRP_VBRK_NOT_IN_BSAD_BID'
	SELECT 
		A.*, 
		CONCAT(DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE), ' day(s)') AS ZF_DOWN_DIFF_CRE_DATE_D,
		CASE
			WHEN DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) < 31 THEN '0-30 days'
			WHEN DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) > 30 AND DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) < 91 THEN '30-90 days'
			WHEN DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) > 90 AND DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) < 181 THEN '90-180 days'
			WHEN DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) > 180 AND DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) < 366 THEN '180-365 days'
			ELSE '>365 days'
		END AS ZF_DOWN_DIFF_CRE_BUCKET,
		CASE
			WHEN DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) < 31 THEN 1
			WHEN DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) > 30 AND DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) < 91 THEN 2
			WHEN DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) > 90 AND DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) < 181 THEN 3
			WHEN DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) > 180 AND DATEDIFF(DAY,B30_VBRK_ERDAT, @DOWNLOADDATE) < 366 THEN 4
			ELSE 5
		END AS ZF_DOWN_DIFF_CRE_BUCKET_ORDER
	INTO SU20_02_XT_TVFK_IN_VBRP_VBRK_NOT_IN_BSAD_BID
	FROM B30_01_IT_INVOICE_DOCS A
	LEFT JOIN A_BKPF B
		ON A.B30_VBRK_VBELN = B.BKPF_AWKEY
	LEFT JOIN SU20_01_RT_TVFK_BILL_DOC_POSTING_BLOCK D
		ON D.TVFK_FKART = A.B30_VBRK_FKART
	WHERE B.BKPF_AWKEY IS NULL AND B.BKPF_AWTYP='VBRK' 



EXEC SP_UNNAME_FIELD 'B30_', 'SU20_02_RT_TVFK_IN_VBRP_VBRK_NOT_IN_BSAD_BID' 
-- Rename the fields
EXEC SP_RENAME_FIELD 'SU20_01_', 'SU20_01_RT_TVFK_BILL_DOC_POSTING_BLOCK' 
EXEC SP_RENAME_FIELD 'SU20_02_', 'SU20_02_XT_TVFK_IN_VBRP_VBRK_NOT_IN_BSAD_BID' 
--


GO
