USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_SU72_Check if all system users have changed passwords]
AS
--DYNAMIC_SCRIPT_START

---Step 1: Identify if all the default system users have been changed password
---So we will find out the default system users have not changed password
EXEC SP_DROPTABLE SU72_01_XT_USR02_PWDCHGDATE_FLK_00000000;
SELECT *,
	IIF( LEN(USR02_SECURITY_POLICY) <> 0, 'Yes','No') AS ZF_SECURITY_POLICY, 
    IIF( LEN(USR02_PWDCHGDATE) <> 0 OR LEN(USR02_BCDA1) <> 0 OR LEN(USR02_BCDA2) <> 0 OR LEN(USR02_BCDA3) <> 0 OR LEN(USR02_BCDA4) <> 0 OR LEN(USR02_BCDA5) <> 0, 'Yes','No') AS ZF_PWDCHGDATE_BCDA1_TO_BCDA5_IS_BLK
INTO SU72_01_XT_USR02_PWDCHGDATE_FLK_00000000
FROM BC16_01_IT_USR02_USERS
WHERE ZF_USR02_DEFAULT_USER LIKE 'Yes';

EXEC SP_RENAME_FIELD 'SU72_01_','SU72_01_XT_USR02_PWDCHGDATE_FLK_00000000';

GO
