USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE      PROCEDURE [dbo].[script_BO01_CUSTOMERS]
WITH EXECUTE AS CALLER
AS

--DYNAMIC_SCRIPT_START
/*Change history comments*/

/*
	Title			:	BO01: Customer master
	  
	--------------------------------------------------------------
	Update history
	--------------------------------------------------------------
	Date		    | Who |	Description
	06/10/2022        KHOA   First version for Sony ECC
*/

-- Create one customer master table including information from the customer master data by company code (KNB1) and address information (KNA1)
DECLARE  
                @CURRENCY NVARCHAR(MAX)                 = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
                ,@DATE1 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
                ,@DATE2 NVARCHAR(MAX)                           = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
                ,@DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
                ,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
                ,@EXCHANGERATETYPE NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
                ,@LANGUAGE1 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
                ,@LANGUAGE2 NVARCHAR(MAX)                = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
                ,@YEAR NVARCHAR(MAX)                     = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
                ,@ID NVARCHAR(MAX)                       = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
                ,@LIMIT_RECORDS INT                    = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)
				,@ZV_SAME_QUARTER_BY_BLDAT NVARCHAR(MAX) = ISNULL((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'ZV_SAME_QUARTER_BY_BLDAT'), '')
 
EXEC SP_DROPTABLE 'BO01_01_TT_A_TCURF'
SELECT 
    TCURF_MANDT,
	TCURF_FCURR,
	TCURF_TCURR,
	CONVERT(DATE,CAST(99999999-TCURF_GDATU AS NVARCHAR), 112) TCURF_GDATU,
	TCURF_FFACT,
	TCURF_TFACT			
INTO BO01_01_TT_A_TCURF
FROM A_TCURF
WHERE TCURF_KURST = 'M' AND TCURF_GDATU < 90000000

EXEC sp_droptable 'BO01_01_IT_CUSTOMER'
SELECT 
	A_KNB1.KNB1_MANDT,
	A_KNB1.KNB1_KUNNR,
	AM_SCOPE.SCOPE_BUSINESS_DMN_L1,
	AM_SCOPE.SCOPE_BUSINESS_DMN_L2,
    A_KNB1.KNB1_BUKRS,
    A_KNA1.KNA1_LOEVM,
    A_KNA1.KNA1_NAME1,
    A_KNA1.KNA1_LAND1,
    A_KNA1.KNA1_KUKLA,
    A_KNA1.KNA1_KONZS,
    A_KNB1.KNB1_LOEVM,
    A_KNA1.KNA1_ORT01,
    A_KNA1.KNA1_STRAS,
    A_KNA1.KNA1_PSTLZ,
    A_KNA1.KNA1_SORTL,
    A_KNA1.KNA1_VBUND,
    A_KNA1.KNA1_KTOKD,
    A_KNA1.KNA1_SPERR,
    A_KNB1.KNB1_AKONT,
    A_KNB1.KNB1_SPERR,
    A_KNA1.KNA1_STCEG,
    A_KNA1.KNA1_ERDAT,
    A_KNB1.KNB1_ERDAT,
    A_KNA1.KNA1_ERNAM,
    A_KNB1.KNB1_ZWELS,
    A_KNB1.KNB1_ZTERM,
    A_KNA1.KNA1_XCPDK, 
    -- add Sony specific ECOT codes 
    A_KNA1.KNA1_BRAN1,
    A_KNA1.KNA1_BRAN2,
    A_KNA1.KNA1_BRAN3,
    A_KNA1.KNA1_BRAN4,
    A_KNA1.KNA1_BRAN5,
    A_KNB1.KNB1_VLIBB,
	A_T001.T001_WAERS AS ZF_T001_KNA1_WAERS,	
	A_T001.T001_BUTXT,
	ZF_VBRP_NETWR_COC,
	ZF_VBRP_NETWR_CUC,
--Khoi added more fields
	KNB1_TOGRU,
	KNB1_LOCKB,
	KNB1_PERNR,
	KNB1_ERNAM,
	KNB1_BEGRU,
	KNB1_KNRZB,
	KNB1_KNRZE
INTO BO01_01_IT_CUSTOMER  
FROM A_KNA1 	  
--customer master data per company code
INNER JOIN A_KNB1 
ON A_KNA1.KNA1_KUNNR = A_KNB1.KNB1_KUNNR
-- get ZF_VBRP_NETWR_COC and ZF_VBRP_NETWR_CUC 
LEFT JOIN
(
		SELECT DISTINCT  
		VBRK_KUNAG , 
		VBRK_BUKRS,
		SUM(CONVERT(money,(VBRP_NETWR * ISNULL(TCURX_FACTOR,1)
			* VBRP_KURSK * COALESCE(TCURF_COC.TCURF_TFACT,1))/COALESCE(TCURF_COC.TCURF_FFACT,1)))	AS ZF_VBRP_NETWR_COC, 

		SUM(((VBRP_NETWR)*ISNULL(TCURX_FACTOR,1))* VBRP_KURSK * COALESCE(TCURF_COC.TCURF_TFACT,1)/COALESCE(TCURF_COC.TCURF_FFACT,1) -- Thuan updated
			* COALESCE(CAST(TCURR_CUC.TCURR_UKURS AS FLOAT),1) * COALESCE(TCURF_CUC.TCURF_TFACT,1) / COALESCE(TCURF_CUC.TCURF_FFACT,1))	AS ZF_VBRP_NETWR_CUC
		FROM A_VBRK
		LEFT JOIN A_VBRP
			ON VBRK_VBELN = VBRP_VBELN
		LEFT JOIN A_T001
		ON  A_T001.T001_BUKRS = A_VBRK.VBRK_BUKRS
	
-- Add currency factor from document currency to local currency

		LEFT JOIN B00_IT_TCURF TCURF_COC
		ON VBRK_WAERK = TCURF_COC.TCURF_FCURR
		AND TCURF_COC.TCURF_TCURR  = T001_WAERS  
		AND TCURF_COC.TCURF_GDATU = (
			SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
			FROM B00_IT_TCURF
			WHERE VBRK_WAERK = B00_IT_TCURF.TCURF_FCURR AND 
					B00_IT_TCURF.TCURF_TCURR  = T001_WAERS  AND
					B00_IT_TCURF.TCURF_GDATU <= VBRK_ERDAT
			ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
			)

            
	-- Add currency factor from company currency to USD

		LEFT JOIN B00_IT_TCURF TCURF_CUC
		ON A_T001.T001_WAERS = TCURF_CUC.TCURF_FCURR
		AND TCURF_CUC.TCURF_TCURR  = @currency  
		AND TCURF_CUC.TCURF_GDATU = (
			SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
			FROM B00_IT_TCURF
			WHERE A_T001.T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
					B00_IT_TCURF.TCURF_TCURR  = @currency  AND
					B00_IT_TCURF.TCURF_GDATU <= VBRK_ERDAT
			ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
			)
		-- Add exchange rate from company currency to USD
		LEFT JOIN B00_IT_TCURR TCURR_CUC
			ON A_T001.T001_WAERS = TCURR_CUC.TCURR_FCURR
			AND TCURR_CUC.TCURR_TCURR  = @currency  
			AND TCURR_CUC.TCURR_GDATU = (
				SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
				FROM B00_IT_TCURR
				WHERE A_T001.T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
						B00_IT_TCURR.TCURR_TCURR  = @currency  AND
						B00_IT_TCURR.TCURR_GDATU <= VBRK_ERDAT
				ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
				) 


		-- Get currency factor
		LEFT JOIN B00_TCURX
		ON B00_TCURX.TCURX_CURRKEY = VBRK_WAERK

		GROUP BY VBRK_KUNAG, VBRK_BUKRS

) AS A ON A.VBRK_KUNAG = A_KNA1.KNA1_KUNNR
-- Get Company Codes
LEFT JOIN A_T001
ON  A_T001.T001_BUKRS = A_KNB1.KNB1_BUKRS
-- Add information from the scope table concerning the business domain   
LEFT JOIN AM_SCOPE                                         
ON   KNB1_BUKRS = AM_SCOPE.SCOPE_CMPNY_CODE



--/*Drop temporary tables*/

EXEC SP_RENAME_FIELD 'BO01_01_', 'BO01_01_IT_CUSTOMER'

GO
