USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE        PROCEDURE [dbo].[script_BP05A_REGUH]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START
BEGIN

/*Change history comments*/

/*
	Title			:	BP05A: REGUH
	  
	--------------------------------------------------------------
	Update history
	--------------------------------------------------------------
	Date		    | Who |	Description
	07/10/2022        KHOA   Cube for the payment settlements data
*/

DECLARE  
@CURRENCY NVARCHAR(MAX)  = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')

-- Create REGUH cube

EXEC SP_DROPTABLE 'BP05A_IT_01_REGUH'
SELECT 
	   REGUH_LAUFD
      ,REGUH_LAUFI
      ,REGUH_XVORL
      ,REGUH_ZBUKR
	  ,AM_SCOPE.SCOPE_BUSINESS_DMN_L1
	  ,AM_SCOPE.SCOPE_BUSINESS_DMN_L2
      ,REGUH_LIFNR
      ,REGUH_KUNNR
      ,REGUH_EMPFG
      ,REGUH_VBLNR
      ,REGUH_WAERS
      ,REGUH_NAME1
      ,REGUH_LAND1
      ,REGUH_ZNME1
      ,REGUH_ZORT1
      ,REGUH_ZLAND
      ,REGUH_ZBNKS
      ,REGUH_ZBNKN
      ,REGUH_ZBNKL
      ,REGUH_ZBKON
      ,REGUH_ZBVTY
      ,REGUH_ZALDT
      ,REGUH_RZAWE
      ,REGUH_RUMSK
      ,REGUH_UBHKT
      ,REGUH_RBETR
      ,REGUH_RWBTR
      ,REGUH_BNKS1
      ,REGUH_BNKL1
      ,REGUH_BNKN1
      ,REGUH_SAKNR
      ,REGUH_HKONT
	  ,T001_WAERS AS ZF_T001_REGUH_WAERS
	  --,AM_EXCHNG.EXCHNG_RATIO AS ZF_EXCHNG_RATIO
	  --,TCURX_CC.TCURX_CURRDEC AS ZF_TCURX_CURRDEC_CC   
	  

	  ,CONVERT(MONEY,REGUH_RWBTR * ISNULL(TCURX_DOC.TCURX_FACTOR,1)  ) AS ZF_REGUH_RWBTR --document currency
	  ,CONVERT(MONEY,REGUH_RBETR * ISNULL(TCURX_CC.TCURX_FACTOR,1) *
		COALESCE(CAST(B00_IT_TCURR.TCURR_UKURS AS FLOAT),1) * 
		COALESCE(B00_IT_TCURF.TCURF_TFACT,1) / COALESCE(B00_IT_TCURF.TCURF_FFACT,1)
		) AS ZF_REGUH_RBETR_CUC -- local amount to USD

	  ,CONVERT(MONEY,(REGUH_RBETR * ISNULL(TCURX_CC.TCURX_FACTOR,1) )) AS ZF_REGUH_RBETR_COC  --local amount

	  ,CONVERT(MONEY,REGUH_RBETR * ISNULL(TCURX_CC.TCURX_FACTOR,1) *
		COALESCE(CAST(B00_IT_TCURR.TCURR_UKURS AS FLOAT),1) * 
		COALESCE(B00_IT_TCURF.TCURF_TFACT,1) / COALESCE(B00_IT_TCURF.TCURF_FFACT,1)
		) AS ZF_REGUH_RWBTR_S_CUC
INTO BP05A_IT_01_REGUH
FROM A_REGUH

--Add house currency
LEFT JOIN A_T001
ON A_REGUH.REGUH_ZBUKR = A_T001.T001_BUKRS


-- Add currency conversion factors for company code currency
LEFT JOIN B00_TCURX TCURX_CC 
ON A_T001.T001_WAERS = TCURX_CC.TCURX_CURRKEY 

--Decimal placess in currencies for document currency 
LEFT JOIN B00_TCURX TCURX_DOC  
ON REGUH_WAERS = TCURX_DOC.TCURX_CURRKEY


    -- Add currency factor from company currency to USD

LEFT JOIN B00_IT_TCURF
ON T001_WAERS = B00_IT_TCURF.TCURF_FCURR
AND B00_IT_TCURF.TCURF_TCURR  = @currency  
AND B00_IT_TCURF.TCURF_GDATU = (
	SELECT TOP 1 B00_IT_TCURF.TCURF_GDATU
	FROM B00_IT_TCURF
	WHERE T001_WAERS = B00_IT_TCURF.TCURF_FCURR AND 
			B00_IT_TCURF.TCURF_TCURR  = @currency  AND
			B00_IT_TCURF.TCURF_GDATU <= A_REGUH.REGUH_LAUFD
	ORDER BY B00_IT_TCURF.TCURF_GDATU DESC
	)
-- Add exchange rate from company currency to USD
LEFT JOIN B00_IT_TCURR
	ON T001_WAERS = B00_IT_TCURR.TCURR_FCURR
	AND B00_IT_TCURR.TCURR_TCURR  = @currency  
	AND B00_IT_TCURR.TCURR_GDATU = (
		SELECT TOP 1 B00_IT_TCURR.TCURR_GDATU
		FROM B00_IT_TCURR
		WHERE T001_WAERS = B00_IT_TCURR.TCURR_FCURR AND 
				B00_IT_TCURR.TCURR_TCURR  = @currency  AND
				B00_IT_TCURR.TCURR_GDATU <= A_REGUH.REGUH_LAUFD
		ORDER BY B00_IT_TCURR.TCURR_GDATU DESC
		) 



-- Add information from the scope table concerning the business domain   
INNER JOIN AM_SCOPE                                         
ON   REGUH_ZBUKR = AM_SCOPE.SCOPE_CMPNY_CODE
--Not a paymnet proposal
WHERE REGUH_XVORL = ''

--/*Drop temporary tables*/
EXEC SP_REMOVE_TABLES '%BP05A_[_]TT[_]%'
EXEC SP_RENAME_FIELD 'BP05A_01_', 'BP05A_IT_01_REGUH'


END
GO
