USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_SU73_Check if powerful profiles are secured]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START

-- Script object: Check if powerful profiles are secured
-- Step 1: select data from A_UST04 table

EXEC SP_REMOVE_TABLES 'SU73_01_XT_UST04_CHECK_POWERFUL_PROFILES_SECURED'

SELECT A.*,
	USR02_CLASS,
	USR02_USTYP,
	USER_ADDR_NAME_TEXTC,
	USER_ADDR_DEPARTMENT,
	USER_ADDR_NAME1,
	USR02_TRDAT,
	USGRPT_USERGROUP,
	-- Add user type description
	(
	CASE USR02_USTYP
		WHEN 'A' THEN 'Dialog'
		WHEN 'B' THEN 'System'
		WHEN 'C' THEN 'Communications Data'
		WHEN 'L' THEN 'Reference (Logon not possible)'
		WHEN 'S' THEN 'Service'
	END 
	) AS ZF_USR02_USTYP_DESCRIPTION,
	-- Add flag to show users related to user's class = SUPER
	IIF(USR02_CLASS = 'SUPER','Yes','No') AS ZF_USR02_BNAME_SUPER_CLASS_FLAG,
	-- Add flag to show sensitive profiles
	IIF(ZF_AGR_UST12_PROFILE LIKE 'S%' 
		OR ZF_AGR_UST12_PROFILE LIKE '%.%' 
		OR ZF_AGR_UST12_PROFILE LIKE '%_ALL%','Yes','No') AS ZF_UST12_PROFILE_SENSITIVE_FLAG,
	-- Add flag to show security profiles
	IIF(ZF_AGR_UST12_PROFILE LIKE 'S%','Yes','No') AS ZF_UST12_PROFILE_SECURITY_FLAG,
	-- Add flag to show sensitive objects
	IIF(ZF_AGR_UST12_OBJCT LIKE '%*%' OR ZF_AGR_UST12_OBJCT LIKE 'S%','Yes','No') AS ZF_UST12_OBJCT_SENSITIVE_FLAG,
	-- Add flag to show security objects
	IIF(ZF_AGR_UST12_OBJCT LIKE 'S%','Yes','No') AS ZF_UST12_OBJCT_SECURITY_FLAG,
	-- Add flag to show sensitive authorizations
	IIF(ZF_AGR_UST12_AUTH LIKE 'S%','Yes','No') AS ZF_UST12_AUTH_SENSITIVE_FLAG,
	IIF(ZF_AGR_UST12_PROFILE IN ('SAP_ALL', 'SAP_NEW', 'SAP_APP', 'S_A.SYSTEM', 'S_A.ADMIN', 'P_BAS_ALL'),'Yes', 'No') AS ZF_UST12_PROFILE_KNOW_AS_SENSITIVE,
	IIF(ZF_AGR_UST12_PROFILE LIKE '%SAP_ALL%'
		OR ZF_AGR_UST12_PROFILE LIKE '%SAP_NEW%'
		OR ZF_AGR_UST12_PROFILE LIKE '%SAP_APP%'
		OR ZF_AGR_UST12_PROFILE LIKE '%S_A.SYSTEM%'
		OR ZF_AGR_UST12_PROFILE LIKE '%S_A.ADMIN%'
		OR ZF_AGR_UST12_PROFILE LIKE '%P_BAS_ALL%','Yes', 'No') AS ZF_UST12_PROFILE_CONTAINS_SENSITIVE_PROFILE
INTO SU73_01_XT_UST04_CHECK_POWERFUL_PROFILES_SECURED
FROM B22_09_IT_UST10S_AGR_PROFILE_OBJCT_AUTH_FIELD_VALUE AS A
-- Get user name
LEFT JOIN A_USER_ADDR
ON A.USR02_BNAME = USER_ADDR_BNAME
LEFT JOIN BC16_01_IT_USR02_USERS AS B
ON A.USR02_BNAME = B.USR02_BNAME
-- Just get user have sensitive profiles, authorizations, objects or user class = SUPER
WHERE 
	A.ZF_AGR_UST12_PROFILE <> ''
	AND
	(
	A.ZF_AGR_UST12_PROFILE LIKE 'S%'
	OR A.ZF_AGR_UST12_PROFILE LIKE '%_ALL%'
	OR A.ZF_AGR_UST12_PROFILE LIKE '%.%'
	OR A.ZF_AGR_UST12_PROFILE LIKE '%*%'
	OR A.ZF_AGR_UST12_OBJCT LIKE '%*%'
	OR A.ZF_AGR_UST12_OBJCT LIKE 'S%'
	OR A.ZF_AGR_UST12_AUTH LIKE 'S%'
	OR A.USR02_BNAME IN
		(
			SELECT DISTINCT USR02_BNAME FROM A_USR02
			WHERE USR02_CLASS = 'SUPER'
		))

-- Rename the fields
EXEC SP_RENAME_FIELD 'SU73_01_', 'SU73_01_XT_UST04_CHECK_POWERFUL_PROFILES_SECURED'
GO
