USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_SU06_Identify movement types and valuation classes that don’t have account check or account assignment]
AS
--DYNAMIC_SCRIPT_START

BEGIN

EXEC SP_REMOVE_TABLES 'SU06%'


--Step 1 Get the list of Transaction/ event Key 
EXEC SP_DROPTABLE SU06_01_RT_T156X_T156W

SELECT *,
 IIF( LEN(TRIM(T156X_XPKON))=0 AND T156X_KZBEW='B','X','') -- Flag the PO movements do not have account assign
 AS ZF_T156X_XPKON_KZBEW_PO_NO_ACCT
INTO SU06_01_RT_T156X_T156W
FROM BC21_01_IT_T156X_T156W_T156T

--Step 2 Get the Standard account determination
 EXEC SP_DROPTABLE SU06_02_RT_T030

 SELECT * 
 INTO SU06_02_RT_T030
 FROM BC21_02_IT_T030_ADD_DESC 

 --Step 3 Get the Material valuation relate to the standard account
 EXEC SP_DROPTABLE SU06_03_RT_MBEW_RELATE_T030

 SELECT DISTINCT 
 MBEW_MATNR,
MBEW_BWKEY,
MBEW_BWTAR,
MBEW_BKLAS,T025T_BKBEZ
INTO SU06_03_RT_MBEW_RELATE_T030 FROM A_MBEW
LEFT JOIN A_T025T ON T025T_BKLAS=MBEW_BKLAS

--Rename all the fields
EXEC SP_RENAME_FIELD 'SU06_01_','SU06_01_RT_T156X_T156W'
EXEC SP_RENAME_FIELD 'SU06_02_','SU06_02_RT_T030'
EXEC SP_RENAME_FIELD 'SU06_03_','SU06_03_RT_MBEW_RELATE_T030'

--STep 4 Filter ACDOCA/BKPF of BKPF_BLART = WE, 
--keep only ACDOCA_RBUKRS, ACDOCA_GJAHR, ACDOCA_BELNR, ACDOCA_BUZEI, ACDOCA_DRCRK, BKPF_AWKEY, 
--and 
EXEC SP_DROPTABLE SU06_04_TT_ACDOCA_BKPF_BLART_EQ_WE

 SELECT DISTINCT B04_08_IT_FIN_GL.*,T001_BUTXT,T003T_LTEXT,USER_ADDR_NAME_TEXTC,SKAT_TXT50
 INTO SU06_04_TT_ACDOCA_BKPF_BLART_EQ_WE
 FROM B04_08_IT_FIN_GL
 LEFT JOIN A_T001 ON T001_BUKRS=B04_GL_ACDOCA_RBUKRS
 LEFT JOIN A_USER_ADDR ON B04_GL_ACDOCA_USNAM=USER_ADDR_BNAME
 LEFT JOIN A_LFA1 ON LFA1_LIFNR=B04_GL_ACDOCA_LIFNR
LEFT JOIN A_T003T ON B04_GL_ACDOCA_BLART=T003T_BLART
LEFT JOIN A_SKAT ON B04_GL_ACDOCA_DRCRK=SKAT_SAKNR AND SKAT_SPRAS='EN'
 WHERE B04_GL_ACDOCA_BLART='WE' AND B04_GL_ACDOCA_AWTYP='MKPF'


 --Step 5 Get the GR transactions, add the GL account from EKKN
 --Get the line have EKKN account only
 --filter out the movement type PO do not assing to any account
EXEC SP_DROPTABLE SU06_05_TT_GR_ADD_EKKN

SELECT DISTINCT BP03_01_MKPF_MJAHR,BP03_01_MKPF_MBLNR,BP03_01_MSEG_ZEILE,EKKN_SAKTO
INTO SU06_05_TT_GR_ADD_EKKN
FROM BP03_01_IT_GR
LEFT JOIN A_EKKN
ON 
	EKKN_EBELN=BP03_01_MSEG_EBELN AND 
	EKKN_EBELP=BP03_01_MSEG_EBELP
 WHERE  EKKN_SAKTO IS NOT NULL AND BP03_01_MSEG_BWART IN
 (
	SELECT DISTINCT SU06_01_T156_BWART
	FROM SU06_01_RT_T156X_T156W
	WHERE SU06_01_ZF_T156X_XPKON_KZBEW_PO_NO_ACCT='X'
 )

--STep 6 Get the GR transactions add GL account from T030 (debit and credit),
--get the lines hava GL account only

EXEC SP_DROPTABLE SU06_06_TT_GR_ADD_T030

SELECT DISTINCT BP03_01_MKPF_MJAHR,BP03_01_MKPF_MBLNR,BP03_01_MSEG_ZEILE,
SU06_02_T030_KONTH,SU06_02_T030_KONTS
INTO SU06_06_TT_GR_ADD_T030
FROM BP03_01_IT_GR
LEFT JOIN SU06_01_RT_T156X_T156W
ON
	BP03_01_MSEG_BWART=SU06_01_T156X_BWART 
LEFT JOIN SU06_03_RT_MBEW_RELATE_T030
	ON 
		BP03_01_MSEG_MATNR= SU06_03_MBEW_MATNR AND
		BP03_01_MSEG_WERKS=SU06_03_MBEW_BWKEY
LEFT JOIN SU06_02_RT_T030 
	ON SU06_03_MBEW_BKLAS=SU06_02_T030_BKLAS AND 
		SU06_01_T156W_VORSL=SU06_02_T030_KTOSL AND 
		SU06_01_T156X_KOMOK=SU06_02_T030_KOMOK
		WHERE  SU06_02_T030_KONTH IS NOT NULL AND SU06_02_T030_KONTS  IS NOT NULL

--Step 7 Add to BKPF/ACDOCA infor about Good receipt
--Flag the case has GL account found in EKKN or not
--Flag the case has GL account = SU06_02_T030_KONTH or not
--Flag the case has GL account = SU06_02_T030_KONTS or not

EXEC SP_DROPTABLE SU06_07_RT_ACDOCA_BKPF_ADD_FLAG

SELECT DISTINCT SU06_04_TT_ACDOCA_BKPF_BLART_EQ_WE.*,
'' AS ZF_ACDOCA_DRCRK_EQ_EKKN_SAKTO,
'' AS ZF_ACDOCA_DRCRK_EQ_T030_KONTH,
'' AS ZF_ACDOCA_DRCRK_EQ_T030_KONTS
INTO SU06_07_RT_ACDOCA_BKPF_ADD_FLAG
FROM SU06_04_TT_ACDOCA_BKPF_BLART_EQ_WE
INNER JOIN BP03_01_IT_GR AS A
ON 
B04_GL_ZF_ACDOCA_AWKEY_YEAR=A.BP03_01_MKPF_MJAHR  AND
 B04_GL_ZF_ACDOCA_AWKEY_DOC_NUM=A.BP03_01_MKPF_MBLNR

--Update the flag, check if ACDOCA_DRCRK is found in T030 (KONTH)
UPDATE SU06_07_RT_ACDOCA_BKPF_ADD_FLAG
SET ZF_ACDOCA_DRCRK_EQ_T030_KONTH='X'
WHERE B04_GL_ACDOCA_DRCRK IN
(
		SELECT DISTINCT SU06_02_T030_KONTH
		FROM SU06_06_TT_GR_ADD_T030  INNER JOIN SU06_07_RT_ACDOCA_BKPF_ADD_FLAG 
		ON B04_GL_ZF_ACDOCA_AWKEY_YEAR=BP03_01_MKPF_MJAHR  AND
			B04_GL_ZF_ACDOCA_AWKEY_DOC_NUM=BP03_01_MKPF_MBLNR
)
--Update the flag, check if ACDOCA_DRCRK is found in T030 (KONTS)
UPDATE SU06_07_RT_ACDOCA_BKPF_ADD_FLAG
SET ZF_ACDOCA_DRCRK_EQ_T030_KONTS='X'
WHERE B04_GL_ACDOCA_DRCRK IN
(
		SELECT DISTINCT SU06_02_T030_KONTS
		FROM SU06_06_TT_GR_ADD_T030  INNER JOIN SU06_07_RT_ACDOCA_BKPF_ADD_FLAG 
		ON B04_GL_ZF_ACDOCA_AWKEY_YEAR=BP03_01_MKPF_MJAHR  AND
			B04_GL_ZF_ACDOCA_AWKEY_DOC_NUM=BP03_01_MKPF_MBLNR
)
--Update the flag, check if ACDOCA_DRCRK is found in EKKN_SAKTO
UPDATE SU06_07_RT_ACDOCA_BKPF_ADD_FLAG
SET ZF_ACDOCA_DRCRK_EQ_EKKN_SAKTO='X'
WHERE B04_GL_ACDOCA_DRCRK IN
(
		SELECT DISTINCT EKKN_SAKTO
		FROM SU06_05_TT_GR_ADD_EKKN  INNER JOIN SU06_07_RT_ACDOCA_BKPF_ADD_FLAG 
		ON B04_GL_ZF_ACDOCA_AWKEY_YEAR=BP03_01_MKPF_MJAHR  AND
			B04_GL_ZF_ACDOCA_AWKEY_DOC_NUM=BP03_01_MKPF_MBLNR
)

--Step 8 Get the good recepts cube
--Add the flag to show the case where MSEG found in T030 and MSEG found in EKKN
EXEC SP_DROPTABLE SU06_08_RT_MSEG_MKPF_GR_ADD_FLAG

SELECT DISTINCT A.*,
IIF (B.EKKN_SAKTO IS NOT NULL,'X','') AS ZF_MSEG_FOUND_IN_EKKN,
IIF (C.SU06_02_T030_KONTH IS NOT NULL,'X','') AS ZF_MSEG_FOUND_IN_T030
INTO SU06_08_RT_MSEG_MKPF_GR_ADD_FLAG
FROM BP03_01_IT_GR AS A
LEFT JOIN SU06_05_TT_GR_ADD_EKKN AS B
             ON B.BP03_01_MKPF_MJAHR=A.BP03_01_MKPF_MJAHR 
			AND B.BP03_01_MKPF_MBLNR=A.BP03_01_MKPF_MBLNR
			AND B.BP03_01_MSEG_ZEILE=A.BP03_01_MSEG_ZEILE
 LEFT JOIN SU06_06_TT_GR_ADD_T030 AS C 
			ON C.BP03_01_MKPF_MJAHR=A.BP03_01_MKPF_MJAHR 
			AND C.BP03_01_MKPF_MBLNR=  A.BP03_01_MKPF_MBLNR
			AND C.BP03_01_MSEG_ZEILE= A.BP03_01_MSEG_ZEILE
WHERE BP03_01_MSEG_BWART IN
 (
	SELECT DISTINCT SU06_01_T156_BWART
	FROM SU06_01_RT_T156X_T156W
	WHERE SU06_01_ZF_T156X_XPKON_KZBEW_PO_NO_ACCT='X'
 )			
--Step 10/ Create EKKN infomation cube
--Get the text for profit center and cost cenetr base on download date

 DECLARE  
     @DOWNLOADDATE NVARCHAR(MAX)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')

EXEC SP_DROPTABLE SU06_09_RT_EKKN

SELECT DISTINCT A_EKKN.*,SKAT_TXT50,CEPCT_LTEXT,CSKT_LTEXT
INTO SU06_09_RT_EKKN
FROM A_EKKN
LEFT JOIN A_SKAT ON SKAT_SAKNR=EKKN_SAKTO  
LEFT JOIN 

 (
    			SELECT *
			FROM
			(
			SELECT
				A_CEPCT.*
				,ROW_NUMBER() OVER( PARTITION BY CEPCT_MANDT, CEPCT_PRCTR, CEPCT_KOKRS ORDER BY CEPCT_DATBI DESC) AS ROW_NR
			FROM A_CEPCT
			WHERE 
			 CEPCT_DATBI> = @downloaddate
			 ) AS A WHERE ROW_NR=1
 ) AS B ON B.CEPCT_PRCTR=EKKN_PRCTR AND CEPCT_KOKRS=EKKN_KOKRS 
LEFT JOIN 

 (
    			SELECT *
			FROM
			(
			SELECT
				A_CSKT.*
				,ROW_NUMBER() OVER( PARTITION BY CSKT_MANDT, CSKT_KOSTL, CSKT_KOKRS ORDER BY CSKT_DATBI DESC) AS ROW_NR
			FROM A_CSKT
			WHERE 
			 CSKT_DATBI> = @downloaddate
			 ) AS C WHERE ROW_NR=1
 ) AS D ON D.CSKT_KOSTL=EKKN_KOSTL AND CSKT_KOKRS=EKKN_KOKRS 



--Step 11 Rename the cube
EXEC SP_UNNAME_FIELD 'B04_GL_','SU06_07_RT_ACDOCA_BKPF_ADD_FLAG'
EXEC SP_RENAME_FIELD 'SU06_07_','SU06_07_RT_ACDOCA_BKPF_ADD_FLAG'

EXEC SP_UNNAME_FIELD 'BP03_01_','SU06_08_RT_MSEG_MKPF_GR_ADD_FLAG'
EXEC SP_RENAME_FIELD 'SU06_08_','SU06_08_RT_MSEG_MKPF_GR_ADD_FLAG'

EXEC SP_RENAME_FIELD 'SU06_09_','SU06_09_RT_EKKN'


END
GO
