USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[script_BO08_TVLP_DELIVERY_ITEM_CATEGORY]
WITH EXECUTE AS CALLER
AS
--DYNAMIC_SCRIPT_START
EXEC SP_REMOVE_TABLES 'BO08_01_IT_DELIVERY_ITEM_CATEGORY'
SELECT *,
		-- Add control for checking for overdelivery description
	(
		CASE
			WHEN TVLP_UEBPR = '' THEN 'No dialog'
			WHEN TVLP_UEBPR = 'A' THEN 'Note about the situation'
			WHEN TVLP_UEBPR = 'B' THEN 'Situation rejected with an error message'
		END
	) AS ZF_TVLP_UEBPR_DESCRIPTION
INTO BO08_01_IT_DELIVERY_ITEM_CATEGORY
FROM A_TVLP
LEFT JOIN A_TVPT
ON TVPT_PSTYV = TVLP_PSTYV
GO
