USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_SU64_CHeck that the secrutiy log is enabled]
AS
--DYNAMIC_SCRIPT_START

--Script objectvie : CHeck that the secrutiy log is enabled

--Step 1 --Filter out the case where PARNAME='rsau/enable'
EXEC SP_DROPTABLE SU64_01_XT_ENABLE_SECURITY_LOG

SELECT DISTINCT
A.*
INTO SU64_01_XT_ENABLE_SECURITY_LOG
FROM BC14_01_IT_PAHI_ADD_AM_PARAMETER_TEST AS A
INNER JOIN 
	(	
		SELECT BC14_01_PAHI_HOSTNAME,BC14_01_PAHI_PARNAME,MAX(BC14_01_PAHI_PARDATE) AS ZF_BC14_01_PAHI_PARDATE_MAX
		FROM BC14_01_IT_PAHI_ADD_AM_PARAMETER_TEST
				WHERE BC14_01_PAHI_PARNAME='rsau/enable'
		GROUP BY BC14_01_PAHI_HOSTNAME,BC14_01_PAHI_PARNAME

	) AS B
	ON A.BC14_01_PAHI_HOSTNAME=B.BC14_01_PAHI_HOSTNAME 
	AND A.BC14_01_PAHI_PARDATE=B.ZF_BC14_01_PAHI_PARDATE_MAX
WHERE A.BC14_01_PAHI_PARNAME='rsau/enable'


--Rename the fields
EXEC SP_UNNAME_FIELD 'BC14_01_','SU64_01_XT_ENABLE_SECURITY_LOG'
EXEC SP_RENAME_FIELD 'SU64_01_','SU64_01_XT_ENABLE_SECURITY_LOG'

GO
