USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE   PROCEDURE [dbo].[SP_CREATE_INDEX](@TABLE_NAME AS NVARCHAR(MAX), @INDEX_NAME AS NVARCHAR(MAX), @KEY_FIELDS AS NVARCHAR(MAX))
AS

-- Check if the index exists
-- If the index exists do nothing
-- If the index does not exist create it


DECLARE @SQL_CMD NVARCHAR(MAX)
IF NOT EXISTS (SELECT NAME FROM SYS.INDEXES WHERE NAME = @INDEX_NAME) 

	BEGIN
		SET @SQL_CMD = 'CREATE NONCLUSTERED INDEX ' + @INDEX_NAME + ' ON '+ @TABLE_NAME +'('+@KEY_FIELDS+');'
		PRINT @SQL_CMD
		EXEC SP_EXECUTESQL @SQL_CMD
	END




GO
