USE [DIVA_SAP_USAGE_S4]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[script_BC32_T16FG_T16FH]
AS
--Step 1 Get the informaiton from release group, add the text description
--DYNAMIC_SCRIPT_START
EXEC SP_DROPTABLE 'BC32_01_IT_T16FG_T16FH'

SELECT 
	A_T16FG.*,
	T16FH_FRGGT,
	CASE WHEN T16FG_FRGOT='1' THEN 'Purchase requisition'
	WHEN T16FG_FRGOT='2' THEN 'Purchase order'
	WHEN T16FG_FRGOT='3' THEN 'Service acceptance'
	WHEN T16FG_FRGOT='3' THEN 'Reserve'
	ELSE 'Not found' END AS ZF_T16FG_FRGOT_DESC
	INTO BC32_01_IT_T16FG_T16FH
FROM A_T16FG LEFT JOIN A_T16FH ON T16FG_FRGGR=T16FH_FRGGR AND T16FH_SPRAS='EN'






GO
