USE [DIVA_TEST_PROGRESS]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[A_005M_CREATE_GL_BANK_ACCOUNT_TABLE_EXE]
--ALTER PROCEDURE [dbo].[A_005L_CREATE_LIST_KEY_WORDS]
WITH EXEC AS CALLER
AS
-- BEGIN


/* Initiate the log */  
--Create database log table if it does not exist
IF OBJECT_ID('LOG_SP_EXECUTION', 'U') IS NULL BEGIN CREATE TABLE [DBO].[LOG_SP_EXECUTION] ([DATABASE] NVARCHAR(MAX) NULL,[OBJECT] NVARCHAR(MAX) NULL,[OBJECT_TYPE] NVARCHAR(MAX) NULL,[USER] NVARCHAR(MAX) NULL,[DATE] DATE NULL,[TIME] TIME NULL,[DESCRIPTION] NVARCHAR(MAX) NULL,[TABLE] NVARCHAR(MAX),[ROWS] INT) END

--Log start of procedure
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Procedure started',NULL,NULL

/* Initialize parameters from globals table */

     DECLARE 	 
			 @CURRENCY NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'currency')
			,@DATE1 NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date1')
			,@DATE2 NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'date2')
			,@DOWNLOADDATE NVARCHAR(MAX)		= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'downloaddate')
			,@DATEFORMAT VARCHAR(3)             = (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'dateformat')
			,@EXCHANGERATETYPE NVARCHAR(MAX)	= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'exchangeratetype')
			,@LANGUAGE1 NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language1')
			,@LANGUAGE2 NVARCHAR(MAX)			= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'language2')
			,@YEAR NVARCHAR(MAX)				= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'year')
			,@ID NVARCHAR(MAX)					= (SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'id')
			,@LIMIT_RECORDS INT		            = CAST((SELECT GLOBALS_VALUE FROM [AM_GLOBALS] WHERE GLOBALS_PARAMETER = 'LIMIT_RECORDS') AS INT)


/*Test mode*/

SET ROWCOUNT @LIMIT_RECORDS

  /*
    Title		    :	Create List of manual GL BANK ACCOUNT table
	This table is used in the red frlag P08_T23, AP transactions with 
	key words   
    
    --------------------------------------------------------------
    Update history
    --------------------------------------------------------------
    Date		  Who |	Description
    23-10-2017	  HT	Create List of manual GL BANK ACCOUNT table
	
  */


-- Step 1/ This table was imported.

-- The structure of the table is as follows:

/*Definition of the AM_LIST_KEY_WORDS table 
[GL_BANK_ACC_MANDT]
	[GL_BANK_ACC_BUKRS]
	[GL_BANK_ACC_HBKID]
	[GL_BANK_ACC_HKTID]
	[GL_BANK_ACC_BANKN]
	[GL_BANK_ACC_BKONT]
	[GL_BANK_ACC_WAERS]
	[GL_BANK_ACC_REFZL]
	[GL_BANK_ACC_DTAAI]
	[GL_BANK_ACC_BNKN2]
	[GL_BANK_ACC_FDGRP]
	[GL_BANK_ACC_ABWAE]
	[GL_BANK_ACC_HKONT]
	[GL_BANK_ACC_WEKON]
	[GL_BANK_ACC_MINDT]
	[GL_BANK_ACC_HBID1]
	[GL_BANK_ACC_HKID1]
	[GL_BANK_ACC_HBID2]
	[GL_BANK_ACC_HKID2]
	[GL_BANK_ACC_WKKON]
	[GL_BANK_ACC_WIKON]
	[Bank role]
	[Principal Bank]
	[Description]
	[AP_GL_BANK_ACC_MANDT]
 */
 /* log cube creation*/
EXEC SP_DROPTABLE 'AM_GL_BANK_ACC'
SELECT DISTINCT T012K_MANDT GL_BANK_ACC_MANDT, T012K_BUKRS GL_BANK_ACC_BUKRS, T012K_HKONT GL_BANK_ACC_HKONT,'' as GL_BANK_TEXT1
		INTO AM_GL_BANK_ACC
		FROM A_T012K
		WHERE ISNULL(T012K_HKONT,'') <> ''
EXEC SP_CREATE_INDEX 'AM_GL_BANK_ACC','AM_GL_BANK_ACC_INDEX','GL_BANK_ACC_MANDT, GL_BANK_ACC_BUKRS, GL_BANK_ACC_HKONT'
INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(DATE,GETDATE()),CONVERT(TIME,GETDATE()),'Cube completed','AM_GL_BANK_ACC',(SELECT COUNT(*) FROM AM_LIST_KEY_WORDS) 


/* log end of procedure*/


INSERT INTO [DBO].[LOG_SP_EXECUTION] ([DATABASE],[OBJECT],[OBJECT_TYPE],[USER],[DATE],[TIME],[DESCRIPTION],[TABLE],[ROWS])
SELECT DB_NAME(),OBJECT_NAME(@@PROCID),'P',SYSTEM_USER,CONVERT(date,GETDATE()),CONVERT(time,GETDATE()),'Procedure finished',NULL,NULL

    
-- END




GO
